### ISSUE TITLE
Font loaded twice when using GOV.UK Frontend with GOV.UK Elements

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1001]
@injms from the Registers team has noticed that when loading GOV.UK Frontend alongside GOV.UK Elements it will load the webfont twice.

This was surprising to me as I expected font-face to ignore a previous declaration.

They found a work around which is to trick GOV.UK Frontend into thinking it's using a custom font which'll prevent the font-face declaration to be output: https://github.com/openregister/registers-frontend/blob/e387d872828fbc5239a4c872fd759911794b021b/app/assets/stylesheets/application.scss#L39

We should keep this in mind when implementing the new version of the font.

**Comment by nickcolley** [comment]
I've seen this happen on GOV.UK too, so I think this is important for us to fix soon.

![image](https://user-images.githubusercontent.com/2445413/47077412-c90d8080-d1f8-11e8-9034-15fbc896ae91.png)

**Comment by nickcolley** [comment]
I've noticed on faster connections the fonts will race each other, so if the original definition returns first it wont try and download the second declared version of the font.

This means on slower connections they will always download.

**Comment by nickcolley** [comment]
We could see if the user has turned on the template compatibility mode, if they have, don't load the font declarations.

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
