### ISSUE TITLE
Select element max-width

### ISSUE THREAD

**Issue by davidjamesstone** [alphagov/govuk-frontend#1009]
The `<select>` element's width is governed by the widths of its `<option>`'s.
When the text in the options grows large, the <select> element can grow to > 100% of the width of its container and break the layout.

Could I suggest a width: 100% or max-width: 100% to fix this.

Many thanks

**Comment by nickcolley** [comment]
We have intentionally removed `width: 100%` for accessibility reasons but I think `max-width: 100%` would work fine to fix this, thanks for raising David!
