### ISSUE TITLE
Replace NodeListForEach helper with Array.from (and polyfill)

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1017]
At the moment we use a helper internally to find each node in the element to enhance using a function called 'NodeListForEach', I think we could replace this with 'Array.from'.

```js
NodeListForEach(document.querySelectorAll('*')).forEach(() => {})
```

vs

```js
Array.from(document.querySelectorAll('*')).forEach(() => {})
```

**Comment by igloosi** [comment]
if we remove entirely from the code base i guess it's a breaking change?

**Comment by nickcolley** [comment]
Yeah we'd have to do this as a deprecation, but I think the effort to for consumers to update will be small since it'd be a like for like swap.

**Comment by nickcolley** [comment]
Not sure there's a pressing reason to do this, unless we prioritise removing polyfills from GOV.UK Frontend...
