### ISSUE TITLE
Anchor links inside tabs don't work

### ISSUE THREAD

**Issue by tijmenb** [alphagov/govuk-frontend#1030]
When you click on an anchor link inside a tab, the first tab will be selected instead of the browser scrolling to the correct place in the page. Tested in Chrome & Firefox.

![](https://media.giphy.com/media/pyzHpxkGvviK0kh9oo/giphy.gif) 

## Steps to reproduce

1. Put a anchor link and anchor in a tab panel
2. Click the link
3. The tab is now selected
4. Click anchor link again
5. Browser now correctly scrolls to anchor

Glitch: 

https://govuk-frontend-tab-bug.glitch.me/

Code:

https://glitch.com/edit/#!/govuk-frontend-tab-bug?path=src/views/index.html:1:0

**Comment by nickcolley** [comment]
This looks to be based on the implementation of the hash handling: https://github.com/alphagov/govuk-frontend/blob/master/src/components/tabs/tabs.js#L106
