### ISSUE TITLE
Font sizing goes to 18px, not 19px

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#1036]
https://hello-govuk-frontend.glitch.me/

At less than tablet size, the H1 goes to 18px, instead of 19px

**Comment by nickcolley** [comment]
Looks like it's also an issue for govuk-heading-m classes

**Comment by nickcolley** [comment]
This seems to be always the case, with GOV.UK Elements using this as well.

@dashouse would know if it's a problem.

It'd be good to know why we have 19px if we are dropping down to 18px for these fonts though...

**Comment by dashouse** [comment]
@joelanman from memory there is a lot of custom font size stuff going on in step-by-step that we would need to manually recreate.

For example I believe when step-by-step is in the sidebar the 16px text content remains 16px at both mobile and desktop, where as the rest of the 16px text changes to 14px. We don't currently have non-responsive type in GOV.UK Frontend so the font size would need to be set explicitly.

And yeah, 24px > 18px on GOV.UK, didn't change any of the font size relationships when we did the typography work.

**Comment by joelanman** [comment]
ok closing this, I just didn't realise we went to 18px
