### ISSUE TITLE
Write integration tests for Character count component

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1039]

**Comment by nickcolley** [comment]
@alex-ju could you push up your branch where you had WIP for this please?

**Comment by alex-ju** [comment]
@nickcolley it seems that I've lost the tests in some branch 😞. Will try and write them today they were exhaustive anyway. Apologies again for not including them from the beginning.

**Comment by aliuk2012** [comment]
I'm closing this issue as #1055 has been merged.
