### ISSUE TITLE
Research how to capture screenshots as part of build

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#104]

**Comment by hannalaakso** [comment]
We can use Browserstack's [API](https://www.browserstack.com/screenshots/api) for generating screenshots: 

We give it the URL to look at and the devices for screenshots. It will return URLs of the screenshots which are hosted on AWS for 90 days. Looking at the docs, there will be a URL per device.

We'll need to write a script to save the images locally from those URLs. There's an example of an API response on the above URL.

Next step for this task would be to test that response from the API works as expected.

**Comment by igloosi** [comment]
alternative http://webdriver.io/guide/services/visual-regression.html

**Comment by nickcolley** [comment]
I had a look at https://percy.io/, obviously a paid for service but potentially worth the cost if we think the maintenance of an in house solution is high

**Comment by igloosi** [comment]
long list https://gist.github.com/cvrebert/adf91e429906a4d746cd

**Comment by nickcolley** [comment]
another long list from that long list's comments https://github.com/mojoaxel/awesome-regression-testing/blob/master/README.md

**Comment by nickcolley** [comment]
This has been superseded by https://trello.com/c/mmggoT9Z/511-spike-automated-visual-regression-testing
