### ISSUE TITLE
Add .govuk-hidden { display: none }

### ISSUE THREAD

**Issue by adamsilver** [alphagov/govuk-frontend#1060]
We need to be able to hide and show elements by toggling the class name.

`.govuk-visually-hidden` isn't always right as we may not want the thing to be perceivable to screen readers. And we'd rather not have to add `aria-hidden="true"` as well.

`[hidden] { display: none; }` is nice but not supported very well. Even in browsers that you can patch, you require the same amount of code. And in any case, IE8, for example, doesn't work because while the JS can change the attribute, the [page won't update the CSS to reflect the change](https://stackoverflow.com/questions/14222123/ie8-not-refreshing-class-after-attribute-value-change).

**Comment by igloosi** [comment]
i think this should be an override, and as such `.govuk-!-display-none`
any thoughts?

**Comment by adamsilver** [comment]
Why do you think this, considering we have govuk-visually-hidden already?

**Comment by igloosi** [comment]
to me it feels more of an override than a utility, but it can honestly be either

**Comment by frankieroberto** [comment]
We have a need for this too. I'm tempted to use the `hidden` attribute though, given that IE8 isn't that big a concern for us.

**Comment by adamszymaszczyk** [comment]
We have a use case for hiding an element on a page from the screen readers as well.
Could you give an estimate on when this issue might be actioned?

**Comment by nickcolley** [comment]
Will be released in this milestone soon: https://github.com/alphagov/govuk-frontend/milestone/27 thanks everyone :)
