### ISSUE TITLE
Bug: Angular project will not compile with latest dev-kit

### ISSUE THREAD

**Issue by shaed-parkar** [alphagov/govuk-frontend#1062]
created a new angular project (v7) and the @angular-devkit/build-angular was the latest (0.10.5) and the app would not compile. eventually figured out that the dev kit had to be downgraded along with the rest of the angular framework so that I can use the govuk-frontend

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

(function (global, factory) {
^
      Invalid CSS after "(": expected selector, was "(function (global, "

**Comment by igloosi** [comment]
@shaed-parkar Hi, i believe you've raised this in the wrong repository.

**Comment by igloosi** [comment]
Hi @shaed-parkar, 
thanks for posting the issue. Just to understand the setup, did you use Angular CLI and then installed govuk-frontend from npm?

**Comment by shaed-parkar** [comment]
Yes. That’s correct

**Comment by igloosi** [comment]
webpack has a special syntax for imports where `~` denoted node_modules.
So in the `src/styles.scss` you can need to import a stylesheets from govuk-frontend like this
`@import "~govuk-frontend/components/button/button";`

See screenshot of of a working example using default setup below

<img width="1588" alt="screen shot 2018-11-10 at 14 32 06" src="https://user-images.githubusercontent.com/3758555/48302531-d535e680-e4f5-11e8-8a73-0965e525e1b9.png">

**Comment by shaed-parkar** [comment]
thank you I will give that a go

**Comment by igloosi** [comment]
If it's ok with you, I'd like to close this issue.

**Comment by shaed-parkar** [comment]
yes that is fine, thanks.

**Comment by igloosi** [comment]
closing as resolved
