### ISSUE TITLE
Allow ErrorSummary component to disable autofocus

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1068]
This may only be a need when using the ErrorSummary in the Design System website, but there might be cases where someone's application had different load events.

https://github.com/alphagov/govuk-design-system/pull/643

**Comment by 36degrees** [comment]
We need to establish conventions for passing options to components to be able to pick this up.

**Comment by nickcolley** [comment]
I got pretty far down the road to figuring this out here: https://github.com/alphagov/govuk-frontend/pull/1238

We decided not to do it since Alex did not need this work to solve this problem in the end.

**Comment by 36degrees** [comment]
Closed by #2494
