### ISSUE TITLE
Compiled component javascript file is exported with GOVUKFrontend namespace

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#1081]
In addition to rolling-up `all.js` we also rollup each component's javascript file. For example [Tabs.js](https://github.com/alphagov/govuk-frontend/blob/master/package/components/tabs/tabs.js)

When we do so, the component is [exported](https://github.com/alphagov/govuk-frontend/blob/master/package/components/tabs/tabs.js#L4) under the `GOVUKFrontend namespace` which conflicts with `all.js` or any other component if you want to, say use an unpublished experimental component from Frontend in Prototype Kit using `window.<something>`

**Comment by igloosi** [comment]
doing some more experimentation, we should also be instead of [`return Tabs`](https://github.com/alphagov/govuk-frontend/blob/master/package/components/tabs/tabs.js#L1299) do export Tabs: `exports.Tabs = Tabs`;

That way users could do the following in their application
```
Array.from(document.querySelectorAll('[data-module="tabs"]')).forEach(($tab) => {
    new GOVUKTabs.Tabs($tab).init()
  })
```

**Comment by 36degrees** [comment]
I don't really understand the problem there – how does that differ from

```
Array.from(document.querySelectorAll('[data-module="tabs"]')).forEach(($tab) => {
    new GOVUKTabs($tab).init()
  })
```

?

**Comment by igloosi** [comment]
at the moment you can't do either. `GOVUKTabs($tab).init()` would be preferable

**Comment by igloosi** [comment]
closing as it hasn't been mentioned by users since
