### ISSUE TITLE
Unneeded padding on warning component?

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1083]
> Noticed that the govuk-warning-text__text element has padding left that includes an extra 15px to compensate for a negative margin left (see below, dotted outline added by me to show boundary of component). Seems like this could be removed and the padding decreased, but there must be a reason for it?

![screen shot 2018-12-03 at 11 30 12](https://user-images.githubusercontent.com/861310/49371364-2a2cdd00-f6ef-11e8-886a-edc4676dd188.png)

_Originally posted by @andysellick in https://github.com/alphagov/govuk-design-system-backlog/issues/71#issuecomment-443679660_

**Comment by 36degrees** [comment]
For reference, it looks like this was [copied from Elements](https://github.com/alphagov/govuk_elements/commit/7a77a95fcd285f068076f421bcec84f518734436).

**Comment by 36degrees** [comment]
Yep, but removing the negative margin and reducing the padding appears to be the same:

```diff
- margin-left: -$govuk-gutter-half;
- padding-left: 65px;
+ padding-left: 50px;
```

<img width="994" alt="screen shot 2018-12-03 at 13 44 55" src="https://user-images.githubusercontent.com/121939/49377275-a7614d80-f701-11e8-846f-0a24da1f6e02.png">

**Comment by nickcolley** [comment]
That's weird, I've asked Andy if he wants to do a PR for this...

**Comment by andysellick** [comment]
I am busy, but I'd like to contribute (if only to experience the process) so I'll try to raise a PR soon (also it's not a huge change). Thanks!

**Comment by nickcolley** [comment]
@andysellick will leave this open for you when you get a second then.

**Comment by stevenaproctor** [comment]
@nickcolley @36degrees Do you think the icon should be vertically aligned to the middle of the paragraph, like in the example, or the top or the paragraph?

**Comment by stevenaproctor** [comment]
@nickcolley I just think it scans better if the icon is at the top of the paragraph. You would naturally scan left to right, not left, down, up, right...if you see what I mean.
