### ISSUE TITLE
Investigate visually hidden text bug in OSX VoiceOver

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1096]
We've had a report from @stevenaproctor that using visually hidden text results in bugs in VoiceOver.

https://github.com/alphagov/govuk-frontend/pull/958#issuecomment-446523349

We should try and reproduce this, I suspect it may be someone testing VoiceOver in Chrome rather than Safari, but since this is a very widespread pattern on GOV.UK (and GOV.UK Frontend) it's worth an investigation.

**Comment by stevenaproctor** [comment]
@nickcolley I got this from our accessibility lead so I doubt it is because they used Chrome.

**Comment by nickcolley** [comment]
This seems to only be a problem with links: https://jsbin.com/mikoqeyibe/1/edit?html,css,output

Buttons read "Change name" whereas links read out "name Change'

**Comment by nickcolley** [comment]
This might be related: 

https://github.com/h5bp/html5-boilerplate/issues/1985

I have updated my example with their suggestion for the visually hidden class and will test again:

https://jsbin.com/qozumosiji/edit?html,css,output

https://output.jsbin.com/qozumosiji

**Comment by nickcolley** [comment]
Aria label

https://jsbin.com/jacapiwane/1/edit?html,css,output

https://output.jsbin.com/jacapiwane

🍏  Mac OSX High Sierra  v10.13.3 (17D47), Safari Version 11.0.3 (13604.5.6):
- Buttons reads "Change name"
- links read out "Change name"

🔴 iOS 12.0.1 VoiceOver
- Button reads "Change name"
- Link reads "Change"

**Comment by nickcolley** [comment]
I have investigated this and recorded the results in this gist: https://gist.github.com/nickcolley/19b80ed24d0364cfd3afd3b1b49c4014

> ## Conclusion
> We should update the govuk-visually-hidden class to remove the negative margin which will fix the ordering issue in VoiceOver for OSX.
> 
> We should recommend using aria-label or aria-labelledby where it makes sense to.
> 
> Visually hidden CSS can result in text not being read out when touching on iOS, this is regrettable but does not cause a hard barrier as users can explore the surrounding content to understand context.

@stevenaproctor I found that the duplicate approach works pretty well but in [VoiceOver iOS it makes the virtual focus area render oddly](https://gist.github.com/nickcolley/19b80ed24d0364cfd3afd3b1b49c4014#visually-hidden-with-css-and-duplicate-aria-hidden-content-1)

**Comment by stevenaproctor** [comment]
@nickcolley I think guidance on which method to use in what situation will be good and essential. Maybe a new entry in '[Typography](https://design-system.service.gov.uk/styles/typography/)'?
