### ISSUE TITLE
Grid columns do not align with service name

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-frontend#1122]
I'm working on a service that makes use of a one third / two thirds column grid layout. The first column is filtering, and main content on the right.

At the moment the main content doesn't align with the service name - but it *almost* does. Enough that it looks like a bug / fault in the code.  Would it be possible for these to align?

<img width="827" alt="screenshot 2019-01-09 at 17 16 28" src="https://user-images.githubusercontent.com/2204224/50916876-2a2da480-1434-11e9-9f23-c784832b6e34.png">

In other places the header aligns with the grids - such as the GOV.UK search box:
<img width="1011" alt="screenshot 2019-01-09 at 17 31 02" src="https://user-images.githubusercontent.com/2204224/50917006-63feab00-1434-11e9-9382-07cfdcf9404c.png">

**Comment by nickcolley** [comment]
Hey Ed, Made a live example to poke here:

https://govuk-frontend-issue-1112.glitch.me/

Looks to be misaligned since the grid has gutters of 30px whereas the header does not, even though the percentages are consistent.

**Comment by edwardhorsford** [comment]
@nickcolley thanks for looking at this. That sounds sensible.

A side effect is there's *slightly* less space for service name in the header - but on mobile they split on to two lines anyway so the impact should be minimal.
