### ISSUE TITLE
Consider adding `autocorrect="off" spellcheck="false"` to inputs

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#1129]
A user is entering their email address on an email input implemented without `type="email"`.

The standard input does not have `autocorrect="off"` so their email address is autocorrected.

<img width="548" alt="screen shot 2019-01-14 at 09 47 26" src="https://user-images.githubusercontent.com/23356842/51105688-99631a00-17e1-11e9-8517-dbf047cfe643.png">

Should we consider `autocorrect="off" spellcheck="false"` on inputs?

If `type="email"` is applied does this remove autocorrect?

**Comment by nickcolley** [comment]
I think we could look at this as part of the WCAG 2.1 work that asks authors to put autocomplete values in their forms.

I imagine if we were to do this we'd only do it in guidance rather than baking it into the components itself since we'd likely break other scenarios that autocomplete is useful?

**Comment by dashouse** [comment]
Sorry this is `autocorrect` not `autocomplete`

**Comment by nickcolley** [comment]
@dashouse yeah the behaviour of these are very similar to autocomplete which is why I'm suggesting we do this alongside the WCAG 2.1 work

**Comment by nickcolley** [comment]
https://davidwalsh.name/disable-autocorrect

## Spellcheck

https://www.w3.org/TR/html51/editing.html#spelling-and-grammar-checking
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck


## Autocapitalize

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

> The autocapitalize attribute never causes autocapitalization to be enabled for an <input> element with a type attribute whose value is url, email, or password.

Non standard but in a working draft:

https://www.w3.org/TR/html53/sec-forms.html#element-attrdef-input-autocapitalize

## Autocorrect

Non standard

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html

**Comment by dashouse** [comment]
@nickcolley thanks for the info 👍

**Comment by 36degrees** [comment]
This definitely seems like it'd be beneficial on text inputs asking for things like reference or document numbers, where spelling and autocorrect behaviours are not generally going to be helpful (I guess unless you have to enter the same reference number _a lot_ and the browser has learnt it as part of its dictionary)

**Comment by edwardhorsford** [comment]
I don't know about defaulting, but it would be great to document some of this somewhere - attributes services should consider.

My general default is to disable spellcheck by default for all inputs, but then enable for inputs accepting sentence-like answers.
