### ISSUE TITLE
Accordion non-js spacing on headers

### ISSUE THREAD

**Issue by dankmitchell** [alphagov/govuk-frontend#1130]
When disabling JS for an accordion; example - https://design-system.service.gov.uk/components/accordion/default/index.html

The spacing between the header and border is lost -

<img width="1392" alt="screen shot 2019-01-14 at 11 14 05" src="https://user-images.githubusercontent.com/3071606/51110088-30829e80-17ef-11e9-82e1-a630b2fbcce7.png">

**Comment by nickcolley** [comment]
I wonder if we should have borders too, @dashouse what do you think?
