### ISSUE TITLE
Investigate colour contrast issues within the footer component

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1135]
## What

Investigate whether there are issues with colour contrast within the footer component.

The links in the footer use dark grey (`#454a4c`) against light grey (`#dee0e2`), which technically at 6.8:1 meets [WCAG 2.1 AA standards for contrast](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) but has been flagged as potentially problematic for users with visual impairments.

|     | Text | Large Text |
|-----|------|------------|
| AA  | ✔️   | ✔️         |
| AAA | ❌   | ✔️         |

## Why

This was flagged in an audit of the design system (5th June 2018):

> "Despite surpassing AA contrast minimum, the grey on grey text could not be read. As a vision impaired user, who does not rely on assistive technology, this contrast provides little luminosity of text which allows for a distorted reading platform. Hovering over this area with a mouse also offers little indication that the link is clickable. This is a result of low contrast and poor font rendering.
>
> "The thicker and larger heading is clearly visible; however, the links are too light to decipher. Magnification provides little improvement.
>
> "Inverted contrast is needed in order to view this area of the page." (DAC-USER-LV-GT-T3-01)

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
