### ISSUE TITLE
SPIKE: Investigate CSS modules 

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1138]
## What

Based on discussions in https://github.com/alphagov/govuk-frontend/issues/1052, we could do a short spike to explore whether it's feasible for GOV.UK Frontend to support CSS modules by either:

1. Generating an extra `[filename].modules.scss` file as part of the build process.
2. Renaming our existing scss files to `[filename].module.scss` - this would be a breaking change.

## Why

We know that some teams in the community use [Create React App](https://github.com/facebook/create-react-app) to build services. We'd like to explore whether we can support these teams by making our scss files follow the naming convention.

## Tasks

- [ ] Investigate options 1 and 2, as well as any other viable options
- [ ] Make a recommendation on next steps

**Comment by nickcolley** [comment]
See https://github.com/alphagov/govuk-frontend/issues/1052#issuecomment-461003745
