### ISSUE TITLE
Explore options for making changes that work for users who are using Frontend alongside Elements / Template

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1140]
## What

There are a number of 'significant' changes that we think we want to make in the near future:

- [Add version 2 of the font to frontend](https://github.com/alphagov/govuk-frontend/issues/1012)
- [Investigate colour contrast issues with the focus state](https://github.com/alphagov/govuk-frontend/issues/1137)
- [Investigate colour contrast issues with hint text](https://github.com/alphagov/govuk-frontend/issues/1134)
- [Investigate colour contrast issues within the footer component](https://github.com/alphagov/govuk-frontend/issues/1135)
- [Investigate colour contrast issues with the header component](https://github.com/alphagov/govuk-frontend/issues/1133)
- [Investigate colour contrast issues within the panel component](https://github.com/alphagov/govuk-frontend/issues/1132)
- [Link hover state does not meet contrast requirements on font sizes below 18px](https://github.com/alphagov/govuk-frontend/issues/987)

We need to define our strategy for handling these changes when Frontend is used alongside the 'legacy' resources (GOV.UK Elements, GOV.UK Template). For example:

- Do we accept that within some services components from Frontend might use a different colour palette? For example, the focus state for different elements on the same page may differ.

- Do we accept that some services might require two versions of the same font to be downloaded by the user?

- Should we use the compatibility mode flag to 'switch' between the two fonts or colour palettes? If so, how long do we support both contexts for? How do we do this without introducing a need to manually review every change in these multiple contexts?

- Should we consider releasing new versions of the legacy codebases that include the same changes?

## Why

GOV.UK Frontend was designed to allow for gradual adoption by service teams so that they could, for example, gradually adopt a component at a time. We are seeing this work well so far on, for example, www.gov.uk.

We need to ensure that when we make 'significant' changes to Frontend we don't negatively impact on teams ability to update to use it.

## Done when

- [x] Documented publicly (potentially in the architecture repository)

**Comment by 36degrees** [comment]
Related: https://github.com/alphagov/govuk-frontend/issues/1001

**Comment by 36degrees** [comment]
Some of the team came together on Tuesday 22nd January to discuss this.

The aim of the session was to explore possible options, understand their pros and cons, and identify any additional work that might be required to support them.

Definitions
===========

**design changes**

Any changes that affect multiple components or the core styles of a page, such as the colour palette or font.

**Legacy products**

GOV.UK Frontend Toolkit, GOV.UK Template, GOV.UK Elements

**'transition to GOV.UK Frontend'**

Update the service to use the new markup, styles and JavaScript from the Design System.

**'current colour palette'**

The colour palette as used currently (as of 22nd January 2019)

**'revised colour palette'**

The colour palette after any changes required to comply with WCAG 2.1

Overview
========

The [Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018](http://www.legislation.gov.uk/uksi/2018/852/contents/made) means that public sector websites [must comply with the international WCAG 2.1 AA accessibility standard](https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps).

A new website (published on or after 23 September 2018) must meet the standards by 23 September 2019.

Existing websites must meet the accessibility standards from 23 September 2020.

In order to comply, we believe that we will need to make substantial changes to the colour palette in order to meet success criterion [1.4.11 Non-Text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html). For example, we may need to introduce changes to the focus state and link hover state.

GOV.UK Frontend is designed such that it can be gradually transitioned to, as it can 'co-exist' with the legacy products without impacting any of the existing styles. This avoids a 'big-bang' release, lowering the barrier to migration by allowing it to be done slowly alongside other work, and reducing risk.

Making substantial changes to the colour palette of GOV.UK Frontend could impact on this ability to transition in this way, as GOV.UK Frontend components on the same page as components from the legacy products would use a different palette. This may be particularly significant for focus states and colours used to denote interactivity, as detailed in scenario 1.

1\. Accept mixed colour palettes
================================

We would release a new version of GOV.UK Frontend that uses the new colour palette.

Services that use both the legacy products and GOV.UK Frontend would end up with a 'mix' of colour palettes, even within the same page. For example, components from GOV.UK Frontend would use the revised focus state, but other elements on the page will use the current focus state.

Steps to upgrade a service
--------------------------

1.  Update GOV.UK Frontend to the latest version, which will introduce the revised colour palette.

2.  Continue to transition the service to use GOV.UK Frontend. During this time, components from GOV.UK Frontend will use the revised colour palette, and existing elements on the page will use the existing colour palette.

3.  Once fully transitioned, remove the dependency on the legacy products. At this point, the colour palette would become consistent again.

Pros
----

-   Easy...

Cons
----

-   Inconsistency within services, even within a single page

-   Teams might try and 'bodge' it by modifying Elements, potentially making it harder to update

-   May result in more support requests

-   Potential reputational damage

-   Services may get 'stuck' in step 2, leaving them in an inconsistent state.

2\. Update the legacy products
==============================

We would release new versions of the legacy products (GOV.UK Frontend Toolkit, GOV.UK Template and GOV.UK Elements) which use the new colour palette.

We would also release a new version of GOV.UK Frontend that uses the new colour palette.

To get a consistent colour palette, service teams who are using both would need to update the legacy products before they could use the new version of GOV.UK Frontend.

Steps to upgrade a service
--------------------------

1.  Update GOV.UK Frontend Toolkit, GOV.UK Elements and GOV.UK Template to the latest versions, and then update GOV.UK Frontend to the latest versions. The revised colour palette is now applied.

2.  Test your service

Pros
----

-   Users don't have to change (much) markup in order to use the new colour palette

-   Adds less complexity to Frontend

-   More likely to happen?

-   Simpler to understand from the users point of view

-   Looks consistent with other pages on GOV.UK earlier in the update process

-   Colour contrast issues resolved earlier in the update process

Cons
----

-   Teams have to be able to update to the latest version of the legacy products before they can start using Frontend

-   Less incentive for users to upgrade as their service will 'look' up to date.

-   Our team doesn't  know the codebase that well

-   Service teams may not update the legacy products, which would have the same effect as scenario 1.

-   Looks like an up to date service earlier, but won't have any of the other accessibility fixes or improvements.

3\. GOV.UK Frontend supports both colour palettes
=================================================

We would release a new version of GOV.UK Frontend.

The colour palette used would be tied to the 'compatibility mode' flag. When compatibility mode is enabled, the old colour palette would be used, otherwise the new colour palette would be used.

Steps to upgrade a service
--------------------------

1.  Update GOV.UK Frontend to the latest version. Ensure the 'compatibility mode' flag is enabled. The colour palette does not change.

2.  Continue to transition the service to use GOV.UK Frontend.

3.  Once fully transitioned, remove the dependency on the legacy products and disable 'compatibility mode'. At this point, the new colour palette would kick in.

Pros
----

-   Consistent with our previous approaches (e.g. the way we introduced rem, which is disabled in compatibility mode)

-   Fits well with a 'soft-launch' of the new colour palette

-   Avoids a big bang change

-   Doesn't require changes to the legacy products

Cons
----

-   Requires us to actively support both use cases for a prolonged period (even for e.g. new components)

-   Introduces overhead in our testing, as we need to test all changes in both 'contexts'.

-   Colour palette will not meet colour contrast until the service is entirely transitioned.

-   Colour palette will be inconsistent with newer services until the service is entirely transitioned.

-   May impact accessibility of new components (e.g. may not be possible to create a component that meets colour contrast using the current

Additional work required
------------------------

-   Allow testing of components in the 'context of' legacy products (compatibility mode on, legacy products included) within the review app

-   Add visual regression testing to GOV.UK Frontend to test in both contexts

4\. Override styles from legacy products in GOV.UK Frontend
===========================================================

We would release a new version of GOV.UK Frontend.

When compatibility mode is on, GOV.UK Frontend would include additional selectors that override styles from the legacy products (for example, overriding the focus state defined in GOV.UK Template)

Steps to upgrade a service
--------------------------

1.  Update GOV.UK Frontend to the latest version. Ensure the 'compatibility mode' flag is enabled. This would apply selectors to override the palette in Elements

2.  Continue to transition the service to use GOV.UK Frontend.

3.  Once fully transitioned, remove the dependency on the legacy products and disable 'compatibility mode'. This would disable the additional selectors.

Pros
----

-   Doesn't require changes to the legacy products

-   Looks consistent with other pages on GOV.UK earlier in the update process

Cons
----

-   Overriding the styles will require higher specificity, which then means GOV.UK Frontend will need even more specificity to counter the overrides... specificity war!

-   Would be very hard to have confidence that this would work across e.g. different versions of the different legacy products

-   Not clear how this would affect custom styles within services

-   Hard to debug

-   Unexpected?

-   Uses the revised palette sooner, but won't have any of the other accessibility fixes or improvements.

-   Looks like an up to date service earlier, but won't have any of the other accessibility fixes or improvements.

-   Bloated CSS?

5\. ["Shame"](https://csswizardry.com/2013/04/shame-css/) stylesheet
====================================================================

We would release a new version of GOV.UK Frontend with the revised palette.

We would also share a 'shame' stylesheet, as a starting point for the services to 'patch' their legacy styles.

Steps to upgrade a service
--------------------------

1.  Update GOV.UK Frontend to the latest version.

2.  Download our 'shame' stylesheet and include it into your service. Iterate the shame stylesheet until everything looks right...

3.  Continue to transition the service to use GOV.UK Frontend.

4.  Once fully transitioned, remove the dependency on the legacy products and the 'shame' stylesheet.

Pros
----

-   Quick...?

-   Service teams have control over the overrides

Cons
----

-   See cons listed for 4...

-   Service teams may introduce very specific selectors / important rules which override styles in Frontend.

6\. Break backwards compatibility
=================================

We would release a new version of GOV.UK Frontend, adopting the revised colour palette and removing compatibility mode entirely.

Teams who wish to use the revised colour palette would need to migrate to the latest release of the previous major version, and then update.

Steps to upgrade a service
--------------------------

Assuming the breaking version is v3.0.0:

1.  Continue to transition the service to use GOV.UK Frontend 2.x.x.

2.  Once fully transitioned, remove the dependency on the legacy products.

3.  Update to GOV.UK Frontend v3.0.0

Pros
----

-   Clear end goal for transition phase

Cons
----

-   Service teams unable to use any new components / features introduced after 3.x until they have finished transitioning.

-   Probably requires us to version the Design System (at least 2.x.x / 3.x.x branches)

-   Will probably end up patching 2.x.x

## Appendix

<details>
  <summary><strong>Additional Notes</strong></summary>

-   We should talk to GOV.UK Publishing

-   We should play some of this back at Monday's Frontend meeting (28th January)

-   We need better documentation to help teams migrate to GOV.UK Frontend

-   We should talk to the accessibility team

-   Potentially stop trying to provide backwards compatibility after 23rd September 2020?

</details>

<details>
  <summary><strong>Original Whiteboard Notes</strong></summary>

![img_6502](https://user-images.githubusercontent.com/121939/51601655-e1c6ba00-1efc-11e9-865b-0dc4830dd255.JPG)


</details>

**Comment by kellylee-gds** [comment]
@36degrees agreed in planning we would document our decision and raise further issues for next steps

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
