### ISSUE TITLE
Date component allows some weird characters

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#115]
The Date component allows users to input some non-numeric characters`e`, `.`, `+` and `-`

**Comment by gemmaleigh** [comment]
Related: https://github.com/alphagov/govuk-frontend/pull/117 

Hanna if you could take a look, that would be ace!

**Comment by hannalaakso** [comment]
These are all allowable characters for a numeric field. See [here](https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in) for discussion on letter "e".

**Comment by hannalaakso** [comment]
Hi Gemma,

Assigning this to you to review. Let me know if there are any more actions for me here.

Thanks,
Hanna

**Comment by nickcolley** [comment]
Is this still an issue @hannalaakso ? Can we close?

**Comment by hannalaakso** [comment]
Yes we can close - this markup no longer exists in GOV.UK Frontend.
