### ISSUE TITLE
[SPIKE] Decide approach to enabling review app to include legacy apps code for testing purposes

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1158]
## What
We need to be able to run the review app to run with two different scenarios/settings:

### Scenario 1
What we have right now:
Include GOV.UK Frontend assets, with [compatibility flags](https://github.com/alphagov/govuk-frontend/blob/master/src/settings/_compatibility.scss) **off** 

### Scenario 2
Include GOV.UK Frontend and the stylesheets/JS from legacy repos Elements, Frontend Toolkit and GOV.UK Template, with compatibility flags **on** 

We're going to need to decide how the app should run the two scenarios to make it easy for us to find any potential differences resulting from the inclusion of the legacy stuff. 

## Why
We need to ensure that including the legacy code doesn't interfere with GOV.UK Frontend styles and components. We can use our existing tests and manually check for visual differences (ideally we'd implement visual regression testing to handle this at a later point). 

Doing this would be super helpful in making sure that the upcoming changes we're having to make to meet WCAG 2.1. and which will affect the styles of the legacy stuff can be gradually migrated to by service teams 😎 

## Done when:
- [ ] Speak with devs in team and make a decision on approach
- [ ] TBC: Implement whatever gets decided

**Comment by nickcolley** [comment]
Oops sorry

**Comment by hannalaakso** [comment]
We discussed with devs and decided the following:
- We want to be able to switch including the legacy repos in review app on and off 
     - This could be implemented with a query string or a specific URL you go to
- There will therefore be four scenarios to test:
    1. Compatibility mode on, legacy repos not included
       - Use the current colour palette
       - Use the new focus styles
    2. Compatibility mode off, legacy repos not included
       - Use the new colour palette
       - Use the new focus styles
    3. Compatibility mode on, legacy repos included
       - Use the current colour palette
       - Use the new focus styles
       - Optional: Include some components from legacy repos on the page
    4. Compatibility mode off, legacy repos included
       - Use the new colour palette
       - Use the new focus styles 

It would be awesome to implement some visual regression testing to test the above but we probably don't have the capability to do this right now.

Created https://github.com/alphagov/govuk-frontend/issues/1262 for the work
