### ISSUE TITLE
Should inputs with active error state be adjusted to remain the same size as inputs without an error?

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#119]
**Potential problem:**
When an input has an error it's border is increased from 2px to 4px. This means that input will become physically bigger than it's previous state.

When this input is in-line or part of a tight lockup with another element the component parts will become mis-aligned.

Should we adjust the padding of the input error state to compensate for the increased border?

For example 

```
.govuk-c-input {
        padding: 5px 4px 4px;
}
.govuk-c-input--error {
        padding: 3px 2px 2px;
}
```

Before | After
<img width="600" alt="screen shot 2017-07-06 at 16 15 39" src="https://user-images.githubusercontent.com/23356842/27918481-064c6ef0-6267-11e7-9ab7-eaee4c81b144.png">

Is there an alternative way of doing this with box-sizing?

**Comment by nickcolley** [comment]
Messing with http://govuk-elements.herokuapp.com/errors/example-form-validation-multiple-questions it doesnt seem to happen, 🤔 

![screen shot 2017-07-06 at 16 39 12](https://user-images.githubusercontent.com/2445413/27919491-b52a125e-6269-11e7-879c-55ebccc3024f.png)

**Comment by igloosi** [comment]
we could do 
```
    border: 2px solid #b10e1e;
    box-shadow: inset 0 0 0 1px #b10e1e;
```

**Comment by edwardhorsford** [comment]
We came up on something similar with an inline error for the character count. I imagine Pay may have had similar challenges.

**Comment by gemmaleigh** [comment]
The border should be larger for inputs with an error, as @nickcolley pointed out in high contrast mode - changing to a border of the same width would make the fields with an error indistinct from those without an error.

![image](https://user-images.githubusercontent.com/417754/28312785-4f500866-6bac-11e7-816e-e559676211f8.png)

For now, we have gone with adjusting the padding - so the border width is thicker, but the overall input height remains the same.
