### ISSUE TITLE
Namespacing [data-module] to avoid conflicts

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1218]
One of the main aims for GOV.UK Frontend is to ensure we do not break services code.

Namespacing is a big part of this, by prefixing certain parts of the codebase with `govuk-` and encouraging services to use `departmentName-` or `app-` we can have more confidence that we will not break their code.

GOV.UK Publishing ran into an issue where their version of accordion code was conflicting with ours: https://github.com/alphagov/collections/pull/1042

I've raised this issue to discuss the impact of this and if we should consider changing the namespace.

Changing the namespace without keeping backwards compatibility would be a breaking change, as always we need to weigh up the risk of not doing this with the risk of making it too hard for people to upgrade in the future.

**Comment by aliuk2012** [comment]
Regarding HTML data attributes there are potentially two options:

`data-govuk-module="accordion"` or `data-module="govuk-accordion`

I prefer the first one because I think we should namespace the key not the value. Its also easier to find with css attribute selectors `[data-govuk-module]` vs `[data-module="govuk-modules"]`

**Comment by nickcolley** [comment]
The way I think about our current setup is it is a halfway house towards custom elements (web components).

In that world, you register a component with a single string so in my mind [data-module="govuk-accordion"] aligns closest to that.

**Comment by nickcolley** [comment]
We asked the community about this idea and it has been accepted: https://github.com/alphagov/govuk-design-system-architecture/pull/16

Rendered: https://github.com/alphagov/govuk-design-system-architecture/blob/master/proposals/006-initialise-javascript-using-govuk-namespaced-data-module-attributes.md

**Comment by aliuk2012** [comment]
Closed #1443
