### ISSUE TITLE
Create RFC for passing options to components in Javascript

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1223]
The purpose is to collect some feedback from the community on adding a programmatic API for the components, in addition to the data API we already use. 

This would also fix https://github.com/alphagov/govuk-frontend/pull/1215 without making a breaking change.

**Comment by nickcolley** [comment]
Started a spike into this https://github.com/alphagov/govuk-frontend/pull/1238

**Comment by nickcolley** [comment]
We are closing this as we thought this was the best way to solve https://github.com/alphagov/govuk-frontend/pull/1215 but now we need more evidence that there's a need for this work, so can explore this again in the future.
