### ISSUE TITLE
Firefox visual bug with back button

### ISSUE THREAD

**Issue by BNewing** [alphagov/govuk-frontend#1236]
This is a tiny issue, but on Firefox, the focus state of the back button has a little visual bug. It has a small white line at the top, which breaks the background highlighting:

<img width="96" alt="image" src="https://user-images.githubusercontent.com/16868713/53803120-a4157200-3f3b-11e9-8860-dda18bd741b4.png">

I found this on a project I was working on and the workaround I implemented was to add a border to the element and make it the same colour as the focus state when focused, and transparent when  not focused.

**Comment by dashouse** [comment]
@BNewing Thanks Beverley, we're in the process of updating the focus style more generally for WCAG 2.1 compliance and the current proposal also fixes this issue.

We'll keep this open so we can refer to it when that work is complete and make sure that is addressed.

**Comment by 36degrees** [comment]
Just to confirm that this has been fixed as part of the focus state changes, and will be going out in GOV.UK Frontend 3.0.

<img width="124" alt="Screen Shot 2019-05-20 at 15 20 34" src="https://user-images.githubusercontent.com/121939/58028546-df731600-7b12-11e9-8a64-17aaada13395.png">
