### ISSUE TITLE
Tabs with weird content rendering without JS

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-frontend#1246]
If I disable js on my computer (Chrome 72.036), I get this:

<img width="583" alt="Screen Shot 2019-03-13 at 10 25 06" src="https://user-images.githubusercontent.com/2204224/54271997-99ca2800-457a-11e9-8ab9-27a25d511c57.PNG">

For [this](https://design-system.service.gov.uk/components/tabs/default/index.html) url.

**Comment by nickcolley** [comment]
My initial thought is that we're not using the encoded character in the CSS which could be the issue: `"— "`

I cannot reproduce this though on my laptop.

Could you let me know the what operating system and version you're using?

**Comment by edwardhorsford** [comment]
Sorry - I'm using OSx 10.13.4

**Comment by edwardhorsford** [comment]
Looks ok on firefox for me - though spacing after the menu is a bit tight.

**Comment by stevesims** [comment]
I see what's in the above screenshot if I change the text encoding in my browser from "default" (i.e. utf-8) to "ISO Latin 1".

**Comment by nickcolley** [comment]
@stevesims thanks a lot, I'll have a look into this.
