### ISSUE TITLE
SASS fails to compile in Scala Play project [sbt-sassify]

### ISSUE THREAD

**Issue by kiddhustle** [alphagov/govuk-frontend#1254]
I see an error when trying to compile a sass file which includes govuk-frontend. 

Tech stack:

- Scala Play 2.4
- SBT-Sassify (lib sass 3.4)
- 

```play.sbt.PlayExceptions$CompilationException: Compilation error[Error: Unknown colour `"blue"`
        on line 20 of node_modules/govuk-frontend/helpers/_colour.scss
>>     @error "Unknown colour `#{$colour}`";
   ----^
]```

I am wondering if the error is down to the version of libsass being used?

**Comment by nickcolley** [comment]
Heya @kiddhustle :),

Thanks for the issue, can you have a check and see if you're using version 2.8.0 or above of `govuk-frontend`?

We fixed an issue recently that might be related:

https://github.com/alphagov/govuk-frontend/blob/master/CHANGELOG.md#280-feature-release

https://github.com/alphagov/govuk-frontend/pull/1235

**Comment by kiddhustle** [comment]
Hi @nickcolley thanks for the quick reply

I checked the version and we are using `2.9.0`

```
"dependencies": {
    "govuk-frontend": "^2.9.0"
  },
```

**Comment by kiddhustle** [comment]
Just double-checking which version of `lib-sass` we are using on our project. Compilation is being handled by the Scala Play framework so currently trying to find where the version is defined

**Comment by theDustRoom** [comment]
We're running a Scala Play application with no issues.
sbt-sassify 1.4.11 which uses libsass version 3.4.9

**Comment by kiddhustle** [comment]
@theDustRoom we are also using sbt-sassify 1.4.11

And yes we are import all like this:

`@import "node_modules/govuk-frontend/all";`

This should work OK right?

**Comment by theDustRoom** [comment]
Yes; we've been using GOV.UK Frontend within our project for ages now without issue - we're using 2.9.0 now but have used the different versions pretty much from release.

You're not overriding $govuk-colours or anything are you?

**Comment by kiddhustle** [comment]
@theDustRoom we are only now migrating from the legacy GOV.UK Elements/Frontend Toolkit/Template etc.

I don't see anything overriding that variable.

I will try and importing only `govuk-frontend` and a few other things and see if I can get anything to work.

I will let you guys know if I find the cause of the problem.

Thanks

**Comment by kiddhustle** [comment]
@theDustRoom @nickcolley I had fresh look at this this morning, and it turns out oour project is currently using `sbt-sassify v.1.4.2` (the person I asked has upgraded to `1.4.11` on his feature branch).

Upgraading to `1.4.11` fixed the problem. Sorry for the confusion, and thanks for the help!
