### ISSUE TITLE
Publish linting rules

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk-frontend#1256]
As part of [GOV.UK efforts to align it's coding standards and style guide with this project](https://github.com/alphagov/govuk_publishing_components/pull/758) we will need the linting rules to be publisher (whether with this package or a separate one) so we can [use it via CI for linting projects across GOV.UK](https://github.com/alphagov/govuk-rfcs/pull/100).

Related issue: https://github.com/alphagov/govuk-frontend/issues/1121

**Comment by 36degrees** [comment]
Depends on #1740

**Comment by vanitabarrett** [comment]
This has been done in [stylelint-config-gds](https://github.com/alphagov/stylelint-config-gds) which we're in the process of adopting and GOVUK is trialling.
