### ISSUE TITLE
Update styles and components to comply with WCAG 2.1

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1263]
Checklist:
- [x] Update to new colour palette
- [x] Meet with devs to agree on actual changes, esp breaking stuff such as markup changes
- [ ] Update styles and components (might want to break this into separate cards following above meeting)
- [ ] Test everything in [four review app scenarios](https://github.com/alphagov/govuk-frontend/issues/1262) with browsers and assistive technology

**Comment by kellylee-gds** [comment]
This epic has been broken down into smaller stories:

[Update links (and things that look like links) to use the new focus style #1302](https://github.com/alphagov/govuk-frontend/issues/1302)

[Update radios and checkboxes to use the new focus state #1304](https://github.com/alphagov/govuk-frontend/issues/1304)

[Update form inputs to use the new focus state #1303](https://github.com/alphagov/govuk-frontend/issues/1303)

[Update buttons to use the new styles and the new focus state #1305](https://github.com/alphagov/govuk-frontend/issues/1305)

[Update tabs to use the new styles and the new focus state #1306](https://github.com/alphagov/govuk-frontend/issues/1306)

[Update accordion to use the new styles and the new focus state #1307](https://github.com/alphagov/govuk-frontend/issues/1307)

**Comment by kellylee-gds** [comment]
Closing issue as it has been broken down into smaller stories
