### ISSUE TITLE
Add documentation for individual component initialisation with the new scope feature

### ISSUE THREAD

**Issue by kr8n3r** [alphagov/govuk-frontend#1267]
In the documentation it is mentioned if you need to [initialise all of frontend in specific sections](https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md#initialise-govuk-frontend-in-only-certain-sections-of-a-page)

Nothing about it is said when importing and [initialising individual components](https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md#initialise-individual-included-components)

For example. to initialise the Accordion, you might look into `all.js` and copy the example
```
var $accordions = scope.querySelectorAll('[data-module="accordion"]')
  nodeListForEach($accordions, function ($accordion) {
    new Accordion($accordion).init()
  })
```
which will result in an error `scope not defined`.

You can easily miss the definition higher up:
`var scope = typeof options.scope !== 'undefined' ? options.scope : document`

which you'd need to put in your app.js.

**Comment by nickcolley** [comment]
Re-opening this just because ideally we should have features documented in the future, even if people are not asking for it a lot.

**Comment by vanitabarrett** [comment]
We think this is probably covered by the following docs now:

https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#select-and-initialise-an-individual-component

https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#select-and-initialise-part-of-a-page
