### ISSUE TITLE
Header component script is not compatible with govuk_template

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk-frontend#1270]
### Context
govuk_template has [an IIFE for header navigation toggle](https://github.com/alphagov/govuk_template/blob/f164b2825b1479d7c7d4bdbec4ba9c8e171f504c/source/assets/javascripts/core.js#L11) which adds functionality to elements that have a `.js-header-toggle` class attached to it.

The header component in govuk-frontend [uses the same `.js-header-toggle` class](https://github.com/alphagov/govuk-frontend/blob/master/src/components/header/header.js#L16) (applied to a button element) to toggle the header.

### Problem
Because the govuk_template script is expecting an anchor instead of a button, it tries to get the `href` attribute and fails to do so if the header component from govuk-frontend is used.

<img width="459" alt="Screen Shot 2019-04-10 at 15 37 29" src="https://user-images.githubusercontent.com/788096/55888136-c471c580-5ba6-11e9-86af-e5fb7ce37e06.png">

### Potential solution
Prefix or change `js-` classes to avoid clashed with other scripts (including the deprecated ones).

I'm happy to raise a PR myself since I think I introduced this bit of code, but I need a decision at the team level on what the solution should be.

**Comment by nickcolley** [comment]
Adding this to the 3.0.0 milestone as a point of discussion, potentially we should be reviewing more than just this class and considering if they should be using a 'js-govuk' prefix.

**Comment by nickcolley** [comment]
We have decided to change our uses of 'js-' to be 'govuk-js-' as per @hannalaakso 's suggestion.

**Comment by aliuk2012** [comment]
Should be fixed in v3.0.0. Closing this as #1444 has been merged.
