### ISSUE TITLE
More spacing between bulleted list items containing longer text

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/govuk-frontend#1272]
Our services uses bulleted lists for summaries of facts and figures, eg:

<img width="701" alt="Screenshot 2019-04-12 at 13 08 02" src="https://user-images.githubusercontent.com/30665/56036240-3cb1c580-5d24-11e9-9025-548c65e90b62.png">

These have tested well, and it's a common pattern also used by ONS in their statistical bulletins (see [example](https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/bulletins/uktrade/february2019)).

We are spacing the bullets out more than the default, as otherwise they are harder to scan, eg:

<img width="672" alt="Screenshot 2019-04-12 at 13 17 16" src="https://user-images.githubusercontent.com/30665/56036707-69b2a800-5d25-11e9-8bbb-31da4e320133.png">

We are currently using this custom modifier to space the bullets out a bit more:

```css
.eff-list--sparse > li {
  @include govuk-responsive-margin(4, "bottom");
}
```

Is this something we could contribute back to the Design System perhaps? I feel like it may be useful for others too.

**Comment by nickcolley** [comment]
This came up when building some new forms, might be worth considering so putting awaiting triage on.

**Comment by timpaul** [comment]
> This came up when building some new forms, might be worth considering so putting awaiting triage on.

Yes, we had a similar need on one of the new coronavirus related services. A big long list of medical conditions that would have been hard to scan without additional spacing.
