### ISSUE TITLE
Various peerDependencies are missing

### ISSUE THREAD

**Issue by colinrotherham** [alphagov/govuk-frontend#1273]
Have you noticed various peerDependency warnings are output on every install?

### How to reproduce

```
npm ci
npm ls
```

Output (excerpt):

```
npm ERR! peer dep missing: gulp@>=4, required by gulp-debug@4.0.0
npm ERR! peer dep missing: gulp@>=4, required by gulp-nunjucks@4.0.0
npm ERR! peer dep missing: eslint@>=5.0.0, required by eslint-config-standard@12.0.0
npm ERR! peer dep missing: eslint@>=5.0.0, required by eslint-config-standard-jsx@6.0.2
npm ERR! peer dep missing: eslint@>=4.19.1, required by eslint-plugin-node@7.0.1
npm ERR! peer dep missing: eslint@^3.0.0 || ^4.0.0 || ^5.0.0, required by eslint-plugin-react@7.11.1
npm ERR! peer dep missing: eslint@>=5.0.0, required by eslint-plugin-standard@4.0.0
npm ERR! peer dep missing: eslint@>=4.19.1, required by eslint-plugin-es@1.4.0
```

One of these (`eslint`) is easy to resolve, but one (`gulp`) will require an upgrade to Gulp v4.

I'd recommend running `npm ls` before the tests to ensure no package dependencies are broken. I'll open a pull request 😊

**Comment by colinrotherham** [comment]
I'll update some out-of-date packages too.

### Before

```
found 290 vulnerabilities (67 low, 210 moderate, 13 high) in 26039 scanned packages
  run `npm audit fix` to fix 30 of them.
  260 vulnerabilities require semver-major dependency updates.
```

### After

```
found 11 vulnerabilities (3 low, 2 moderate, 6 high) in 884815 scanned packages
  6 vulnerabilities require semver-major dependency updates.
  5 vulnerabilities require manual review. See the full report for details.
```

Without any breaking changes.

**Comment by colinrotherham** [comment]
I went ahead and upgrade every single package in https://github.com/alphagov/govuk-frontend/pull/1277, and fixed all the breaking changes:

```
found 5 vulnerabilities (2 low, 1 moderate, 2 high) in 890376 scanned packages
  5 vulnerabilities require manual review. See the full report for details.
```

There are still a few vulnerabilities in `sassdoc`, `node-sass` and `gulp-sass` but I'm sure these will be fixed in due course.

**Comment by colinrotherham** [comment]
This can be closed now https://github.com/alphagov/govuk-frontend/pull/1277 has been merged

**Comment by hannalaakso** [comment]
Thanks again for your work on this @colinrotherham 👍
