### ISSUE TITLE
Check that Frontend works with overridden text style properties

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1285]
Ensure that Frontend works with overridden text style properties, allowing it to meet [Success Criterion 1.4.12 Text Spacing](https://www.w3.org/TR/WCAG21/#text-spacing)

https://knowbility.org/blog/2018/WCAG21-1412TextSpacing/

https://www.w3.org/WAI/GL/wiki/Results_of_Bookmarklet_Tests_for_Issue_78

**Comment by 36degrees** [comment]
Tested by adding the following code to the review app:

```
// Based on https://www.html5accessibility.com/tests/tsbookmarklet.html
[class^="govuk-"] {
  line-height: 1.5 !important;
  letter-spacing: 0.12em !important;
  word-spacing: 0.16em !important;
}

.govuk-body {
  margin-bottom: 2em !important;
}
```

And checking all of the example pages for issues.

Aside from some minor cosmetic issues (such as the ! icon in the warning text component being skewed), I couldn't see any instances of text being cut off or overlapping, nor text not adjusting as expected (except where styles from Elements are being used)

## Announcements
![announcements](https://user-images.githubusercontent.com/121939/57622002-a53ecd00-7584-11e9-9729-8ae29165499f.jpg)

## Applicant details
![applicant-details](https://user-images.githubusercontent.com/121939/57622003-a5d76380-7584-11e9-99da-e3bed0010823.jpg)

## Bank holidays
![bank-holidays](https://user-images.githubusercontent.com/121939/57622004-a5d76380-7584-11e9-9d2a-4dc40453d8ea.jpg)

## Check your answers
![check-your-answers](https://user-images.githubusercontent.com/121939/57622005-a5d76380-7584-11e9-9908-02093ad08cb5.jpg)

## Confirm delete
![confirm-delete](https://user-images.githubusercontent.com/121939/57622007-a5d76380-7584-11e9-9072-8c2a860a65ac.jpg)

## Feedback
![feedback](https://user-images.githubusercontent.com/121939/57622008-a5d76380-7584-11e9-9fd3-deaf8f4e76a9.jpg)

## Have you changed your name
![have-you-changed-your-name](https://user-images.githubusercontent.com/121939/57622009-a5d76380-7584-11e9-91a6-5e181601d91b.jpg)

## How do you want to sign in
![how-do-you-want-to-sign-in](https://user-images.githubusercontent.com/121939/57622010-a66ffa00-7584-11e9-9e87-9560c897e6c3.jpg)

## News and communications
![news-and-communications](https://user-images.githubusercontent.com/121939/57622012-a66ffa00-7584-11e9-9549-20fb82a23aa5.jpg)

## Passport details
![passport-details](https://user-images.githubusercontent.com/121939/57622013-a66ffa00-7584-11e9-8e35-fd958d2ecb53.jpg)

## Renew driving licence
![renew-driving-licence](https://user-images.githubusercontent.com/121939/57622014-a66ffa00-7584-11e9-8ee9-1aaec4905826.jpg)

## Service manual topic
![service-manual-topic](https://user-images.githubusercontent.com/121939/57622017-a7089080-7584-11e9-815b-3c29b4463871.jpg)

## Start page
![start-page](https://user-images.githubusercontent.com/121939/57622018-a7089080-7584-11e9-916e-940b900509d3.jpg)

## Update your account details
![update-your-account-details](https://user-images.githubusercontent.com/121939/57622020-a7089080-7584-11e9-94c5-861a564fd682.jpg)

## Upload your photo
![upload-your-photo](https://user-images.githubusercontent.com/121939/57622022-a7089080-7584-11e9-8a04-470b3f96c941.jpg)

## What is your address
![what-is-your-address](https://user-images.githubusercontent.com/121939/57622023-a7089080-7584-11e9-8424-c6e66b464882.jpg)

## What is your nationality
![what-is-your-nationality](https://user-images.githubusercontent.com/121939/57622024-a7a12700-7584-11e9-85a4-0717db926b49.jpg)

## What is your postcode
![what-is-your-postcode](https://user-images.githubusercontent.com/121939/57622025-a7a12700-7584-11e9-9eb7-e0ce5b80d163.jpg)

## What was the last country you visited
![what-was-the-last-country-you-visited](https://user-images.githubusercontent.com/121939/57622026-a7a12700-7584-11e9-80fc-b3fd4a4af67b.jpg)

**Comment by 36degrees** [comment]
I'm going to close this as I don't think there's anything we need to fix.
