### ISSUE TITLE
Open-ssl error for pull requests opened from forks

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk-frontend#129]
The environment variables for Tenon aren't available for forks: 
https://travis-ci.org/alphagov/govuk-frontend/jobs/252049398#L457

The build fails and the tests don't run.
Ideally the tests should run, even if we can't run Tenon to check components from forks.

Needs further investigation.

**Comment by nickcolley** [comment]
Don't believe this is a problem anymore: https://github.com/alphagov/govuk-frontend/pull/538
