### ISSUE TITLE
Add ability to set attributes on `body` in Template

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-frontend#1293]
It should be possible to set custom attributes in Template `body`. User need detailed here: https://github.com/alphagov/govuk_template/pull/285

Split from: https://github.com/alphagov/govuk-frontend/issues/971

Part of https://github.com/alphagov/govuk-design-system/issues/777

**Comment by aliuk2012** [comment]
Linked to https://github.com/alphagov/govuk-design-system-backlog/issues/185

**Comment by nickcolley** [comment]
Since this was asked for in the old project I'm going to close this for now and see if someone else needs it.
