### ISSUE TITLE
Documented xlink:href on SVG fallback image is… missing…

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1299]
In the header component, we talk about the importance of the (empty) `xlink:href` attribute in the fallback `<image>` tag:

https://github.com/alphagov/govuk-frontend/blob/8370f97b1ac7c7499df2a8b155d44c6f7136a17a/src/components/header/template.njk#L35-L39

However, we don't actually include that attribute:

https://github.com/alphagov/govuk-frontend/blob/8370f97b1ac7c7499df2a8b155d44c6f7136a17a/src/components/header/template.njk#L43

🤔 

We do [include the xlink:href attribute in the Design System](https://github.com/alphagov/govuk-design-system/blob/d6ac9f9bdecdcc5719a26ba3dc14df0210def4ae/views/partials/_header.njk#L31) where the header component originated from  – it looks like it was omitted when the component was copied in #695.

We should double check whether this attribute actually does have the effect we say it does (https://css-tricks.com/a-complete-guide-to-svg-fallbacks/ suggests it does), and then either reintroduce the missing attribute or update the documentation.

**Comment by nickcolley** [comment]
The article suggests that it does work, but without it it downloads the logo unnecessarily: 

"In most browsers, therefore, it is sufficient to include an <image> tag with a src attribute (pointing to your fallback image) inside your inline SVG: the old browsers will download the fallback, the new browsers won't. Except for Internet Explorer, which downloads the fallback image even when it doesn't display it. The solution is to put a null xlink:href attribute on the element. The IE developer tools still show it requesting the fallback, but it aborts almost immediately (<1ms in IE11 or IE10/IE9 emulation mode), before downloading anything. It looks like this:"
