### ISSUE TITLE
Update accordion to use the new styles and the new focus state

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#1307]
## What

Update accordion to use the new focus style as per the [preview branch](https://github.com/alphagov/govuk-frontend/pull/1245).

## Why

We're updating the focus style as part of [making the Design System meet WCAG 2.1](https://github.com/alphagov/govuk-design-system/issues/677) – specifically with regard to WCAG 2.1 1.4.11 Non-Text Contrast (#1137).

## Done when…

- [x] Accordion updated to use the new focus state
- [x] Tested in all [browsers that we support](https://github.com/alphagov/govuk-frontend#browser-support)
- [x] Tested in legacy mode (using the deprecated libraries)
- [x] Tested with zoom up to 400%
- [ ] Tested with ZoomText
- [ ] Tested in Windows High Contrast mode
- [ ] Tested with overridden colours in the browser

**Comment by 36degrees** [comment]
Closed by #1324
