### ISSUE TITLE
Textarea error border overhangs on IE8

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1311]
In modern browsers the 30px bottom margin both on `govuk-textarea` and `govuk-form-group` would just collapse. On IE8 the component ends up having 30px `bottom-margin` which pushes the error border out.

![Screen Shot 2019-05-01 at 14 39 12](https://user-images.githubusercontent.com/5007934/57019818-72f5ad00-6c1f-11e9-9522-790e32ed1652.png)

**Comment by kellylee-gds** [comment]
Since internet explorer 8 is functional only, we have decided the time it would take to fix this is not worth the effort.
