### ISSUE TITLE
Test the pre-release of GOV.UK Frontend 3.0 with developers

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-frontend#1349]
## What
We need to publish and test a pre-release of v3 to test with teams. So far GOV.UK Publishing, GOV.UK Pay and Digital Marketplace have agreed to help us test this.

## Why
Give us confidence that v3 is ready for official release and to help identify any issues for services migrating over to v3.

## Who needs to know about this
Developers, Mark

## Further detail
We will also test the [release notes](https://github.com/alphagov/govuk-frontend/issues/1348) in conjunction with the pre-release.

## Done when

- [x] Created a pre-release, including DAC changes, name spacing changes and font v2
- [x] Finished pre-release notes
- [x] Agreed timings with teams that have agreed to help us
- [x] Decided who on the team will observe each migration test
- [x] Received feedback from teams

**Comment by aliuk2012** [comment]
GOV.UK Pay would like to be involved in pre-release testing

**Comment by kellylee-gds** [comment]
Closed as moved to done
