### ISSUE TITLE
Incorrectly nested landmarks in GOV.UK Frontend review application

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1399]
This issue is from a May 2019 external accessibility audit report.

**WCAG Reference**: [4.1.1 Parsing (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/parsing.html)
**Issue ID**: DAC_Issue15
**URL**: http://govuk-frontend-v3.herokuapp.com/full-page-examples/bank-holidays

## Summary

The ‘aside’ landmark had been incorrectly placed within the `<main>` element

## Screen Shot
![](https://user-images.githubusercontent.com/2445413/58708945-f5a19180-83b0-11e9-9636-ca794837e92c.png)

The ‘aside’ landmark has been placed inside the ‘main’ element which is not semantic. This did not affect users, however.

## Current Code Ref(s)
```html
<aside class="app-related-items" role="complementary"> <h2 class="govuk-heading-m" id="subsection-title"> Related content </h2> <nav role="navigation" aria-labelledby="subsection-title"> <ul class="govuk-list govuk-!-font-size-16"> <li class="gem-c-related-navigation__link"> <a class="govuk-link" href="#/holiday-entitlement-rights">Holiday entitlement</a> </li>
<li class="gem-c-related-navigation__link"> <a class="govuk-link" href="#/school-term-holiday-dates">School term and holiday dates</a> </li> </ul> </nav> </aside> </div> </main>
```

## Solution
Ensure that all landmarks are nested correctly and that the ‘aside’ is placed outside of the ‘main’ element.

**Comment by nickcolley** [comment]
I've put `awaiting-triage` on this since I think we should discuss if this issue is a mistake with how we implemented this review page, or something that we encourage by the design of the [page template](https://design-system.service.gov.uk/styles/page-template/).

**Comment by 36degrees** [comment]
We have decided to ignore this recommendation for now, as this doesn't appear to impact users and there doesn't appear to be anything in the spec that prevents `<aside>` elements from appearing within `<main>` elements.

The HTML 5.1 spec does say:

> The main content area of a document includes content that is unique to that document and excludes content that is repeated across a set of documents such as site navigation links, copyright information, site logos and banners and search forms (unless the document or application’s main function is that of a search form).
>
> – https://www.w3.org/TR/html51/grouping-content.html#elementdef-main

However we are using `<aside>` elements for _related_ links, which do have a semantic relationship to the content within `<main>` and theoretically could be unique to each page.

(See also Example 40 in the spec, which shows an `<aside>` within a `<main>`, albeit for contextual prose)

We should revisit this decision if we find that this has a tangible impact on users.

(Note also that the pages on GOV.UK from which these examples are drawn _do_ have the `<main>` wrapped only around the two-thirds column. They also do not use an `<aside>`, just a `<nav>`)
