### ISSUE TITLE
Make all form elements the same height

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#141]
If our form elements were the same height it would make it much easier to maintain a vertical rhythm and to create horizontal form layouts where necessary.

For example, we sometimes need to align buttons to the right of form fields (eg. search boxes). They'd look a lot nicer if they were the same height.

I'm thinking of the following elements in particular: radios, checkboxes, text fields, select boxes, type-aheads, buttons.

**Comment by edwardhorsford** [comment]
Somewhat relevant - I feel like our inputs on mobile (text input, select, etc) could be bigger.

Right now we scale our font down on mobile, but we don't scale our checkboxes or radios - we should have a look and see what the correct size is.

**Comment by igloosi** [comment]
touch points recommendation is 44px at least

**Comment by igloosi** [comment]
to do this do we need to involve anyone else?

**Comment by gemmaleigh** [comment]
I'd imagine @dashouse would want to be involved.

**Comment by igloosi** [comment]
ok so our normal button is 40px but our start button is 45px
our checkbox/radio are 38px and dont change on mobile
select is 33px on desktop but as the font changes on mobile breakpoint, it becomes only 28px tall

 if we were to normalize heights, i'd be good to establish a common size and behaviour on breakpoints

**Comment by gemmaleigh** [comment]
What about increasing the input height to 40px, making radio buttons and checkboxes the same - then they would also line up with the button. 

The text size for these inputs is currently 16px for smaller screens and 19px for tablet and up. 

We could increase the text size for smaller screens to 19px but we would need to change the other typography mixins too, as all text is set to be smaller initially and then increase in size for larger screens.

**Comment by igloosi** [comment]
to start with we could just change the size on the items and leave typography for later. only element that relies on font for it's size is select (setting fixed size on that makes the nta font not vertically aligned to the box !)

**Comment by edwardhorsford** [comment]
@gemmaleigh on paper that sounds sensible.

Can we get options deployed somewhere so we can test on a range of devices? This is one I think we really need to play with.

**Comment by gemmaleigh** [comment]
See #160.

**Comment by 36degrees** [comment]
Closed by #160.
