### ISSUE TITLE
Report bug for NVDA date input issue

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1423]
## What

We should [should raise an issue with NVDA](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md) to report what we have found with `[type=number]`: https://github.com/alphagov/govuk-frontend/issues/1408

## Why

NVDA are aware of the issue that could impact the rest of the web

## Done when

- [x] Bug is raised with NVDA
- [x] Bug report is added to reported bugs repo: https://github.com/alphagov/reported-bugs

**Comment by 36degrees** [comment]
Done.

https://github.com/alphagov/reported-bugs/issues/41
