### ISSUE TITLE
Update tabs and accordion components to use simpler focus state

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1424]
## What

In the recent accessibility audit we found that the focus styles for the tabs component and accordion component were confusing.

Dave has prototyped how this should look and it has been agreed as a team: https://github.com/alphagov/govuk-frontend/pull/1394

## Why

- Make these components focus state clearer

## Done when

- [x] Tabs component matches Dave's prototype
- [x] Accordion component matches Dave's prototype
- [x] Close associated issue https://github.com/alphagov/govuk-frontend/issues/1405

**Comment by aliuk2012** [comment]
fixed in #1445
