### ISSUE TITLE
Build a user research prototype to test GOV.UK Frontend 3.0

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1428]
The prototype should be of a plausible service with a broad range of users, to make recruitment of participants easier.

It should contain at least one example of all the proposed design changes in GOV.UK Frontend 3.0 - the version with the simpler focus state styles for tabs and accordions.

One option is to reuse and update the [Temporary Events Notice prototype](https://govuk-temporary-event-notice.herokuapp.com/) that was created to test some of our original components.

**Comment by DebsDee** [comment]
I'll be working on the prototype here: [Research prototype repo](https://github.com/alphagov/focus-state-prototype)
