### ISSUE TITLE
Namespace Frontend inside a govuk directory

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1451]
## What

As agreed in https://github.com/alphagov/govuk-design-system-architecture/pull/15, we plan to namespace GOV.UK Frontend by creating a new folder called govuk/ and move all the GOV.UK Frontend source files into it.

The folder structure should look something like this:

```
.
├── README.md
├── govuk
│   ├── all-ie8.scss
│   ├── all.js
│   ├── all.scss
│   ├── assets
│   ├── common.js
│   ├── components
│   ├── core
│   ├── helpers
│   ├── objects
│   ├── overrides
│   ├── settings
│   ├── template.njk
│   ├── tools
│   ├── utilities
│   └── vendor
├── govuk-prototype-kit.config.json
└── package.json
```

## Why are we doing this?

We are doing this to make it easier for users to import things, in a way that is explicit and avoids conflicts in their application, in response to feedback.

For more information, see [the proposal](https://github.com/alphagov/govuk-design-system-architecture/blob/180731f8f4ffc6739c5c913e2cb4d5d7955b205f/proposals/005-namespace-govuk-frontend-nunjucks-sass-using-a-nested-folder-structure.md#namespace-govuk-frontend-nunjucks-and-sass-using-a-nested-folder-structure).

## Done when…

- [x] We've make the changes to the folder structure as per [the spike](https://github.com/alphagov/govuk-frontend/pull/1393)
  - consider retaining history – should we use `git mv`?
- [x] We've updated the Sass and JS entry points in package.json
  - Keep govuk/components in nunjucks paths for compatibility
- [x] We've sure that `package` and `dist` build correctly and that tests pass
- [x] We've updated relevant documentation in GOV.UK Frontend
  - https://github.com/alphagov/govuk-frontend/tree/master/package
- [x] We've tested that things like our webpack example still work as we think they will
- [x] We have considered the assets directory and if we need to change to `govuk/assets` namespace
- [ ] We've update the prototype kit config
  - make sure it works by including it in the Prototype Kit

**Comment by aliuk2012** [comment]
https://github.com/alphagov/govuk-frontend/pull/1466 updates the documentation

**Comment by 36degrees** [comment]
I've split updating the prototype kit config out into [a separate issue](https://github.com/alphagov/govuk-frontend/issues/1484) which I think means this can now be closed
