### ISSUE TITLE
Release v2.13.0

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1452]
## What

There are currently a number of changes that have been merged but not released.

> 🆕 New features:
> 
> - Support custom text on meta title 
> 
>   Hard coded 'Support Links' is replaced by `params.meta.visuallyHiddenTitle` this has a default off Support links.
> 
>   ([PR #1387](https://github.com/alphagov/govuk-frontend/pull/1387))
> 
> 🔧 Fixes:
> 
> - Fixes the color of disabled secondary and warning button variants
> 
>   ([PR #1392](https://github.com/alphagov/govuk-frontend/pull/1392))
> 
> - Adds missing height and width attributes to the fallback crown PNG in the header.
> 
>   ([PR #1419](https://github.com/alphagov/govuk-frontend/pull/1419))
> 
> - Fixes alignment of the fallback crown PNG with 'GOV.UK' in the header in IE8
> 
>   ([PR #1419](https://github.com/alphagov/govuk-frontend/pull/1419))

We should do a v2.13.0 release before we merge the `v3` branch into master, as it may be a short while before we can get v3 out.

## Done when…

- [ ] Release notes updated to use new style (optional?)
- [ ] Release published to npm
- [ ] Release created in GitHub releases with release notes
- [ ] Prototype Kit updated and released
- [ ] Design System updated and deployed
- [ ] Frontend release promoted on `#govuk-design-system` channel
- [ ] Prototype Kit release promoted on `#prototype-kit` channel

**Comment by hannalaakso** [comment]
Closed by https://github.com/alphagov/govuk-frontend/pull/1456
