### ISSUE TITLE
link-buttons do not focus like regular buttons do in firefox

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-frontend#1464]
## What
In Firefox, by default very few items can be focused - but buttons can.

However, our link buttons can't. This means if you have two items styled like buttons, one a button and one a link button, only one can be focused.

Can be seen in this video tabbing through the new cookie banner:
![govuk-button-link-focus-bug](https://user-images.githubusercontent.com/2204224/59766704-b02e0100-9298-11e9-9f65-e1238a41b021.gif)

## Why
We have two things that look like buttons, but focus behaves differently in them. This feels wrong. We shim link buttons with js and `role=button` to help make them behave like buttons - but this appears to be a case where it's not enough. 

## Anything else
I note Firefox's default behaviour is pretty useless - but since it's default it would be good if our link buttons could behave like the thing they look like.

If others don't see this issue - check you haven't enabled firefox's option to make all tabable things tabable.

**Comment by nickcolley** [comment]
We're going to do a quick investigation to see if `[tabIndex=0]` might give us a more consistent behaviour.

If it doesn't or this isn't something we want to do, we'll close this and reference it as a note in the backlog entry for buttons.

**Comment by nickcolley** [comment]
OK I tried in Safari and Firefox, and `[tabindex=0]` does not seem to make things tabbable when these settings are enabled.

**Comment by nickcolley** [comment]
I have raised a bug for this on Firefox's bug tracker for them to consider: https://github.com/alphagov/reported-bugs/issues/43

**Comment by nickcolley** [comment]
Thanks for raising, Ed this is good to know.

**Comment by edwardhorsford** [comment]
Nice, thanks @nickcolley!
