### ISSUE TITLE
Accordion Component Reuse

### ISSUE THREAD

**Issue by tmakin** [alphagov/govuk-frontend#1470]
## Objective
Allow accordion components to be re-initialised after accordion is updated

## Context
I'm using Accordion inside a single page Angular application by manually initialising the component after the dom elements have been rendered. However, because dom elements are reused by Angular I end up with multiple `govuk-accordion__controls` elements if the route data changes. My workaround hack is to remove the offending dom nodes before calling `init()` again, but it's not pretty.

## Solutions
I see two possible solutions:
1. Check to see if `accordion__controls` exists before adding a new node inside the `init()` call.
2. Add a `destroy()` method which removes all event listeners and any extra dom nodes that were injected by the component.

Personally I favour option 2 as it already used by the `details` component and would provide a consistent hook for clearing up resources inside single page apps.

## Related
https://github.com/alphagov/govuk-frontend/issues/1127

**Comment by timpaul** [comment]
Thanks for this @tmakin. We're going to close this issue, but we'll deal with is as part of this one: 'Investigate components being initialised more than once' #1127
