### ISSUE TITLE
Docs for Rails/Webpacker

### ISSUE THREAD

**Issue by duncanjbrown** [alphagov/govuk-frontend#1474]
We recently added `govuk-frontend` to a Rails project using webpacker ([commit](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training/commit/f13884a0c8d2835e291cb3c62f2ff5156aa6bb71)). Are you interested in a PR with a write-up for the docs?

**Comment by aliuk2012** [comment]
Hi @duncanjbrown 

Thank you for opening this issue and offering to submit a pull request. 

The team discussed your proposal and decided that it would not be a good idea to include guidance for any particular framework for the following reasons:
- Currently, we do not support specific frameworks like Rails etc.
- The team would not be able to update or maintain such documentation and lack the knowledge of all the variety of frameworks available

We do however acknowledge that we should try to provide better support for frameworks. We spoke about creating a page with a list of community developed projects that use govuk-frontend. This page would hopefully, help point people to other resources and help the community of those frameworks grow and maintain themselves.

We are aware of a really good Rails boilerplate repo that Department of Education has developed (https://github.com/DFE-Digital/govuk-rails-boilerplate) which uses webpacker. 

I hope this has helped in some way but if you have any further questions or issues please contact us. Please feel free to re-open this issue if you would like to discuss this further.

Kind regards,
Alistair Laing
GOV.UK Design System team
