### ISSUE TITLE
Fieldset legend heading XL cutting off descender

### ISSUE THREAD

**Issue by ChazUK** [alphagov/govuk-frontend#1476]
The descenders of my headings appear to be getting cut off and the whole heading squashed vertically when trying to use the legend as a heading pattern. I'm using v2.13.0, code below.

```
<fieldset class="govuk-fieldset">
  <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
    <h1 class="govuk-fieldset__heading">
      Sign In
    </h1>
  </legend>
</fieldset>
```

`legend` has these computed styles:
```
border-bottom-color: rgb(11, 12, 12);
border-bottom-style: none;
border-bottom-width: 0px;
border-image-outset: 0px;
border-image-repeat: stretch;
border-image-slice: 100%;
border-image-source: none;
border-image-width: 1;
border-left-color: rgb(11, 12, 12);
border-left-style: none;
border-left-width: 0px;
border-right-color: rgb(11, 12, 12);
border-right-style: none;
border-right-width: 0px;
border-top-color: rgb(11, 12, 12);
border-top-style: none;
border-top-width: 0px;
box-sizing: border-box;
color: rgb(11, 12, 12);
display: table;
font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
font-size: 48px;
font-weight: 700;
height: 50px;
line-height: 50px;
margin-bottom: 15px;
max-width: 100%;
overflow-x: hidden;
overflow-y: hidden;
padding-bottom: 0px;
padding-inline-end: 0px;
padding-inline-start: 0px;
padding-left: 0px;
padding-right: 0px;
padding-top: 0px;
white-space: normal;
width: 158px;
-webkit-font-smoothing: antialiased;
-webkit-border-image: none;
```

`h1` has these computed styles
```
color: rgb(11, 12, 12);
display: block;
font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
font-size: 48px;
font-weight: 700;
height: 50px;
line-height: 50px;
margin-block-end: 0px;
margin-block-start: 0px;
margin-bottom: 0px;
margin-inline-end: 0px;
margin-inline-start: 0px;
margin-left: 0px;
margin-right: 0px;
margin-top: 0px;
white-space: normal;
width: 158px;
-webkit-font-smoothing: ant
```

<img width="522" alt="Screenshot 2019-07-02 at 18 07 36" src="https://user-images.githubusercontent.com/768108/60532502-50eada80-9cf5-11e9-88e6-11b7f0dac5c4.png">

<img width="507" alt="Screenshot 2019-07-02 at 18 08 08" src="https://user-images.githubusercontent.com/768108/60532506-534d3480-9cf5-11e9-9be3-2d50a89d0214.png">

**Comment by 36degrees** [comment]
@ChazUK thanks very much for taking the time to report this.

I believe this is the same issue recorded in #1239, so I'm going to close this. I'd recommend [subscribing to receive updates to that issue](https://help.github.com/en/articles/subscribing-to-and-unsubscribing-from-notifications#managing-your-notification-settings-for-an-issue-or-pull-request) if you want to be updated on any activity.

If you believe this is a separate issue to the one recorded in #1239, please feel free to re-open this.
