### ISSUE TITLE
Focus state styling overlaps surrounding text in certain scenarios

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1477]
Raised by a community member.

We could consider giving links a raised z-index, but I think that could introduce other issues.

![](https://user-images.githubusercontent.com/2445413/60505309-5f1c0500-9cbb-11e9-88db-9e1214f392f7.png)

Can be reproduced with the following markup:

```html
<p class="govuk-body">Yes (<a class="govuk-link" href="#">Edit</a>)</p>
```

**Comment by timpaul** [comment]
Following a conversation with @stephenjoe1, we've agreed to side-step the issue by removing the left and right padding from the focus states, so they'll look like this:

![image](https://user-images.githubusercontent.com/1590604/61040591-cb3bee80-a3c8-11e9-9761-4aba23f42c40.png)

**Comment by nickcolley** [comment]
Is @dashouse happy with this decision?

Can we see what impact that would make to:

- components like tabs
- links that wrap over multiple lines

**Comment by timpaul** [comment]
Yep - Dave, Ste McC and Mark H are all happy with this approach
