### ISSUE TITLE
Implicit mappings of landmark roles

### ISSUE THREAD

**Issue by glenpike** [alphagov/govuk-frontend#1482]
We've constructed our layouts from the recommended [HTML in the GDS documentation](https://design-system.service.gov.uk/styles/page-template/), but now our [accessibility testing tools](https://github.com/dequelabs/axe-matchers) are flagging that we should not be adding `aria-role` to things like `<header>` and `<main>` because the browser natively implies these for certain elements/tags - https://a11yproject.com/posts/aria-landmark-roles/

I'm not sure if this is an issue per-se, but should the documentation reflect this, or are there times where the aria-role is actually needed?

**Comment by hannalaakso** [comment]
Hi @glenpike thanks a lot for letting us know about this. 

We're doing some work right now to document any known validation/accessibility warnings: https://github.com/alphagov/govuk-frontend/issues/1280 We will hopefully have some more documentation around this soon. 

I'm going to close your issue as it's going to be covered by https://github.com/alphagov/govuk-frontend/issues/1280.

Thanks again for raising this, it helps us to prioritise the wider issue 👍
