### ISSUE TITLE
Investigate why role="group" is applied automatically and consider removing

### ISSUE THREAD

**Issue by EddieCurtis** [alphagov/govuk-frontend#1483]
I have noticed the following error in our accessibility testing:

> The “group” role is unnecessary for element “details”.

The attribute is added automatically by the file govuk-frontend-2.13.0.min.js (or relevant version number) in the dist directory of this project.

In my example the attribute is added to a `<details>` tag which changes from:
`<details class="govuk-details govuk-!-margin-top-1">`
to:
`<details class="govuk-details govuk-!-margin-top-1" role="group">`

I cannot work around this by adding `role="none"` to the source code as it still gets overwritten with `role="group"`.

Please can we investigate why this attribute is being set, and consider removal to remove this error from our testing? This is very low priority for my team as we can ignore individual errors from the test results, but it might be a nice thing to investigate to see if we can improve.

**Comment by 36degrees** [comment]
@nickcolley was this addressed by #1523? Can this now be closed, as we're now only applying the `role` when we're polyfilling?

**Comment by nickcolley** [comment]
Yeah we can close this now, thanks for raising Eddie :)
