### ISSUE TITLE
Product name wraps onto new line with non full-width header

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1502]
The product name wraps when it doesn't need to, when used in a non full-width header.

![localhost_3000_components_header_with-product-name_preview](https://user-images.githubusercontent.com/121939/61457889-32294c80-a961-11e9-9350-3e30f339f243.png)

I believe this is because of the `width: 33%` declaration on `govuk-header__logo`, which is necessary for correct layout when the header has a service name and/or navigation:

https://github.com/alphagov/govuk-frontend/blob/edec2e977b64c2b54332c1a97a1ec1b2461f84a6/src/govuk/components/header/_header.scss#L136-L146

**Comment by nickcolley** [comment]
I've investigated this issue and https://github.com/alphagov/govuk-frontend/issues/1635 and think that we probably want to try and explore flexbox/grid with an approach that allows the content in the header dictate space.

**Comment by hannalaakso** [comment]
Some notes from team discussion:
-  Test with longest possible product name: “Platform as a Service”?

**Comment by kr8n3r** [comment]
this is what I've ended up doing on paas product pages
![paas-header](https://user-images.githubusercontent.com/3758555/85371965-088d8380-b529-11ea-949b-00c9ba844071.gif)

**Comment by vanitabarrett** [comment]
As discussed in V4 scoping session, we probably need to get a better idea of the changes GOV.UK are making to the header and any changes we may need to make to match before we look into this.
