### ISSUE TITLE
All caps text in the tag component is harder to read

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1504]
We [advise against using all caps on GOV.UK](https://www.gov.uk/guidance/content-design/writing-for-gov-uk#capital-letters-are-harder-to-read), because it's harder for people to recognise words from their shape if they are in all caps.

But, we use all-caps in the tag component, which is current used in the phase banner and task list.

## Done when

- [ ] TBC
- [ ] "Details of breaking change" section below completed to help with writing release notes

## Details of breaking change

- which users are affected: TBC
- the change that’s been made: TBC
- changes users will have to make: TBC
- impact of users not making those changes: TBC

**Comment by dashouse** [comment]
Design wise this is done, but approach to release needs to be discussed. See https://github.com/alphagov/govuk-frontend/pull/1549

**Comment by edwardhorsford** [comment]
I'd like to put an argument for keeping them as is, or to know if there's any evidence for this.

It's important that these tags look visually distinct on the page, and that they not look like links. In changing these to sentence case, I think we risk reducing the usability and distinctiveness of them.

As I understand it the guidance was based on research of reading comprehension for long form paragraphs of text. Was any of the research about single words in all caps? or do we have any evidence from usability testing that these are causing issues for users? It would be good to know if this change is based on any research or evidence of issues.

**Comment by mrkwrght** [comment]
> I'd like to put an argument for keeping them as is, or to know if there's any evidence for this.
> 
> It's important that these tags look visually distinct on the page, and that they not look like links. In changing these to sentence case, I think we risk reducing the usability and distinctiveness of them.
> 
> As I understand it the guidance was based on research of reading comprehension for long form paragraphs of text. Was any of the research about single words in all caps? or do we have any evidence from usability testing that these are causing issues for users? It would be good to know if this change is based on any research or evidence of issues.

Do you have any research which backs this up? I know they is a lot of research around All caps text reading for dyslexia and it being harder..

**Comment by edwardhorsford** [comment]
> > I'd like to put an argument for keeping them as is, or to know if there's any evidence for this.
> > It's important that these tags look visually distinct on the page, and that they not look like links. In changing these to sentence case, I think we risk reducing the usability and distinctiveness of them.
> > As I understand it the guidance was based on research of reading comprehension for long form paragraphs of text. Was any of the research about single words in all caps? or do we have any evidence from usability testing that these are causing issues for users? It would be good to know if this change is based on any research or evidence of issues.
> 
> Do you have any research which backs this up? I know they is a lot of research around All caps text reading for dyslexia and it being harder for them.

I've not personally ever seen issues with uppercase tags or heard from other teams that they were an issue (the uppercase aspect at least). As far as I know all the referenced research is about long-form blocks of text - not this sort of usage.

With that said, I'm not trying to argue there is no issue - only that we should keep in mind how this might otherwise impact the pattern. In a similar way to bold text - which should avoided in large blocks of text, but [might make a specific piece of text clearer](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bold).

**Comment by mrkwrght** [comment]
as a dyslexia person and someone how has done a lot of research around the topic. the way dyslexia people read is based on the shapes of words when something is all caps it looks like a block and can take more time for someone to read. 

@tempertemper has done a lot of research into tags too and this was part of it.

**Comment by hannahjump** [comment]
Adding to what @mrkwrght says -  all capital letters are harder for users with dyslexia to read. [The British Dyslexia Association](https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide) advise against it (the bottom bullet point under the ‘readable fonts’ heading). Also the [accessibility poster for users with dyslexia](https://ukhomeoffice.github.io/accessibility-posters/posters/accessibility-posters.pdf) talks about this.

**Comment by vanitabarrett** [comment]
As discussed in the v4 prioritisation, we think this work would be good to do, but this is something that the task list working group will be looking at so it makes sense to wait and see what comes out of that. I'm going to move this into Nice To Have for now so we don't lose track of this work if the task list make a confident decision before v4 is released.

**Comment by owenatgov** [comment]
With the new design of the tag component which removes the forced uppercase, this is now solved.
