### ISSUE TITLE
Form elements do not scale well if only font size increased

### ISSUE THREAD

**Issue by andysellick** [alphagov/govuk-frontend#1519]
If you `zoom text only` in Firefox, select elements retain their 40px height but the text within them becomes larger and therefore cropped from the bottom edge.

<img width="678" alt="Screen Shot 2019-08-01 at 14 30 10" src="https://user-images.githubusercontent.com/861310/62297312-e4d0d300-b468-11e9-9e98-390152b7ae23.png">

Doesn't seem to be as much of a problem for text inputs.

Can't reproduce the problem in Chrome because the zoom text only option isn't available.

Noticed this during user testing on a phone of GOV.UK's search, specifically where we have select elements [in finders](https://www.gov.uk/search/news-and-communications).

(can't remember what kind but possibly an iPhone 7?)

Side note: doing this on the Design System site causes the currently active menu item to be crossed out instead of underlined:

<img width="1199" alt="Screen Shot 2019-08-01 at 14 31 28" src="https://user-images.githubusercontent.com/861310/62297443-2497ba80-b469-11e9-84e0-b0dfb5e73727.png">

**Comment by andysellick** [comment]
This appears to be fixable by changing the height from using `px` to `em` but I think we already discussed this and there was a reason not to do it? Can someone remind me?

**Comment by nickcolley** [comment]
There seems to be some concern to nested font sizing: https://github.com/alphagov/govuk-frontend/commit/5f4d20c2ef9549c0e4596239f77067e0462ff89a

But perhaps `rem` would be fine?

**Comment by andysellick** [comment]
Interestingly on testing it seems `rem` is far less predictable than `em`. `rem` in the component guide produces one height but the same thing tested inside `finder-frontend`'s search results in a much smaller height (actually creating the original issue in a different way). `em` produces a consistent height in both interfaces.

**Comment by andysellick** [comment]
Looks like the reason for that is the body font size isn't set in the component guide (?) - we might need to look into that.

**Comment by nickcolley** [comment]
The main issue with 'em' and 'rem' when using it with the legacy GOV.UK Template is that GOV.UK Template messes with the root font size, which is likely what you're seeing.

**Comment by nickcolley** [comment]
We do have ways to only use relative units when compatibility mode is not turned on that we could consider.

**Comment by 36degrees** [comment]
It looks like this _can_ affect text inputs, but only at extreme values (I had to modify the values for `toolkit.zoomManager.zoomValues` and `zoom.maxPercent` in Firefox's `about:config` to do this):

<img width="1392" alt="Screen Shot 2019-08-07 at 16 02 06" src="https://user-images.githubusercontent.com/121939/62633936-e00a9400-b92c-11e9-9495-03603a40d67d.png">

We'd probably also want to scale text inputs and buttons at the same time to ensure that they remain aligned – so I'm going to rename this to 'form inputs do not scale well…'.

**Comment by nickcolley** [comment]
@andysellick I think we'd need to avoid using `em` units as it is unpredictable depending on what their parent's font size, so we'd want to explore `rem` (but only outside compatibility mode).
