### ISSUE TITLE
Encouraging first time contributors + Hacktoberfest

### ISSUE THREAD

**Issue by htmlandbacon** [alphagov/govuk-frontend#1520]
:wave:

I was just wondering if for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) if it would be nice to do something cross Government workshop to help people contribute to the [govuk-frontend](https://github.com/alphagov/govuk-frontend) or the [govuk-prototype-kit](https://github.com/alphagov/govuk-prototype-kit).

I'd happily collaborate on some materials for this and run this in Newcastle or equally chip in for stickers, if people think it is a good idea?

**Comment by nickcolley** [comment]
Hey Colin,

We're fans of this kind of pro-active stuff...

Here's some examples of first timer issues: https://github.com/alphagov/govuk-frontend/issues?q=is%3Aissue+label%3Afirst-timers-only+is%3Aclosed

We also ran a [Learn GitHub for content designers session](https://www.eventbrite.co.uk/e/learn-github-for-content-designers-tickets-55155944916?aff=eemailordconf&utm_campaign=order_confirm&utm_medium=email&ref=eemailordconf&utm_source=eb_email&utm_term=viewevent) where [we created issues for that](https://github.com/alphagov/govuk-design-system/issues?q=is%3Aissue+label%3A%22Learn+GitHub+for+content+designers%22+is%3Aclosed)

That work resulted in shipping the new guidance for content updates: https://design-system.service.gov.uk/community/propose-a-content-change-using-github/

The majority of the time is in putting together good first timer issues, I'll see if the team is interested in doing something for this month and let you know!

**Comment by hannalaakso** [comment]
The event has now passed so closing the issue. Thanks for raising it @htmlandbacon it was a really nice idea. Our team might be interested in doing something similar in the future.
