### ISSUE TITLE
Checkbox accessibility issue on iOS

### ISSUE THREAD

**Issue by LeeGathercole** [alphagov/govuk-frontend#1535]
We have noticed that on iOS devices when navigating our website using a keyboard that it is not possible to select a checkbox. 

This works as expected on desktops

**Comment by 36degrees** [comment]
Hi Lee,

I've tested a [reduced test case](https://codepen.io/36degrees/pen/jONyZor) that uses the native checkboxes and radio buttons – i.e. without any styling or JavaScript from GOV.UK Frontend – using my iPad (running iOS 12.4) and this is also the case there.

It appears that iOS only supports navigating to "Text boxes and lists" using the tab key. macOS supports navigating to "all controls" but [this has to be enabled](https://a11yproject.com/posts/safari-keyboard-navigation/), and is commonly referred to as 'full keyboard access'.

I've found a [blog post that suggests full keyboard access might be coming to iOS 13](https://appletoolbox.com/use-an-iphone-or-ipad-without-touch-how-to-use-full-keyboard-access-to-do-just-that/), but I haven't been able to find any reference to it in the settings in the latest public beta.

I don't think there's anything we can do here, so I'm going to close this as I think it's iOS' default behaviour. But please feel free to re-open if I've missed anything.
