### ISSUE TITLE
Footer layout isn't aligned with content layout

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#1539]
As noticed on GovWifi, the flexbox auto layout used in the footer means that the columns do not lock into the grid.

**Example from GovWifi**
<img width="1044" alt="Screen Shot 2019-08-28 at 11 53 40" src="https://user-images.githubusercontent.com/23356842/63849764-a278b400-c98a-11e9-9d1b-fdc871c3ebc2.png">

With equal content, the content is not distributed evenly, the first column takes up more space. Adding content to the second or third column will take away space from the first, which is why the GovWifi example looks **almost** right, but it's coincidental.

**Recreated in the Prototype Kit**
<img width="1055" alt="Screen Shot 2019-08-28 at 11 52 15" src="https://user-images.githubusercontent.com/23356842/63849793-b1f7fd00-c98a-11e9-91f3-1ed3e452de62.png">

Is there anything we can add to the flexbox properties to ensure min or max width of content?

## Done when

- [ ] TBC
- [ ] "Details of breaking change" section below completed to help with writing release notes

## Details of breaking change

- which users are affected: TBC
- the change that’s been made: TBC
- changes users will have to make: TBC
- impact of users not making those changes: TBC

**Comment by nickcolley** [comment]
I've had a look into this, I think the way flexbox works means that even though the proportions are correct in certain scenarios the footer will not align with the main grid system.

I have proposed a fix to improve the specific issues raised by Dave here for three columns: https://github.com/alphagov/govuk-frontend/pull/1542

I believe to fix this we need to improve how the footer works:
https://github.com/alphagov/govuk-frontend/tree/spike-only-default-two-thirds-footer-for-two-sections

This will require a small but breaking change, so will put this against the 4.0.0 milestone

**Comment by 36degrees** [comment]
We may want to look at #1284 at the same time as this.

**Comment by vanitabarrett** [comment]
As discussed in v4 prioritisation, we think this work is important but it's quite broad at the moment. We should probably do a timeboxed investigation into this issue and [this related one](https://github.com/alphagov/govuk-frontend/issues/1726) to explore a few different layout systems for the footer and see how they perform.
