### ISSUE TITLE
Summary List Component renders actions incorrectly if first row don't have any actions specified

### ISSUE THREAD

**Issue by adamszymaszczyk** [alphagov/govuk-frontend#1545]
Below snippet renders the component incorrectly, ref to for a screenshot https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6/p1567164598025800

> <dl class="govuk-summary-list">
> 
>     <div class="govuk-summary-list__row">
>       <dt class="govuk-summary-list__key">
>         Name
>       </dt>
>       <dd class="govuk-summary-list__value">
>         Sarah Philips
>       </dd>
>       
>     </div>
>     <div class="govuk-summary-list__row">
>       <dt class="govuk-summary-list__key">
>         Date of birth
>       </dt>
>       <dd class="govuk-summary-list__value">
>         5 January 1978
>       </dd>
>         <dd class="govuk-summary-list__actions">
>             <a class="govuk-link" href="#">
>                 Change<span class="govuk-visually-hidden"> date of birth</span>
>             </a>
>         </dd>
>     </div>
>     <div class="govuk-summary-list__row">
>       <dt class="govuk-summary-list__key">
>         Contact information
>       </dt>
>       <dd class="govuk-summary-list__value">
>         72 Guild Street<br>London<br>SE23 6FH
>       </dd>
>         <dd class="govuk-summary-list__actions">
>             <a class="govuk-link" href="#">
>                 Change<span class="govuk-visually-hidden"> contact information</span>
>             </a>
>         </dd>
>     </div>
>     <div class="govuk-summary-list__row">
>       <dt class="govuk-summary-list__key">
>         Contact details
>       </dt>
>       <dd class="govuk-summary-list__value">
>         <p class="govuk-body">07700 900457</p><p class="govuk-body">sarah.phillips@example.com</p>
>       </dd>
>         <dd class="govuk-summary-list__actions">
>             <a class="govuk-link" href="#">
>                 Change<span class="govuk-visually-hidden"> contact details</span>
>             </a>
>         </dd>
>     </div>
> </dl>

**Comment by nickcolley** [comment]
I'm going to close this out since I think we've resolved your issues, if people run into this again we might need better guidance or to consider an approach which does not require these void elements.
