### ISSUE TITLE
SVG accessibility improvements

### ISSUE THREAD

**Issue by peteryates** [alphagov/govuk-frontend#1551]
It appears that the SVGs used in the header (crown) and footer (OGL logo) don't contain any [`<title>` or `<description>` elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title).

Is it _necessary_ for these graphics to be made accessible? There is other text that conveys their meaning already present in the header and footer.

Perhaps linking the SVG's to the appropriate text via [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) is enough?

Not sure if this is actually necessary but thought it was worth raising

**Comment by nickcolley** [comment]
Hey @peteryates,

Both of these images are intentionally presentational and have alternative text for users of assistive technologies that give the necessary context without having to understand the visual graphic.

- the crown logo is set to `[role=presentation]` which removes it from the accessibility tree, the context for the link is given by the text 'GOV.UK'.
- the OGL logo is a CSS background image which means it does not appear in the accessibility tree, the context for the link is given by the text 'Crown Copyright'.

Appreciate you taking the time to question this and double checking this with us, I'm going to close this as I think this is all OK.

Nick
