### ISSUE TITLE
Checked radio button with conditional reveal does not expand on page refresh in IE11

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1552]
When interacting with the radio group and selecting the first time the conditional reveal is opened.

When you refresh the page, the first input is remembered as a checked input but the conditional reveal is not open.

I have only reproduced this on IE11 so far, but potentially might be an issue with error playback so we should construct an example of that too.

## Steps to reproduce

1. Use IE11 + JAWs 2018 (might be optional)
2. Go to https://govuk-frontend-review.herokuapp.com/components/radios/with-conditional-items/preview
3. Tab to first input
4. Press space to activate
5. Refresh page

**Comment by 36degrees** [comment]
Will be fixed by #1842
