### ISSUE TITLE
Undocumented parameter `row.classes` in summary-list

### ISSUE THREAD

**Issue by dabd** [alphagov/govuk-frontend#1555]
The [`row.classes` parameter](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/summary-list/template.njk#L19) is undocumented in the [yaml](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/summary-list/summary-list.yaml#L6-L62) for the `summary-list` component.

**Comment by 36degrees** [comment]
Thanks for flagging this, @dabd 👍 

We've fixed this in #1556, but just to let you know the change won't show up in the Design System until we roll out the next release.
