### ISSUE TITLE
Icons don't resize with text

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1569]
WCAG 2.1 requires that user can [resize text to at least 200% ](https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html). When text is resized (see https://github.com/alphagov/govuk-frontend/issues/1519), our icons don't resize with text. We might not wish them to, this issue is partly for reference.

## Crown icon when text resized to 32 (16 x 2 = 200%)
(Once https://github.com/alphagov/govuk-frontend/issues/1568 is fixed)
![Screen Shot 2019-09-12 at 16 55 40](https://user-images.githubusercontent.com/5007934/64800272-35664080-d57e-11e9-924e-aac7815f36db.png)

## Warning icon when text resized to 200% in Chrome
![Screen Shot 2019-09-12 at 16 52 34](https://user-images.githubusercontent.com/5007934/64800702-eff64300-d57e-11e9-8a61-8cb98cb67bc9.png)

## Arrow icon when text resized to 200%
![Screen Shot 2019-09-12 at 16 57 29](https://user-images.githubusercontent.com/5007934/64800646-d6ed9200-d57e-11e9-8327-8d603ad0ae47.png)

# How text was resized in browsers

## Chrome 
Settings > Appearance > Customise fonts

## Firefox
Set View > Zoom > Zoom text only. Press +/-
or Preferences > Language and appearance > Font size

## Safari
To increase the font size, press Option-Command-Plus sign (+)
To decrease the font size, press Option-Command-Minus sign (-)

## Edge 
Can't resize text apart from "Reading view" which removes form elements from the view.

## IE 8-11
Page > Text size > Largest

## iOS 
**Text can't resized in browser. See https://github.com/alphagov/govuk-frontend/issues/882**

## Android Chrome/Firefox
Settings > Accessibility > Text scaling

**Comment by nickcolley** [comment]
We're going to only fix the icons that loose their meaning when scaled up, in the examples shown here that means the warning icon but there may be other components, so we should double check.
