### ISSUE TITLE
Header Component - Custom HTML option for links

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-frontend#1573]
I am trying to use the header component but running into a couple of issues while adding a logout link. 

1. The current component does not support custom html only text and url for the navigation links. If I use html in `text` it still works but obviously it wraps `<a>` around the html. This raises issues with keyboard navigation (tabbing twice to go to the form element) and style focus.

eg.
```
{{
    govukHeader({
      'serviceName': 'Digital Marketplace',
      'navigation': { 'text': '<form method="post" action="google.com">
              <input type="submit" class="logout-button" value="Log out" />
              <input type="hidden" name="csrf_token"/>
            </form>',
      'href': url_for('external.render_login')
    })
  }}
```

![Sep-13-2019 13-42-10](https://user-images.githubusercontent.com/3441519/64864488-1d022e80-d62f-11e9-9b8a-3f877438adf2.gif)

To avoid this I could change it to a link but this changes the request from a `post` to `get` which is not considered good practice.

**Comment by nickcolley** [comment]
We decided as a team that we'd support the simplest case which is to allow HTML alongside text

**Comment by hannalaakso** [comment]
Some notes from team discussion on this:
- Seems like a legitimate use case
- We should consider not breaking existing functionality but adding a new option

**Comment by hannalaakso** [comment]
I just looked into this. You **can** already include HTML for the navigation links but what you can't do is to include HTML and:
- not have it wrapped in `<a class="govuk-header__link" href="#">`
- have it render without passing through `href` 

neither of which you want if you want to render a form.

Even if we allowed rendering of HTML without `href` being set and removing the `<a>` tag, to style the form correctly `.govuk-header__link` would need to be on the input eg.

```html
<li class="govuk-header__navigation-item">
	<!-- Omitted <a class="govuk-header__link" href="#"> from here-->
	<form method="post" action="google.com">
	  <input type="submit" class="logout-button **govuk-header__link**" value="Log out" />
	  <input type="hidden" name="csrf_token"/>
	</form>
    <!-- Omitted </a> from here-->
</li>
```

## Potential solutions

1. Do nothing code wise and advise teams wanting to add a "Log out" button etc. that they should use the HTML version of header.
2. Allow rendering of HTML without `<a class="govuk-header__link"` and advise in guidance that `.govuk-header__link` should be applied to form input. `.govuk-header__link` would also need additional styles added to override browser resets for `<input>` elements. Also semantically it would no longer be a link so we might have to consider renaming the class to `govuk-header__action` etc.
3. Same as 2. but also add a boolean attribute `renderForm` for the navigation item which needs to be set to enable this behaviour so it's so opaque.

**Comment by 36degrees** [comment]
I think I'm leaning towards 3.

Do we think that `govuk-header__link` is always going to do what we want for things that are not links? I think it'd be difficult to ensure that the class is always going to work for 'any' HTML, so I'm wondering if we should just leave the styling up to the user?
