### ISSUE TITLE
Crown logo is not always aligned with logotype

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1575]
Speaking with Dave it seems you can't reproduce this on his machine but I have been able to on Browserstack.

<img width="691" alt="Screen Shot 2019-09-16 at 14 04 28" src="https://user-images.githubusercontent.com/2445413/64961352-31dbfd80-d88d-11e9-9dff-111835d4b043.png">

Safari shows the logo lower instead of higher.

**Comment by dashouse** [comment]
I believe something has happened to increase the header size by 4px, the crown has stayed in the same place

**Comment by nickcolley** [comment]
When testing in browser stack, Chrome 75 is fine 76 is not.

**Comment by nickcolley** [comment]
If you move the font sizing CSS to the child element it brings back the previous behaviour, with some small adjustments needed.

Options:

1. Raise a bug report with Chrome
2. Make non-breaking CSS adjustments
3. Make a breaking change in version 4 to change the logo to entirely SVG

**Comment by colinrotherham** [comment]
@nickcolley I nearly raised this yesterday as I've been working on an old project (GOV.UK Elements) and spotted the alignment difference!

Can confirm in Chrome 77.

![Logo](https://user-images.githubusercontent.com/415517/64967832-1545c280-d899-11e9-8e4c-4d3b6b218809.png)

**Comment by nickcolley** [comment]
@kr8n3r moving the existing CSS to the wrapper of that element resolves the issue but that's good to know thanks.

**Comment by nickcolley** [comment]
## Short term

We're going to fix this in CSS 

## Longer term

We've been thinking about replacing this with an inline SVG which includes the 'GOV.UK' text within the image itself.

This would also mean that when the fallback fonts are loaded then the logo will be correct, this could be useful if we were to change the loading strategy to 'swap'.

Includes Internet Explorer 8 issues.

We'll create another issue once we've done the short term work.

**Comment by 36degrees** [comment]
As found by @trevorsaint, it looks like adding `display: inline-block` to the `span.govuk-header__logotype` fixes this (at least in Chrome – will need x-browser testing)
