### ISSUE TITLE
Add test coverage for template.njk

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1580]
We have tests for all of our components to ensure that when the component macros are called the correct HTML is outputted.

We should add test coverage for template.njk to ensure that when the different blocks and variables are set the correct HTML is also outputted. This would avoid situations where for example incorrect whitespace or quote marks may cause attributes to be applied incorrectly, or not at all.

**Comment by hannalaakso** [comment]
Fixed by https://github.com/alphagov/govuk-frontend/pull/1628
