### ISSUE TITLE
Axe error: "Radio inputs with the same name attribute value" violation on radios / checkboxes with conditional reveals

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1591]
Running Axe against the radios and checkboxes conditional reveals flags the following error 
``` 

Radio inputs with the same name attribute value must be part of a group
<input class="govuk-radios__input" id="how-contacted-conditional-1" name="how-contacted" type="radio" value="email" aria-controls="conditional-how-contacted-conditional-1" aria-expanded="false">

To solve this violation, you need to:

Fix at least one (1) of these issues:

All elements with the name "how-contacted" do not reference the same element with aria-labelledby
Fieldset contains unrelated inputs
```

Some initial findings: https://github.com/alphagov/govuk-frontend/issues/979#issuecomment-525833255

Originally raised by @injms on [alphagov/govuk-design-system](https://github.com/alphagov/govuk-design-system/issues/524)

Split off from https://github.com/alphagov/govuk-frontend/issues/979

**Comment by nickcolley** [comment]
From Hanna in the other thread:

### Error: "Radio inputs with the same name attribute value must be part of a group"

#### Underlying issue
A bit of a question mark this but it's related to the inputs nested inside the reveals - removing them stops the error.

### Notes: 
- note that the Voiceover behaviour can be reproduced with VO + Arrow Right (twice)

**Comment by 36degrees** [comment]
Relevant thread: https://github.com/dequelabs/axe-core/issues/176

Particularly, this comment:

> Just for the record, here is why that code is currently there: having a radio group like that with the same name, makes the browser interpret certain keyboard commands (up and down arrow) to move the selection and the keyboard focus between the items in the group. If there are a lot of other elements interspersed within that group, this can lead to difficulty understanding where in the form you are (as a screen reader user for example).
>
> Also, in the case of checkbox groupings with much stuff interspersed, the difficulty can be in understanding how all the fields relate to one another.

https://github.com/dequelabs/axe-core/issues/176#issuecomment-195444801

However, it looks like the rule that triggered this was removed from Axe in 3.4 due to false positives.

**Comment by querkmachine** [comment]
This violation was removed in Axe 3.4, which is now many, many, many years old (the current version is 3.80!)

I'm going to close off this issue as I don't think there's anything more for us to do here.
