### ISSUE TITLE
govuk-visually-hidden-focusable mixin incorrectly sets margin to inherit when focused

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1597]
https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/helpers/_visually-hidden.scss#L73

I think this is trying to 'undo' the `margin: 0` applied when not focused.

However, I don't think this makes sense – this means that if you have a margin on your `<body>` then e.g. the skip link will inherit that margin too, as seen in https://github.com/alphagov/paas-admin/issues/426

**Comment by nickcolley** [comment]
Probably wont get away with 'initial' (https://caniuse.com/#feat=css-initial-value) here due to browser support...

**Comment by nickcolley** [comment]
Only way around this I can think of is to use `:not()` and have the skip link always show on older browsers.
