### ISSUE TITLE
Static Assets Import - Incorrect Source Destination

### ISSUE THREAD

**Issue by aabdullah6** [alphagov/govuk-frontend#1612]
in the documentation:
 
app.use('/assets', express.static(path.join(__dirname, '/node_modules/govuk-frontend/assets')))

should be:

app.use('/assets', express.static(path.join(__dirname, '/node_modules/govuk-frontend/**govuk**/assets')))

**Comment by nickcolley** [comment]
Thank you for letting us know about this!
