### ISSUE TITLE
Button component: minor documentation inaccuracies

### ISSUE THREAD

**Issue by risicle** [alphagov/govuk-frontend#1617]
Hi, just noticing a few inconsistencies in the documentation for the "button" component, "nunjucks macro options" dropdown section.

From what I can tell, the only _actual_ *required* option is `text` or `html`, where `name`, `type`, and  `value` are also listed as *required*. This particularly doesn't make sense when the table mentions there is a default for the value.

Also, I realize this table is space-constrained, but it would be useful to mention the default for _each_ of the options here without having to read through the long-form documentation lower down (which is great to have of course).

**Comment by nickcolley** [comment]
Thanks for raising this issue.

We're going to fix this issue and then review the Nunjucks options documentation for the rest of the components at a later date.
