### ISSUE TITLE
Lack of validation of empty array types generates incorrect markup?

### ISSUE THREAD

**Issue by dabd** [alphagov/govuk-frontend#1618]
This is an issue I have found in a few components that have array parameters.

[This example](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/header/template.njk#L62) illustrates it.
```nunjucks
{% if params.navigation %}
    <button type="button" class="govuk-header__menu-button govuk-js-header-toggle" aria-controls="navigation" aria-label="Show or hide Top Level Navigation">Menu</button>
    <nav>
...
```
When the array is empty `params.navigation` is still a `truthy` value so it will create the button but no navigation. If this is not the intended outcome, should a guard be added to check for an empty array?

**Comment by nickcolley** [comment]
Hello @dabd!

I believe we could do something like:

```javascript
{% if params.navigation && (params.navigation | length) %}
```

in Nunjucks to check that there an array is not empty but I would need to double check this.

Is this something that you've run into in development or just an observation based on looking at the code, this will help us prioritise this.

**Comment by dabd** [comment]
Hi @nickcolley, thanks for the quick reply!

This is something that I've found out by running tests on an implementation of the library's components we're working on.  Our tests are checking for parity of the generated markup, and for some test cases we were getting different results because we are checking for empty arrays.  

This creates a bit of a dilemma between having a faithful implementation or doing validations based on assumptions that might be incorrect.  It would be nice to have these checks if that is the correct thing to do.  Thanks!

**Comment by nickcolley** [comment]
Thank you for the extra context! I've added the `awaiting-triage` label this means we'll meet as a team and discuss what we want to do next.

**Comment by edwardhorsford** [comment]
This seems sensible to me. We recently added support for not outputting markup where something wasn't provided - this feels like a natural extension.

**Comment by dabd** [comment]
It is not blocking us, but it would be nice to have those issues fixed so
we don't have to encode them in our implementation or add validations that
would make implementations diverge. I'm not a JavaScript developer but
maybe people in our team could contribute with PRs.

**Comment by silasl** [comment]
A PR has been raised for this: https://github.com/alphagov/govuk-frontend/pull/1638

**Comment by hannalaakso** [comment]
@dabd I believe that https://github.com/alphagov/govuk-frontend/pull/1638 has fixed this so closing the issue but you can re-open if needed.
