### ISSUE TITLE
Sass mixins, functions and variables are not publicly documented

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1634]
Users can only find documentation for our Sass mixins, functions and variables by looking through the code or in the Sass docs section of the frontend review app, which is not generally advertised.

Examples of things that users might need include helpers like `govuk-clearfix` or `govuk-media-query`.

One option would be to document these in the Design System. There is no place for this in the Design System as it stands, although we have previously considered renaming Styles to Foundations to allow for this type of content. 

There is a [prototype](https://overrides-and-utilities--govuk-design-system-preview.netlify.com/styles/media-queries/) that shows one way this might work.

**Comment by nickcolley** [comment]
> I recently discovered the `govuk-text-colour` mixin, and wondered when to use that vs the variable $govuk-text-colour. - @edwardhorsford

**Comment by edwardhorsford** [comment]
I'd just like to say that I find the sass docs section of the review app *extremely* helpful - both for the detail and coverage, and for it being more "developer" focused so I'm not having to filter out the guidance for the reference material.

I appreciate wanting one resource for all users, but a separate spec-style guidance would be very valuable to point people at.

**Comment by 36degrees** [comment]
Closing as this has been done:

https://frontend.design-system.service.gov.uk/sass-api-reference/#sass-api-reference
