### ISSUE TITLE
[Question] details component on Edge displays expanded and unable to collapse

### ISSUE THREAD

**Issue by aminmc** [alphagov/govuk-frontend#1642]
Hello,

I have a details component which works fine in chrome and safari however in edge it looks like this:

![Screenshot 2019-11-14 at 09 18 05](https://user-images.githubusercontent.com/290639/68850325-ba2f2100-06cb-11ea-8a18-16f82f8c4d99.png)

Nothing happens if you click on the help link and the message is always present.  I have called the initAll() function and I can see other components working correctly.  Just wondering if anyone else might have experienced this before? Any guidance on this would be appreciated.

**Comment by jamesmking** [comment]
Have you included the `data-module="govuk-details"` attribute on the `<details>` tag, so it looks like: `<details class="govuk-details" data-module="govuk-details">`

**Comment by aminmc** [comment]
Hi @jamesmking 

The markup looks like:

```html
<details data-module="govuk-details" class="govuk-details" >
    <summary class="govuk-details__summary">
                        <span class="govuk-details__summary-text">
                          Help
                        </span>
    </summary>
    <div class="govuk-details__text">
        Hello
    </div>
</details>
```
Interestingly in chrome and safari I can see open attribute being added and removed

```html
<details data-module="govuk-details" style="margin-top: 5px" class="govuk-details" open="">
    <summary class="govuk-details__summary">
                        <span class="govuk-details__summary-text">
                          Help
                        </span>
    </summary>
    <div class="govuk-details__text">
        Hello
    </div>
</details>
```

**Comment by nickcolley** [comment]
Hello @aminmc !

There is a polyfill that is run in Edge since it does not [support the details element out of the box](https://caniuse.com/#feat=details), could you please check that the JavaScript for GOV.UK Frontend is loaded on your page?

Could you also check what version of GOV.UK Frontend you are using and let us know as it may help us debug your issue.

Nick

**Comment by aminmc** [comment]
@nickcolley thanks for getting back! I'm currently using version 3.3.0. I'm using webpack and have a react application. In the js code that is used in the presentational component I'm doing the following:

```js
import {initAll} from 'govuk-frontend'
initAll();
```
Chances are i'm doing something wrong :)

**Comment by aminmc** [comment]
@nickcolley as i figured it was user error. After some debugging i worked out that the init method was being called before the page was being rendered as a result the polyfill wasn't being applied. Re adjusted the code and it works as expected. Sorry for wasting your time on this!.

Cheers
