### ISSUE TITLE
Make character count use hint component

### ISSUE THREAD

**Issue by LBHELewis** [alphagov/govuk-frontend#1645]
Currently the character count component contains a hint with markup (`<span class="govuk-hint">`) rather than using the hint component. Could this use the hint component instead? Happy to put in a PR myself, but wasn't sure whether this was a decision rather than a bug, because of the javascript taking place in this component?

**Comment by nickcolley** [comment]
I can't be certain it seems like it could be using the hint component macro and still output everything it needs to, if you wanted to raise a pull request to change this that sounds good!

**Comment by LBHELewis** [comment]
I've added a PR here: https://github.com/alphagov/govuk-frontend/pull/1650

**Comment by 36degrees** [comment]
Closed in #1650
