### ISSUE TITLE
Long text in footer columns do not wrap

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-frontend#1647]
While trying to implement the footer component for Digital Marketplace, we came across an issue with the footer, It doesn't seem to support long navigation text.

We wanted a three-column layout like this:

![image](https://user-images.githubusercontent.com/3441519/68927588-050a7080-0780-11ea-8add-608c4183342a.png)

However, as soon as you have links with a lot of content the layout breaks into two columns and the third column overflows onto another row as in this example:

![image](https://user-images.githubusercontent.com/3441519/68927730-53b80a80-0780-11ea-84de-ac39e2545702.png)

I think the expected behaviour should be that the link text adheres to the column width and wraps itself.

I haven't tested this out in other browsers but I did have this problem in Chrome 78.

**Comment by nickcolley** [comment]
We have another issue here relating to the footer layout, makes me think we should be using CSS Grid for this: https://github.com/alphagov/govuk-frontend/issues/1539

**Comment by aliuk2012** [comment]
Something interestingly if I reduce the window to tablet/mobile than the link text wraps.

Desktop:
![image](https://user-images.githubusercontent.com/3441519/69617723-8e4b5e00-1030-11ea-80b7-f0d242196cf1.png)


Table/mobile

![image](https://user-images.githubusercontent.com/3441519/69617785-ab802c80-1030-11ea-8c96-d41fdfdcd90d.png)

**Comment by aliuk2012** [comment]
Looks like it might be an issue with `flex-basis` anything other than desktop gets `flex-basis: 200px` added but in desktop it is not and the li items seem to have 100% width which is why the text does not wrap on desktops.

**Comment by aliuk2012** [comment]
I'll see if I can find some time to did a bit deeper into the issue but I think this is a bug and not a feature request.

**Comment by 36degrees** [comment]
We believe this was resolved by the changes in #2462.
