### ISSUE TITLE
Problem with fsevents@1.2.7 and Node.js 12

### ISSUE THREAD

**Issue by colinrotherham** [alphagov/govuk-frontend#1662]
Since the Node.js 12 update I've been unable to install GOV.UK Frontend via `npm ci` (clean install from lockfile) without errors:

```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and node@12.13.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@12.13.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
```

```
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
```

No pre-built binary exists for **fsevents@1.2.7** on Node.js 12
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v72-darwin-x64.tar.gz

The current lockfile in the project requires **fsevents@1.2.7** for Gulp, Jest and Nodemon.

Version 1.2.9+ is required for Node.js 12 compatibility.

**Comment by colinrotherham** [comment]
With minor updates I managed to get it to install.

But now I'm seeing high CPU usage from `gulp nodemon`. I think we need to go through the outdated packages and ensure we have Node.js 12 support for all.

For example **nodemon@2.0.1** adds chokidar v3 for file watching (including Node.js 12 fixes via **fsevents@~2.1.1**) but this hasn't been applied yet.

![Nodemon CPU usage](https://user-images.githubusercontent.com/415517/69446116-a333a300-0d4b-11ea-8698-f732ebd1a54c.png)

**Comment by colinrotherham** [comment]
Slightly related, other older dependencies still want Node.js 4:

```
npm WARN notsup Unsupported engine for to-markdown@2.1.0: wanted: {"node":"^4"} (current: {"node":"12.13.1","npm":"6.12.1"})
npm WARN notsup Not compatible with your version of node/npm: to-markdown@2.1.0
```

**Comment by nickcolley** [comment]
Hey Colin,

Can you let me know the use case for using `npm ci` instead of `npm install`?

Sorry you're running into these issues since the upgrade!

**Comment by colinrotherham** [comment]
If you want a clean install exactly as the author intended use `npm ci` (removes **node_modules** and installs the exact versions found in the lockfile).

If you want minor version bumps and patch releases to be included use `npm install`, best avoided as this can slip in unintended consequences to production.

**Comment by colinrotherham** [comment]
@nickcolley I've got `npm ci` working perfectly now in https://github.com/alphagov/govuk-frontend/pull/1663

**Comment by nickcolley** [comment]
Hmm when I run `npm ci` and then `npm start` it stalls on nodemon with this branch, investigating...

**Comment by nickcolley** [comment]
Same again with these steps:

1. `rm -rf node_modules`
2. `npm cache clean --force`
3. `nvm use`
# Node.js v12.13.1 (npm v6.12.1)
4. `npm install`
5. `npm start`

Hands on 'nodemon', I have seen the following error once when cancelling after waiting a while, which may or may not be related.

```
npm start[10:52:16] The following tasks did not complete: dev, serve, watch, nodemon
[10:52:16] Did you forget to signal async completion?
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read EIO
    at TTY.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Domain instance at:
    at ReadStream.EventEmitter.emit (domain.js:493:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by colinrotherham** [comment]
Thanks @nickcolley, I've done the same and it's all working here.

I'll see what I can find for that error message.

**Comment by nickcolley** [comment]
That error might be a red herring just from me cancelling.

**Comment by colinrotherham** [comment]
@nickcolley Possibly not related, but the gulp watch task doesn't return anything.

Gulp needs a promise to resolve, or stream, in return.

**Before**
```js
gulp.task('watch', () => {
  gulp.watch(paths1, gulp.parallel('some', 'tasks', 'here'))
  gulp.watch(paths2, gulp.parallel('more', 'tasks', 'here'))
})
```

**After**
```js
gulp.task('watch', () => Promise.all([
  gulp.watch(paths1, gulp.parallel('some', 'tasks', 'here')),
  gulp.watch(paths2, gulp.parallel('more', 'tasks', 'here'))
]))
```

Does that improve the error message you get back?

Pushed it as an extra commit.

**Comment by nickcolley** [comment]
```
[11:23:06] Starting ‘nodemon’...
[11:23:06] Finished ‘watch’ after 15 ms
```

It gets one past the `nodemon` task to `watch` but hangs again.

**Comment by nickcolley** [comment]
Chatting with Colin he suggested to make sure there's no other Node.js instance running so I ran

`killall node`

and tried again and it succeeded running.

Interestingly it says

```
Server started at http://localhost:3000
Server started at http://localhost:3000
Server started at http://localhost:3000
```

Which suggests the server is being spun in three times?

**Comment by colinrotherham** [comment]
@nickcolley Can I fix that please??

I always got it twice when developing with GOV.UK Frontend! 😁 

But now we're returning a promise from "gulp watch" you've got another condition where files are changed _after_ the nodemon/watchers have started.

i.e. Nodemon has received two file change events, so you see the initial startup log plus two more restarts in the terminal (3 in total).

**Comment by colinrotherham** [comment]
@nickcolley On first build, Nodemon was buffering 153 file changes in _docs_, _package_, _sassdoc_ which aren't needed for dev server restart so we can reduce this somewhat.

Can you try this? I've narrowed it down to `./app` and `./src/govuk`.

```js
return nodemon({
  watch: [
    paths.app,
    paths.src
  ],
  script: 'app/start.js'
})
```

Give it a go? Pushed again to https://github.com/alphagov/govuk-frontend/pull/1663

**Comment by nickcolley** [comment]
Yeah, seems like a good idea, let's give it a go. Thanks for helping with this Colin :)
