### ISSUE TITLE
Internet Explorer installation documention not clear from install guide

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1675]
When going through [Installing with npm](https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md) there is a mention of Internet Explorer at the bottom but nowhere else, I think this could mean most of our users will not be aware they need to setup separate build stuff for IE8.

We might want to consider restructuring the install steps to be more task oriented rather than grouped by technology.

**Comment by EoinShaughnessy** [comment]
Closing this as the linked content no longer exists (although Frontend docs has the similar-seeming [Install with npm](https://frontend.design-system.service.gov.uk/installing-with-npm/#install-with-node-js-package-manager-npm). Also, it seems unlikely many/any users are going to install using IE8 either now or in the future.
