### ISSUE TITLE
Header navigation text cannot be customised or translated

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1682]
The header contains hardcoded English strings in the template:

- Show or hide Top Level Navigation
- ~~Menu~~
- Top Level Navigation

https://github.com/alphagov/govuk-frontend/blob/584ea8d77f499fe4a7e5d7a5cdfbd6f6587416f6/src/govuk/components/header/template.njk#L63

https://github.com/alphagov/govuk-frontend/blob/584ea8d77f499fe4a7e5d7a5cdfbd6f6587416f6/src/govuk/components/header/template.njk#L65

This means this text cannot be customised or translated (for example into Welsh) whilst using the Nunjucks template.

**Edit: split the customising of 'menu' into https://github.com/alphagov/govuk-frontend/issues/1904**

**Comment by HughePaul** [comment]
Also in the footer, the visually hidden text "Support Links" and the copyright text, which would be "Mae’r holl gynnwys ar gael dan Drwydded y Llywodraeth Agored v3.0, ac eithrio lle nodir yn wahanol
© Hawlfraint y Goron" in Welsh

**Comment by hannalaakso** [comment]
Thanks for the feedback @HughePaul 👍 

> the visually hidden text "Support Links" 

I've left a comment to this effect on https://github.com/alphagov/govuk-frontend/issues/1763.

> the copyright text

This is covered by https://github.com/alphagov/govuk-frontend/issues/1290.
