### ISSUE TITLE
Be explicit about which Sass compilers we support

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1683]
## What

Document which Sass compilers we expect GOV.UK Frontend to correctly compile with, including minimum versions.

## Why

By being explicit about which Sass compilers we support we enable our users to make informed decisions about their build pipeline.

This will also help us when making changes, as we'll be able to make informed decisions about which features we can safely use. This is especially important given the current landscape and the different features supported by the different compilers (see http://sass-compatibility.github.io for details)

## Questions / prompts

- If we drop support for a compiler, or change the minimum version of a compiler (e.g. so that we can start relying on a newer Sass feature) does that count as a breaking change?
- Where would users expect to find this information?
- Is there a way of defining this in the `package.json` file such that any unmet dependencies are flagged at install time? Or otherwise detecting / flagging this to the user?

**Comment by m-green** [comment]
Hi @36degrees - can you involve me when you kick this one off please? I should have time to write this - and I'd like to be involved in the discussions about where it would sit.

**Comment by nickcolley** [comment]
Todo:

- [ ] list all compilers that people use.
- [ ] test GOV.UK Frontend in those compilers.
- [ ] note if we could add them as part of our test suite.

**Comment by 36degrees** [comment]
> test GOV.UK Frontend in those compilers.

http://sass-compatibility.github.io/ might be useful in working out what features we are using that rely on particular versions of the different compilers.

I am slightly concerned that there may be features that we are relying on that would not cause the Sass compilation to fail, but would result in incorrect CSS being outputted, which may be harder to detect?

> note if we could add them as part of our test suite.

I _think_ that's covered by https://github.com/alphagov/govuk-frontend/issues/1684?

**Comment by nickcolley** [comment]
@36degrees that card says to me 'do the work' but I imagine it'll be impractical to use the Ruby sass gem in our project so we wouldnt just do it, hence why I've added a reminder to make a note when I go through them...

**Comment by 36degrees** [comment]
Yeah, I think dart-sass is the reference implementation, which is why it's not listed there, but it'd be useful to know what version different features were implemented in (unless they've all been supported since the first version?) I guess we'll find out…

**Comment by nickcolley** [comment]
https://github.com/nickcolley/govuk-frontend-sass-compilers
