### ISSUE TITLE
Fail the build if compilation fails with any of our supported Sass compilers

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1684]
## What

Compile the GOV.UK Frontend Sass using the minimum version of each of the Sass compilers that we support.

Fail the build if it fails to compile using any one of them.

## Why

So that we have the confidence to ship releases whilst knowing that they should work with any of the Sass compilers that we support

## Questions / prompts

- Should we also consider compare the output of the different compilers to ensure they're effectively equivalent? (May be very difficult if there are big differences in order / whitespace etc?)
- Check to see if any other Sass frameworks are already doing this.
- What impact will this have on our CI run time?

## Dependencies

- [x] Be explicit about which Sass compilers we support #1683

**Comment by nickcolley** [comment]
From my investigation there is very minor differences in the output, to test the minimum of libsass we'd need to run an older version of Node.js

We could however consider testing dart-sass, but I think it's probably worth relying on support issues instead given what I've seen.

**Comment by 36degrees** [comment]
This is what I had in mind for testing different Sass compilers:

https://github.com/alphagov/govuk-frontend/compare/test-sass-compilers?expand=1

Which results in a build output like this:
https://travis-ci.com/alphagov/govuk-frontend/builds/150464036

I _believe_ we could set the additional two tasks up as separate jobs rather than separate stages, which would allow them to run in parallel rather than in series. I'm just trying to get my head around the syntax required to do that.

Is that less complex than you'd been imagining?

**Comment by nickcolley** [comment]
> Is that less complex than you'd been imagining?

Being able to conditionally specify node versions with Travis simplifies most of my worries.

Would be good to keep any eye on the additional time it might take, or if it could create a bottleneck.
