### ISSUE TITLE
SVGImage does not support `src` attribute

### ISSUE THREAD

**Issue by paroxp** [alphagov/govuk-frontend#1688]
## What

You seem to be using SVGs, with a [fallback image defined as `src` attribute of an `image` tag][1]. This appears not to be a thing in accordance to the [API reference][2].

**I'm not certain if this causes any issues.** I do know, that using the `href` tag that is in fact documented, will break the design by loading both svg and fallback image.

Stumbled upon this whilst writing some syntax in TypeScript'ed React.

[1]: https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/header/template.njk#L42
[2]: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image

**Comment by nickcolley** [comment]
Heya :)

This is done intentionally so that the header will display the fallback only in older browsers, it is documented in our known warnings:

https://github.com/alphagov/govuk-frontend/issues/1280#issuecomment-509588851

Thank you for checking with us but I will close this as there's no action to take at this time.

**Comment by 36degrees** [comment]
The IE developer tools might show it requesting the fallback, but it should abort almost immediately before downloading anything. If you're seeing both requests actually completing in any browser, please let us know which browser / OS you're seeing this in so we can investigate.

Thanks

**Comment by paroxp** [comment]
Thanks Nick, that's exactly what I was looking after.

Just to answer Oliver:
<img width="240" alt="Screenshot 2020-01-07 at 15 08 29" src="https://user-images.githubusercontent.com/2418945/71905241-a64deb80-315f-11ea-9d57-8f1031640b4e.png">
But like Nick mentioned, this is somewhat desired :) I guess my types system needs to remain sad.

**Comment by 36degrees** [comment]
@paroxp I'm not seeing that in Chrome… is that using the exact same markup / styles as in GOV.UK Frontend?

**Comment by paroxp** [comment]
No no, as I've mentioned in the initial issue:

> using the `href` tag that is in fact documented, will break the design by loading both svg and fallback image

sorry for the confusion.
