### ISSUE TITLE
Disabled select text colour too faint?

### ISSUE THREAD

**Issue by kr8n3r** [alphagov/govuk-frontend#1692]
this is the browser default style 
<img width="251" alt="Screenshot 2020-01-09 at 11 08 37" src="https://user-images.githubusercontent.com/3758555/72062841-7f62f700-32d0-11ea-8a83-954ec8c793e3.png">

**Comment by nickcolley** [comment]
I've created a demonstration page of all our elements that can be disabled and screenshotted them across browsers.

Findings:

1. Some components have a styled disabled state
1. Some components dont have a 'disabled' option.
1. Some operating systems show a disabled state but others do not.

Recommendation:
1. create disabled states for elements that 
1. investigate if styling the disabled state for the select input would work across operating systems/browsers

<details>
<summary>Screenshots (generated by browserstack)</summary>

![win7_ie_9 0](https://user-images.githubusercontent.com/2445413/72365138-97cb7b00-36ef-11ea-868f-aa7f9cee3597.png)
![win7_ie_8 0](https://user-images.githubusercontent.com/2445413/72365140-98641180-36ef-11ea-8fde-3a864ef1bf34.png)
![win7_ie_11 0](https://user-images.githubusercontent.com/2445413/72365141-98641180-36ef-11ea-9d6e-29cb88d16eb5.png)
![win7_ie_10 0](https://user-images.githubusercontent.com/2445413/72365142-98fca800-36ef-11ea-9548-2a49661cb6fc.png)
![win10_edge_18 0](https://user-images.githubusercontent.com/2445413/72365143-98fca800-36ef-11ea-8960-4e951df607ad.png)
![win10_chrome_71 0](https://user-images.githubusercontent.com/2445413/72365144-98fca800-36ef-11ea-9d21-d6ab5b3cb0f7.png)
![macmo_safari_12 1](https://user-images.githubusercontent.com/2445413/72365147-99953e80-36ef-11ea-9a87-288b2e81e550.jpg)
![macmo_chrome_71 0](https://user-images.githubusercontent.com/2445413/72365148-99953e80-36ef-11ea-8239-38477e385c48.png)
![9 0_Samsung-Galaxy-S9-Plus_portrait_real-mobile](https://user-images.githubusercontent.com/2445413/72365149-99953e80-36ef-11ea-9554-cb1250d7c11b.jpg)
![12_iPhone-XS_portrait_real-mobile](https://user-images.githubusercontent.com/2445413/72365150-99953e80-36ef-11ea-945d-e9a01c2cc87d.jpg)

</details>
