### ISSUE TITLE
Hint for fieldset not announced if first input has hint

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1696]
We're using the [Checkbox items with hints](https://design-system.service.gov.uk/components/checkboxes/#checkbox-items-with-hints) pattern in our service and I've noticed something in VoiceOver (can't comment on JAWS or NVDA). Here's an abbreviated version of the code from the example:

```html
<fieldset aria-describedby="nationality-hint">
    <legend>
        <h1>What is your nationality?</h1>
    </legend>
    <span id="nationality-hint">
        If you have dual nationality, select all options that are relevant to you.
    </span>
    <div>
        <input id="nationality" name="nationality" type="checkbox" value="british" aria-describedby="nationality-item-hint">
        <label for="nationality">British</label>
        <span id="nationality-item-hint">
            including English, Scottish, Welsh and Northern Irish
        </span>
    </div>
    <!-- etc. -->
```

The hint text for the `aria-describedby` on the `input type="checkbox"` supersedes the hint text for the `aria-describedby` on the `fieldset`. So the user **only gets one hint** read to them when they jump to the input through the tab index – the one on the `input`, rather than the `legend`.

It doesn't feel right that the hint text on the `fieldset` isn't read out, when it would be if there was no hint text on the `input`, but maybe it's deliberate to reduce noisiness or for some other reason. Anyone encountered this before?

_Originally posted by @tempertemper in https://github.com/alphagov/govuk-design-system-backlog/issues/37#issuecomment-573084855_

**Comment by hannalaakso** [comment]
We did [some testing](https://docs.google.com/spreadsheets/d/1Q-jTC8bcBagPHLlhyxH81FSqlNL446kyMU04st9PJxE/edit#gid=0). The main problems to look at are:
- Jaws with Chrome doesn't announce the input label
- NVDA with FF and Chrome, iOS VoiceOver and Mac VoiceOver read out the question, the input label, the input hint but not the fieldset hint
- NVDA with Edge and IE11 only reads out input label and the input hint (no question or fieldset hint)

It might be worth trying to move the `aria-describedby` to `<legend>` or `<h1>`, or move the fieldset hint inside the legend itself. However this might have already been previously explored. What do you think @36degrees?

**Comment by 36degrees** [comment]
> It might be worth trying to move the `aria-describedby` to `<legend>` or `<h1>`, or move the fieldset hint inside the legend itself.

We've used various different approaches before:

- https://github.com/alphagov/govuk_elements/pull/153
- https://github.com/alphagov/govuk_elements/pull/187
- https://github.com/alphagov/govuk_elements/pull/461
- https://github.com/alphagov/govuk_elements/pull/485
- https://github.com/alphagov/govuk_elements/pull/484
- https://github.com/alphagov/govuk_elements/pull/507
- https://github.com/alphagov/govuk-frontend/pull/681
- https://github.com/alphagov/govuk-frontend/pull/684

We moved the hint / error message out of the legend in #681, based partly on the research in https://github.com/alphagov/govuk_elements/issues/574.

The current approach feels like it's the most semantically 'correct' of all the options we've tried. The  hint describes the `group` of elements, which is represented by the `fieldset`. The hint does not 'describe' the `legend`, nor the `heading`.

My preference would be to raise bugs against NVDA / Jaws, and not to revisit the implementation unless we see evidence that this is having a serious impact on users or we learn that we're going 'against the spec'.

**Comment by nickcolley** [comment]
Minimal test case: https://jsbin.com/qayirilaci/7/edit?html,css,output

**Comment by nickcolley** [comment]
Closing this out as raised issues, hopefully they get resolved! We can re-open if this becomes a more serious issue for our users.
