### ISSUE TITLE
Accessibility - High contrast mode arrows/caret

### ISSUE THREAD

**Issue by Dawdre** [alphagov/govuk-frontend#1707]
![image](https://user-images.githubusercontent.com/11505395/72816809-9e627100-3c60-11ea-9a27-c76c030a4d2e.png)
![image](https://user-images.githubusercontent.com/11505395/72816833-a91d0600-3c60-11ea-8814-6985a66b9500.png)

High contrast mode in Windows produces these effects on the details and back link components. This appears to be because High contrast mode adds borders on all sides to any element with a border. Thus producing a square. Is this a known issue?

Much appreciated

**Comment by hannalaakso** [comment]
Hi @Dawdre thanks for raising this 🙌 I'm going to close your issue as I think it's covered by https://github.com/alphagov/govuk-frontend/issues/937. Feel free to comment on that issue if you have any additional comments.
