### ISSUE TITLE
ReadWrite - screenreader - highlighted text not read out = legend tags

### ISSUE THREAD

**Issue by FeyAgape** [alphagov/govuk-frontend#1710]
When using Read Write with the screen reader option it should highlight the text as it reads it out but it doesn't highlight any of the questions.

It has been diagnosed that this is an issue with Read Write - they don't highlight text with a legend.

The GOV.UK Frontend demo sites that have been used to test…

1. Content page
http://govuk-frontend-review.herokuapp.com/full-page-examples/announcements
i.e. Regular `<h1>`, `<h2>` etc

2. Form page without legend
http://govuk-frontend-review.herokuapp.com/full-page-examples/update-your-account-details
i.e. Regular `<h1>` with field `<label>` tags

3. Form page with legend
http://govuk-frontend-review.herokuapp.com/full-page-examples/what-is-your-address
i.e. Legend with field `<label>` tags.

**Comment by hannalaakso** [comment]
Thanks for raising this @FeyAgape. 

We've tested with Read&Write v12.0.60, Chrome version 79 and Support for Read&Write Desktop Chrome extension v2.0 and haven't been able to replicate this.

We're highlighting the back link on the form pages (your examples 2 and 3), press Play and the legend text is read out correctly. 

Could you give us more details on how to reproduce:
- Version of Read&Write software, browser and version and any browser extension and version
- Steps to reproduce (what text highlighted, what buttons pressed in Read&Write)

**Comment by FeyAgape** [comment]
We've tested using Read&Write v11.5.4, internet explorer 11.1069.17134.0

**Comment by nickcolley** [comment]
I've tested with Internet Explorer 11 and the legend is still read out, can you give some clear steps on what you're doing please?

**Comment by 36degrees** [comment]
We're going to close this as we haven't been able to reproduce it and we haven't heard from you.

If you're able to provide clear steps on what we need to do to reproduce it, please comment if you'd like us to re-open this issue.
