### ISSUE TITLE
Add disabled option for input components consistently

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-frontend#1712]
## What
Some input components can be disabled but do not have an option in Nunjucks to do this, we should make sure all input components that can be disabled have this option.

## Why
Make sure our component APIs are predictable and consistent

## Who needs to know about this
Developers

## Further detail
We don't need to document this in the Design System guidance as an example as we don't recommend people do this, but it will be in the macro options.

See this related issue for more context: https://github.com/alphagov/govuk-frontend/issues/1692#issuecomment-574274312

## Done when

- [x] File upload has a top level 'disabled' option
- [x] Select has a top level 'disabled' option
- [x] Text input has a top level 'disabled' option
- [x] Textarea has a top level 'disabled' option

**Comment by querkmachine** [comment]
This has been shipped as part of #3187. 🚀
