### ISSUE TITLE
Spike approaches to internationalisation

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1714]
## What
In https://github.com/alphagov/govuk-frontend/issues/1709, we will hopefully have identified some possible approaches to internationalisation that we want to investigate further. We've also previously spoken about three options:

1. Using some kind of internationalisation library (how does this work in practice? Is this too complex for what we need?)
2. Allow services to provide us with the relevant translated string that they want to use (How does this work in situations where we need to deal with multiples/plurals, e.g: character count)
3. Add a Nunjucks macro option language flag which toggles the component to Welsh (How would we get and maintain Welsh translations now and for future components? Is this scalable?)

We need to make some decisions on which approach would work best for us. We need to keep in mind:

- We may want to implement a combination of approaches, especially if we have a short-term requirement to provide Welsh translations, but we need something more flexible in future
- Any approach we pick should work with what [service teams are currently doing in their own applications](https://github.com/alphagov/govuk-frontend/issues/2566)
- Whether any of these solutions would also apply more generally to configuring more complex components and, if so, how

## Why
So that we can get a better understanding of the approaches that work for us.
So that we can talk about the advantages and disadvantages of the approach in any proposal we write and share with the community.

## Who needs to know about this
Developers

## Depends on
https://github.com/alphagov/govuk-frontend/issues/1709 and https://github.com/alphagov/govuk-frontend/issues/2566

## Done when

Note: it's likely that we may want to spike a few different approaches. It may make sense to write up separate cards for each spike when we know what those look like, so that they can be worked on in parallel/by different people. We can then come together to discuss what we've learnt.

- [x] We've tried out some viable approaches
- [x] Written up what we've learnt from our spikes
- [ ] Will anything we do here affect ports of GOV.UK Frontend?
- [ ] We have decided on an approach and are ready to share this with teams

**Comment by querkmachine** [comment]
There is a draft PR of a potential approach currently open for feedback. 
- #2614
