### ISSUE TITLE
Write and share a proposal for internationalisation

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-frontend#1715]
## What
Write and share a proposal for our approach to internationalisation, specifically translating hardcoded strings in component JavaScript. The proposal needs to include:

- details of how we expect people to pass translations into component JS
- any specific questions or concerns we have that we'd like to get feedback on
- who we'd like to hear from, e.g: if we think questions may be answered by a specific audience
- a way to get in touch or show an interest in being approached by our team with any follow-up questions

We're going to post this proposal as a Github discussion, and share it via Slack and the mailing list.

## Why
Internationalisation is complex and we want to make sure that our approach works for service teams. We've already identified some potential things that may cause issues for service teams, but we don't have confidence in knowing whether they are real problems or not. 

## Who needs to know about this
Developers; Tech Writer

## Depends on
https://github.com/alphagov/govuk-frontend/issues/1714

## Done when

- [x] Draft a proposal
- [x] Decide how to share the proposal, e.g: Github discussions vs Github PR in architecture repo vs anything else
- [x] Decide how long we want to give for feedback
- [x] Share the proposal with the community on Slack
- [x] Share the proposal via the mailing list
- [x] Decide on what to do next based on community feedback
- [x] Reply to comment from port maintainer asking for a JSON file of translations and ask for clarity on why and what they'd use it for
- [x] Provide an update explaining the data-attributes approach we'll be implementing too.
- [x] Close proposal

**Comment by querkmachine** [comment]
[I've drafted a proposal](https://docs.google.com/document/d/1y0Zh4m9qImcqfIhtoqndMInAOp4nTU2ORSukPgPTZEk/edit), however we're unsure as to how necessary this is as we have two draft PRs already created. We may wish to produce comms and have people review the PRs directly, rather than solicit feedback on a proposal document.

**Comment by nickcolley** [comment]
Just so you know that proposal is hidden from outside GDS, so you might want to consider making it public only or copying it into your message if it contains anything useful for the record going forwards.

**Comment by trang-erskine** [comment]
No longer relevant.

**Comment by vanitabarrett** [comment]
@querkmachine I've suggested some changes to your original proposal. Would you be happy to go review and accept/reject/comment as you see fit?

**Comment by vanitabarrett** [comment]
Proposal has been published as a new Github discussion here: https://github.com/alphagov/govuk-frontend/discussions/2740

@calvin-lau-sig7 is currently reviewing the comms I've put together, and I'll send them out once we're happy with them.

I've set a deadline for feedback of 12th August for now, as we mentioned giving people at least 1 week.

**Comment by vanitabarrett** [comment]
Moving this into Blocked until 12th August

**Comment by vanitabarrett** [comment]
Feedback gathered and actions noted down in this doc: https://docs.google.com/document/d/1B9ag7WPN0dDuBxVSKntVBxUM7Y7xVTKromKPcZwIjZc/edit#
