### ISSUE TITLE
Back link's arrow and border do not scale

### ISSUE THREAD

**Issue by adamliptrot-oc** [alphagov/govuk-frontend#1717]
## Problem

If you increase the browser's font size the Back Link component's arrow and border do not scale with the copy.

![before](https://user-images.githubusercontent.com/14074579/73466109-4ec72800-4379-11ea-976d-b37809608d1f.gif)

Screenshot from Chromium Edge v79 on Mac with font size set to large in edge://settings/fonts

![image](https://user-images.githubusercontent.com/14074579/73464048-330e5280-4376-11ea-9b7e-3faff3a276b3.png)

This is caused by the css-arrow and border being set in px

## Solution

Replace/override px values with em values so they scale in proportion to the copy. 

![after](https://user-images.githubusercontent.com/14074579/73466135-5686cc80-4379-11ea-95d3-b88106062350.gif)

**Comment by hannalaakso** [comment]
Related: https://github.com/alphagov/govuk-frontend/issues/1569
