### ISSUE TITLE
Consider alternatives for `gulp-better-rollup`

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1718]
Raised on behalf of @aliuk2012.

[`gulp-better-rollup` is currently without a maintainer](https://www.npmjs.com/package/gulp-better-rollup#looking-for-maintainer). We should consider finding an alternative library that is being actively maintained.

**Comment by nickcolley** [comment]
We don't want to update this as far as I know since newer versions of rollup dont support Internet Explorer 8.

**Comment by hannalaakso** [comment]
Going to close this as we don't have any intention of upgrading the package because we're reliant on the IE8 support in the current version.
