### ISSUE TITLE
Document our JavaScript component conventions

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1721]
## What
Write documentation for our JavaScript component conventions.

## Why
We've done all the hard work in https://github.com/alphagov/govuk-frontend/issues/1719 to decide what our JavaScript component conventions are and our approach for public vs private methods. We should make sure we document these decisions somewhere.

## Who needs to know about this
Developers; Tech Writer

## Depends on

- [x] https://github.com/alphagov/govuk-frontend/issues/1719

## Done when

- [ ] Decide where this documentation should live (probably the govuk-frontend repo somewhere)
- [ ] Draft documentation for our conventions
- [ ] Reviewed by tech writer and developers
- [ ] Published

**Comment by 36degrees** [comment]
Closing, although we should make sure we're including this as part of our 'done when' criteria other JavaScript related work
