### ISSUE TITLE
are this supporting to Angular framework ?

### ISSUE THREAD

**Issue by siva563** [alphagov/govuk-frontend#1737]
Is this supporting the Angular Framework?

Could you please help me how to install and how to link for Angular 8.

Thanks in advance !!!

**Comment by 36degrees** [comment]
Hi Siva,

I'm going to close this GitHub issue to avoid duplication, as we have a separate email conversation going on as well.

Ollie

**Comment by Nosfistis** [comment]
Hi @36degrees,

I am part of the UK-BEIS PMRV team, and as part of our project we have created a project-agnostic Angular library wrapping the govuk-frontend project. It is thoroughly unit tested and follows Angular best practices.

Currently it is hosted in the PMRV project's private repository, but we were thinking of open sourcing / publishing it, if possible under the official organization. I understand from your reply that there is an email conversation about this topic. What do you think about our proposal?

**Comment by timpaul** [comment]
Hi @Nosfistis - thanks - this sounds interesting. We link to community-developed [tools and resources for the GOV.UK Design System](https://design-system.service.gov.uk/community/resources-and-tools/), providing they meet [these criteria](https://design-system.service.gov.uk/community/contribution-criteria/#developing-a-community-resource-or-tool). Let us know if you have any questions!

**Comment by Nosfistis** [comment]
Thanks for the reply! I will introduce it to the team and come back with a response soon!
