### ISSUE TITLE
Remove `govuk-tag--inactive` class

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1757]
## What
Remove the `govuk-tag--inactive` class as it now duplicates what the `govuk-tag--grey` class does.

## Why
As discussed in https://github.com/alphagov/govuk-frontend/pull/1711#discussion_r370634942, https://github.com/alphagov/govuk-frontend/pull/1711 adds a new class `govuk-tag--grey`, the naming of which is inline with the other new tag colour classes.

## Who needs to know about this
Developers, Tech Writer

## Done when

- [ ] `govuk-tag--inactive` class has been removed
- [x] "Details of breaking change" section below completed to help with writing release notes

## Details of breaking change

- which users are affected: If you use `govuk-tag--inactive`
- the change that’s been made: `govuk-tag--inactive` has been removed
- changes users will have to make: Replace `govuk-tag--inactive` with `govuk-tag--grey`
- impact of users not making those changes: Tag will use default style instead of greyed-out style

**Comment by lfdebrux** [comment]
I've had a go at filling out the details of breaking change in this ticket.

**Comment by lfdebrux** [comment]
I've got a PR to remove the class, including a first pass update to the release notes.
