### ISSUE TITLE
Update GOV.UK Frontend repo docs to link to new tech docs

### ISSUE THREAD

**Issue by m-green** [alphagov/govuk-frontend#1759]
## What
After the new Tech Docs Template (TDT) tech docs are published, we need to update Frontend to: remove documentation that's been moved to the TDT, and update links so they point to the TDT.

## Why
So there's no duplicate documentation, and user journeys work from the Frontend repo to the TDT.

## Who needs to know
Mark, devs

## Done when
Updated existing [test branch](https://github.com/alphagov/govuk-frontend/tree/test_moving_docs) to:

- [ ] removed documentation that's been moved to the TDT
- [ ] updated links so they point to the TDT

Then:
- [ ] published

**Comment by 36degrees** [comment]
Not sure why this is closed – think this still needs a review.
