### ISSUE TITLE
MS Edge (very old version) Accordion and details elemement

### ISSUE THREAD

**Issue by aminmc** [alphagov/govuk-frontend#1761]
Hello,

I've come across an issue with using accordion and details elements when using Edge version 42 (not an issue with Edge version 79+). When you expand an accordion item the details elements cannot be opened or closed.  If you close the accordion then the details elements work as expected.  I understand this is an issue with a very old browser but most of our users are stuck using this version of edge (there are plans to upgrade but not sure about timeframes).  Accordion state is stored in session storage so I can't imagine that could cause a problem.

Any pointers were to look for the cause of this issue would be appreciated. 

Thank you.

**Comment by 36degrees** [comment]
Hi Amin,

I've tried to reproduce this by including an accordion and a details component on the same page, using Edge 42.17134.1.0 on Windows 10, but have not been able to – both components are working as expected.

Are you able to provide any more details about how the details and accordion are placed on the page? A URL where I can try and reproduce this or a code example would be ideal.

Can you also confirm which version of GOV.UK Frontend you are using, and that you're including and initialising the JavaScript correctly?

Ollie

**Comment by sarah-mc** [comment]
Hi @36degrees 

Thanks for getting back to me.  After doing a bit more debugging I worked out that I was using an internal library class which wrapped your JS APis which was causing the issue. Once i removed it and used the your JS apis directly to initialise the components it started to work. 

Thank you again and sorry to have raised the issue!

**Comment by aminmc** [comment]
Hi @36degrees

Thanks for getting back to me. After doing a bit more debugging I worked out that I was using an internal library class which wrapped your JS APis which was causing the issue. Once i removed it and used the your JS apis directly to initialise the components it started to work.

Thank you again and sorry to have raised the issue!

**Comment by 36degrees** [comment]
No problem at all – glad you were able to get it sorted 👍
