### ISSUE TITLE
Make task list into a component

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1764]
## What

Make task list into a component in GOV.UK Frontend. It's currently [a pattern in the Design System](https://design-system.service.gov.uk/patterns/task-list-pages/) which links to an [example in the prototype kit](https://govuk-prototype-kit.herokuapp.com/docs/templates/task-list) ([code](https://github.com/alphagov/govuk-prototype-kit/blob/master/docs/views/templates/task-list.html)). 

## Why

With the addition of guidance in https://github.com/alphagov/govuk-design-system/issues/1183 it would be good to have coded examples of the task list in the Design System.

This would also make it possible to version the task list and to make it part of the public API of GOV.UK Frontend.

It would also make it easier to find the code in the Design System: we had a query from a user who didn't know where to find the coded example. 

## Further detail

The task list is more of a page than a component so we'd need to consider whether it makes sense for it be published as a component, especially in the Design System.  

## Who needs to know about this
Tim, developer

# Done when

- [x] A decision has been made
- [x] A card has been written with follow up actions

**Comment by EoinShaughnessy** [comment]
Should this issue link to [#2261](https://github.com/alphagov/govuk-frontend/pull/2261)?

**Comment by owenatgov** [comment]
I'm closing this as it'll be covered by https://github.com/alphagov/govuk-frontend/pull/2261 as Eoin noted above
