### ISSUE TITLE
Accordion underline on hover is removed when over plus/minus symbol

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1769]
## Steps to reproduce

1. Mouse over the plus/minus symbol for a section in the accordion.

## Expected result

The underline text-decoration on the section title should remain visible.

## Actual result

The underline text-decoration on the section title is removed.

![accordion-hover-bug](https://user-images.githubusercontent.com/121939/77547607-5270ba00-6ea5-11ea-9c20-cb31b08b040f.gif)

**Comment by 36degrees** [comment]
Adding `pointer-events: none` to the icon seems to fix this in Chrome, but won't do anything for older browsers that do not support `pointer-events`.

**Comment by nickcolley** [comment]
Might be able to use a selector on the parent like so: `.header:focus .button`
