### ISSUE TITLE
Documentation for `label` on radio and checkboxes components is misleading

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/govuk-frontend#1779]
The macro options for the checkboxes component (see https://design-system.service.gov.uk/components/checkboxes/) and radios component suggests that you can use the the `text` and `html` options for `label` within `items`, but this doesn’t work, you have to use the `text` or `html` options for the `item` instead.

I’m guessing this is because the documentation automatically uses the macro documentation for the nested govukLabel component?

**Comment by colinrotherham** [comment]
As a quick fix, I've added the correct subset of `params` to `radios.yaml` and `checkboxes.yaml` in:

* https://github.com/alphagov/govuk-frontend/pull/4563

But this causes the `isComponent` link not to render so another tweak is needed in:

* https://github.com/alphagov/govuk-design-system/pull/3372
