### ISSUE TITLE
Consider renaming group for media queries to break points

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1828]
## What
[/settings/_media-queries.scss](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/settings/_media-queries.scss#L2) uses the group name `media-queries` but actually contains breakpoint related things. This means that frontend docs have a [Media queries section](https://frontend.design-system.service.gov.uk/sass-api-reference/#media-queries) that contains information about breakpoints but sounds like it has information about media queries themselves - I was helping someone on support and this tripped me up! 

The actual [media query mixin](http://127.0.0.1:4567/sass-api-reference/#govuk-media-query) is further down the page. 

We could consider renaming the group from `media-queries` to `break-points` (and also renaming the file, although this could be a breaking change for some users).

## Why
Renaming the group from `media-queries` to `break-points` would be more reflective of what the file contains and reduce the duplication of things called media query/queries in the docs. 

## Who needs to know about this
Devs, Mark

**Comment by 36degrees** [comment]
My intent was to group things using the same groupings across different layers, so you have e.g. colour settings and colour helpers, typography settings and typography helpers.

The media query helper is in the 'layout' group which is probably a better granularity than having a group just for media queries. My preference would be to continue to use the same groups within each layer, but move the breakpoint settings into the layout group.
