### ISSUE TITLE
Document date input change from `type="number"` to `inputmode="numeric"` in next breaking release

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1829]
We made a markup change to the date input component from `<input […] type="number" pattern="[0-9]*">` to `<input […] type="text" inputmode="numeric" pattern="[0-9]*">` in https://github.com/alphagov/govuk-frontend/pull/1704. 

Since the change was in a non-breaking release we treated it as an enhancement and didn't document steps for making the change in the release note. However we should document the steps to make this change in people's projects in the release note of the next breaking release.

**Comment by 36degrees** [comment]
This was included as a recommended change in the release notes for v4.0.
