### ISSUE TITLE
custom font url handler does not work

### ISSUE THREAD

**Issue by sjclemmy** [alphagov/govuk-frontend#1831]
https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/tools/_font-url.scss#L19
The construction of this variable `$use-custom-function` never returns true:
  ```
$use-custom-function: variable-exists("govuk-font-url-function")
    and $govuk-font-url-function
    and function-exists($govuk-font-url-function);
```
if I define a function called `govuk-font-url-function` the above variable is never satisfied because `variable-exists("govuk-font-url-function")` returns false, `$govuk-font-url-function` errors and `function-exists($govuk-font-url-function)` is incorrect syntax and so errors. The syntax should be `function-exists(govuk-font-url-function)`

I'm using `gulp-sass` and the compiler is `node-sass`.

**Comment by 36degrees** [comment]
Hi Steve,

The `$govuk-font-url-function` should be a string with the _name_ of the function that you want to use. The function does not need to be called `govuk-font-url-function`.

This allows you to define your own function, but also to use existing built-in functions provided by your framework (for example, the `font-url` helper provided in the Rails asset pipeline).

(The `function-exists` call in that check is ensuring that the function named by `$govuk-font-url-function` exists, not that there is a function called `govuk-font-url-function`)

```scss
@function my-url-handler($filename) {
  // Some custom URL handling
  @return url('example.woff');
}

$govuk-font-url-function: 'my-url-handler';
```

You can see a few other examples in the [Sass API reference](https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-font-url-function).

Hope that helps – please let me know how you get on.

**Comment by sjclemmy** [comment]
ah ok - the penny drops. I'm glad I asked, I'm not familiar with the sass syntax, that makes perfect sense.
Thanks for the quick response 😄
