### ISSUE TITLE
Consider changing govukHint to wrap its content in a DIV rather than a SPAN

### ISSUE THREAD

**Issue by matthewmascord** [alphagov/govuk-frontend#1835]
Services may have a valid reason to include hint copy that includes block level elements such as P or UL. For example, on the Gov.UK cookies page, https://www.gov.uk/help/cookies

At the moment the govukHint component wraps the markup it accepts in a SPAN and this causes HTML validation errors if developers include block level elements because block level elements are not allowed within a SPAN.

https://github.com/alphagov/govuk-frontend/tree/master/src/govuk/components/hint

**Comment by 36degrees** [comment]
This also came up in https://github.com/alphagov/govuk-design-system/issues/778#issuecomment-561130513
