### ISSUE TITLE
JavaScript modules are attached to the same global variable when imported individually

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk-frontend#1836]
### Context

[When we compile the JavaScript assets to UMD we attach them to `GOVUKFrontend`](https://github.com/alphagov/govuk-frontend/blob/master/tasks/gulp/compile-assets.js#L160-L167), which [works well when importing all components](https://github.com/alphagov/govuk_publishing_components/pull/1472/files#diff-b7cab78200d934a1e9398c273d9f5be5L3), but not so great [when importing individual scripts](https://github.com/alphagov/govuk_publishing_components/pull/1472/files#diff-3fd0e8584efb3f8d58f4656b5dc2c618R5).

### Problem
For example, in GOV.UK Publishing Components, when importing multiple components individually from `govuk-frontend` only the last one will be available.
```ruby
//= require govuk/components/accordion/accordion.js
# accordion.js is exposed via window.GOVUKFrontend; not GOVUKFrontend.Accordion as expected
//= require govuk/components/accordion/button.js
# button.js is exposed via window.GOVUKFrontend; accordion.js is lost
```
As a workaround, [we attached the component to another global](https://github.com/alphagov/govuk_publishing_components/pull/1472/files#diff-3fd0e8584efb3f8d58f4656b5dc2c618R5) `GOVUK.Modules.[ComponentName]` right after importing it.

### Potential solution
Update [compile-assets.js](https://github.com/alphagov/govuk-frontend/blob/master/tasks/gulp/compile-assets.js) script to attach components to `GOVUKFrontend.[ComponentName]` instead of `GOVUKFrontend`.

## Done when

- [ ] Importing multiple individual component JavaScript modules no longer overwrites the previous one
- [x] "Details of breaking change" section below completed to help with writing release notes

## Details of breaking change

- which users are affected: users who import component JavaScript individually
- the change that’s been made: component JavaScript is now attached to `window.GOVUKFrontend.[ComponentName]` rather than `window.GOVUKFrontend` to avoid multiple imports for individual components overwriting each other
- changes users will have to make: any users who important component JavaScript individually may have written their own code to work around this problem or may be relying on the JavaScript being available with `window.GOVUKFrontend`. Users must update references to account for the new naming, for example switching calls to `window.GOVUKFrontend` to `window.GOVUKFrontend.[ComponentName]`
- impact of users not making those changes: their JavaScript code may error as it's unable to find the correct module

**Comment by 36degrees** [comment]
Although the current behaviour definitely doesn't seem 'correct', I think we'd have to treat this as a breaking change so I'm going to attach this to the 4.0 milestone.

**Comment by alex-ju** [comment]
Thank you @36degrees! I'm pretty confident I introduced this problem, so happy to work on it if the team decides so.

**Comment by vanitabarrett** [comment]
Had a discussion in the v4 planning session about whether we should make this change backwards compatible by supporting the current way of doing things with the new way (and then removing that in a later release). I think we're all in agreement that the current behaviour is a bug that people are now probably relying on working in that way (as we haven't had many reports of this issue). Probably needs a little bit of investigation into what the fix would look like before we know for certain whether it's something to include in v4.

**Comment by vanitabarrett** [comment]
Moving this into Blocked for now as I've asked Alex from GOV.UK to test this change to make sure it works for them. Waiting to hear back.
