### ISSUE TITLE
Using grid classes in forms prevents clicking

### ISSUE THREAD

**Issue by Nosfistis** [alphagov/govuk-frontend#1844]
## The issue
The grid classes, e.g. `govuk-grid-column-one-quarter`, currently use `float: left` in order to position themselves.

If any kind of input is placed within that space, it is not clickable.

## Reproduction
Tested with this snippet:
```html
<div class="govuk-grid-row">
  <div class="govuk-grid-column-three-quarters">
    <div class="govuk-form-group">
      <h1 class="govuk-label-wrapper"><label class="govuk-label govuk-label--l" for="event-name">
        What is the name of the event?
      </label>
      </h1>
      <input class="govuk-input" id="event-name" name="event-name" type="text">
    </div>
  </div>
</div>
```

## Solution
Grid columns need to apply positioning: `position: relative;`.

**Comment by 36degrees** [comment]
Hi Mike,

I've not been able to reproduce this. Are you able to provide any more information? Where are you including the code from GOV.UK Frontend? Are there any of your own styles being applied to other elements on the page that might be affecting this?

Thanks.

**Comment by Nosfistis** [comment]
It seems that I cannot reproduce it either now. I am not sure why, but the input correctly receives focus on click.

If I am able to reproduce this again I will comment here.

**Comment by 36degrees** [comment]
Hi Mike,

Thanks for letting us know. I'm going to close this for now, but if you are able to reproduce this feel free to add a comment and we'll re-open.
