### ISSUE TITLE
Spike creating test fixtures for a single component

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1864]
Part of #1830 

---

## What

Spike creating test fixtures for a single component:

- Update the tests for that component to use the examples in the YAML file consistently
- Explore how we can create fixtures from the component YAML as part of the 'build:package' task
- Explore different formats for the fixtures – (e.g. separate files, separate folders, one file)
- Create fixtures for the single component
- Understand how including fixtures will affect the package size

## Why

Doing this will:

- allow us to publish a pre-release that we can share with the community in order to get feedback
- help us uncover any unforeseen issues, or unanswered questions
- help us to better understand the complexity of implementing this for all components

**Comment by vanitabarrett** [comment]
Pre-release generated here: https://github.com/alphagov/govuk-frontend/tree/pre-release-spike-test-fixtures
