### ISSUE TITLE
Draft documentation for using test fixtures

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1865]
Part of #1830 

---

## What

Draft documentation on how to use test fixtures to check that a port uses the same HTML as GOV.UK Frontend.

## Why

Doing this will allow us to include draft documentation in a proposal we can share with the community in order to get feedback.

**Comment by 36degrees** [comment]
We'll revisit what we need to do around documenting this once we've put the proposal out and got feedback from the community.

**Comment by hannalaakso** [comment]
After chatting to @m-green we're going to revisit the format of the release notes as part of this documentation work.

**Comment by m-green** [comment]
I can't add the docs as a linked PR so here's the link: https://github.com/alphagov/govuk-frontend-docs/pull/74
