### ISSUE TITLE
Create a proposal for how test fixtures will work

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1867]
Part of #1830 

---

## What

Using the results of the spike (https://github.com/alphagov/govuk-frontend/issues/1864), the pre-release (https://github.com/alphagov/govuk-frontend/issues/1866) and the draft documentation (https://github.com/alphagov/govuk-frontend/issues/1865), create a proposal that we can share with the community to gather feedback.

## Why

By gathering feedback from the community early, we can validate whether our intended approach will work for port maintainers, and identify any potential issues.

**Comment by 36degrees** [comment]
Initial draft: https://docs.google.com/document/d/10YEYal0yWZcLBNT_4f2XDFHdl-m7z_qKKhHsmXhp7hE/edit

**Comment by vanitabarrett** [comment]
The proposal has been posted on the [original issue](https://github.com/alphagov/govuk-frontend/issues/1830#issuecomment-665075842)
