### ISSUE TITLE
Finalize release notes for v3.8.0

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1877]
## What

- [ ] Write final release notes
- [ ] Developer review
- [ ] 2i

## Who needs to be involved 

@m-green and whoever is doing the release

**Comment by 36degrees** [comment]
@m-green we think everything that's going in to v3.8 has now been merged, so the changelog should now have everything that needs to be included in the final release notes:

https://github.com/alphagov/govuk-frontend/blob/master/CHANGELOG.md#unreleased

**Comment by m-green** [comment]
@36degrees Thank you - will take a look now!
