### ISSUE TITLE
Redirect Sass docs in review app to Sass API reference in Frontend Docs

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1892]
## What

Redirect from http://govuk-frontend-review.herokuapp.com/docs to https://frontend.design-system.service.gov.uk/sass-api-reference/#sass-api-reference

We may need to provide a way to run the 'generic' Sass docs locally so that we can use it to preview documentation before we do a release.

## Why

Avoid the confusion of having two versions of the Sass docs available, and point anyone who may have the existing docs bookmarked to the new docs.

**Comment by EoinShaughnessy** [comment]
Are we linking from the Heroku app to the Sass docs?

Or are we linking to the Sass docs, instead of to the Heroku app? (If so, where are we linking _from_?)

**Comment by EoinShaughnessy** [comment]
@36degrees Our ['Coding standards' doc](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/coding-standards/css.md) contains a link to http://govuk-frontend-review.herokuapp.com/docs:

> The syntax is used to generate a [SassDoc application](http://govuk-frontend-review.herokuapp.com/docs/) that documents SCSS in a readable format.

Should the link in above quote go to https://frontend.design-system.service.gov.uk/sass-api-reference/#sass-api-reference instead?

**Comment by 36degrees** [comment]
@EoinShaughnessy yes, I think it probably should! Great catch. I don't think we should call it a 'SassDoc application' if we change the link though, and the wording could be clearer… maybe something like:

> The SassDoc comments are used to generate the [Sass API reference in the GOV.UK Frontend docs](https://frontend.design-system.service.gov.uk/sass-api-reference/).

**Comment by 36degrees** [comment]
It's also odd that we link 'SassDoc' to the specific SassDoc documentation on file level annotations. That doesn't make sense to me – it should probably just link to the SassDoc homepage?

**Comment by EoinShaughnessy** [comment]
@36degrees Thanks! That wording looks good. I'll raise a PR, separate to this issue, that includes both your wording and a link to the SassDoc homepage.
