### ISSUE TITLE
Remove sass-lint while switching to stylelint

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#1898]
## What
[This PR](https://github.com/alphagov/govuk-frontend/pull/1875) introduces stylelint alongside our existing linting (using sass-lint). We need to remove sass-lint, so we're only using stylelint.

## Why
GOVUK needs to move away from scss-lint as it's blocking their upgrade from Ruby SASS to Sassc. They have chosen stylelint and have raised a PR against GOVUK Frontend to demonstrate how we may switch to stylelint to match. This will also be shared with the frontend community so we can aim for consistency across GDS.

**Comment by vanitabarrett** [comment]
WIP PR raised, but waiting to see if anything new comes out of https://github.com/alphagov/govuk-frontend/issues/1897

**Comment by m-green** [comment]
Hi @vanitabarrett - could you let me know when you start work on this so we can take a look at documentation in plenty of time?

**Comment by vanitabarrett** [comment]
@m-green Yep, will do! Waiting for https://github.com/alphagov/govuk-frontend/issues/1897 , and then will ping you once we've made some decisions on that 🙂
