### ISSUE TITLE
Confused by the documentation for radios 'conditional'

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#1903]
I was trying to use the conditional option on radios.

I saw that the example used

```
conditional:{
    html:"<p> ...
```

I didn't need html, just a sentence so I thought I could use `text` instead of `html` as you can in other places in Frontend. However, I tried it and it didn't work - there's no text option here.

When I re-read the docs, I misread and thought the 'conditional' option, being a string, could just accept text.

However, I misread it, that doesn't work - the docs actually say:

> conditional | string | If true, content provided will be revealed when the item is checked.

But I don't think this is correct? In the examples, `conditional` is not a string, it's an object with only one property - `html`

I wonder if this might be better as two options:

`conditionalHTML` and `conditionalText`

This would avoid another object, and be more consistent with the use of HTML and text elsewhere?

**Comment by vanitabarrett** [comment]
@joelanman Can you provide a link to that in the docs, as that looks like it needs correcting? It should read:

```
conditional | boolean | If true, content provided will be revealed when the item is checked.
conditional.html | string | Provide content for the conditional reveal.
``` (which I can see on https://design-system.service.gov.uk/components/checkboxes/)

Good point about being able to provide a `text` option though, that definitely seems to better match what we do elsewhere.

**Comment by joelanman** [comment]
It was radios I was looking at:

https://design-system.service.gov.uk/components/radios/

I would say even `boolean` is a bit confusing, as the examples don't use a boolean, they use an object

**Comment by 36degrees** [comment]
For now we've agreed just to remove the `conditional` entry from the macro options for radios and checkboxes, which will make it consistent to the way the accordion works and is documented (apart from not supporting `conditional.text`).

**Comment by mogusbi-motech** [comment]
The documentation around this is still a bit off as it still suggests setting `conditional` with a text value would work, which it definitely doesn't judging by the code below:

https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/radios/template.njk#L14-L19

Documentation reference: https://design-system.service.gov.uk/components/radios/

![image](https://user-images.githubusercontent.com/53015240/112020024-eeb8b580-8b27-11eb-814d-bee45e02799f.png)

**Comment by EoinShaughnessy** [comment]
The macro options for radios and checkboxes still display conditional entries. Do we need to remove these entries?

**Comment by joelanman** [comment]
just come across this again in my work - `conditional` is still listed as a string option

**Comment by joelanman** [comment]
thanks!
