### ISSUE TITLE
Footer top border discrepancy between GOV.UK and Design System

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1927]
The footer currently in use on GOV.UK has a 10px `#1d70b8` border along the top edge:

![www gov uk_ (2)](https://user-images.githubusercontent.com/121939/90892874-f65b8480-e3b5-11ea-949f-b9f6c9b736f5.png)

The footer component in the Design System has a 1px `#b1b4b6` border along the top edge.

![design-system service gov uk_components_footer_default_index html (1)](https://user-images.githubusercontent.com/121939/90892885-fb203880-e3b5-11ea-9781-e517c97a068b.png)

**Comment by CharlotteDowns** [comment]
The GOV.UK team have used the blue border to integrate the blue 'is anything wrong with this page?' questionnaire. They also use it to add more differentiation from one section of the page to the next, this is especially true on service pages. 

The added complexity of the footer working across all of the services on GOV.UK, especially those with unique styling, has lead the team to use extra elements to aid with footer distinction.
