### ISSUE TITLE
Unclear if phase banner `tag` is required

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#1930]
The phase banner [params](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/phase-banner/phase-banner.yaml#L12) state that the `tag` is not required. However, if you leave out the `tag` param, you get an empty tag:

<img width="1016" alt="Screenshot 2020-08-26 at 16 54 42" src="https://user-images.githubusercontent.com/29889908/91326962-dadce900-e7bc-11ea-85b2-1aefaf8d3f1a.png">

Possible options:

- Make it required, and it renders an empty tag if you don’t pass one (similar to screenshot above)
- Only output a tag if tag.text or tag.html are passed, and leave it ‘optional’
- Only output a tag if tag.text or tag.html are passed, and say it’s required

**Comment by terrysimpson99** [comment]
See also discussion at: https://github.com/alphagov/govuk-design-system-backlog/issues/57

**Comment by MalcolmVonMoJ** [comment]
We have kept the phase banner, but without a tag.  

![image](https://user-images.githubusercontent.com/32877315/94676557-71984a80-0313-11eb-8c4c-72091ffd5b84.png)

We do, however, keep the tag for internal development, testing and staging environments.  

![image](https://user-images.githubusercontent.com/32877315/94676670-9987ae00-0313-11eb-89cf-b843d6d7207f.png)

**Comment by nabeelamir-defra** [comment]
Hi would it be possible to "Only output a tag if tag.text or tag.html are passed, and leave it ‘optional’". Similar to the above screenshot we would like to keep the phase banner, but without the tag. At the moment we're using pure html to achieve this, but would like to use the component.

**Comment by hannalaakso** [comment]
@nabeelamir-defra Thanks for your message. Making the phase banner component officially support your use case would be changing the purpose of the component. As the component relates to service assessments, status of projects etc., doing so would need to be a conversation involving many people from across government.

There is a a separate component for [feedback link for asking users for feedback about a service,](https://github.com/alphagov/govuk-design-system-backlog/issues/117) it might be worth reading through the comments on that issue and leaving a comment on the thread explaining your use case and how the feedback link component should meet them. Any user research you might have done in this area would be particularly valuable.

**Comment by querkmachine** [comment]
As has been noted, the Phase Banner is used to convey details of the development and assessment phase of a service. We would expect it to include a Tag as part of this use, and do not intend for it to be used as a generic site-wide messaging component. 

To that end I've updated the documentation to mark the tag parameter as being required.
