### ISSUE TITLE
Legacy FE toolkit script for `<details>` conflicts with GOV.UK Frontend details script

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#1969]
## What
Our details component JavaScript conflicts with the legacy FE toolkit JavaScript because the legacy script targets any `<details>` elements on the page instead of name spaced components. This means that our details component is styled correctly but doesn't open in IE11 if page also instantiates the toolkit details JavaScript. 

We do this [in the review app](https://github.com/alphagov/govuk-frontend/blob/master/app/views/partials/legacyJavaScript.njk#L19) for testing purposes. 

## Why
We could fix this but the chances of this being a problem for service teams seem very low as it would most likely be in the midst of a service migrating to GOV.UK Frontend and having both the GOV.UK Frontend details and the legacy details instantiated on the same page.

## Who needs to know about this
Developers only?

**Comment by 36degrees** [comment]
Closing as [we're removing compatibility mode](https://github.com/alphagov/govuk-frontend/issues/2769) and we don't currently plan to fix this as we've seen no evidence of it affecting users.
