### ISSUE TITLE
Style disabled form fields with `cursor: not-allowed`

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#1978]
I wonder if styling the disabled button with `cursor: not-allowed` would provide more affordance to the user?

_Originally posted by @jesseyuen in https://github.com/alphagov/govuk-design-system-backlog/issues/34#issuecomment-528365796_

**Comment by 36degrees** [comment]
Would it make sense to add this as a comment on https://github.com/alphagov/govuk-frontend/issues/1713 instead of making it a separate issue?

**Comment by timpaul** [comment]
Closing as this suggestion is now integrated into  #1713
