### ISSUE TITLE
Details Tag works in Chrome and Not in IE 11

### ISSUE THREAD

**Issue by hari-gillala** [alphagov/govuk-frontend#1980]
Problem with 'GOV.UK Frontend' (https://frontend.design-system.service.gov.uk/)

I am using the following code, to get the details control.

I have tried with the  1) Nunjucks and 2)HTML.

1) Nunjucks
![UsingNunjucks](https://user-images.githubusercontent.com/55185692/93827380-0d192380-fc61-11ea-83f6-34e66fef16b4.JPG)

2) HTML
![UsingHtmlJPG](https://user-images.githubusercontent.com/55185692/93827200-b27fc780-fc60-11ea-8898-47b1a6cf1dff.JPG)

**Problem**
---------
It renders okay in 
1)  Chrome  
2) Firefox 
 but in IE 11, I get the following issue. 

![IE11Error](https://user-images.githubusercontent.com/55185692/93827543-5f5a4480-fc61-11ea-97d4-15c718e9c666.JPG)

 

In Chrome
![Chrome](https://user-images.githubusercontent.com/55185692/93827663-9a5c7800-fc61-11ea-9052-b5ce8cf60af3.JPG)

why it works in chrome and not in IE 11

**Comment by hannalaakso** [comment]
Thanks for raising this issue @hari-gillala. We haven't been able to replicate it in IE11 so I'm going to close this issue. However if you have a version we could take a look at please let us know and we can investigate. If you prefer, you can [contact us](https://design-system.service.gov.uk/#support) via Slack or email.
