### ISSUE TITLE
Create release notes for v3.10.0

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#1986]
## What

Write the release notes for GOV.UK Frontend v3.10.0

## Why

To help users understand what changes have been made in the 3.10.0 release.

## Who needs to be involved 

@EoinShaughnessy and whoever is doing the release

## Done when…

This will be done when the release notes:

- [x] have been drafted
- [ ] have been reviewed by a developer
- [ ] have been 2i'ed

**Comment by EoinShaughnessy** [comment]
Release notes drafted: https://github.com/alphagov/govuk-frontend/pull/2019
