### ISSUE TITLE
Decide and document how we release fixes for earlier major versions

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2004]
## What
Split from https://github.com/alphagov/govuk-frontend/issues/1958.

We currently haven't decided or documented how we would issue a patch fix for an earlier major version. 

This is both a product issue (how far back in time does our backwards compatibility go?) and a technical one.

An example scenario would be if we discovered a serious bug in GOV.UK Frontend 3.x.x after we release v4.0.

## Why
It would be good contingency to decide (and document if appropriate) how we should handle a scenario like the one above.

## Further detail
We think we have [documented how we think we would handle this from a technical point of view ](https://docs.google.com/document/d/1avJPHEJ4hENt5LEcMwxp90zl1WS72Tx6qdoN2JOhXCE/edit#heading=h.sxm5dic2qz4c) but a question around handling the `latest` npm tag remains (see below),

## Done when
- [x] We've discussed with the product owner how we want to solve this problem- the browser support work has forced our hand on this a bit as we'll need to maintain v4 and v5+
- [x] If necessary, we've investigated and decided how we avoid moving the `latest` tag on npm 
- [x] If necessary, we've created docs for the process of releasing a fix for an earlier major version

**Comment by lfdebrux** [comment]
> I think the biggest question we've thought of is how we avoid moving the latest tag on npm (e.g: we don't want v4.2.0 to show up as the latest release if v5 is already out)

This is fairly straightforward to do, `npm publish` accepts a `--tag` argument [[1](https://docs.npmjs.com/cli/v8/commands/npm-publish#tag)] that lets you specify a tag other than `latest`.

There does need to be a tag [[2](https://stackoverflow.com/questions/68230173/publishing-a-previous-major-version-to-npm-with-no-tag-and-avoiding-latest)], and there isn't any documented convention on what the tag should be if not latest [[3](https://docs.npmjs.com/cli/v8/commands/npm-dist-tag)], but npm themselves use the pattern `latest-<major version>` [[4](https://www.npmjs.com/package/npm?activeTab=versions)], which makes sense to me.

We'd need to modify the [publish-release script](github.com/alphagov/govuk-frontend/tree/main/bin/publish-release.sh) to allow overriding the tag, but we might be able to add logic to generate the tag for the dev, from the major version.
