### ISSUE TITLE
Test notification banner with assistive technologies

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2010]
## What
When we took the notification banner to the accessibility clinic, we focused on specific questions that we wanted answers to. Now that we have access to AssistivLabs, we can use that to test the notification banner with assistive technologies more generally and check there aren't any issues we weren't aware of.

## Why
To test against different assistive technologies; to understand where the notification banner may need any improvements

## Done when

Tested with the following and added any issues to https://github.com/alphagov/govuk-frontend/issues/2011:
- [x] JAWS 2020 / Chrome
- [x] JAWS 2020 / IE11
- [x] NVDA 2020.3 / Firefox 81
- [x] NVDA 2020.3 / Chrome 86
- [x] Voiceover / Safari (macOS Catalina)
- [x] Voiceover / Safari (iOS 14)
- [x] Talkback / Chrome 86 (Android 10)
- [x] Windows Magnifier or Apple Zoom (screen magnifiers) \| Latest \| Any

**Comment by hannalaakso** [comment]
Currently looking at https://github.com/alphagov/govuk-frontend/issues/2011 but I've created a sheet to start testing things with the behaviours I _think_ we want to test: https://docs.google.com/spreadsheets/d/1_0giLl5oRJ-Ocljv20ES6zA9vmMgIXIbdu05LbVMka8/edit#gid=0

**Comment by hannalaakso** [comment]
I've been testing this by running the [prototype from the accessibility clinic](https://github.com/alphagov/gaap-assistive-tech-research-prototype/tree/notification-banner-testing) locally and pointing it at a pre-release of https://github.com/alphagov/govuk-frontend/pull/2014 (`npm install --save alphagov/govuk-frontend#d636d1d8`).

**Comment by hannalaakso** [comment]
Some subsequent testing that was done after investigating https://github.com/alphagov/govuk-frontend/issues/1954 and deciding to add `aria-labelledby` to the notification banner role=alert variant for now: https://docs.google.com/spreadsheets/d/1KrgPdKf8M6zsNZcRPUG0r7H1-1aREW5QgnjhhfVHIag/edit#gid=0
