### ISSUE TITLE
Change title to titleText in notification banner Nunjucks API

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2015]
## What

Update the Nunjucks template for the notification banner to accept a `titleText` rather than `title` to match the use of `titleHtml`

## Why

To be consistent with the options we use elsewhere, where we use `text` / `html` suffixes together.

## Who needs to know about this

Developers, tech writer

## Done when…

- [x] Template is updated to use `titleText`
- [x] Examples and tests are updated to pass and reference `titleText`
- [x] Macro options documentation is updated to use `titleText`

**Comment by EoinShaughnessy** [comment]
Hi, @36degrees . Ok if I update the macro doc that I'm currently working on? See: https://docs.google.com/document/d/1umg8m9EwsII0NFq7vk3xVu8vcOQhWLRm2IGxDp3Y1Qw/edit?usp=sharing
