### ISSUE TITLE
Create release notes for v3.10.1

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-frontend#2046]
## What
Write the release notes for GOV.UK Frontend v3.10.1

## Why
To tell users what fixes we've added to the Notification banner component

## Who needs to know about this
@36degrees and whoever else might be doing the release

## Done when
- [x] Release notes have received 2i approval
- [ ] A developer approves the addition in GitHub

**Comment by EoinShaughnessy** [comment]
I've sent the notes for tech writer review.

**Comment by EoinShaughnessy** [comment]
The notes have received 2i approval. I've now raised a PR.

**Comment by EoinShaughnessy** [comment]
@36degrees Should I move this card to Done? Or delete it since we've closed https://github.com/alphagov/govuk-frontend/pull/2047?

**Comment by 36degrees** [comment]
@EoinShaughnessy close it and move it to done – thanks for getting them through 2i so promptly 🙂

**Comment by EoinShaughnessy** [comment]
Have reopened this as we're getting 2i on the addition of https://github.com/alphagov/govuk-frontend/pull/2031.

**Comment by 36degrees** [comment]
We're now leaving #2031 out of this release as we need to update some additional documentation, so moving this back to done!
