### ISSUE TITLE
Improve docs for setting up a preview of GOV.UK Frontend branch

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2057]
## What
We have some guidance about [publishing a pre-release of GOV.UK Frontend](https://github.com/alphagov/govuk-frontend/blob/master/docs/releasing/publishing-a-pre-release.md) which essentially allows you to preview your GOV.UK Frontend branch in the Design System. 

It would be good to do a tech writer review of the above docs.

We have a subsequent card https://github.com/alphagov/govuk-design-system/issues/1425 to link to these docs from the Design System community section.

## Why
We should improve these docs to help contributors set up previews of their work in the Design System and saving our team time spent on supporting contributors.  

## Who needs to know about this
Eoin

## Done when
- [x] A tech writer has reviewed [Publishing pre-release of GOV.UK Frontend](https://github.com/alphagov/govuk-frontend/blob/master/docs/releasing/publishing-a-pre-release.md) guidance

**Comment by hannalaakso** [comment]
@EoinShaughnessy I've split linking to the doc to a separate card https://github.com/alphagov/govuk-design-system/issues/1425.

**Comment by EoinShaughnessy** [comment]
I've edited the doc to reflect the change of scope — towards users who have already made branch changes before they go to publish a pre-release. See https://github.com/alphagov/govuk-frontend/pull/2056.
