### ISSUE TITLE
Spurious release tag v9.8.0

### ISSUE THREAD

**Issue by gunjam** [alphagov/govuk-frontend#2062]
Currently I'm including this whole repo as a dependency in my project so I can access the unbundled js to build my own components and produce a bundle that only includes the GOV.UK components I actually use (hopefully in the future I can access the ES modules from the govuk-frontend repo directly, see https://github.com/alphagov/govuk-frontend/issues/711).

Unfortunately govuk-frontend has a release tag of v9.8.0 (which I'm assuming came over from the prototype-kit in error) which means my build pipeline keeps complaining I haven't updated from 3.10.1 to 9.8.0 and there's no way I can resolve this other than ask you to delete it 🙏. Could you get rid of it somehow?

Thanks.

**Comment by 36degrees** [comment]
Thanks for flagging @gunjam – very odd. I've deleted the v9.8.0 tag.

I'd be curious to see how you're using the unbundled JS – is your project public on GitHub or somewhere I could take a look?

**Comment by gunjam** [comment]
You can check our [all.js](https://github.com/dwp/pension-credit-apply-citizen-ui/blob/master/assets/all.js) in our public repo, it's a bit out of date but were due a release soon.
