### ISSUE TITLE
Provide an option to disable font smoothing

### ISSUE THREAD

**Issue by adityapahuja** [alphagov/govuk-frontend#2087]
## Related component

GOV.UK Typography (font smoothing)

## Context

Currently, GOV.UK Typography is using the following settings taken from `govuk-frontend/src/govuk/helpers/_typography.scss`.

```
@mixin govuk-typography-common($font-family: $govuk-font-family) {
  font-family: $font-family;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  ...
}
```
It makes the text appear blurry on external monitors (1920x1200 or less). Updating these settings to disable font smooth makes the text appear sharp and clear on the external monitors. It would be good to have an option to allow us to disable font smoothing on a website. Please see the screenshot below. On the left hand side, the website has font smoothing enabled. On the right hand side, the website has font smoothing disabled.

<a href="https://drive.google.com/uc?id=10PfOEfTGoUpIS4rrU4M32ct17dCpwc24"><img src="https://drive.google.com/uc?id=10PfOEfTGoUpIS4rrU4M32ct17dCpwc24" style="width: 500px; max-width: 100%; height: auto" title="Click for the larger version." /></a>

## Alternatives

There are no workarounds. Disabling anti-aliasing or font smoothing option in a browser does not affect a website using GOV.UK typography.

## Additional information (if applicable)

A user doesn't like reading blurry text and copies the text from the website into a word processor to read instead of the website.

**Comment by timpaul** [comment]
Hi @adityapahuja - thanks for the feedback. 

We discussed this as a team and agreed that we wouldn't want to make this a configurable option for service teams, as it's unlikely to impact one service more or less than another.

As we've not had users complain about font smoothing before, we'll leave this for now, unless we get similar feedback in the future.

Thanks again
