### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by abbott567** [alphagov/govuk-frontend#2090]
## Related component
It affects core colours, so will affect most components in some way but perhaps indirectly.

## Context
A lot of operating systems now support 'Dark Mode'. Modern browsers can support CSS for `prefers-color-scheme` but GOV.UK does not provide it as an enhancement. When browsing GOV.UK content in dark mode, the background is still pure white which can be quite harsh on the eyes in low light environments. 

## Alternatives
N/A

## Additional information (if applicable)
Not really requesting the feature be implemented at this stage, just wanting to open up the discussion and to see if it's something we perhaps need to consider.

**Comment by 36degrees** [comment]
Hey @abbott567,

Thanks for raising this. There's already a [backlog issue for dark mode](https://github.com/alphagov/govuk-design-system-backlog/issues/177) with some discussion already happening – are you happy to continue this discussion there instead?

**Comment by abbott567** [comment]
Hi, @36degrees , of course. As usual I just couldn't find anything already open! 
Checked Design System and Frontend, but not the Backlog! 

I'll add that to my places to check in future!

**Comment by abbott567** [comment]
Closing in favour of [https://github.com/alphagov/govuk-design-system-backlog/issues/177](https://github.com/alphagov/govuk-design-system-backlog/issues/177)
