### ISSUE TITLE
Summary list links are hard to localise

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#2094]
## Related component
Summary panel

## Context
Trying to localise the 'Change' links into another language.

## Additional information (if applicable)
https://github.com/alphagov/govuk-design-system-backlog/issues/36#issuecomment-694167301

**Comment by 36degrees** [comment]
I'm going to close this as from reading the linked backlog comment, I think it's the same thing as #2649 which covers this in more detail.
