### ISSUE TITLE
Add styling for cookie banner

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2098]
## What
Style the notification banner as agreed. 

## Who needs to know about this
Developers, designers

## Depends on
- [Add Nunjucks macro template, tests and examples for cookie banner](https://github.com/alphagov/govuk-frontend/issues/2099)

## Done when

- [x] Styles added
- [x] Styles have been reviewed by a designer

**Comment by vanitabarrett** [comment]
Note: We may want to add a border-bottom to make it easier for users using high contrast mode to be able to identify where the banner ends.
