### ISSUE TITLE
Decide markup for the cookie banner component

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2100]
## What
Once we've made a decision on [whether the cookie banner question and confirmation are one component](https://github.com/alphagov/govuk-frontend/issues/2095), we should decide how we want to structure the markup.

This is **roughly** how the GOV.UK markup is constructed. Do we want to follow a similar approach?

```
<wrapper div role=region aria-label="">
	<govuk-width-container>
  		<govuk-grid-row>
			<govuk-grid-column-two-thirds>
            	<div cookie-banner__message>
					<h2 heading>
					<p body text>
				<div cookie-banner__buttons>
					<button accept>
					<button settings>
close all divs etc.
	<govuk-width-container>	
		<p confirmation-message	
			<a link to cookie-page>
		<button to hide confirmation>
close all divs etc.
```    
## Why
There are a few different things we could do here. Making a decision about these upfront will simplify the development process.

## Depends on
- [Decide if the cookie banner question and confirmation are one component](https://github.com/alphagov/govuk-frontend/issues/2095)

## Who needs to know about this
Developers

## Done when

- [ ] We've made a decision
- [ ] We've added a rough outline of the markup to this card (which we can then use to create the macro)

**Comment by vanitabarrett** [comment]
I think I'm partly doing this as part of https://github.com/alphagov/govuk-frontend/issues/2099
