### ISSUE TITLE
Design Nunjucks API for cookie banner component

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2101]
## What

Work out what the API for the cookie banner and 'You’ve accepted all cookies'  banner should look like.

Where possible, it should be consistent with the APIs for our existing components.

There are a few things we need to consider:

- If we decided in https://github.com/alphagov/govuk-frontend/issues/2095 that the cookie banner question and confirmation are one component, do we want a single option to set the 'type' of cookie banner? What would that 'type' do in the macro? Would users be able to override any settings?
- Are we making any roles/attributes decided in https://github.com/alphagov/govuk-frontend/issues/2102 flexible, so that the user can override them?

## Depends on

- [Decide if the cookie banner question and confirmation are one component](https://github.com/alphagov/govuk-frontend/issues/2095)
- [Decide roles and aria attributes for the cookie banner](https://github.com/alphagov/govuk-frontend/issues/2102)

## Why

By designing and agreeing the API for the component upfront we can ensure that it behaves consistently with our other components.

## Who needs to know about this
Developers

## Done when

- [x] We've made a decision on the above
- [x] We've added a draft API specification to this card (which we can then use to create the macro)

**Comment by vanitabarrett** [comment]
No decision made yet, but the current thinking is to have the banners (question and confirmation) as the same component and have the API look something like this:

```
govukCookieBanner({
    banners: [
        {
            heading: "Cookies on GOV.UK",
            text: "We use cookies on GOV.UK",
            actions: [
                {
                    text: "Accept cookies",
                    name: "cookies",
                    value: "accept"
                },
                {
                    text: "Reject cookies",
                    name: "cookies",
                    value: "reject",
                }
            ]
        },
        {
            text: "You have accepted cookies"
            actions: [
                {
                    text: "Hide banner"
                }
            ]
        }
    ]
})
```

**Comment by vanitabarrett** [comment]
Note that we'll need an ariaLabel option to override the default one

**Comment by vanitabarrett** [comment]
We may need the ability to turn off `role=alert` on confirmation banners

**Comment by vanitabarrett** [comment]
Draft doc: https://docs.google.com/document/d/1LNsNsIxwTw9zda89SyV1SKpe3lTVUpiT6p6SYp0LBZ0/edit#

**Comment by vanitabarrett** [comment]
Doc has been drafted and shared with @EoinShaughnessy. Going to close this card now as the tech writer/2i side is covered by https://github.com/alphagov/govuk-frontend/issues/2103
