### ISSUE TITLE
Write cookie banner Nunjucks macro options documentation

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#2103]
## What
Our docs need explain what options the cookie banner macro requires and how the macro can be configured.

Once we've added some of these draft macro options in https://github.com/alphagov/design-system-team-internal/issues/405, we should have them reviewed by a tech writer and 2i'ed.

## Who needs to know about this
Eoin, developers

## Depends on
- [Design Nunjucks API for cookie banner component](https://github.com/alphagov/design-system-team-internal/issues/403)
- [Add Nunjucks macro template, tests and examples for cookie banner](https://github.com/alphagov/design-system-team-internal/issues/405)

## Done when
- [x] Developer to draft doc
- [x] Review by Technical Writer
- [x] Content 2id if necessary
- [x] PR raised with new docs content

**Comment by EoinShaughnessy** [comment]
@kellylee-gds The team is happy with the current draft, so I've sent the content for 2i.

**Comment by EoinShaughnessy** [comment]
Current draft (now out for review): https://docs.google.com/document/d/1LNsNsIxwTw9zda89SyV1SKpe3lTVUpiT6p6SYp0LBZ0/edit#

**Comment by EoinShaughnessy** [comment]
Content has cleared pre-i. I've now sent it for 2i.

**Comment by EoinShaughnessy** [comment]
This content has passed 2i.

**Comment by vanitabarrett** [comment]
Content has passed 2i and latest version is in the feature branch.

Ongoing discussion around renaming the macro option `banners` to `messages` and what affect that might have on the documentation. Have shared a draft of what it might look like for opinions https://github.com/alphagov/govuk-frontend/pull/2129/files
