### ISSUE TITLE
Create a feature branch for draft cookie banner component

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#2104]
## What
Create a feature branch in govuk-frontend for the cookies work.

## Why
There are lots of moving parts to the cookie work. It would be too big for one PR and having a feature branch means some of us will be able to work on some things in parallel.

## Who needs to know about this
Developers

## Done when

- [x] Feature branch created in Github
- [x] Feature branch is protected so you cannot commit directly to it
- [x] Let other developers in the team know

**Comment by vanitabarrett** [comment]
I've added a feature/cookie-banner branch to govuk-frontend and added branch protection rules to feature/* (will apply to the cookie banner branch and hopefully any other feature branches we might make in the future)

https://github.com/alphagov/govuk-frontend/tree/feature/cookie-banner
