### ISSUE TITLE
Draft Slack comms for release of cookie banner component and cookies page

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#2108]
## What
Draft comms that we will release on Slack.

## Why
- So users know what new features have been released.

## Who needs to know about this
Content Design and Design to draft comms, review by team on Slack

## Done when
- [x] Look at previous examples
- [x] Speak to SME about legal information that should included
- [x] Include acknowledgment of any contributors
- [x] Message drafted
- [x] 2i'd by team
- [x] Posted when we've done the release

**Comment by kellylee-gds** [comment]
Moved to blocked as announcement is ready for when we publish

**Comment by calvin-lau-gds** [comment]
Copy reviewed by team is here:
[https://docs.google.com/document/d/1jVyMB7i94NOeflWaf3kE4Q4APMXGfluK3rOh74IHO08/edit?usp=sharing](https://docs.google.com/document/d/1jVyMB7i94NOeflWaf3kE4Q4APMXGfluK3rOh74IHO08/edit?usp=sharing)

**Comment by calvin-lau-gds** [comment]
Good to go - may just need a final check for any contributor acknowledgements needed.
