### ISSUE TITLE
Agree the no-JS behaviour of the cookie banner and cookies page

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2111]
## What
Agree how the cookie banner will work with Javascript disabled.
Agree how the cookies page will work with Javascript disabled.

Need to think about:

- Services that set cookies using Javascript and nothing else
- Services that set cookies server-side only
- Services that set some cookies server-side and some using Javascript
- Services that only set essential cookies when Javascript is disabled

## Why
The cookie banner component is likely to be quite basic compared to our other components where we would normally handle this kind of behaviour for users. However, we still need to think about how the banner and cookies page should behave, whether there is anything we need to implement to help service teams (e.g: something they can hook into), and write some guidance.

## Who needs to know about this
Developers
Designers
Technical Writer
Content Designer

## Done when

- [ ] Considered the scenarios above and documented how we think the banner would work in each case
- [ ] Considered the scenarios above and documented how we think the cookies page would work in each case
- [ ] Created new cards for any new work we need to do as a result, e.g: tweaks to the component, extra guidance

**Comment by hannalaakso** [comment]
https://docs.google.com/document/d/1A74edb0jKKLND3BI4covxn35AMTDbbuJxjsEy6Y-jK0/edit#heading=h.fkstm3tmbdfk

**Comment by hannalaakso** [comment]
Guidance now added to https://docs.google.com/document/d/1QAA_9GVd5Uxbx9kOXPpYLf6U6yVGb5fnCbLNA60fSII/edit
