### ISSUE TITLE
Make changes to the page template to handle the new cookie banner

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2113]
## What
Make any necessary changes to the page template to support the cookie banner

## Why
In https://github.com/alphagov/govuk-frontend/issues/2096, we will have agreed where the cookie banner will sit in the page template. We may need to do some work to rename or add a new block to the template. 

## Depends On
https://github.com/alphagov/govuk-frontend/issues/2096

## Who needs to know about this
Developers

## Done when

- [ ] Implement changes to page template

**Comment by 36degrees** [comment]
@hannalaakso as we're using `bodyStart` for the cookie banner, I don't _think_ there's anything to do for this now? Should we close it?

**Comment by hannalaakso** [comment]
@36degrees Good question. I don't think we can test anything.
