### ISSUE TITLE
Create release notes for v3.11.0

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-frontend#2116]
## What
Write the release notes for GOV.UK Frontend v3.11.0

## Why
To help users understand what changes have been made in the 3.11.0 release.

## Who needs to be involved 
Tech Writer and whoever is doing the release.

## Done when
- [x] release notes have been drafted
- [ ] release notes have been reviewed by a developer
- [ ] have been 2i'ed by Tech Writer community

**Comment by EoinShaughnessy** [comment]
I've drafted some [release notes in a Google Doc](https://docs.google.com/document/d/1HtHLI_dBnSjVtUW_2nClZNzSkiw525Yom2Cq3ERlsmM/edit#).

They need a couple of links:
- guidance page for cookie banner
- GitHub issue re creating cookie banner (if there is an issue for this, like there was for notification banner)

**Comment by EoinShaughnessy** [comment]
Content has passed 2i. I'll raise a PR now.
