### ISSUE TITLE
Write accessibility findings for the cookie banner backlog issue

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2146]
## What

We tested the cookie banner, including accepting/rejecting/hiding the banner, on assistive technologies. We found some vendor bugs and put in place some workarounds for unexpected behaviour.

We should document these findings in the [backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/12). 

## Why

To inform teams how the cookie banner was tested and what the findings were. Also to remind ourselves down the line of what we found. 

## Who needs to know about this
Developers

## Further detail

We should probably talk at least about
- the bugs we found
- the decision we took around using `hidden` vs. `display=none;`
- the focusing behaviour, including [not giving the banner a visible focus outline](https://github.com/alphagov/govuk-frontend/issues/2128)
- [the feedback from the accessibility clinic](https://github.com/alphagov/govuk-frontend/issues/2106#issuecomment-773932405)

## Done when

- [x] We've drafted the backlog entry and the developers in the team have reviewed it
- [x] We've published it on the [backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/12) 
- [x] We've agreed whether we should link to the backlog entry from the Design System guidance, and raised another card if appropriate
- [ ] We've raised card for the bugs, including vendor bugs, discovered during the investigation

**Comment by hannalaakso** [comment]
I've started writing some of this up in here: https://docs.google.com/document/d/1WZ0Rd7GPwEj5GNfxifIVoQc37lKTIW7ddfCcDjRQx1g/edit#

**Comment by hannalaakso** [comment]
Findings from the accessibility clinic: https://github.com/alphagov/govuk-frontend/issues/2106#issuecomment-773932405

**Comment by 36degrees** [comment]
Closed by https://github.com/alphagov/govuk-design-system-backlog/issues/12#issuecomment-785798231
