### ISSUE TITLE
summary-list component contains axe accessibility issue

### ISSUE THREAD

**Issue by alittlecross** [alphagov/govuk-frontend#2150]
## Description of the issue

Using the summary-list component with multiple rows where some do not have actions; the component adds a span to those rows. This is considered a serious issue by the Axe accessibility tool, presenting the below error when using the axe-core chrome extension:

`<dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements`

The section of the template relating to this is [here](https://github.com/alphagov/govuk-frontend/blob/8748418071b7e753a2085b409d10e1c2fb40990e/src/govuk/components/summary-list/template.njk#L42).

The issue may be resolvable by using a div instead so long as the govuk-summary-list__actions class results in the elements rendering the same.

## Steps to reproduce the issue

Use the summary-list component with multiple rows where some do not have actions. Using the axe-core chrome extension on the page that contains that component:

<img width="2032" alt="Screenshot 2021-02-16 at 10 49 57" src="https://user-images.githubusercontent.com/15965227/108053079-dc3cef00-7044-11eb-8c52-d0b61247a0b1.png">

## Actual vs expected behaviour

No accessibility issue.

## Environment (where applicable)

I am using the below however the component remains the same in the current version of the toolkit and colleagues have witnessed the same behaviour on macOS Mojave, with other versions of Chrome.

- Operating system: macOS Catalina
- Browser: Chrome
- Browser version: 88.0.4324.150
- GOV.UK Frontend Version: 3.10.1

**Comment by 36degrees** [comment]
Hi @alittlecross – thanks for flagging this.

I _think_ this is the same as issue https://github.com/alphagov/govuk-frontend/issues/1806 – would you mind checking?

**Comment by alittlecross** [comment]
Yep - Malcolm is in fact on my team, but raised that before I joined - then I didn't thoroughly search the issues to check it hadn't been raised before - apologies.

**Comment by 36degrees** [comment]
No worries – thanks again for flagging it!
