### ISSUE TITLE
Improve polyfilling doc

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-frontend#2159]
## What
Revise [polyfilling doc](https://github.com/alphagov/govuk-frontend/blob/master/docs/contributing/polyfilling.md) to:
- explain how it can help users
- make it style guide-compliant

## Why
This doc is for contributors.
Our tech docs workshop produced [lots of good feedback about how we could enhance it](https://jamboard.google.com/d/1EtFuseIw27TnchGy8VaYEwkcxpF_ixMZVYtpqjoUvIQ/viewer?f=0).
If its contents are still helpful, then it seems worthwhile to improve the doc.

## Who needs to know about this
Delivery Manager, Developers, Senior Product Manager, Technical Writer

## Done when
- [ ] We confirm a user need exists?
- [ ] Technical Writer revises doc
- [ ] Developers review doc
- [ ] Doc gets 2i'd
- [ ] Doc published

**Comment by EoinShaughnessy** [comment]
@hannalaakso Should this issue go into the current sprint or the backlog?

**Comment by 36degrees** [comment]
Superseded by #3722
