### ISSUE TITLE
Update node dependency version in package.json

### ISSUE THREAD

**Issue by gunjam** [alphagov/govuk-frontend#2162]
The current LTS version of Node.js is 14, although this repo's package.json is pinned to version 12.13.1. 12 is still in active support but this restrictive versioning is causing an issue for my project (more info in issue [711](https://github.com/alphagov/govuk-frontend/issues/711#issuecomment-791419464)).

**Comment by lhokktyn** [comment]
I'd second this request to loosen this versioning restriction, if at all possible. [Contribution guidance](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/running-locally.md) suggests the project aims to track the latest active LTS too.

On manually updating the `.nvmrc` to v15, the module appears to compile and run ok, but that's a very dirty, high-level check. Are there any issues that document the reasons we cannot go beyond v12 at the moment?

**Comment by 36degrees** [comment]
@lhokktyn how are you currently consuming GOV.UK Frontend?

The [published package](https://www.npmjs.com/package/govuk-frontend) does not have any upper restrictions on node version – it's only the private top level package (which includes the dependencies for our tooling etc) in the repository that has those restrictions.

**Comment by lhokktyn** [comment]
> @lhokktyn how are you currently consuming GOV.UK Frontend?

We're pulling straight from the git source as described by @gunjam above (we're colleagues) in order to optimise the asset bundle served up to the browser.

This issue has become more prominent in our workflow since we've adopted some of the newer syntax available in the active LTS (14) elsewhere in our project. We work around it with clunky usage of `nvm`, but it'd be great if the govuk-frontend source could track the active LTS as it's baseline.

As I say, it _appears_ to compile ok up to v15 on the face of it so perhaps the `.nvmrc` has remained unchanged (last updated Nov 2019) because it's not breaking build pipelines?

**Comment by georgeherby** [comment]
I am also referencing this repo from the source so facing the same issues mentioned here where I am running version 14.17.0 and the version check stops `npm install` from completing

**Comment by jenbutongit** [comment]
Direct installation via GH aside, there are two groups that would benefit from v14 (although, it’s more of a venn intersection)

* You (GDS/maintainers) v14 will get security updates and fixes.
  * I would suggest that you also specify ^14 to force consumers to use node 14 in their own projects
* You / maintainers + consumers of the package(s) - will be able to leverage new ECMAScript features now available in v14 - without the need for a transpiler like babel.
  * you would still need a transpiler for anythign that needs to target the browser, but for any of your build tools or scripts that aren’t included in the package can be non-babel’d

Do *not* upgrade to anything above v14. If you're not aware, odd numbered major releases of node are short lived (6 months), and are more of a precursor to the next version. v16 is in active development - not ready for production environments. It's only available for people who want to play with new toys
