### ISSUE TITLE
Add info about links styled as buttons to cookie macros 

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-frontend#2166]
## What

Update [cookie banner](https://design-system.service.gov.uk/components/cookie-banner/) macro options to explain how users can render a link styled as a button.

## Why

This option could help users if:
- their cookie banner needs to work without JavaScript
- they have already accepted or rejected cookies - so, when they press **Hide** and the page reloads, the banner is hidden

PR with technical details about this change: [Enable cookie banner to set link styled as a button](https://github.com/alphagov/govuk-frontend/pull/2164)

## Who needs to know about this

Delivery Manager, Developers, Technical Writer

## Done when

- [x] Developer drafts update
- [x] Technical Writer reviews update and actions any further changes
- [x] Technical Writer gets update 2i'd
- [ ] Update published

**Comment by EoinShaughnessy** [comment]
Google Doc with content changes: https://docs.google.com/document/d/1BhH2VGCUkbltc5k9hAjSPBCxG7emdX12xxeNinJwOiU/edit

**Comment by vanitabarrett** [comment]
Do we also need to update the description for the following option?

https://github.com/alphagov/govuk-frontend/blob/59c11ee8267930c34a85cbbf7cfd621a57360ed3/src/govuk/components/cookie-banner/cookie-banner.yaml#L55

**Comment by EoinShaughnessy** [comment]
> govuk-frontend/src/govuk/components/cookie-banner/cookie-banner.yaml

**Comment by EoinShaughnessy** [comment]
> Do we also need to update the description for the following option?
> 
> https://github.com/alphagov/govuk-frontend/blob/59c11ee8267930c34a85cbbf7cfd621a57360ed3/src/govuk/components/cookie-banner/cookie-banner.yaml#L55

Great shout! As a replacement for what's currently there, could something like the below work?

>  The `href` for a link. Set `button` and `href` to render a link styled as a button.

Would we need to say anything about `href` overriding `submit`?

**Comment by vanitabarrett** [comment]
@EoinShaughnessy That sounds good to me. I'm not sure if we'd need to mention submit - it feels like it might be covered in the `type` description?

**Comment by EoinShaughnessy** [comment]
@vanitabarrett Ah yes, of course. Cool, I'll raise a PR with these changes. Once I get dev sign-off, I'll send the content changes for 2i.
