### ISSUE TITLE
Option to hide rows if they are empty.

### ISSUE THREAD

**Issue by stuaxo** [alphagov/govuk-frontend#2169]
It would be nice if I could specify and option, per row, to hide that row if the data passed in is not available.

## Alternatives
I haven't written the workaround yet, but will do.

## Additional information (if applicable)
For an app @ DIT, we there is data where *almost* every instance of a field should be empty, so don't wish to show it by default.

**Comment by 36degrees** [comment]
Hi @stuaxo,

Thanks for raising this. Can I just check, does your request relate to a specific component? It sounds like this might relate to either tables or the summary list, but it's not clear.

**Comment by vanitabarrett** [comment]
Hi @stuaxo,

We've not heard from you in a while. Please can you confirm what component this feature request relates to, to help us understand the problems you're coming across?

**Comment by stuaxo** [comment]
The fact I can't make much sense of my own bug report isn't a great sign, I'll go back to the app we are developing and see if I can work out what I meant :)

**Comment by stuaxo** [comment]
Here's a bit of example code - I'm not super familiar with govuk frontend, so I guess the component is something like the summary-list ?

```html
<div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Certificate ID
        </dt>
        <dd class="govuk-summary-list__value">
          K012
        </dd>
      </div>
</div>
```

The idea is that we have a bunch of rows with different things, but some where the value is empty and it would be good to have a way to auto hide those.

**Comment by vanitabarrett** [comment]
Hi @stuaxo,

You're right, this is the summary list component. You can read our guidance on using the summary list here: https://design-system.service.gov.uk/components/summary-list/

Because the component uses the description list (`<dl>`) HTML element, you should only use it to present information that has a key and **at least one value**. Have you got an example of where you're using the summary list with empty values?

**Comment by vanitabarrett** [comment]
Hi @stuaxo . Just wondering if you've got a more specific example for this feature request. If you want to hide rows where there is no value, that feels like something you might want to do by filtering the data before passing it into the component, but I may have misunderstood what you're trying to do.

**Comment by stuaxo** [comment]
Hi, 
  I think that sounds like a good solution - it's been a while since I worked this component - so I'll shut this, hopefully someone trying to solve the same issue will find your answer.

Thanks,
Stuart
