### ISSUE TITLE
Write release notes for Frontend v3.12.0

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2179]
## What

Write the release notes for GOV.UK Frontend v3.12.0

## Why

To help users understand what changes have been made in the 3.12.0 release.

## Who needs to be involved 
Eoin, Ollie

## Done when…

This will be done when the release notes:

- [x] have been drafted
- [x] have been reviewed by a developer
- [x] have been 2i'ed

**Comment by EoinShaughnessy** [comment]
Release notes have passed 2i and are ready to publish.
