### ISSUE TITLE
Rename the default branch to `main`

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2190]
The default branch for this repository will soon be renamed from `master` - a potentially offensive term - to `main`. Many other GitHub communities are also renaming their default branches. To learn more about this welcome news, check out [Git’s statement about why branch renaming matters](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

You may need to make changes if you have a local copy or fork of this repository. You can view our guidance on this [Github issue](https://github.com/alphagov/govuk-design-system/issues/1597).

**Comment by lfdebrux** [comment]
This work has now been completed, the default branch of this repository is now called `main`.

You may need to make changes if you have a local copy or fork of this repository. You can view our guidance on this [Github issue](https://github.com/alphagov/govuk-design-system/issues/1597).
