### ISSUE TITLE
Scope release v4.0.0

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-frontend#2193]
## What
Decide what's in the v4.0 release.

## Why
Work out what goes in our last version of v3.x.x and what breaking changes should be in v4.0.0. 

## Who needs to know about this
Whole team

## Done when

- [x] Review previous plan https://github.com/alphagov/govuk-frontend/projects/4
- [x] Agree on breaking change for v4.0.0 and set milestone
- [x] Remove milestone from deprioritised issues
- [x] Write up [v4.0.0 epic card](https://github.com/alphagov/govuk-frontend/issues/2274)

**Comment by vanitabarrett** [comment]
Running a session on Tuesday - will move into blocked until then.

**Comment by vanitabarrett** [comment]
Update: have sorted most potential v4 issues, just 3 left to sort which I'll look through tomorrow. @kellylee-gds has also run some ways of working sessions. Ideas have been collected on how to address some of the challenges - Kelly is trying to find some time before I go on leave to go through these and decide on next steps.

**Comment by vanitabarrett** [comment]
All potential work for v4 has been discussed with the team and decisions made on the work. The [v4.0.0 project board](https://github.com/alphagov/govuk-frontend/projects/5) shows all the work we have decided to include and exclude from v4.0.0, as well as 'nice to have' work.

**Comment by vanitabarrett** [comment]
All work now reflected in the [v4.0.0 milestone](https://github.com/alphagov/govuk-frontend/milestone/22)

**Comment by vanitabarrett** [comment]
I've moved the checklist item on this card about ways of working into a new epic: https://github.com/alphagov/govuk-frontend/issues/2341
