### ISSUE TITLE
Consider documenting `data-nosnippet` addition to cookie banner component

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2196]
## What
Consider documenting the `data-nosnippet` attribute. It's not a breaking change, it's an improvement to the existing HTML, but people using the HTML for the cookie banner component will need to add this attribute manually.

## Why
In https://github.com/alphagov/govuk-frontend/pull/2192 we added the `data-nosnippet` attribute to the cookie banner component.

## Who needs to know about this
Developers, Technical Writer, Content Designer

## Done when

- [x] Decided whether to document this change
- [x] Drafted content

**Comment by 36degrees** [comment]
This was included as a recommended change in the release notes for v4.0.
