### ISSUE TITLE
Known issue: hover state is mis-painted on links within CSS multiple-column layouts

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-frontend#2204]
## Description

When you hover your cursor over a link, only the thickness of that link's underline should change.

However, if you have links within a [multiple-column layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns) and your browser uses Chromium, then hovering your cursor over a link also changes the thickness of other, non-hovered link underlines.

![image](https://user-images.githubusercontent.com/72507742/116082284-2371dc80-a693-11eb-928e-4d4e925bf1ee.png)

Occasionally, the underline on some links may disappear entirely.

This issue will affect you if:
- your browser uses Chromium (for example, Chrome, Edge or Opera),
- you have links within a [multiple-column layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns)
- you have opted your service into the [GOV.UK Design System's new link styles](https://github.com/alphagov/govuk-frontend/pull/2183)

## How to fix this issue

- Choose not to opt in to the new link styles
- Remove the thicker underline from links in columns by turning off the hover state
- Change your layout so that it does not use a CSS multiple-column layout (albeit doing this could be very time-consuming)

We have [reported this issue to Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1190987).

In the future, when Chromium fix the bug that's causing these issues, we'll turn on link styles by default.

**Comment by 36degrees** [comment]
It looks like this issue [may have been fixed in Chrome 102](https://bugs.chromium.org/p/chromium/issues/detail?id=1190987#c15) 🎉

**Comment by 36degrees** [comment]
Closing this issue as Chrome 102+ has reached 95%+ adoption.
