### ISSUE TITLE
GitHub Action to add a diff of the changes to dist to release PRs fails with `Error: Argument list too long`

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2225]
## Description of the issue

For example, https://github.com/alphagov/govuk-frontend/pull/2224/checks?check_run_id=2575562845

## Steps to reproduce the issue

When raising a release PR, we have a GitHub Action that is meant to add a diff of the changes to dist (what a mouthful!) as a comment on the PR.

This failed when we were trying to release v3.12.0 with `Error: Argument list too long`

Possibly because the diff output was too long to be passed as an environment variable to the script?

## Actual vs expected behaviour

The GitHub Action should add the diff to the PR, but failed.

## Environment (where applicable)

N/A

**Comment by lfdebrux** [comment]
Someone else has had the same issue, and fixed it by using a temporary file instead of an environment variable

https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867/5
