### ISSUE TITLE
Updated link style on Accordion "Open all" Button

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#2235]
Very minor issue but I believe the new link style (which I love) may be having unintended consequences on the Accordion "Open all" link.

<img width="84" alt="Screenshot 2021-05-24 at 19 38 48" src="https://user-images.githubusercontent.com/23356842/119393167-81acd200-bcc8-11eb-9e99-708090f95fd3.png">

<img width="100" alt="Screenshot 2021-05-24 at 19 38 35" src="https://user-images.githubusercontent.com/23356842/119393175-83769580-bcc8-11eb-8295-ff7c702dbd3d.png">

<img width="84" alt="Screenshot 2021-05-24 at 19 38 42" src="https://user-images.githubusercontent.com/23356842/119393179-840f2c00-bcc8-11eb-93f1-a63a4661cb65.png">

From memory, this link may not have had an underline before but the states had the border or box-shadow align with the border of the top of the first accordion.

Now the design has changed it may be worthwhile to increase the spacing between the "Open all" link and the first accordion as there is no longer a need for them to be butted up against each other.

Also 👋 ❤️

**Comment by christopherthomasdesign** [comment]
Hi @dashouse 👋  thanks for raising this

We're currently working on iterating the accordion design with the GOV.UK team. You can see some [work-in-progress designs and working group feedback](https://github.com/alphagov/govuk-design-system-backlog/issues/1#issuecomment-839802842) if you're interested. We'll make sure the new designs don't have any problems like this. But I think cos we're planning to change the accordion in near future, we may leave this issue for now.

**Comment by dashouse** [comment]
@christopherthomasdesign Awesome, thanks for the update. It was a "just in case" issue :)
