### ISSUE TITLE
Migrate GOV.UK Frontend build pipeline to use Dart Sass

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2239]
## What

Migrate GOV.UK Frontend's tooling to use Dart Sass rather than LibSass.

**This does not include migrating to the module system or dropping support for LibSass or Ruby Sass – we'll continue to test against and support all three compilers for the time being.**

This only affects which compiler we use internally to generate the stylesheets used in the review app, and when compiling minified stylesheets for 'dist'.

## Why

Dart Sass is the only one of the three compilers we support that is not deprecated. Increasingly, new projects should and likely will be using Dart Sass.

Changes are being made to Dart Sass including deprecations (like #2238) which may cause warnings and other issues for our users. Using Dart Sass as our primary compiler will help us to identify these issues earlier.

## Who needs to know about this

Developers

## Done when

- [ ] GOV.UK Frontend build pipeline updated to use Dart Sass rather than LibSass

**Comment by querkmachine** [comment]
We may want to re-evaluate priority on this as we're starting to run into compatibility issues running node-sass with Node 16 on Apple Silicon Macs (#2574).

node-sass has apparently been updated to work on Node 16, though some commenters seem to dispute the efficacy of those fixes (sass/node-sass#3077, sass/node-sass#3090). It does not have any support for arm64 architecture as of writing (open issue sass/node-sass#3033), and this is likely not a priority given the package has been deprecated.
