### ISSUE TITLE
Support nonce attribute on js-enabled script

### ISSUE THREAD

**Issue by natcarey** [alphagov/govuk-frontend#2246]
## Related component

This relates to the template.

## Context

In the template there's an [inline script tag which cannot be customised](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/template.njk#L31), this is causing us problems at HMRC.  We want to encourage teams to move away from an `unsafe-inline` CSP header, The [currently advised approach](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#select-and-initialise-an-individual-component) of using a SHA in the CSP header to allow this exact script would have to be duplicated across the ~350 services at HMRC.

We're concerned that duplicating this SHA would cause problems if it needs updating in the future.  Teams who miss this when updating to new versions would break some javascript components.  If they are aware that they need to update this they would have to go and look for the new SHA.  I'm aware that changing this would be considered a breaking change but it's still a step which I believe should be avoided in our future upgrade processes.

For some use-cases inside HMRC teams are already using `nonce` for scrips which is supported by the Play Framework which we use for our frontends.  The change required to support this is provided in [pull request 2245](https://github.com/alphagov/govuk-frontend/pull/2245), this would allow us to encourage teams to make this change with confidence that future updates will be supported without changing the CSP config.

## Alternatives

This has previously been discussed in the issues [Inline script in template.njk block by CSP](https://github.com/alphagov/govuk-frontend/issues/1811) and [Script Content Security Policy (CSP) blocks inline script](https://github.com/alphagov/govuk-frontend/issues/1657).  These were resolved by documenting the SHA required to allow this script.  The risk of needing to change this later is a larger concern for us with the number of services we support.

**Comment by 36degrees** [comment]
This would need documenting in the:

- [page template guidance in the Design System](https://design-system.service.gov.uk/styles/page-template/#options)
- [CSP guidance in the Frontend Docs](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#if-your-javascript-is-not-working-properly)
