### ISSUE TITLE
Create release notes for v3.13.0

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-frontend#2247]
## What
Create the release notes for GOV.UK Frontend v3.13.0.

## Why
To help users understand what changes have been made in the 3.13.0 release.

## Who needs to know about this
@EoinShaughnessy and whoever else does the release

## Done when
This will be done when the release notes have been:
- [x] drafted
- [x] reviewed by a developer
- [ ] 2i'd

**Comment by EoinShaughnessy** [comment]
Draft release notes: https://docs.google.com/document/d/1OV488IaVwGRAdPsRRzVev7VHJCWoRc0IvK3QyPGL7TE/edit

**Comment by EoinShaughnessy** [comment]
The current draft https://docs.google.com/document/d/1OV488IaVwGRAdPsRRzVev7VHJCWoRc0IvK3QyPGL7TE/edit has passed 2i.

**Comment by EoinShaughnessy** [comment]
Is there more content to be added, or can I raise a PR?

**Comment by 36degrees** [comment]
@EoinShaughnessy I think there'll be 2 additions:

- Avoid ink skipping on link hover state underlines (#2251) – which I think should be listed as a fix
- Add "None of the above" and "or" divider to checkboxes (#2151) – which will need documenting as a new feature and probably requires a bit more thought
