### ISSUE TITLE
Draft Slack comms for v3.13.0 release

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2254]
## What

Draft comms that we will release on Slack.

## Why

So users know what new features have been released.

## Who needs to know about this

Content Design and Design to draft comms, review by team on Slack

## Done when

- [x] Include acknowledgment of any contributors
- [x] Message drafted
- [x] 2i'd by team
- [x] Posted when we've done the release

**Comment by calvin-lau-sig7** [comment]
[Comms draft in Google Docs](https://docs.google.com/document/d/1uquNdV55co5NLBkkvvxDUq43qDDmEySDrBEFDjukiII/edit?usp=sharing), being reviewed by @36degrees and nearly good to go. Could benefit from a sense-check from another team member.
