### ISSUE TITLE
Generated README files

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#226]
To avoid duplicating code examples and documentation manually, as well as having full docs in the source directory for each component,  we generate the README markdown file and a dev preview page from the same set of nunjucks templates. 

This will allow us to test our assumptions with consumers.

It could be the case that we disable the generation task once we are confident in the docs content, but there is still the question creating and updating docs for component when a contribution happens.

**Comment by 36degrees** [comment]
@igloosi this has been done, right?

**Comment by igloosi** [comment]
yeah done
