### ISSUE TITLE
HTML5 validation error

### ISSUE THREAD

**Issue by dan-earle** [alphagov/govuk-frontend#2263]
validator.w3.org reports:

Error: Attribute src not allowed on element image at this point.

From line 49, column 19; to line 49, column 160

          <image src="assets/images/govuk-logotype-crown.png" xlink:href="" class="govuk-header__logotype-crown-fallback-image" width="36" height="32"/>`

This was already reported but missed here; first issue on this old bug: [#1298](https://github.com/alphagov/govuk-frontend/issues/1298)

## Description of the issue
HTML5 validator reports: `Error: Attribute src not allowed on element image at this point.` for uk gov logo

## Steps to reproduce the issue
Go to [https://validator.w3.org/#validate_by_uri](https://validator.w3.org/#validate_by_uri) and enter https://design-system.service.gov.uk/ look at issue **(Error) number 2**

## Actual vs expected behaviour
Hoping no validation errors :)

## Environment (where applicable)
Windows PC

- Operating system:
- Browser:
- Browser version:
- GOV.UK Frontend Version: 3.12.0

**Comment by dan-earle** [comment]
Sorry is already covered by https://github.com/alphagov/govuk-frontend/issues/1280 and will be fixed in next version

**Comment by 36degrees** [comment]
Thanks @dan-earle. I can confirm that this was fixed in GOV.UK Frontend v3.13.0, which was released last week.
