### ISSUE TITLE
Add inverse breadcrumb and back link modifiers

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2266]
## What

Add a modifier to the breadcrumbs component to invert the colours, for situations where breadcrumbs appear against dark backgrounds (for example, in the blue masthead on product pages)

## Why

The [product page example](https://github.com/alphagov/product-page-example) repo currently contains [CSS to invert breadcrumbs](https://github.com/alphagov/product-page-example/blob/master/source/stylesheets/modules/_breadcrumbs.scss) for use on product pages across GaaP.

There are already various examples of inverse breadcrumbs on GOV.UK, for example on the Coronavirus page, on topic pages and across the various GaaP product pages:

![Screenshot 2021-07-05 at 11 57 46](https://user-images.githubusercontent.com/121939/124461595-bbbdc900-dd88-11eb-86c3-8bb7bfca62fb.png)
![Screenshot 2021-07-05 at 11 57 52](https://user-images.githubusercontent.com/121939/124461599-bc565f80-dd88-11eb-8620-892463ea3230.png)
![Screenshot 2021-07-05 at 11 57 54](https://user-images.githubusercontent.com/121939/124461602-bceef600-dd88-11eb-994d-cfa3e9230f2c.png)
![Screenshot 2021-07-05 at 11 58 00](https://user-images.githubusercontent.com/121939/124461604-bd878c80-dd88-11eb-96db-64170b4afe75.png)
![Screenshot 2021-07-05 at 12 00 55](https://user-images.githubusercontent.com/121939/124461606-bd878c80-dd88-11eb-85cf-45e1e332fbb4.png)

It would make sense to add a modifier for back links at the same time, as they occupy the same position on the page and are conceptually similar.

## Who needs to know about this

Designers, developers

## Further detail

Many of these examples also add a border to the bottom of the breadcrumb. Is that needed? Is that a part of the breadcrumb?

## Done when

- [x] Inverse breadcrumb modifier added
- [x] Inverse back link modifier added
- [x] Examples added to the review app

**Comment by 36degrees** [comment]
GOV.UK Publishing Components also include [a modifier class for inverse breadcrumbs](https://github.com/alphagov/govuk_publishing_components/blob/main/app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss#L4-L23).

**Comment by querkmachine** [comment]
The actual modifiers have been added in #3774, however we're keeping this open in the interim for a couple of reasons:

- The examples of the modifiers in the review app are currently less than ideal. #3780 has been opened to account for that.
- The added modifiers don't account for the bottom border that some usages have. Would this be another additional modifier class to add?

**Comment by 36degrees** [comment]
> The actual modifiers have been added in #3774, however we're keeping this open in the interim for a couple of reasons:
> 
> * The examples of the modifiers in the review app are currently less than ideal. [Allow for viewing of inverse modifications of components in the review app #3780](https://github.com/alphagov/govuk-frontend/issues/3780) has been opened to account for that.

#3780 has now been closed, so I think this is resolved.

> * The added modifiers don't account for the bottom border that some usages have. Would this be another additional modifier class to add?

If we think that's important then I suggest we raise it as a new issue so that it's clear what the change we want is. The title of this issue has nothing to do with bottom borders.

Once that's done I suggest we then close this and move it to 'Ready to release'.

**Comment by querkmachine** [comment]
The latter is now raised as #3914, so I'm going to close this as being done.

**Comment by colinrotherham** [comment]
Similar to how we test the `default` example, should we add `inverse` ones into Percy too?
