### ISSUE TITLE
Add inverse button modifier

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2267]
## What

Add a modifier to the button component for situations where buttons appear against dark backgrounds (for example, in the blue masthead on product pages)

## Why

The [product page example](https://github.com/alphagov/product-page-example) repo currently contains [CSS for inverse buttons](https://github.com/alphagov/product-page-example/blob/cc4ee7f89693ec9d29b6f13833ea72986486c898/source/stylesheets/modules/_inverted-button.scss) for use on product pages across GaaP.

There are already various examples of inverse buttons across the various GaaP product pages, including the Design System:

![Screenshot 2021-07-05 at 13 22 14](https://user-images.githubusercontent.com/121939/124471795-37be0e00-dd95-11eb-87fb-963dc2b35baa.png)
![Screenshot 2021-07-05 at 13 22 23](https://user-images.githubusercontent.com/121939/124471801-38ef3b00-dd95-11eb-80b2-a9864146ecf1.png)
![Screenshot 2021-07-05 at 13 22 31](https://user-images.githubusercontent.com/121939/124471803-3987d180-dd95-11eb-942f-e076eb3d1c1a.png)
![Screenshot 2021-07-05 at 13 22 37](https://user-images.githubusercontent.com/121939/124471804-3987d180-dd95-11eb-8507-db094815c36e.png)

## Further information

- How do the 'start button' and 'inverse' modifiers combine?
- Some of these buttons are as big as start buttons, but don't have the chevron. What are the rules around button sizes and chevrons?

## Who needs to know about this

Designers, developers

## Done when

- [ ] Inverse modifier for buttons added
- [ ] Example(s) added to review app

**Comment by edwardhorsford** [comment]
A big +1 from me. I've had to recreate styles for these intro banners on three services. I suspect this is a very widely used pattern in government.

**Comment by edwardhorsford** [comment]
To note that this would make building [interruption pages](https://github.com/alphagov/govuk-design-system-backlog/issues/27) much easier.

**Comment by chrisadesign** [comment]
Inverse button is usually used on the proposed [interruption card](https://github.com/alphagov/govuk-design-system-backlog/issues/27).

**Comment by paulrobertlloyd** [comment]
Needed to add an inverted button style for use with [a masthead component](https://github.com/x-govuk/govuk-prototype-components/tree/main/x-govuk/components/masthead), which is a recreation of the blue banner shown in the opening comment of this thread: https://github.com/x-govuk/govuk-prototype-components/blob/main/x-govuk/components/masthead/_button.scss

Also had to create the same for use with an interruption card used on another prototype: https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data-prototype/blob/main/app/components/button/_button.scss (from which I used the code from the masthead component)

I can see why this is not included in the design system, as currently there are no components that use an inverted button style. That said, plenty of examples exist in the wild, all slightly different. Also the precedent is set with an inverted link style being present also.

The one complication with an inverted button style is that you need to know the background it is sitting on for the button text to match. In examples of the interruption and masthead components that is always `$govuk-brand-colour`, but I can imagine cases where that might not be the case.
