### ISSUE TITLE
Multiple actions in Summary list don't align when they go over one line

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#2281]
## Description of the issue
(From support) As seen here, when there are multiple action that go over one line, they don't line up with each other, and the spacing is inconsistent - especially on the right.
https://govuk-frontend-review.herokuapp.com/components/summary-list/extreme/preview

## Steps to reproduce the issue
Use multiple actions as in the example above

## Actual vs expected behaviour
Actions align/spaced more consistently

## Environment (where applicable)

- GOV.UK Frontend Version: 3.13.0

**Comment by joelanman** [comment]
https://github.com/DFE-Digital/govuk-components/issues/218#issuecomment-886200168

**Comment by lfdebrux** [comment]
![Screenshot of problem](https://user-images.githubusercontent.com/503614/127305281-5940c2f2-ecf8-4a26-a0d7-e10027cacefa.png)

**Comment by frankieroberto** [comment]
Intriguingly, the bug doesn't appear in Safari, but does in Chrome. Removing `margin-right: 10px;` and replacing it with `padding-left: 10px` fixes it. (The padding-left might also have to be removed on the first item).
