### ISSUE TITLE
Document how to resize text in different browsers and devices

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2294]
## What
Document how to resize text on different browsers/devices. At the moment the instructions for doing this are hidden in an [old PR description](https://github.com/alphagov/govuk-frontend/issues/1569) ( > 'How text was resized in browsers'), it would be useful to move them into our docs to speed up the process of testing.

## Why

We tend to test if our components work when text is resized (magnified) using different browser or device settings devices. This is especially useful with visual changes that change text size and/or contain icons or other visual signifiers to ensure that the component is still usable when the text is resized. 

Documenting how to do this would help us and contributors to do the required testing.

## Further detail

We should link to the new doc from https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/testing.md or the upcoming component accessibility acceptance criteria doc.

Note that resizing text using browser settings is different from zooming in on the whole screen using magnification software such as Windows Magnifier.

## Who needs to know about this
Developer, Technical Writer

## Done when

- [x] We decide doc location
- [x] Technical Writer drafts doc
- [x] Developer reviews doc
- [x] Doc gets 2i'd
- [ ] We publish the doc

**Comment by EoinShaughnessy** [comment]
Are we going to publish this content as a standalone doc within https://github.com/alphagov/govuk-frontend/tree/main/docs/contributing?

**Comment by EoinShaughnessy** [comment]
Some of the browser functionality described in [#1569, the old PR](https://github.com/alphagov/govuk-frontend/issues/1569), has changed in the meantime.

I've tested the current functionality on my mobile and home desktop devices, and listed it in the draft doc: https://docs.google.com/document/d/1WWJtRqYm4QBjDovpuxj4rbe8K9Bv4Vd2MQymp4O3-0A/edit

**Comment by EoinShaughnessy** [comment]
[Doc](https://docs.google.com/document/d/1WWJtRqYm4QBjDovpuxj4rbe8K9Bv4Vd2MQymp4O3-0A/edit) has passed pre-i and I'm now sending it for 2i.

**Comment by EoinShaughnessy** [comment]
Doc has passed 2i.
