### ISSUE TITLE
Support macro caller blocks

### ISSUE THREAD

**Issue by axle-h** [alphagov/govuk-frontend#2299]
## Context
GDS components support passing HTML content inline or via a variable with separate `set` block. Often the structure of this content means that passing HTML content inline is messy or impossible. This results in many `set` blocks that are disconnected from their components, which is difficult to read.

A solution to this would be to support the `caller()` block within GDS macros. From Nunjucks documentation: A call block enables you to call a macro with all the text inside the tag. This is helpful if you want to pass a lot of content into a macro. The content is available inside the macro as `caller()`.

```
{% macro add(x, y) %}
{{ caller() }}: {{ x + y }}
{% endmacro%}

{% call add(1, 2) -%}
The result is
{%- endcall %}
```

Since you can only have one caller block per component, this would only be appropriate for the canonical component body (where that makes sense per component) eg the content of `govukWarningText`.

I would expect that the GDS components implementation of this would use `caller()` as a fallback on top of the existing `text` and `html` options.

## Alternatives
No alternative required, the library works fine as-is. This is just a nice-to-have.

**Comment by vanitabarrett** [comment]
Hi @axle-h 👋 I believe supporting `call` in more govuk-frontend components is already covered in an existing issue in this repository here: https://github.com/alphagov/govuk-frontend/issues/941 . Are you happy for me to close your issue as it duplicates #941 ?

**Comment by axle-h** [comment]
ah apologies, I had searched for 'caller' but had no hits, yes please close this.

**Comment by vanitabarrett** [comment]
No problem @axle-h , it's still useful for our team as it means we know multiple people would find this feature helpful!
