### ISSUE TITLE
Component tests within a test suite are not isolated from each other

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-frontend#2303]
## Cause

By default [jest-puppeteer] creates a new browser context and page for each test suite (collection of tests in a file), but not for each test (this is not documented, but evident from reading the [jest-puppeteer source code](https://github.com/smooth-code/jest-puppeteer/blob/v5.0.4/packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js)). This means that for each test the same Chrome tab is used, including any shared state (for example, if a test visits a page with `page.goto`, in the next test the tab will still have that same page open). 

## Consequences

This means that tests can affect each other, which is bad practice, as it can cause difficult to debug problems.

Because this lack of isolation it is also goes against most developer's expectations, so contributors who are not aware of the lack of isolation may not add test teardown functions where they are needed.

This problem recently manifested with the accordion component, where it was found that the session storage would cause tests to fail where they should pass (see #2301 for more details).

## Impact of debt

Medium.

Most of our components do not have shared state so the chances of hitting this issue are low, however it does reduce confidence in our tests and make it harder for contributors to write valid tests. There is also a small risk that there are current bugs in our code that are being hidden by this issue.

## Effort to pay down

Medium.

It is trivial to reset the browser state after each test; we can add a global `afterEach` function to call [`resetPage()` or `resetBrowser`](https://github.com/smooth-code/jest-puppeteer/tree/master#globaljestpuppeteerresetpage). However, currently this would break a large number of our tests, which (inadvertently or otherwise) assume that the browser state is not cleared between tests and use `beforeAll` instead of `beforeAll`.

Fixing this issue would also most likely cause our tests to be slower, due to the overhead of resetting the browser; it is not clear what the scale of the slowdown would be however, as currently adding the teardown function breaks most tests, but it could be as large as 2x.

## Overall rating

Medium.

[jest-puppeteer]: https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-environment-puppeteer

**Comment by colinrotherham** [comment]
Related to

* https://github.com/alphagov/govuk-frontend/issues/3049

Where we can look at browser/session isolation using a framework
