### ISSUE TITLE
Update docs to explain that accordion summary line can only contain phrasing content

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#2310]
## What

As explained in https://github.com/alphagov/govuk-frontend/issues/2309, we’re changing the design of the accordion which means that the summary line can only contain [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content).

We should update the relevant docs about this restriction: https://github.com/alphagov/govuk-frontend/blob/1c57eab2f74c4873ee5685cc6ad822a36f824352/src/govuk/components/accordion/accordion.yaml#L38 

## Why

To help our users understand that having elements other than phrasing content inside the summary line is not valid HTML, and also that the summary content should be simple content (elements other than phrasing content inside the summary would be likely not be an appropriate use of the accordion component)

## Who needs to know about this
Technical writer, developer

## Done when

- [x]  We’ve updated the Nunjucks documentation

**Comment by EoinShaughnessy** [comment]
The Nunjucks update has passed 2i. See [#2313](https://github.com/alphagov/govuk-frontend/pull/2313).

**Comment by hannalaakso** [comment]
@EoinShaughnessy Thanks for updating the docs. We should make this information available to users of the HTML version too. I guess that would fall somewhere between this ticket and https://github.com/alphagov/govuk-design-system/issues/1684 - I've left a note on that issue.
