### ISSUE TITLE
Create release notes for GOV.UK Frontend v4.0.0 (major breaking release)

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-frontend#2314]
## What

Create release notes for GOV.UK Frontend v4.0.0.

## Why

To tell users about the changes we've made and explain what they may need to do. Changes needed may depend on different scenarios, so we need to make sure users understand **when** they need to make changes.

## Who needs to know about this

Technical Writer, Developers

## Done when

- [x] Technical Writer and Developers meet to scope work
- [x] Technical Writer drafts release notes
- [x] Developer reviews and approves release notes
- [x] Release notes pass 2i

**Comment by EoinShaughnessy** [comment]
Draft doc: https://docs.google.com/document/d/1sANEJKi1PQmjwipdxViIz_gx5PJM_rUTfwelfAU8kcc/edit

**Comment by vanitabarrett** [comment]
Release notes for developer review: https://docs.google.com/document/d/1atVBJI2ETBskZay_coZJxEsL1T4BOgoKY9BKszyr4Bo/edit#heading=h.3tiprhyq874l

**Comment by EoinShaughnessy** [comment]
@vanitabarrett Release notes have passed 2i and I've [added the approved contents into the changelog](https://github.com/alphagov/govuk-frontend/pull/2473). Let me know what else I can help with!
