### ISSUE TITLE
Draft Slack comms for v3.13.1 release

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2319]
## What
Tell users about release of Frontend v3.13.1. These are mostly error fixes, particularly for users using forced colour mode.

[Draft comms document](https://docs.google.com/document/d/1uquNdV55co5NLBkkvvxDUq43qDDmEySDrBEFDjukiII/edit?usp=sharing)

## Why
So users know what fixes have been released.

## How

On Design System homepage:
- update 'What's new' panel of Design System homepage https://github.com/alphagov/govuk-design-system/pull/1856

On Github:
- add short backlog comment in Radios and Checkboxes (link to release notes)

On Slack, post message on:
- #gov-uk-design-system on GDS
- #gov-uk-design-system on x-gov
- #design on x-gov

On email, send to list:
- Mailchimp - new and updated components and patterns — [preview](https://us1.campaign-archive.com/?e=[UNIQID]&u=ada1bae4b177beb9e03502ced&id=c5798ef528)

## Who needs to know about this
Content Design

## Done when
- [x] Include acknowledgment of any contributors
- [x] Message drafted
- [x] 2i'd by team
- [x] Posted when we've done the release

**Comment by calvin-lau-sig7** [comment]
i've edited this ticket to outline the (small) comms plan for this, not just Slack. Made some assumptions on where else we want to tell users, but I'll check with everyone when we review draft messages together.
