### ISSUE TITLE
Test early v4.0.0 release notes with users

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2351]
## What
Test the first few entries in the v4.0.0 release notes to get feedback from users. We should aim to test a few different 'types' of changes, for example: removing a deprecated class; a bug fix which requires a user to make changes to their code or setup.

## Why
We want to find out if users understand what changes they need to make from the release notes we've drafted for v4.0.0. 

## Who needs to know about this
Technical writer; user researcher; developers

## Done when

- [x] Drafted a few entries for the release notes which we can test with users
- [x] Include find out about breaking changes https://github.com/alphagov/design-system-team-internal/issues/514 
- [x] We've tested the release notes with some users and gathered feedback
- [x] Identified tweaks/changes we need to make following that feedback

**Comment by kellylee-gds** [comment]
Agreed there wasn't value in doing this as we think biggest challenge to users will be navigating the release notes which we will test as part of #2352

**Comment by EoinShaughnessy** [comment]
@RosieClayton Our users normally read our release notes on GitHub. Does it make a difference that we'll be sharing Google Docs with them, i.e., is that a different experience compared with what they're usually used to?

**Comment by EoinShaughnessy** [comment]
@RosieClayton Ah cool, yeah that's a good point about getting feedback on the content, etc. For a preview version, I was thinking maybe we could just share copies of this [draft doc]https://docs.google.com/document/d/1zXF8tRgbRJm8863-laNLB9ZcB4AbWdkNI-IGDtCth2U/edit?pli=1#heading=h.icv1a7bx25lyurl), once we've added all the content we need to, and it's been through the 2i review process.

**Comment by EoinShaughnessy** [comment]
I've shared a [draft of release note content for the accordion changes](https://docs.google.com/document/d/1I7y1lXUjwLmkCSVO2NLADFOdT4GrcrFSFHTJF8Jf3Hs/edit?pli=1) with the team.

When I've actioned any feedback, I'll add it into the [draft release notes for testing with users](https://docs.google.com/document/d/1zXF8tRgbRJm8863-laNLB9ZcB4AbWdkNI-IGDtCth2U/edit?pli=1#heading=h.icv1a7bx25ly).

**Comment by EoinShaughnessy** [comment]
We've now gathered [user feedback](https://docs.google.com/document/d/1t4ctbDUJOXUHaEzWcIWHRRKm5fEs64l9YVrfcyReh6E/edit#heading=h.r683xzaxbba1) and identified these issues for addressing in the release notes:

- give more detail about change involving `$govuk-border-width-form-element-error` variable
- explain reason for optional change, to help devs who might be unfamiliar with coding for accessibility

I'll create a new issue to cover these updates.
