### ISSUE TITLE
Test v4.0.0 pre-release and release notes with users

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2352]
## What
Once we have completed the majority of the work for v4.0.0, we should create a pre-release which we can share with users and get them to test out the update process and release notes.

## Why
So that we can identify any issues with the release / release notes early and fix them before we do the actual release.

## Who needs to know about this
Developers; Tech Writer; User Research

## Dependent On

- [x] The majority of the changes being included in v4.0.0 being finished
- [x] The v4.0.0 release notes being complete

## Done when

- [x] Drafted comms for sharing the pre-release. Point people to the pre-release and the release notes
- [x] Include a deadline for feedback?
- [x] We have generated a pre-release for v4.0.0
- [x] We have shared the pre-release with our users
- [x] We have actioned any feedback

**Comment by EoinShaughnessy** [comment]
In the comms (Slack message) for the pre-release, where should we tell users to leave feedback? In a Slack thread?

**Comment by EoinShaughnessy** [comment]
Rough draft of pre-release comms: https://docs.google.com/document/d/1HEAVQZBVOVOvsVqMlwtxbNySS31-B0Iu8X6ZT93fyFc/edit#

**Comment by EoinShaughnessy** [comment]
[Feedback from users.](https://docs.google.com/document/d/1IAcg5Fi9kOLiTAav5MKL6lB2UKZIiczdghMUTaTQI5I/edit) No changes requested, but worth retaining for evidence of how they use notes and what they like.
