### ISSUE TITLE
Minor rounding issues with width of grid columns due to Sass precision

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2361]
## Description of the issue

The percentage widths of our one-third and two-third grid widths are only defined to 4 decimal places:

https://github.com/alphagov/govuk-frontend/blob/093cfe8dad077e22eedfdb6de0067c7972f93761/src/govuk/settings/_measurements.scss#L21-L28

When the browser does the maths to convert these percentages back into pixels, this results in a slight rounding error.

## Steps to reproduce the issue

1. Look at the reported width of a two-thirds and one-third column in Chrome dev tools.

## Actual vs expected behaviour

Chrome dev tools reports the width as 329.98 and 659.98px for one-third and two-third columns respectively, rather than 330px and 660px.

![Screenshot 2021-09-24 at 13 44 58](https://user-images.githubusercontent.com/121939/134677803-574a746c-548f-4d81-802b-b9334f246e0f.png)

Meanwhile in Safari, the width is reported as 330px / 660px, but the kerning between the first and second letter of every line in the one-third column is looser than it should (probably most obvious between the 'a' and 'n' of 'and' in the fourth line) – this doesn't happen if the precision is increased to 6 decimal places:

| 4 decimal places | 6 decimal places |
| -- | -- |
| ![Screenshot 2021-09-24 at 13 47 51](https://user-images.githubusercontent.com/121939/134677061-79b6f323-e2e4-4477-8321-9f199037ac57.png) | ![Screenshot 2021-09-24 at 13 47 55](https://user-images.githubusercontent.com/121939/134677054-5b0d105f-0bd9-4759-bc46-009c6e92ab88.png) |

Neither of these are really issues, but they're minor annoyances that we should consider fixing when we look at our Sass precision.

## Other related issues

- #2199

**Comment by 36degrees** [comment]
To fix this, I believe we need to:

- increase the number of decimal places for the percentages to at least 6
- change the precision used by our own Sass compiler for the review app / dist builds to 6 decimal places (or migrate to dart-sass, which has a hardcoded precision of 10dp)
- document that teams will configure the precision for their own compiler if using node-sass

**Comment by colinrotherham** [comment]
> To fix this, I believe we need to:
> 
> * increase the number of decimal places for the percentages to at least 6
> * change the precision used by our own Sass compiler for the review app / dist builds to 6 decimal places (or migrate to dart-sass, which has a hardcoded precision of 10dp)
> * document that teams will configure the precision for their own compiler if using node-sass

This will be fixed in:

* https://github.com/alphagov/govuk-frontend/pull/3199

I've confirmed in latest Chrome and Safari that 5dp precision is enough so I don't think we need extra docs
