### ISSUE TITLE
Create release notes for GOV.UK Frontend v3.14.0 (Feature release)

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2364]
## What

Create release notes for GOV.UK Frontend v3.14.0 (feature release).

## Why

To tell users about the fixes we've made and the new features we've introduced.

- fix for the panel component overflow issue
- adding new override text alignment classes
- adding the ability to specify negative spacing in the `govuk-spacing` mixins

We also debated adding the [documentation for previous changes](https://github.com/alphagov/govuk-frontend/issues/2340) into this release to avoid additional 'bloat' in the v4.0.0 release notes. Might be worth trialling writing the documentation for one of these changes to see how well it fits in with the 3.14.0 release notes and how it might work.

## Who needs to know about this
Technical Writer, Developers

## Done when

- [x] Technical Writer / Developer drafts release notes 
- [x] Technical Writer / Developer drafts documentation for previous change - trial one to start with, to see if this approach to include them in the 3.14.0 release notes will work?
- [x] PR raised for release notes - this will work slightly differently because we're following [a different process](https://docs.google.com/document/d/1Ybq_DonZqzX1vOrwxUmXC_ff9Yazdqn7ToEDVVay6ec/edit#), ask developer for assistance
- [x] Release notes pass 2i

**Comment by EoinShaughnessy** [comment]
@vanitabarrett I took the most recent entries to the 'Unreleased' bit of our [Changelog](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md), and added them to a [draft Google doc](https://docs.google.com/document/d/1klkjIXgVPIaNtb-i8MVP2uFrc7L_SIHO3CCH3D9avMc/edit).

At the end of the doc, I've added a section for the [previous changes](https://github.com/alphagov/govuk-frontend/issues/2340). Could something like that work?

**Comment by vanitabarrett** [comment]
We drafted documentation in the release notes for previous changes, but have decided not to include it for 3.14.0. It feels slightly strange to be referring to changes that are nowhere to be seen in that release. It also means that if a user blindly follows semantic versioning, they’re more likely to not read release notes for fix/feature versions and they’ll miss this.

**Comment by EoinShaughnessy** [comment]
@vanitabarrett [Release notes PR](https://github.com/alphagov/govuk-frontend/pull/2369) has passed 2i. Is there anything else I should do (since we're trialling a different process)?

**Comment by vanitabarrett** [comment]
[Release notes PR](https://github.com/alphagov/govuk-frontend/pull/2374) against the `support/3.x` branch
