### ISSUE TITLE
HTML and Nunjucks tabs not descriptive when using JAWS

### ISSUE THREAD

**Issue by abbott567** [alphagov/govuk-frontend#2375]
## Description of the issue
The tabs don't contain hidden text like the other elements. 

So, when you list them in JAWS you get a list which resembles the following:
- HTML
- Nunjucks
- HTML
- Nunjucks
- HTML
- Nunjucks

Other elements have visually hidden text, so when you list the elements they still make sense for example: 
```html 
<a href=...>
  Open this <span class="govuk-visually-hidden">button </span>example in a new window
</a>
```
When you list the links with JAWS you get a list which resembles the following:
- open this button example in a new window
- open this start button example in a new window
- open this secondary button example in a new window

## Steps to reproduce the issue
Use `CTRL + INSERT + C` to list all aria-controls and combo-boxes in JAWS.

## Suggestion
Adding the same visually hidden identifier to the HTML and Nunjucks tabs so they read something like:
- HTML code example for button
- Nunjucks code example for button
- HTML code example for start button
- Nunjucks code example for start button

**Comment by abbott567** [comment]
Opened in GOV.UK Frontend by mistake. Re-opened in Design System: https://github.com/alphagov/govuk-design-system/issues/1916

**Comment by 36degrees** [comment]
Thanks @abbott567! We are able to move issues between repos, so if that happens again feel free to just add a comment and we can move it instead (nothing wrong with closing and re-opening, moving it is just slightly tidier).
