### ISSUE TITLE
Select elements have grey background in Firefox

### ISSUE THREAD

**Issue by matteason** [alphagov/govuk-frontend#2435]
## Description of the issue
In the latest Firefox release (94.0.1), `select` elements have a grey background by default. This makes them look disabled:

![image](https://user-images.githubusercontent.com/1935173/142191720-4fc81853-9000-454f-bf41-5fb8105096bb.png)

This also affects the main GOV.UK site:

![image](https://user-images.githubusercontent.com/1935173/142191617-ce27b6aa-426f-4ccc-ac6c-0d488c1d4b89.png)

I think strictly this is a Firefox issue, but from https://bugzilla.mozilla.org/show_bug.cgi?id=1715064 it sounds like they consider it an expected change.

There was a similar issue with Ubuntu a couple of years ago (https://github.com/alphagov/govuk-frontend/issues/1659). The issue was closed off because setting a background colour on `select` caused issues in Firefox if the user has changed their browser default colours, but that issue now [appears to be fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1335476#c18)

## Steps to reproduce the issue
1. Download the latest Firefox release
2. Visit https://design-system.service.gov.uk/components/select/

## Actual vs expected behaviour
I would expect the background of the select to match the background colour of the page

## Environment (where applicable)

- Operating system: Windows 10 and macOS
- Browser: Firefox
- Browser version: 94.0.1
- GOV.UK Frontend Version: 3.14.0

**Comment by matteason** [comment]
Sorry, for some reason GitHub isn't rendering the images in my initial post, but it will in comments 🤷‍♀️

Image 1:
![image](https://user-images.githubusercontent.com/1935173/142191720-4fc81853-9000-454f-bf41-5fb8105096bb.png)

Image 2:
![image](https://user-images.githubusercontent.com/1935173/142191617-ce27b6aa-426f-4ccc-ac6c-0d488c1d4b89.png)

**Comment by vanitabarrett** [comment]
A bit of testing to confirm when this was introduced:

Windows 10, Firefox 94: Grey background
Windows 10, Firefox 95 (beta): Grey background
Windows 10, Firefox 93: White background

Mac, Firefox 94: Grey background
Mac, Firefox 95 (beta): Grey background
Mac, Firefox 93: White background

**Comment by matteason** [comment]
Thanks @vanitabarrett - I was just about to say, I've reinstalled Firefox 93 on Win10 and the `select` background is white

**Comment by vanitabarrett** [comment]
Thanks for raising this @matteason . We've decided that we think this probably isn't high priority enough to be included in our next major release and given it's technically an issue with Firefox, we're hoping that by the time we revisit it after our next release there might have been some more activity in that Firefox bug report you linked to.

That's not to say we won't consider setting a background (and foreground) colour for the select to try and give us more control over the styling, but it's something that we'll need to test with other browsers and with high contrast mode first.

**Comment by danacotoran** [comment]
For the record, the select component is also displaying with a grey background and blue text on mobile Safari (screenshot from iOS 15.2.1).

<img src="https://user-images.githubusercontent.com/7116819/151769633-4b724119-d752-40c2-a064-f72032467ca4.png" width="400">

The colour contrast between the text and background colour seems insufficient.

**Comment by vanitabarrett** [comment]
Thanks @matteason and @danacotoran for raising these issues - we've implemented a fix which should be released in the next version of GOV.UK Frontend. I'm also going to write up a ticket to report the issue in Safari, as it applies to the default select dropdown (i.e: it's not specific to the GOV.UK Frontend select).
