### ISSUE TITLE
Incorrect content width on summary list rows when not all rows have actions

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk-frontend#2495]
## Description of the issue

When using the summary-list nunjucks macro, when some rows have actions and some do not, the width given to the values in the row becomes too thin. This is most notable when using long content.

If all rows have actions the content has the correct width.

This commit could be the culprit: https://github.com/alphagov/govuk-frontend/pull/2323/commits/29358635a77efa5a81b923ad644e42bc8481ce45

| v3.14 | v4.0 | v4.0 with just one row |
|--|--|--|
|![v3 14 0](https://user-images.githubusercontent.com/319055/149177626-8aa70652-9ec2-4d99-a44d-508500882092.png) | ![v4 0 0](https://user-images.githubusercontent.com/319055/149177639-962c8cb5-11eb-4232-8c6a-910babe71619.png) | ![v4 0 0-no-other-rows](https://user-images.githubusercontent.com/319055/149177635-d4383dca-f89e-4b6e-9db1-055f728df292.png)

| v4 | If I add width 50% to the container |
|--|--|
| ![Screenshot 2022-01-12 at 16 05 13](https://user-images.githubusercontent.com/319055/149178373-a8b28576-f0c8-4d9e-a10c-de26c541b43a.png) | ![Screenshot 2022-01-12 at 16 05 07](https://user-images.githubusercontent.com/319055/149178380-d19886ce-3eee-48ee-883f-a68139512922.png) |

### Design system examples

This bug is visible on the design system examples too (https://design-system.service.gov.uk/components/summary-list/#adding-actions-to-each-row) – look at the two contact details rows:

![Screenshot 2022-01-12 at 16 18 57](https://user-images.githubusercontent.com/319055/149179346-916f0bea-194c-4556-88f2-2e5d042d0634.png)

## Steps to reproduce the issue
See design system example

## Actual vs expected behaviour
Expected content to remain the same width

## Environment (where applicable)
- Operating system: Mac
- Browser: Chrome
- Browser version: 96
- GOV.UK Frontend Version: 4.0.0

**Comment by 36degrees** [comment]
This seems to happen specifically if the first row does not have actions, at least in Chrome.

Setting `width: 20%` on `.govuk-summary-list__row--no-actions:after` seems to fix it – though we also probably only need the pseudo-element at all on tablet and above.
