### ISSUE TITLE
Duplicated JavaScript code across components

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2501]
### Cause

Some of our components have very similar/the same JavaScript functionality. A recent example is when we copied some of the error summary JavaScript to add to the Skip Link component (https://github.com/alphagov/govuk-frontend/pull/2450/commits/291066469f248b696d26e6baea02ff5f76e17e93).

### Consequences

There are some positives and negatives of this.

Negatives:

- If we want to change the way a function works or fix a bug, we might make the change in one place and forget to make it in the other places it's been copied to
- It's a slight maintenance overhead
- Slight performance implications
- Causes some visibility issues - it's not clear where functions have been implemented/used before, so sometimes we end up building things from scratch without realising one component already does it

Positives:

- We have 3 times as much CSS as JavaScript at the moment, so it's not a big performance issue
- Makes it easier for us to judge the result of any changes to these functions because we know exactly where they're being used

### Impact of debt

Low

### Effort to pay down

Low

### Reason (effort to pay down)

We think we'd want to have more confidence in our JavaScript testing strategy before making these changes. Sharing functions between components means we might be more likely to introduce unintended changes to component behaviour without realising. We should make sure our testing coverage is good enough to pick up on these.

### Overall rating

Low

**Comment by colinrotherham** [comment]
We only really have had big duplicated things:

1. Different `getFragmentFromUrl()` implementations across **Error summary**, **Skip link** and **Tabs**
2. Different `setFocus()` implementations across **Error summary**, **Notification banner**, **Skip link**

We fixed 1) in https://github.com/alphagov/govuk-frontend/pull/4320 and I'll open quick PR for 2)
