### ISSUE TITLE
Update Node.js to active LTS version

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-frontend#2504]
## What

Update the project to use the latest active Long Term Support (LTS) version of Node.js for development, testing, and deployment.

## Why

This project currently uses Node.js version 14, which has been in maintenance since last October (2021-10-19) and won't receive new features.

## Who needs to work on this

Developer

## Who needs to review this

Developer, Tech lead

## Done when

- [ ] Update `.nvmrc`
- [ ] Update `package-lock.json` to use lockfile v2

**Comment by domoscargin** [comment]
We've encountered some issues with this change on Mac M1 devices. They appear to related to `node-sass`, which we use in our tests and with `gulp-sass`.

`gulp-sass` will not support M1 chips with the `node-sass` compiler.

We've managed to get this working on M1 machines by deleting `node_modules`, then running:

```
nvm use
npm uninstall node-sass -g && npm cache clean -force && npm install node-sass
nvm use
npm install
```

Current theories are that the issue might be related to installing with Node v14, then installing this change, and something going awry in the switch. We're going to test installing straight from this branch and see if a clean install works.

We're then going to decide whether:

* We stick to Node 14 for a while
* We push the Node 16 update and document these steps for devs to troubleshoot any issues
* We look at switching to `dart-sass`

**Comment by jpveooys** [comment]
Did you try `npm rebuild` after swapping out the Node.js version out of interest?

**Comment by domoscargin** [comment]
> Did you try `npm rebuild` after swapping out the Node.js version out of interest?

We did, but no luck.

**Comment by querkmachine** [comment]
As a little after-the-fact question: Given there's some faff involved in updating from v12 to v16, would it be useful to add that as something in the changelog/release notes?

**Comment by domoscargin** [comment]
@querkmachine Are there general issues with updating from v12 to v16?

**Comment by querkmachine** [comment]
@domoscargin I meant v14, sorry.

**Comment by domoscargin** [comment]
Ah, right!

I'd lean towards not including something in the release notes, since this shouldn't affect anybody but devs/contributors.

But maybe something in the changelog with a "only for contributors" type warning?
