### ISSUE TITLE
Create release notes for GOV.UK Frontend v4.0.1 (fix release)

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2508]
## What
Create release notes for GOV.UK Frontend v4.0.1 (fix release)

## Why
To tell users about the fixes we've made.

## Who needs to work on this
Technical Writer, Developers

## Who needs to review this
Developers

## Done when

- [x] Technical writer / developer drafts release notes
- [x] Release notes pass 2i
- [ ] PR raised for updating the release notes in the Changelog

**Comment by domoscargin** [comment]
We haven't added this change to the CHANGELOG, but we should thank the contributor in our release notes.

#2516

**Comment by EoinShaughnessy** [comment]
Draft doc to share with pre-i and 2i reviewers (thought it might be easier to review than a PR): 
https://docs.google.com/document/d/1ag3bi-4z-QdR3nYxYNUq-8G6Sbd-_sQ3cW03e7CC410/edit#

**Comment by EoinShaughnessy** [comment]
Release notes have passed pre-i, so I've now sent them for 2i.

**Comment by EoinShaughnessy** [comment]
@domoscargin Thanks for flagging this! I think we're going to thank them in the Slack comms and possibly also the Mailchimp sendout.

**Comment by EoinShaughnessy** [comment]
We've done everything on the 'Done when' checklist. Should we now move this issue to the 'Done' column on our Kanban? Or should we hold off till we've actually put the release name at the top of the notes and published them?

**Comment by vanitabarrett** [comment]
@EoinShaughnessy I'm trying a slightly different way of structuring our release epics this time, so this card doesn't need to hang around while we wait to do the release. The release documentation instructs us to add the release name at the top of the notes, so that'll be covered when we do the release. So if you're happy, I suggest we move this to done?

**Comment by EoinShaughnessy** [comment]
@vanitabarrett Ah cool, gotcha. Over to 'Done' it goes!
