### ISSUE TITLE
Write and share a proposal for our browser support

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2519]
## What
We should write up our findings and decisions into a proposal of some sort. 

## Why
The proposal lets us collect all our research findings, decisions and future planning into one place. This gives us something to share among GDS (e.g: the frontend community) and also outside of GDS, e.g: the x-gov community, to see if our approach will work for them.

## Who needs to work on this
Developers; Tech Writer

## Who needs to review this
Developers; Tech Writer; Frontend Community; X-Gov Community

## Done when

- [x] Draft a proposal in [the draft document](https://docs.google.com/document/d/1WVmLETSWiBgFqrrMWoHNSmBeCHqTosINE7lM69i8-9g/edit#). Consider what impact these changes will have on our codebase/users
- [x] Draft an email and Slack message for sharing the proposal
- [x] Copy the proposal into a new document (to avoid noise on the original doc) and allow people to comment
- [x] Update feedback date in proposal doc 
- [x] Share proposal with the GDS Frontend community (core-frontend mailing list)
- [x] Review feedback from GDS Frontend community
- [x] Reply to comments from GDS Frontend community
- [x] Decide format for sharing proposal with x-gov, e.g: Github discussion, entry in Github architecture repo
- [x] Share proposal with wider x-gov community to gather feedback
- [x] Write any follow-up cards (see below)

If it looks like the proposal will be accepted, we should write cards to implement/decide the following:

- [x] Card to figure out documentation for v4 (design system AND frontend docs)
- [x] Card for ensuring our support branch release process works for previous major versions (existing card)
- [x] Card for revisiting v4 support in 12 (?) months and either extending the time limit or ending support then
- [x] Any other cards for actually doing this work and reducing the support to functional (e.g: updating Github READMEs, removing polyfills, stop serving JS to IE etc)
- [x] Removing the IE8 stylesheet
- [x] Updating govuk-frontend docs (e.g: README, accessibility/browser testing) with new browser support level, referencing v4 and what we mean by 'functional'
- [x] Drafting answers for potential questions we might get on support

**Comment by vanitabarrett** [comment]
Resource that may be helpful for drafting a proposal: https://technology.blog.gov.uk/2018/06/26/changing-our-testing-requirements-for-internet-explorer-8-9-and-10/

**Comment by vanitabarrett** [comment]
Matt has suggested that we should include something in comms on this change to say that it doesn't mean GOV.UK (or in our case, GOV.UK Frontend / the Design System) will stop working in older browsers. See https://docs.google.com/presentation/d/1L93j8m4L2R2QU87FrKcMSrNzyD1fi3FSMzEGCfTRTvs/edit#slide=id.g1132d02f0e8_0_176

**Comment by EoinShaughnessy** [comment]
@vanitabarrett Should this proposal have a similar structure to our [test fixtures](https://docs.google.com/document/d/10YEYal0yWZcLBNT_4f2XDFHdl-m7z_qKKhHsmXhp7hE/edit?pli=1) and [import removal](https://docs.google.com/document/d/1Qa7VNuBk81MxbweefT0XrIErKTUKFw6PbUvysY0ae7I/edit) proposals?

**Comment by vanitabarrett** [comment]
@EoinShaughnessy I think it probably makes sense to use that at least for a starting point - we can change it if we find the structure doesn't work well for us this time.

**Comment by vanitabarrett** [comment]
The proposal is ready to go now. The next steps are to copy the proposal into a new doc to avoid comments generating noise on the original doc (if we think that's helpful), and draft and email/Slack message to share it with the core-frontend mailing list. I've added those as checklist items to this card.

**Comment by EoinShaughnessy** [comment]
Have shared draft proposal with GDS frontend channel and core-frontend mailing list.

**Comment by EoinShaughnessy** [comment]
I've posted another reminder into the frontend channel on GDS channel.

**Comment by vanitabarrett** [comment]
The JavaScript squad had a catch-up today and we looked through the comments we've received from the FE devs. We think we probably need to pin down some of the details to our approach before we send this out to the wider community. I've written up a card for that here: https://github.com/alphagov/govuk-frontend/issues/2579

For now, I'm going to put this into Blocked

**Comment by vanitabarrett** [comment]
@querkmachine should we move this into Blocked while the proposal is out to GDS developers?

**Comment by querkmachine** [comment]
@vanitabarrett Can do. Makes sense from a tracking perspective, if not a labelling one—it's still "in progress", just with third-parties.

**Comment by querkmachine** [comment]
Moved back to in progress as the proposal is being prepared for sharing with the wider community.

**Comment by querkmachine** [comment]
The proposal is now open for public and cross-government feedback: https://github.com/alphagov/govuk-frontend/discussions/2607

**Comment by vanitabarrett** [comment]
Moving into Blocked until 13th May (the deadline for feedback)
