### ISSUE TITLE
Audit our component JavaScript and ensure it meets our new JavaScript conventions

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2560]
## What
Audit our existing component JavaScript to ensure it meets our new JavaScript conventions, as decided in https://github.com/alphagov/govuk-frontend/issues/1720

## Why
We're going to document our JavaScript conventions, so we should make sure our component JavaScript meets that! This should be done alongside/shortly after https://github.com/alphagov/govuk-frontend/issues/1721 so there isn't a big delay between documenting our conventions and actually applying them.

## Who needs to work on this
Developers

## Who needs to review this
Developers

## Done when

- [ ] We've audited our current component JavaScript and know where improvements need to be made to match our conventions
- [ ] We've updated our component JavaScript code to match conventions (or, if the work is large and can be worked on in parallel by developers, we've written new tickets to tackle the issues we've spotted)

**Comment by 36degrees** [comment]
I don't think this is relevant any more – there's work to do to improve the JavaScript for our components but I think it's covered by other issues and we'll start to refactor components as we touch them for other improvements.
