### ISSUE TITLE
Publish documentation for our component JavaScript API

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2564]
## What
In https://github.com/alphagov/govuk-frontend/issues/2563 we decided where and how we would document our public JavaScript API for users. This card covers actually writing that documentation and publishing it on the platform/pages we agreed.

## Why
So users are informed about what JavaScript methods are available to them, when they might need to use them and why.
We should make sure this information is easily discoverable rather than relying on users digging into our code on Github to find out more.

## Who needs to work on this
Tech Writer; Developer

## Who needs to review this
Developers

## Done when

- [ ] Audit our component JavaScript to decide what needs documenting for each component
- [ ] Draft documentation
- [ ] Draft is reviewed by tech writer and developers
- [ ] PR is raised to add documentation to [the agreed place](https://github.com/alphagov/govuk-frontend/issues/2563)
- [ ] Decide if we want to do any research with the documentation before publishing it?
- [ ] Published

**Comment by 36degrees** [comment]
Closing as we're now publishing our [JavaScript API Reference](https://frontend.design-system.service.gov.uk/javascript-api-reference/) as part of the frontend docs
