### ISSUE TITLE
Draft comms for v4.1.0

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2594]
## What
Draft comms for the next release (v4.1.0)

## Why
So that users know what is included in v4.1.0 and want to update.

## How

- [x] Draft a PR to update the 'What's new' section on the Design System homepage
- [x] Raise a PR to update the [Design System roadmap](https://design-system.service.gov.uk/community/roadmap/) - add the release to the 'Recently Shipped' column **and** move the character count fix work
- [x] Draft Slack messages for [#govuk-design-system on GDS](https://gds.slack.com/archives/CAF8JA25U), [#govuk-design-system on x-gov](https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6) and [#design on x-gov](https://ukgovernmentdigital.slack.com/archives/C062GAGLW)
- [x] Draft an email to send to the mailing list 

## Who needs to know about this
Developers; Content Design; Tech Writer

## Done when

- [x] Comms approach and key messages planned with team members involved
- [x] Made sure to thank any contributors for this release
- [x] Comms drafted
- [x] Feedback gathered from team members involved
- [x] 2i'ed and approved with any subject matter experts

**Note: this card can be moved to Done once the comms is drafted and has been approved by the team. There will be a separate card to actually post the comms**

**Comment by EoinShaughnessy** [comment]
Google Doc for release comms: https://docs.google.com/document/d/1Bgu5HYklc28TVH6pxL_XQtf3Sz1eaGOZv-pbH2e3Tpc/edit#heading=h.aq509akj0nmt

Just has a draft 'What's New' message in it so far.

**Comment by EoinShaughnessy** [comment]
Have also drafted email and Slack messages: https://docs.google.com/document/d/1Bgu5HYklc28TVH6pxL_XQtf3Sz1eaGOZv-pbH2e3Tpc/edit#heading=h.pxrmyv72tuw0

**Comment by vanitabarrett** [comment]
Created a draft PR here for the "What's New" message and the roadmap updates: https://github.com/alphagov/govuk-design-system/pull/2185
