### ISSUE TITLE
Create release notes for v4.1.0

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2595]
## What
Write the release notes for GOV.UK Frontend v4.1.0

## Why
To help users understand what changes have been made in the 4.1.0 release.

## Who needs to work on this
Tech Writer; Developers

## Who needs to review this
Developers; Tech Writer + 2i

## Done when

This will be done when the release notes:

- [x] have been drafted
- [x]  have been reviewed by a developer
- [x] have been 2i'ed

**Comment by EoinShaughnessy** [comment]
Google Doc for sharing with 2i reviewers: https://docs.google.com/document/d/1exhsKsmsk_6HkybbNKIEokkFWShybFKXYe2_9WWToEU/edit#

**Comment by EoinShaughnessy** [comment]
Have shared [draft](https://docs.google.com/document/d/1exhsKsmsk_6HkybbNKIEokkFWShybFKXYe2_9WWToEU/edit#) with pre-i reviewer.

**Comment by EoinShaughnessy** [comment]
Release notes have passed pre-i. I've now sent them for 2i.

**Comment by EoinShaughnessy** [comment]
Release notes have passed 2i. Have raised PR containing recommended changes: https://github.com/alphagov/govuk-frontend/pull/2624

**Comment by EoinShaughnessy** [comment]
Have merged #2624.
