### ISSUE TITLE
Remove any IE8-10 specific styles and stylesheet(s)

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2622]
## What
Remove any IE8 specific styles, as we're dropping support for IE in a future breaking release.

## Why
We have decided to reduce support for IE11 in GOV.UK Frontend and drop support completely for IE8-10. We [shared these proposed changes](https://github.com/alphagov/govuk-frontend/discussions/2607) with the frontend community in GDS and across government, and have only received positive feedback.

We will make these changes in a future breaking release of GOV.UK Frontend (likely v5.0.0).

## Who needs to work on this
Developers; possibly Tech Writer

## Who needs to review this
Developers

## Done when

- [x] Remove any IE8-10 specific styles/stylesheets
- [ ] Update/remove any associated documentation

**Comment by querkmachine** [comment]
We've decided to handle the docs changes after all of the IE removals have taken place, rather than doing them piecemeal, so I'm closing this as done.

**Comment by romaricpascal** [comment]
For refrerence, the documentation updates are tracked by: https://github.com/alphagov/govuk-frontend-docs/issues/188 😊
