### ISSUE TITLE
Update how we load JavaScript in browser

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2639]
## What

We're updating how browsers should load our JavaScript to ensure it only runs in browsers that are actually capable of executing it, letting older browsers show our components in their non-JavaScript state. 

This involves:

- `govuk-frontend` providing code that can be parsed in any browser supporting `<script type="module">`
- recommending to use `<script type="module">` to avoid scripts being downloaded in older browsers

## Why
We have decided to reduce support for IE11 in GOV.UK Frontend and drop support completely for IE8-10. We [shared these proposed changes](https://github.com/alphagov/govuk-frontend/discussions/2607) with the frontend community in GDS and across government, and have only received positive feedback.

As part of this proposal, we said we would stop shipping JavaScript to IE browsers. These browsers will fall back to a no-JavaScript experience.

## Who needs to work on this
Developers; Tech Writer

## Who needs to review this
Developers

## Done when

```[tasklist]
### Update JavaScript loading
- [x] Define new strategy for JavaScript loading
- [ ] https://github.com/alphagov/govuk-frontend/issues/3721
- [ ] https://github.com/alphagov/govuk-frontend/issues/3482
- [ ] https://github.com/alphagov/govuk-frontend/issues/3504
- [ ] https://github.com/alphagov/govuk-frontend/issues/3508
- [ ] https://github.com/alphagov/govuk-frontend/issues/3509
- [ ] https://github.com/alphagov/govuk-frontend/issues/3507
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/308
- [ ] https://github.com/alphagov/govuk-design-system-architecture/issues/27
- [ ] https://github.com/alphagov/govuk-design-system-architecture/issues/26
```

**Comment by colinrotherham** [comment]
Was going to add https://github.com/alphagov/govuk-frontend/issues/2639 but that's also done

Can mark this as closed too 🎉
