### ISSUE TITLE
4.1.0 breaks require.resolve to find all.js client javascript

### ISSUE THREAD

**Issue by HughePaul** [alphagov/govuk-frontend#2643]
## Description of the issue
The new export block in the package.json breaks the ability to look for the main module using `require.resolve`

This should probably look more like:
```
  "exports": {
    "require": "./govuk/all.js",
    "import": "./govuk-esm/all.mjs"
  },
```
## Steps to reproduce the issue
```
require.resolve('govuk-frontend');
```

```
node:internal/modules/cjs/loader:488
      throw e;
      ^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ./node_modules/govuk-frontend/package.json
    at new NodeError (node:internal/errors:371:5)
```

## Actual vs expected behaviour
Returns full path location of all.js compiled client javascript

## Environment (where applicable)

- Operating system: ubunu 18.04
- Browser: N/A
- Browser version: N/A
- GOV.UK Frontend Version: 4.1.0
- NodeJS Verson: 16.x.x

**Comment by 36degrees** [comment]
@HughePaul you mention `app.js` in the issue title and in the actual vs expected behaviour section, but `app.js` is part of the tooling in the repo and is not published as part of the package. Just to double check, I'm assuming you meant `all.js` – is that correct?

**Comment by HughePaul** [comment]
yes that branch works as expected, eg:

```
$ node -e 'console.log(path.relative(".", require.resolve("govuk-frontend")))'
node_modules/govuk-frontend/govuk/all.js
```
