### ISSUE TITLE
4.1.0 Breaks the ability to import scss files with webpack sass-loader

### ISSUE THREAD

**Issue by Garethp** [alphagov/govuk-frontend#2645]
## Description of the issue
With 4.1.0 introducing the `exports` key into package.json it breaks the ability for `sass-loader` to resolve calls such as `@import 'govuk-frontend/govuk/base.scss';` or `@import 'govuk-frontend';` because the scss files are no longer exported.

## Steps to reproduce the issue
Pacakges:
```js
{
    "sass-loader": "13.0.0",
    "webpack": "^5.72.1",
    "webpack-cli": "^4.9.2",
    "sass": "^1.52.1",
}
```

Use Webpack with sass-loader as such: 
```js
          {
            loader: "sass-loader",
            options: {
              sourceMap: true,
              sassOptions: {
                includePaths: ["node_modules"],
              },
            },
          },
```

Have it process a scss file looking like this:

```scss
@import "govuk-frontend/govuk/base.scss";
```

Observe the following error:

```
ERROR in ./src/css/index.scss
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
3 │ @import "govuk-frontend/govuk/base.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/css/index.scss 3:9  root stylesheet
```

## Actual vs expected behaviour
At the moment it simply throws an error because the scss files aren't being exported, in `4.0.1` and previous it succeeded without any issue. Especially considering that 4.1.0 was a minor update and not a major update, it shouldn't throw an error when trying to import using sass-loader

**Comment by RossMcMillan92** [comment]
This can be recreated by generating a new react app with create-react-app.

I have tried both of the following and neither work.

```scss
@import 'govuk-frontend/govuk/all.scss';
```

```scss
@import 'govuk-frontend';
```

This does work:
```scss
@import 'node_modules/govuk-frontend/govuk/all.scss';
```

However, including "node_modules" in the path may not work correctly in monorepos as there may be no consistent node_modules folder.

**Comment by vanitabarrett** [comment]
@Garethp Thank you for raising this issue. We've raised a PR with the suggested fix and tested to the best of our ability, but wondered if you'd be interested in helping test that this fix solves the issue for you?

You can test this by installing our pre-release:

`npm install --save "alphagov/govuk-frontend#6be3da17"`

cc @RossMcMillan92 @richpjames this may also be of interest to you. Any help testing this out would be greatly appreciated! 🙏

**Comment by richpjames** [comment]
@vanitabarrett that prerelease seems to have fixed the issue we were having - thanks!

**Comment by Garethp** [comment]
That solves the issue for me! Thanks for the quick fix
