### ISSUE TITLE
Create release notes for v4.2.0

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2662]
## What
Write the release notes for GOV.UK Frontend v4.2.0

## Why
To help users understand what changes have been made in the 4.2.0 release.

## Who needs to work on this
Tech Writer; Developers

## Who needs to review this
Developers; Tech Writer + 2i

## Done when

This will be done when the release notes:

- [x] have been drafted
- [x] Made sure to thank any contributors for this release - we should thank the people who raised the ESM issues and help us test pre-releases:
    - [x] https://github.com/alphagov/govuk-frontend/issues/2645
    - [x] https://github.com/alphagov/govuk-frontend/issues/2643
    - [x] https://github.com/alphagov/govuk-frontend/issues/2633
- [x] have been reviewed by a developer
- [x] have been 2i'ed

**Comment by vanitabarrett** [comment]
Release notes draft doc here: https://docs.google.com/document/d/1rqBb9vxm7pqycdlCbNwXwKSbfC5SAIjAmeVRhwI-SUQ/edit#
