### ISSUE TITLE
govukRadios and govukCheckboxes macro option "value" not working

### ISSUE THREAD

**Issue by NikhilNanjappa** [alphagov/govuk-frontend#2691]
## Description of the issue

Components like [govukRadios](https://design-system.service.gov.uk/components/radios/), [govukCheckboxes](https://design-system.service.gov.uk/components/checkboxes/) have a macro option named `value`, `values` respectively. These options when passed is supposed to mimic the `checked` behaviour by pre-selecting the provided option. However, this does not happen. Looked at the source code as well and it seems like the `params.value` is not being used at all which could explain why it does not work as intended.

## Steps to reproduce the issue

```
{% from "govuk/components/radios/macro.njk" import govukRadios %}

{{ govukRadios({
  idPrefix: "where-do-you-live",
  name: "where-do-you-live",
  value: "england",      <-- should check "england" option but doesnt
  items: [
    { value: "england", text: "England" },
    { value: "scotland", text: "Scotland" }
  ]
}) }}
```

## Actual vs expected behaviour

**Actual:**
`value` macro option of govukRadios does **not** pre-select the provided option.
`values` macro option of govukCheckboxes does **not** pre-select the provided option(s).

**Expected:**
`value` macro option of govukRadios should pre-select the provided option.
`values` macro option of govukCheckboxes should pre-select the provided option(s).

## Environment (where applicable)

- Operating system: MacOS Monterey v12.4
- Browser: Chrome
- Browser version: Version 103.0.5060.114 (Official Build) (x86_64)
- GOV.UK Frontend Version: 3.14.0 (npm)

**Comment by querkmachine** [comment]
If upgrading isn't possible at this time, you can set the current option using the `checked` parameter. 

To use your example, you would set `checked: true` on the 'england' option:

```nunjucks
{% from "govuk/components/radios/macro.njk" import govukRadios %}

{{ govukRadios({
  idPrefix: "where-do-you-live",
  name: "where-do-you-live",
  items: [
    { value: "england", text: "England", checked: true },
    { value: "scotland", text: "Scotland" }
  ]
}) }}
```

**Comment by NikhilNanjappa** [comment]
@36degrees @querkmachine - are there any breaking changes upgrading from 3.14.0 to 4.2.0 ?

**Comment by querkmachine** [comment]
@NikhilNanjappa There are, you can find a list of breaking changes on [the 4.0.0 release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.0).

You can find a list of non-breaking changes from other interim releases on [the releases page](https://github.com/alphagov/govuk-frontend/releases).

**Comment by NikhilNanjappa** [comment]
Thanks @querkmachine - Upgraded to `4.2.0` and since I only use macros, there were hardly any changes!

**Comment by NikhilNanjappa** [comment]
Closing as I was using `3.8.0` and this feature was introduced in `4.2.0`
