### ISSUE TITLE
Accordion content.text doesn't render with the right font

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#2703]
## Related component

Accordion

I wasn't sure if this is a bug or a feature request!

If you use the `content.text` option in accordion, the text doesn't look right - it doesn't use the normal gov.uk typography. As such, I'm not sure if `content.text` is useful? I think you'd have to add your own css to style it.

Maybe `content.text` could be wrapped in `<p class="govuk-body">` by default?

**Comment by vanitabarrett** [comment]
Agree that doesn't seem right. I'm surprised it's not been raised as an issue before now, but maybe a lot of people use the `html` option instead!

**Comment by querkmachine** [comment]
Note: This is also the case if when using `text` in the tabs component's panels.
