### ISSUE TITLE
Refactor linting tasks to remove Gulp

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2710]
## What
Update `tasks/gulp/lint.js` to replace Gulp with our own lint scripts. There are two tasks in this file, one to lint SCSS and one to lint JS. Note that we currently [spawn a process to run the linting tasks](https://github.com/alphagov/govuk-frontend/pull/2512). We could probably tidy this up a bit.

## Why
We have [made the decision to move away from Gulp](https://github.com/alphagov/govuk-frontend/issues/2558) and write our own build scripts.

## Who needs to work on this
Developers

## Who needs to review this
Developers

## Done when

- [x] tasks/gulp/lint.js no longer sdepends on Gulp
- [x] `standard` and `stylelint` are as up to date as feasible
- [x] docs/contributing/tasks.md has been updated
- [x] NPM scripts `lint`, `lint:js` and `lint:scss` work correctly
- [ ] ~lint.js has been relocated to tasks folder~

**Comment by colinrotherham** [comment]
I've struck off the last "Done when" task as we no longer need a separate **lint.js** file for `'lint:scss'`

We have a new task helper `npmScriptTask()` which calls npm scripts directly:

```mjs
/**
 * Umbrella styles tasks (for watch)
 * Runs Sass code quality checks and compilation
 */
gulp.task('styles', gulp.series(
  npmScriptTask('lint:scss', ['--silent']),
  'scss:compile'
))
```

**Comment by colinrotherham** [comment]
I've unintentionally done three of the tasks (sorry) so I'll assign myself to this one

**Comment by colinrotherham** [comment]
✅ All our `stylelint` and `standard` packages are up to date too

There's one more related change so I've opened https://github.com/alphagov/govuk-frontend/pull/2916
