### ISSUE TITLE
Refactor file copying tasks to remove Gulp

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2711]
## What
Update `tasks/gulp/copy-to-destination.js` to replace Gulp with our own file copying script. There are currently two tasks in this file, one for copying source files to a destination, and one for copying the ESM source files to a destination.

## Why
We have [made the decision to move away from Gulp](https://github.com/alphagov/govuk-frontend/issues/2558) and write our own build scripts.

## Who needs to work on this
Developers

## Who needs to review this
Developers

## Done when

- [x] tasks/gulp/copy-to-destination.js no longer depends on Gulp
- [x] `heroku` and `test` npm scripts no longer rely on `taskArguments.destination`
- [x] file copying tasks no longer rely on `taskArguments.destination`
- [x] docs/contributing/tasks.md has been updated
- [x] All dependencies are as up to date as is feasible
- [x] copy-to-destination.js has been relocated to tasks/copy-to-destination.js (or similar)

**Comment by colinrotherham** [comment]
Accidentally completed in: https://github.com/alphagov/govuk-frontend/commit/2051717b9c2341f5502e42cfd06abd0c0b021e63
