### ISSUE TITLE
Update our browser support strategy

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#2718]
## What

We're looking to move to a graded system for defining the support received by the different browsers out there. This system will define not only in which browsers features run, but also the level of testing we intend to do with them and the priority we'll give to bugs.

## Why

Currently Frontend uses specific versions of particular browsers to determine the minimum level of browser support and what polyfills/prefixes are needed: principally Internet Explorer 8 and Safari 9, which indirectly provide support for older versions of 'evergreen' browsers. 

As we transition into reducing support for IE11, and dropping all supporting for IE8–10, we want to reassess how we decide how our minimum level of browser support will work in a world where we only (or mainly) support evergreen browsers. 

## Who needs to work on this

Developers, content designers

## Who needs to review this

Developers, content designers

## Done when

```[tasklist]
- [x] #3227
- [x] #3292
- [ ] https://github.com/alphagov/govuk-frontend/issues/3511
- [ ] https://github.com/alphagov/govuk-frontend/issues/2623
```

**Comment by querkmachine** [comment]
I started [writing a document](https://docs.google.com/document/d/11k6gPEj_NFC0bhzvkQdWAJz7Rbt-cvRvPMXpMBIuCng/edit?usp=sharing) (internal only) positing various methods that we could determine future browser support.

**Comment by stevenjmesser** [comment]
We've unpacked the work needed to come to a decision on future browser support. It's kept in a Trello board which isn't open, but we'll add discrete actions to the team board.

First 3 actions:
[] For each JavaScript component, document all possible levels of progressive enhancement (by browser support)
[] Spike ways of cutting the mustard (e.g. guarding everything with a feature check)
[] Sketch out alternative browser support tables

**Comment by 36degrees** [comment]
Main things left to do:

- Understand how browser support applies to CSS
- Review the existing draft and see if we can simplify it at all – see if rationale can be split out into a decision record / the PR
- Move browser support details from README to frontend docs and update

**Comment by romaricpascal** [comment]
README details are within the [Browser and assistive technology support section](https://github.com/alphagov/govuk-frontend#browser-and-assistive-technology-support)


> GOV.UK Frontend supports:
>
> -    [recommended browsers](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in) and Internet Explorer 11
> -    [recommended assistive technologies](https://www.gov.uk/service-manual/technology/testing-with-assistive-technologies#which-assistive-technologies-to-test-with)
> -    Internet Explorer 8, 9 and 10, although components may not look perfect
> -    your users overriding colours in Windows, Firefox and Chrome

**Comment by 36degrees** [comment]
Gonna call this done!
