### ISSUE TITLE
Unable to switch between tabs component. 

### ISSUE THREAD

**Issue by ramsharma-prog** [alphagov/govuk-frontend#2722]
## Issue
> We are unable to switch between tabs when html or nunjucks code copied over to IDE. Could see the the url switching from one tab to another but the UI tab does not switch. 

Code:

<div class="govuk-tabs govuk-body" data-module="govuk-tabs">

    <h2 class="govuk-tabs__title">
        Contents
    </h2>

    <ul class="govuk-tabs__list">
        <li class="govuk-tabs__list-item govuk-tabs__list-item--selected">
            <a class="govuk-tabs__tab" href="#{{titles}}">
                Comment summary</a>
        </li>

        <li class="govuk-tabs__list-item">
            <a class="govuk-tabs__tab" href="#{{criteria}}">
                Assessment criteria </a>
        </li>
    </ul>

    <div class="govuk-tabs__panel" id="{{titles}}">
        {% for title  in titles %}
        <h2 class="govuk-heading-m govuk-!-margin-top-5 comment-heading">{{ title['section_name'] }}</h2>

        <div class="grey-background padding-all">
            <a class="govuk-link--no-underline govuk-link--no-visited-state" href="">
                Add a comment </a>
        </div>
        {% endfor %}
    </div>

    <div class="govuk-tabs__panel govuk-tabs__panel--hidden" id="{{criteria}}">
        <h2 class="govuk-heading-l">{{criteria}}</h2>
    </div>

</div>

**Comment by ramsharma-prog** [comment]
Hi @querkmachine The code was amended  from tabs component's  HTML to use for a service however if I copy& paste the  raw HTML from tabs component, it still doesn't not switch between the tabs unless I am missing something? Normally components work as it is when the raw HTML is copied over to an IDE.

**Comment by querkmachine** [comment]
Is the JavaScript module for the tabs component being loaded? 
https://frontend.design-system.service.gov.uk/get-started/#5-get-the-javascript-working

**Comment by ramsharma-prog** [comment]
@querkmachine  Following code:

    <script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>
  <script nonce="{{ csp_nonce() }}" src="{{ url_for('static', filename='govuk-frontend/govuk-frontend-4.0.0.min.js') }}"> </script>
  <script nonce="{{ csp_nonce() }}">
    window.addEventListener('load', (event) => {
        window.GOVUKFrontend.initAll();
        AssessFrontend.initAll();
    });
  </script>

**Comment by ramsharma-prog** [comment]
@querkmachine There was an error in the code. It's working  now! 
Appreciate your response & help!
