### ISSUE TITLE
Summarise approach and decisions for internationalisation in the Design System backlog 

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2749]
## What
Write up a summary of our final approach for internationalisation and why we decided to follow that approach. Might also be a good opportunity to talk about the other things we tried and explain why those don't work. Also anything we've decided not to do (e.g: because it's not part of our MVP solution; because it's out of scope).

## Why
We should try and be transparent about the decisions we make, to help people understand why we've done things a certain way. 
This may also help as somewhere to refer people to if we get questions on support.

## Who needs to work on this
Content, Developer

## Who needs to review this
Content, Developer

## Done when

- [ ] On Github, add backlog comment in backlog, e.g https://github.com/alphagov/govuk-design-system-backlog/issues/99

**Comment by kellylee-gds** [comment]
From mid-sprint review:
- Look through Google Drive for relevant documentation related to i18n. Pull information from docs we think will be useful to users
- Check whether we have guidance in internal docs about how to translate components (if not, this feels like it's own card tbh)
- Use decision summaries published previously as a template for recording this information (like [Cookie Banner](https://github.com/alphagov/govuk-design-system-backlog/issues/12#issuecomment-845097722))

@claireashworth

**Comment by kellylee-gds** [comment]
This reads really well to me, thanks for sharing @claireashworth. @romaricpascal please can you also review.

**Comment by romaricpascal** [comment]
That was some thorough gathering of all the I18n related issues! Cheers @claireashworth! Added a couple of comments on the doc so we can clarify a few things and then we should be in a good place.

**Comment by 36degrees** [comment]
I think the backlog issue makes as much sense as anywhere.

I have added a few (hopefully minor!) comments to the Google Doc, but generally think it's looking really good. Thanks for doing all the hard work to pull all of that together, @claireashworth! 🙌🏻

**Comment by claireashworth** [comment]
Comments completed and summary published on #99 'Supporting multiple languages'.
