### ISSUE TITLE
Update documentation on tasks

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2772]
## What
Update `docs/contributing/tasks.md` and `docs/contributing/coding-standards` to remove references to `gulp`, and bring the descriptions of tasks up to date.

## Why
We have [made the decision to move away from Gulp](https://github.com/alphagov/govuk-frontend/issues/2558) and write our own build scripts.

Some of our guidance is already slightly out of sync with our current tasks, and will get more out of sync as we remove gulp from our tooling.

(There's a separate issue of how we prevent this guidance from getting out of sync in the future...)

## Who needs to work on this
Developer, Technical Writer

## Who needs to review this
Developer, Technical Writer

## Done when

- [x] We've decided which script aliases and tasks we're going to provide guidance for
- [x] We've updated `docs/contributing/tasks.md`
- [ ] ~We've removed any references to gulp in the documentation~

**Comment by colinrotherham** [comment]
I'm going to close this as we've picked up documentation on the individual build task issues

Some named Gulp tasks do remain for developer convenience but they're limited to:

### Project level

```console
npx gulp build:package
npx gulp build:dist
npx gulp screenshots
```

### Review app

```console
npx --workspace app -- gulp build
npx --workspace app -- gulp dev
npx --workspace app -- gulp scripts
npx --workspace app -- gulp styles
```

They're only documented when not called by an npm script

For example `npm run build:package` calls `gulp build:package`
