### ISSUE TITLE
Draft comms for 4.3.1 release

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2774]
## What
Tell users about release of GOV.UK Frontend v4.3.1

## Why
So users know what fixes have been released.

## Who needs to work on this
Content design / tech writer

## Done when

Where applicable, comms drafted for:

- [x] Mailchimp
- [x] Slack (`#govuk-design-system` and `#design` on x-gov Slack; `#govuk-design-system` and `#frontend` on GDS Slack)
- [x] What's New panel of Design System homepage
- [x] Roadmap on  Design System website (not needed)
- [x] Comms has been reviewed by the team and is ready to go when we release

**Comment by vanitabarrett** [comment]
I've started a bit of a draft here: https://docs.google.com/document/d/1FZRplMwDmDxAM5Y4bJVi4PbxbyaoZxserb27zFiHQSk/edit#heading=h.oe987g5cr2yt
