### ISSUE TITLE
Create release notes for GOV.UK Frontend v4.3.1 (fix release)

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2775]
## What
Create release notes for GOV.UK Frontend v4.3.1 (fix release)

## Why
To tell users about the fixes we've made.

## Who needs to work on this
Technical Writer, Developers

## Who needs to review this
Developers

## Done when

- [x] Technical writer / developer drafts release notes
- [x] Not required for fix release - Release notes pass 2i
- [x] PR raised for updating the release notes in the Changelog

**Comment by vanitabarrett** [comment]
2i not required for fix release notes, I'll share them (along with any drafted comms) with the team to look over.
