### ISSUE TITLE
Let teams know we will be retiring compatibility mode in v5.0

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#2789]
## What
Let the community know that we will be removing compatibility mode in govuk-frontend 5.0

Part of https://github.com/alphagov/govuk-frontend/issues/2769

## Who needs to work on this
Content designers, Developers

**Comment by owenatgov** [comment]
A blog has been drafted and is now with comms.

**Comment by 36degrees** [comment]
@owenatgov we've now released v5 – is this still useful in terms of communicating the change? If not, can we close this?

**Comment by owenatgov** [comment]
We decided to supersede this with general comms work around 5.0, specifically a blog post. I haven't been following that work very closely since it was brought up to me but it's out now so the ship has sailed. I'll close this!
