### ISSUE TITLE
Add ability to pass translation strings into accordion component via JS

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend#2802]
## What
Add ability for users to pass a translation object in via JavaScript (at the point of initialisation). This is an alternative method to passing translation strings via the Nunjucks macros (data-attributes).

Example:

```
new Accordion($element, {

  "i18n.showAllSections": "Show everything"

}).init()
```

## Why
Some users may prefer to pass translation strings via JavaScript, or it may be better suited to their service.

## Who needs to work on this
Developers

## Who needs to review this
Developers

## Done when

- [x] It’s possible to provide translations to the accordion component via JavaScript
- [x] Expanded logic which looks up translations passed via data attributes, to lookup translations provided by JavaScript
- [x] Data attribute translations take priority over JS translations, if both provided
- [x] The accordion component still works if no/only some translations are passed (falls back to defaults)
- [x] The accordion component has tests which cover the ability to translate via JavaScript

**Comment by 36degrees** [comment]
Does this also include being able to pass config via `initAll`, or should that be a separate story?
