### ISSUE TITLE
summary-list.yaml contains invalid value for property visuallyHiddenText

### ISSUE THREAD

**Issue by kyle-bowden** [alphagov/govuk-frontend#2803]
## Description of the issue

PlatUI has recently upgraded our play-frontend-hmrc service with the new govuk-frontend version(**v4.3.1**)
after the upgrade, we had a failing view test around the **summary-list** component.

The problem was that the **visuallyHiddenText** [property](https://github.com/alphagov/govuk-frontend/blob/9fc06138fca9bdb16350910360234441c79d3c10/src/govuk/components/summary-list/summary-list.yaml#L55) which is a string is being set with a [boolean](https://github.com/alphagov/govuk-frontend/blob/9fc06138fca9bdb16350910360234441c79d3c10/src/govuk/components/summary-list/summary-list.yaml#L159) value.

## Environment (where applicable)

- GOV.UK Frontend Version: v4.3.1

**Comment by 36degrees** [comment]
@kyle-bowden we're currently planning to change instances of `false` for `visuallyHiddenText` to `null`.

Will that fix the issue that you're having with your tests?

**Comment by kyle-bowden** [comment]
> @kyle-bowden we're currently planning to change instances of `false` for `visuallyHiddenText` to `null`.
> 
> Will that fix the issue that you're having with your tests?

@36degrees Yes, that will be fine, thank you.
