### ISSUE TITLE
Surface errors thrown in Puppeteer's browser in test output

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2859]
## What

For all of our behavioural tests (which use Jest Puppeteer), if there is an error thrown in the JavaScript running in the headless browser, then surface the error in the test output (and, if possible, fail the test).

## Why

So that we know about the error, rather than just seeing the side effects of the JavaScript failing (things not happening that we expect, because the execution of the script has failed) – which makes it much easier to understand what's going on.

We thought this was covered by jest-puppeteer's `exitOnPageError` config (which defaults to true) but that doesn't seem to have the desired effect.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] If there is an error thrown in the JavaScript running in the headless browser, then the error is surfaced in the test output
- [x] (Ideally) If there is an error thrown in the JavaScript running in the headless browser, then the test that triggered the actions on the page that caused the JS error fails

**Comment by colinrotherham** [comment]
This was closed by https://github.com/alphagov/govuk-frontend/pull/2933 🎉
