### ISSUE TITLE
Update extensions config to work with Prototype Kit v13

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2889]
## What

Update the extensions config file and add any additional integration points required for GOV.UK Frontend to work correctly in (the future) v13 of the Prototype Kit.

## Why

A new major version of the Prototype Kit will shortly be released which includes some changes to the extension system that affect us.

Specifically, the kit will no longer:

- [import the Nunjucks macros from GOV.UK Frontend](https://github.com/alphagov/govuk-prototype-kit/commit/b0a00d0e0ea690aa6a1fc7afe4965ac3d1842698#diff-de5bfb198cbb93aa8dbe90bc8bc7fc47cb774eb8ea9c29adfb74b9d3f094e1a7L6-L33)
- [configure asset paths, enable the new link styles or turn on global styles](https://github.com/alphagov/govuk-prototype-kit/pull/1615/files#diff-2face5d2ac364af976444f039a125fe75a3e254566b256d30710e28e0831527bL1-L6)
- [call `window.GOVUKFrontend.initAll`](https://github.com/alphagov/govuk-prototype-kit/pull/1615/files#diff-13d1eef409ff4224cdda96f8fa06fc7a89392f6bcf7056ee79453d20919e472eL17-L20)

So, we now need to provide the integration points to take care of those things, some of which relies on new functionality in v13 of the Prototype Kit – **some of which may not yet be stable**. This means we'll need to work closely with the Prototype Kit team to ensure that what we end up releasing will work with v13.0.0 of the Prototype Kit.

## Who needs to work on this

Developers

## Who needs to review this

Developers, Developers from the Prototype Kit team

## Done when

- [ ] We've confirmed what the stable 'API' for the Prototype Kit extensions system will look like
- [ ] The extensions config and supporting files, when included in the Prototype Kit, takes care of: 
  - [ ] importing the Nunjucks macros for all components
  - [ ] configuring the asset paths
  - [ ] enabling the new link styles
  - [ ] turning on global styles
  - [ ] calling `window.GOVUKFrontend.initAll`
- [ ] We've shared a pre-release of GOV.UK Frontend with the Prototype team and they have confirmed that it works as expected

**Comment by 36degrees** [comment]
@nataliecarey is open to pairing on this.

She has already raised a PR that could be updated (https://github.com/alphagov/govuk-frontend/pull/2851)

**Comment by 36degrees** [comment]
How should we record this change in the changelog and release notes, if at all?

Arguably it's a new feature but it doesn't seem relevant for folks reading the release notes as it's more about unlocking a feature of the Prototype Kit?

Maybe we should include it in fixes? 'Add support for Prototype Kit v13 plugin system'?

**Comment by colinrotherham** [comment]
Just included it under "Fixes" as discussed: https://github.com/alphagov/govuk-frontend/pull/2981
