### ISSUE TITLE
Tabs component binds the same method multiple times

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#2896]
## What

The tabs component [binds the `onTabClick` and `onTabKeydown` listeners multiple times](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/tabs/tabs.mjs#L59-L60), while only a single version of that bound method is necessary.

Furthermore, it stores each bound version on the `$tab` element, poluting the object from the DOM.

These methods could be bound only once before looping and stored on the component instead.

## Why

Avoid unnecessary extra functions being created and poluting objects from the browser.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] The method is bound prior to looping and stored on the component rather than the element

**Comment by 36degrees** [comment]
Fixed by #2987 (https://github.com/alphagov/govuk-frontend/commit/478f642cf76363694d57c20b1c71d7ed72d53c8a)
