### ISSUE TITLE
Use consistent terminology when talking about pluralisation

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#2914]
## What

Prompted by [Ollie's comment on the CharacterCount macro options](https://github.com/alphagov/govuk-frontend/pull/2895#discussion_r993192355)

Have consistent words for refering to:
- the "zero", "one", "two", "few", "many", "other" keys 
- the translated messages attached to these when providing translations
- the object associating the keys to the message

We don't want to invent new terms, just get some consistency in the codebase so we always refer to those in the same way.
There are a few specifications/documents that deal with the topic and will likely have terms we can reuse:

- TC39's specification of `Intl.PluralRules`' `select` method, used to transform a number into the `one`,`two`, `few`... string: https://tc39.es/ecma402/#sec-pluralruleselect. That's the JavaScript API shipped in browser and node to help with localisation and pick the right plural forms. And [its documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules)
- The Unicode specification about documentation: https://cldr.unicode.org/index/cldr-spec/plural-rules
- Mozilla's documentation of translation best practices: https://mozilla-l10n.github.io/documentation/localization/dev_best_practices.html#use-proper-plural-forms
- Libraries using a similar system referenced in @querkmachine's initial document about internationalisation:
  - [banana-i18n](https://wikimedia.github.io/banana-i18n/#plurals)
  - [i18next](https://www.i18next.com/translation-function/plurals)
  - [Fluent](https://projectfluent.org/)
  - [Lingui.JS](https://lingui.js.org/guides/plurals.html)

## Why

That's help us be clear about what exactly our code and documentation refers to

## Who needs to work on this

Content designers, Developers

## Who needs to review this

Content designers, Developers

## Done when

- [ ] Terms have been agreed upon
- [ ] Code and docs have been updated to be consistent with the chosen terms

**Comment by 36degrees** [comment]
We're going to close this and wait to see if we see issues with people not understanding our documentation relating to pluralisation.
