### ISSUE TITLE
Introduce Nunjucks macros abstracting data attribute rendering

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#2917]
## What

Abstract rendering of data-attributes for passing configuration into a `govukDataAttributes` with a call of the following shape:

```njk
{{
	govukDataAttributes({
	   'attribute-name': value,
	   'other-attribute-name': {
		  value: otherValue, 
	      testUndefined: true,
	      escape: false # Only if there are instances we don't escape the attributes
	   }
	})
}}
```

Expand the concept with a helper for internationalisation attributes that relies on `plurals` or `string` key instead of `value` and delegates to `govukDataAttributes`, building the `i18n.<attribute-name>[.plural-category]` attribute name. Based on [the ideas in this comment](https://github.com/alphagov/govuk-frontend/pull/2895#discussion_r994400894).

## Why

Setting the attributes is very repetitive in the templates and always the same shape:
1. if {{value}} or {{value !== undefined}} to condition the rendering of the attribute itself
2. output " data-{{name}}="{{value | escape}}"

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Abstraction macros have been introduced and tested
- [ ] Component templates have been updated to use the abstractions

**Comment by querkmachine** [comment]
I notice that an [i18n related macro](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/macros/i18n.njk) was added a couple of months ago, that seems related to this idea. 

Is this issue still relevant or in need of updates in response to that?

**Comment by colinrotherham** [comment]
Hadn't realised this issue existed. We nearly implemented this in:

* https://github.com/alphagov/govuk-frontend/pull/3867

Fairly quick to pull out another macro (for data- or regular attributes in general) from `govukI18nAttributes()`
