### ISSUE TITLE
Rename 'Phase tag' component to 'Tag'

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#292]
The Phase tag component has generic value beyond it's use in the Phase banner component.

For example, we could use it to style the task statuses in the task list pattern.

For this reason we should remove the reference to 'phase' from the name.

This is an example of a component that goes by a number of names - we should add 'pill' and 'chip' as aliases.

**Comment by 36degrees** [comment]
At the minute the tag will always be blue – do we need to make the tag more generic and allow it to be used with a wider palette of background colours?

There's also a right margin on the tag which makes sense when it's used as part of the phase banner, but less so if it was e.g. floated right as part of the task list. So we might want to remove the margin and specify it as part of the phase banner component.

**Comment by igloosi** [comment]
so `tag tag--phase (blue), tag--`something?

**Comment by joelanman** [comment]
Both of those examples are 'status' - might that work as a name?

**Comment by timpaul** [comment]
I think 'status' might be too narrow a term. It's more of a pure UI component - though it's worth calling out statuses as a good use case in the guidance.

**Comment by igloosi** [comment]
status-tag?

**Comment by joelanman** [comment]
Cool, tag sounds good then

**Comment by timpaul** [comment]
OK, following a conversation with @igloosi and @36degrees:

- we'll design the 'Tag' component to meet the needs of the 2 use cases we currently know about (phase banners and task lists)
- the default colour will be white on blue
- there will be an inactive variant which will have a grey background

**Comment by igloosi** [comment]
resolved in #291
