### ISSUE TITLE
Consider alternative names for the `I18n` class

### ISSUE THREAD

**Issue by colinrotherham** [alphagov/govuk-frontend#2926]
## What
As a team we're not sure if our `I18n` "Internationalisation" class is fully-featured enough to carry the name. The class does most of what _we_ need but (knowingly) lacks various features we may need in the future.

Do we need a new name? We should investigate

## Why

These features were noted as not supported during the original spike:

[#2614 [DO NOT MERGE] Internationalisation support](https://github.com/alphagov/govuk-frontend/pull/2614)
>* Alternative grammar forms, gendered forms, or switching strings based on an arbitrary context.
>* Bi-directional (Bidi) text strings (mixing left-to-right and right-to-left strings) without munging up formatting.

We're also aware of things like:

>The list of languages currently supported is pretty much arbitrary, and ones we don't need to support can be removed.

Is that a problem?

## Who needs to work on this

Developers, Content Designers

## Who needs to review this

Developers, Content Designers

## Done when

- [ ] New name decided (or not)
- [ ] New name applied in code

**Comment by romaricpascal** [comment]
How about `Messages` or is it too basic? This focuses the role of that class on giving you access to messages more than its internationalisation capacities.

**Comment by 36degrees** [comment]
Assuming we do make the I18n class private (see #2927) I'm not too fussed about resolving this before we ship v4.4.0 as we can change the name without it being a breaking change.

Obviously if we were planning on making it public at some point we'd want to revisit this first.

With that in mind are we happy to take this out of the v4.4.0 milestone and push this conversation down the line a bit?

**Comment by colinrotherham** [comment]
I'm happy with the "private + same name" combo 👍

Consider it considered, or rename it to **Consider making the `I18n` class public**?

As in, once we're happy it's stable and well documented

**Comment by romaricpascal** [comment]
Sounds good to leave it on the side for now and revisit when/if we make the API public at some point in the future. No need to hold up 4.4.0 for an internal name 😄

**Comment by romaricpascal** [comment]
That said, the `i18n` name also appears publicly in the API when you're setting the content of messages, so we may be stuck with that name for a while:

```html
<div ... data-i18n.charactersUnderLimit="...." ...>...</div>
```

```js
new CharacterCount($element, {
   i18n: {
      charactersUnderLimit: ...
      ...
   }
   ...
})
```

**Comment by 36degrees** [comment]
Have removed from the milestone and will close this in favour of adding a note to #2977 to re-consider the name before making it public.
