### ISSUE TITLE
Consider making the `I18n` class private

### ISSUE THREAD

**Issue by colinrotherham** [alphagov/govuk-frontend#2927]
## What

Do we want to consider `I18n` "private" whilst we continue changing, refactoring, improving?

We've already noted in https://github.com/alphagov/govuk-frontend/issues/2926 that we may rename our `I18n` class

## Why

Making features "public" means we can't make breaking changes without major releases
Making features "private" (or for internal use) means we're relatively free to make changes where needed

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] Decision made on private versus public
- [x] Change made in code to remove **GOVUKFrontend.I18n** from `govuk/all.js`

**Comment by romaricpascal** [comment]
Concensus at the meeting was to keep it private for now and possibly open it up in a future release, so opened up #2941 to deal with it 😊
