### ISSUE TITLE
Finalise Nunjucks options and JSDoc for new config introduced in v4.4.0

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#2944]
## What

Pull the Nunjucks macro options and JSDoc for new config introduced in v4.4.0 into [the draft doc](https://docs.google.com/document/d/1ztulyMp_pxi-uJimWrKQtnfSjdDDIN4Qr9rKmAHWO_0/edit#) so that it can be reviewed by our tech writer, and then 2i'ed.

Once the changes have been reviewed, update the component YAML files and the JS files to reflect any revisions.

## Why

As the Nunjucks macro options and the JSDoc are part of our published documentation, they should be reviewed by our tech writer before we do the release.

## Who needs to know about this

Tech writers

## Done when

- [x] The draft doc has a version of the Nunjucks macro options and JSDoc approximately as they would appear when published in the Design System / Frontend Docs
- [x] The Nunjucks macro options and JSDoc has been reviewed in the draft doc by the tech writer
- [x] The Nunjucks macro options and JSDoc has been 2i'ed
- [ ] Any revisions have been reflected in the component YAML / JS

**Comment by romaricpascal** [comment]
@claireashworth I've pulled the current content we have in our JSDoc inside the document, split by components and with a little intro and some notes on why I left out some parts of the JSDoc to focus on what's strictly necessary for the next release.

**Comment by romaricpascal** [comment]
And the Nunjucks macro descriptions should be split as they will appear in the table.
