### ISSUE TITLE
Create release notes for GOV.UK Frontend v4.4.0 (feature release)

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2955]
## What
Create release notes for GOV.UK Frontend v4.4.0 (feature release)

## Why
To tell users about the changes we've made.

## Who needs to work on this
Technical Writer, Developers

## Who needs to review this
Developers

## Done when

- [x] Technical writer / developer drafts release notes
- [x] Release notes pass 2i
- [x] PR raised for updating the release notes in the Changelog

**Comment by colinrotherham** [comment]
Released in https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.0
