### ISSUE TITLE
Release v4.4.0 of GOV.UK Frontend to npm 🚀

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#2956]
## What
Release GOV.UK Frontend v4.4.0 to npm, following the [release process](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing.md)

## Who needs to work on this
Developers

## Done when

- [x] The package has been published on npm
- [x] The release has been created on Github

**Comment by colinrotherham** [comment]
Published to npm:

* https://www.npmjs.com/package/govuk-frontend/v/4.4.0

Released to GitHub:

* https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.0
