### ISSUE TITLE
Update all dependencies using Dependabot

### ISSUE THREAD

**Issue by colinrotherham** [alphagov/govuk-frontend#2960]
## What

Consider using Dependabot's `dependabot.yml` config to set up:

1. Update PRs for all dependencies (npm, GitHub Actions, Ruby gems etc)
2. Document temporarily out-of-date packages we can't upgrade yet
3. Document legacy packages that we can't upgrade

## Why

An action to investigate automatic dependency updates was raised at our Design System retro

Primarily to avoid lengthy "catch up" PRs like https://github.com/alphagov/govuk-frontend/pull/2937, but also to catch breaking changes early (little and often) as it gets much more difficult as time passes like https://github.com/alphagov/govuk-frontend/pull/2924

Benefits include:

1. Saves time not managing updates
2. Raises awareness of available bug fixes, deprecations
4. Updates to child dependencies can [unblock security updates](https://github.com/alphagov/govuk-frontend/security/dependabot)
5. Maintains pace with the Frontend community 😩

Downsides include added code review time (although in theory we're still up on time saved)

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] Dependabot `dependabot.yml` config added to project
- [ ] Decision made on how often to check for updates (daily, weekly)
- [x] Known packages with "worrying updates" configured to be ignored
- [x] Known package acceptable semver ranges configured in `package.json`
- [ ] ~Pull requests labelled [`dependencies`](https://github.com/alphagov/govuk-frontend/labels/dependencies) added to [**Design System Sprint Board**](https://github.com/orgs/alphagov/projects/4)~

**Update:** We'll need to our "classic" project if we want to automate moving Dependabot PRs onto the board via: https://github.com/marketplace/actions/add-to-github-projects

Optionally we may want to expand the [**Diff changes to dist**](https://github.com/alphagov/govuk-frontend/actions/workflows/diff-change-to-dist.yaml) GitHub Action workflow to run against dependency PRs

**Comment by colinrotherham** [comment]
Continuing to improve our config with:

* https://github.com/alphagov/govuk-frontend/pull/2992

**Comment by colinrotherham** [comment]
@36degrees Think we just need to decide if we're going with "weekly" or "daily" then this is done?

**Comment by 36degrees** [comment]
Let's go with daily for now and we can always change it if we find it doesn't work for us.
