### ISSUE TITLE
Add a link style for non-link elements

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#298]
Occasionally you need to style something that’s not a link as a link. For example, summary tags are styled as links on GOV.UK, and occasionally form controls need to be styled as links.

**Comment by igloosi** [comment]
visual example?
one could use `govuk-c-link` class on one hand. the other one is that there are mixins or extendable [silent classes](https://csswizardry.com/2014/01/extending-silent-classes-in-sass/) or all the things

**Comment by nickcolley** [comment]
Hey Tim,

I think we're covering this by shipping components that look like links, for example the details component.

Could you give an example where you'd need a generic way to do this?

**Comment by timpaul** [comment]
Happy to treat it on a case-by case basis. If we find ourselves doing it a lot then we'll know we might need a class for it.
