### ISSUE TITLE
Allow for both responsive and fixed form field lengths

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#299]
By default our input and select fields switch to 100% width for small screen sizes. In some cases however we want them to remain at a fixed width. For example, very short fields designed to take a specific number of characters, like day, month, year and postcode.

**Comment by nickcolley** [comment]
Hey Tim, is this fixed with the width override classes?

https://govuk-design-system-production.cloudapps.digital/styles/layout/#width-override-classes

**Comment by 36degrees** [comment]
I don't think it is – the width overrides all revert to 100% width on mobile.

I think if we implemented character-width'ed inputs those could/should be the same width at all breakpoints?

**Comment by timpaul** [comment]
I think for now we should work with the hypothesis that fixed-width fields should snap to 100% for mobile devices, because:
- it makes them easier to hit
- there's no risk they will be wider than the viewport

We may be proven wrong on this, but we can open another issue if that's the case.

**Comment by timpaul** [comment]
I'd like to reopen this issue, because:

a) the current width-overrides are proportional - we also need fixed ones (for short fields like postcode and telephone number)
b) the working group recently reviewed the [telephone number pattern](https://github.com/alphagov/govuk-design-system-backlog/issues/101) and the feedback was that we need to apply a fixed width to telephone number fields

@dashouse has proposed [the following solution using ex units](https://codepen.io/iknowdavehouse/pen/KZMKjw)

**Comment by dashouse** [comment]
@timpaul I felt like I could turn this around in 20 mins...

I have made a PR on GOV.UK Frontend with a proposed solution using the `ch` unit.
You can see it in action at the bottom of this page on the preview URL - https://govuk-frontend-review-pr-626.herokuapp.com/examples/form-alignment

**Things that would need to be tested**
- The `ch` unit browser compatibility - https://caniuse.com/#feat=ch-unit (At the moment it will go 100% width)
- That it changes size when using a fallback font
- That there's enough space on the right for the safari prefill icon

**Comment by dashouse** [comment]
I have updated this to be a modifier of the input component, rather than an override after suggestions from @36degrees 

I have also moved back to `ex` for better browser support

Can be previewed here - https://govuk-frontend-review-pr-626.herokuapp.com/components/input

**Comment by nickcolley** [comment]
Closed by https://github.com/alphagov/govuk-frontend/pull/626, thanks @dashouse
