### ISSUE TITLE
Set up decision log

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3048]
## What

Set up a decision log to record the decisions we make along the way and why we made them.

## Why

Keep a history of our decisions for when we need to dig back in the past.

## Who needs to work on this
Delivery Manager

## Who needs to review this
Developers

## Done when

- [x] Identified where the decision log will live
- [x] Agreed criterion of the log
- [x] Reviewed by team
- [ ] Published

**Comment by kellylee-gds** [comment]
Reopening as we want to host it in a Github project board rather than Google Sheets
