### ISSUE TITLE
Minified JS in `dist` errors in IE8

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#3136]
## Description of the issue

The minified JavaScript we provide in the `dist` directory (which is also included in the zip file attached to each release) errors in IE8 – seemingly because of transformations made by Uglify JS.

Although we have plans to drop support for IE8-10 shortly, our [current browser support](https://github.com/alphagov/govuk-frontend#browser-and-assistive-technology-support) includes Internet Explorer 8, 9 and 10, 'although components may not look perfect'.

## Steps to reproduce the issue

Load the review app in IE8 (after #3050 has been merged)

## Actual vs expected behaviour

The page should load without errors. Instead we get:

> Object does not support this property or method

## Environment (where applicable)

- Operating system: Windows 7
- Browser: Internet Explorer
- Browser version: 8.0
- GOV.UK Frontend Version: N/A

**Comment by 36degrees** [comment]
Looks like this might be fixed by #3013.

**Comment by colinrotherham** [comment]
We now have two fixes to pick:

1. https://github.com/alphagov/govuk-frontend/pull/3137
2. https://github.com/alphagov/govuk-frontend/pull/3013

But equally we could merge 1) and take on 2) at a later date

**Comment by colinrotherham** [comment]
I've checked out previous releases, enabled UglifyJS, and tested in IE8 via Browserstack

### [GOV.UK Frontend releases](https://github.com/alphagov/govuk-frontend/releases)

* [**v4.3.1**](https://github.com/alphagov/govuk-frontend/releases/tag/v4.3.1) – using [`uglify-js@3.6.9`](https://github.com/mishoo/UglifyJS/releases/tag/v3.6.9) (works in IE8)
* [**v4.4.0**](https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.0) – using [`uglify-js@3.17.4`](https://github.com/mishoo/UglifyJS/releases/tag/v3.17.4) (broken in IE8)
* [**v4.4.1**](https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.1) – using [`uglify-js@3.17.4`](https://github.com/mishoo/UglifyJS/releases/tag/v3.17.4) (broken in IE8)

See full diff in [compare view](https://github.com/mishoo/UglifyJS/compare/v3.6.9...v3.17.4)

**Comment by colinrotherham** [comment]
Closed by https://github.com/alphagov/govuk-frontend/pull/3137
