### ISSUE TITLE
Accordion: Have the option to not restore accordion state

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#3182]
## Related component
Accordion

## Context
Currently, in browsers that support `sessionStorage` and have it enabled, the Accordion component will remember the open and closed state of each section and will restore this state when the page is visited in future, provided the browser hasn't been closed and `sessionStorage` hasn't been otherwise cleared.

## Alternatives
Currently there are two ways around this:
- Programatically clear `sessionStorage` using JavaScript on page load.
- Randomise the `id` of the accordion, as this affects the key that the state is stored against.

Setting the `expanded` parameter on each section doesn't work, as this only affects the accordion's initial state on first visit, not the state stored in `sessionStorage`.

## Additional information
There have been a few occassions on Slack and in [the backlog issue](https://github.com/alphagov/govuk-design-system-backlog/issues/1) where developers have not wanted this functionality within their service. 

Some developers have also encountered issues where multiple accordions use the same `id`, and the state from one accordion is transposed onto another. 

Now that we have a relatively well-defined methodology for passing configuration options to components, we may want to provide an option to disable this state-remembering functionality.

**Comment by querkmachine** [comment]
Whatever we do here might also want to be mirrored for the Tabs component, as that currently lacks state restoration despite some demand for it:

- #1976

**Comment by CharlotteDowns** [comment]
I think it's also [mentioned here in the Accordion backlog issue](https://github.com/alphagov/govuk-design-system-backlog/issues/1#issuecomment-1110872575)

> Hi,
> Sorry if this is the wrong place to write this issue I am having. I am using this accordion component and having issues with it remembering expanding selection between different sessions.
> Example, select "show all sections" clicked on a deal. Insert new deal and go to page with accordion on a different url-> all sections are expanded. Press "hide all sections" and insert a new deal and navigate to it on a different url and all sections are closed. Repeat.
I have set expanded: false in items and have kept it as false to try and force it to be closed but it doesn't seem to work.

**Comment by querkmachine** [comment]
@davidc-gds raised an interesting point today that this is basically allowing for two different behavioural modes for accordions, which might be confusing to users as no indication of whether their state will be remembered or not is given.

Whilst I understand this point (and consistency is king both in UX and for code maintenance purposes!), I don't think this is a blocker to introducing this change. 

For better or worse, we also don't make a distinction as to whether a button will submit a form or direct to another page like a link, nor do we indicate whether a checkbox or radio button will expand nested controls or not, and those are arguably more significant 'inconsistent' behaviours. 

I'd also only expect this functionality to be used in places where the sessionStorage functionality has already been identified as an issue for users or the user journey, rather than it being added haphazardly. We may want to codify that in guidance at some point if it does become a problem.
