### ISSUE TITLE
Using govuk-frontend with Rails 7 and esbuild

### ISSUE THREAD

**Issue by RobNicholsGDS** [alphagov/govuk-frontend#3196]
## Description of the issue
The way JavaScript assets are loaded in Rails 7 means that they are not immediately available within the HTML document. This means that copying `/node-modules/govuk-frontend/govuk/all.js` to `app/javascript/govuk.js` and adding a `require "./govuk"` call to `app/javascript/application.js` is not enough to make `window.GOVUKFrontend` available in the page.

In addition the following lines are needed in the `app/javascript/application.js`

```javascript
require ('./govuk');
import GOVUKFrontend from "./govuk"
window.GOVUKFrontend = GOVUKFrontend
```
This is a small addition to the app but took me some time to track down [what was causing the problem](https://discuss.rubyonrails.org/t/struggling-with-javascript-and-esbuild-rails-7/79698/4) with a solution being found in a [stackoverflow post](https://stackoverflow.com/questions/70921378/how-to-install-jquery-and-bootstrap-in-rails-7-app-using-esbuild-without-webpac).

I wasn't sure where I should post this information and hope this issue is an appropriate way of doing so.

## Steps to reproduce the issue
Follow the steps described in ["Get the JavaScript working" of the govuk-frontend documentation.](https://frontend.design-system.service.gov.uk/get-started/#5-get-the-javascript-working).

When the page is loaded the following JavaScript error will occur:
```
items:nn Uncaught TypeError: Cannot read properties of undefined (reading 'initAll')
    at items:nn:nn
```
Where the items point to the code:
```
window.GOVUKFrontend.initAll()
```
If `app/javascript/application.js` is updated as detailed above the JavaScript loads as expected and the error message is no longer displayed.

## Environment
This is using a Rails 7 app with the JavaScript configured using the jsbundling-rails gem and via:
```
  rails javascript:install:esbuild
```

**Comment by romaricpascal** [comment]
Hi Rob,

Thanks for reporting this, it is indeed the right place and it seems we need to clarify our documentation a bit, sorry.
 
Given Rails 7 bundles the JavaScript using esbuild, the preferred way of importing `govuk-frontend` (if [installed via npm](https://guides.rubyonrails.org/working_with_javascript_in_rails.html#adding-npm-packages-with-javascript-bundlers)) would be to follow our guidance for [Importing JavaScript using a bundler](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#import-javascript-using-a-bundler).

Our [Get started page](https://frontend.design-system.service.gov.uk/get-started/#5-get-the-javascript-working) describes the scenario for when`govuk-frontend` javascript is served as-is, from a folder where static assets are directly served (that would be the `public` folder in Rails, I believe), which didn't apply to your situation.

We'll look to clarify our guidance so getting started is clearer when using a bundler.

**Comment by RobNicholsGDS** [comment]
Thanks Romaric for getting back to me. The guidance in [Importing JavaScript using a bundler]([Importing JavaScript using a bundler](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#import-javascript-using-a-bundler)) does look better than the technique I was using. I'll implement that in my app over the next few days.
