### ISSUE TITLE
Review use `indent` in our templates

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#3211]
## What
We use [`indent`](https://mozilla.github.io/nunjucks/templating.html#indent) across our component templates. Do we still need to do this?

## Why
The primary intent of using `indent` in our context is to make it look tidy when a developer is viewing the source for a page with our components on. There's a question now about how valuable this is based on the reckon that most devs will use dev tools over view source and that we pretty print our HTML.

We should investigate if this is still valuable. If so, we should see if there are things we can do to improve and/or document our use of it. If not, we should remove it.

### Places we use indent
In many of the below examples there are more than one use of `indent` so look at the whole file as well as the referenced line.

- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/button/template.njk#L48
-  https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/checkboxes/template.njk#L85
- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/cookie-banner/template.njk#L50
- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/date-input/template.njk#L40
- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/file-upload/template.njk#L16
- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/input/template.njk#L16
- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/label/template.njk#L11
- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/phase-banner/template.njk#L10
- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/radios/template.njk#L25
- https://github.com/alphagov/govuk-frontend/blob/853403db206aa2fad1daef33e517bdc1c4a61d9a/src/govuk/components/select/template.njk#L16 

### Extra things to think about
- Could we add something to our load process to auto-indent our HTML?
- Are there other benefits of `indent` other than for view source? 

## Who needs to work on this
Developers

## Done when

- [ ] Confirm why we use `indent`
- [ ] Decide if we should continue using `indent` or not
- [ ] Consider alternatives to using `indent`/more efficient ways to leverage `indent`

**Comment by colinrotherham** [comment]
Turns out that `indent()` etc is vital to indent included HTML other than the first line

I've adding `indent()` where necessary and formatted all our Nunjucks HTML in:

* https://github.com/alphagov/govuk-frontend/pull/4448

**Comment by owenatgov** [comment]
I'm in the process of reviewing that PR but I don't fully grasp how `indent()` is vital. Could you elaborate please?

**Comment by colinrotherham** [comment]
Yeah course, I should say it's vital to "carry the indent level" from the one macro to the next for tidiness sake only

I'll add some examples below using this little unindented macro:

```njk
{% macro govukExample() %}
<article>
  <h2>Example</h2>
  <p>Hello Owen</p>
</article>
{% endmacro %}
```

## Without indent

See how the macro contents isn't indented at all?

It appears to indent the macro's 1st HTML line, but that's from the 2 spaces before `{{ govukExample() }}`

### Input

```njk
<section>
  <h1>Demo</h1>
  {{ govukExample() }}
</section>
```

### Output

```html
<section>
  <h1>Demo</h1>
  <article>
  <h2>Example</h2>
  <p>Hello Owen</p>
</article>

</section>
```

## Without indent, nested

As above, only the macro's 1st HTML line is indented by the spaces before `{{ govukExample() }}`

But none of the macro's subsequent HTML lines are indented at all

### Input

```njk
<div class="govuk-grid-row">
  <div class="govuk-grid-column">
    <section>
      <h1>Demo</h1>
      {{ govukExample() }}
    </section>
  </div>
</div>
```

### Output

```html
<div class="govuk-grid-row">
  <div class="govuk-grid-column">
    <section>
      <h1>Demo</h1>
      <article>
  <h2>Example</h2>
  <p>Hello Owen</p>
</article>

    </section>
  </div>
</div>
```

## With indent

Notice now how `indent(2)` adds 2 spaces to the macro's 2nd, 3rd and 4th HTML lines too?

### Input

```njk
<section>
  <h1>Demo</h1>
  {{ govukExample() | trim | indent(2) }}
</section>
```

### Output

```html
<section>
  <h1>Demo</h1>
  <article>
    <h2>Example</h2>
    <p>Hello Owen</p>
  </article>
</section>
```

## With indent, nested

With a nested example we now begin at 6 spaces (not 2) so we need ~`indent(2)`~ `indent(6)`

But notice how `indent(6)` still adds 6 spaces to each subsequent macro HTML line?

### Input

```njk
<div class="govuk-grid-row">
  <div class="govuk-grid-column">
    <section>
      <h1>Demo</h1>
      {{ govukExample() | trim | indent(6) }}
    </section>
  </div>
</div>
```

### Output

```html
<div class="govuk-grid-row">
  <div class="govuk-grid-column">
    <section>
      <h1>Demo</h1>
      <article>
        <h2>Example</h2>
        <p>Hello Owen</p>
      </article>
    </section>
  </div>
</div>
```

**Comment by colinrotherham** [comment]
Just a quick variation to the above too

Lots of our formatting issues were with `params.html` which also needs indenting

For example, take this Nunjucks macro instead:

```njk
{% macro govukExample(html) %}
<article>
  {{ html | trim | safe | indent(2) }}
</article>
{% endmacro %}
```

## With indent, nested `html` param

Taking the macro above, notice how we indent both the macro contents and the `{% set html %}` param?

1. Nunjucks view applies `indent(2)` to `govukExample()` affecting `<article>` contents
2. Nunjucks macro applies `indent(2)` to the `{% set html %}` param contents

### Input

```njk
{% set html %}
<h1>What about me?<h1>
<p>Indents can be cumulative<p>
{% endset -%}

<section>
  <h1>Demo</h1>
  {{ govukExample(html) | trim | indent(2) }}
</section>
```

### Output

```html
<section>
  <h1>Demo</h1>
  <article>
    <h1>What about me?<h1>
    <p>Indents can be cumulative<p>
  </article>
</section>
```

**Comment by owenatgov** [comment]
Cheers Colin that makes sense!

**Comment by colinrotherham** [comment]
I've added some suggestions to [Accordion](https://github.com/alphagov/govuk-frontend/pull/4448#discussion_r1412225441), [Breadcrumbs](https://github.com/alphagov/govuk-frontend/pull/4448#discussion_r1412226123) and [Button](https://github.com/alphagov/govuk-frontend/pull/4448#discussion_r1412227241) for @owenatgov to review

**Comment by colinrotherham** [comment]
I've closed the original PR in favour of smaller easier-to-review PRs instead

Good to link to https://github.com/alphagov/govuk-frontend/pull/4448#issuecomment-1816376424 for the various compromises we tried

**Comment by colinrotherham** [comment]
Thanks for all these reviews @romaricpascal

Thought I'd got them all but I'd not split out **Task list** or **Tabs**  so will reopen

You'll see some more PRs coming through shortly

**Comment by colinrotherham** [comment]
@owenatgov All done ✅
