### ISSUE TITLE
For each JavaScript component, document all possible levels of progressive enhancement (by browser support)

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#3227]
## What

For each level of progressive enhancement, document:

1. Browser features or APIs required
2. Browser features or APIs that could be polyfilled
3. Browser grade necessary for the enhancement
4. Whether the enhancement is optional (can break) or mandatory

Assume that ES6 is the baseline. Go through the above and see whether an enhancement is optional (can break) or mandatory. For example, we don't mind about adding a comma separator in Character count for `1000`.

Consult the designers after we have some reckons on what's optional or mandatory.

**Initial timebox:** 3 days.

## Goal

Settle on some concepts or principles (for example, never hide content) and define what are our core features or components.

## Rabbit holes

Don't think about refactoring or rewriting the component, consider the progressive enhancement.

## JavaScript components

- Accordion
- Button
- Character Count
- Checkboxes
- Details
- Error Summary
- Header
- Notification banner
- Radios
- Skip link
- Tabs

**Comment by owenatgov** [comment]
I've additionally added Exit this Page to the trello board we're working from. I've tried to be clear that it's not yet published and that there are certain features still being investigated.

**Comment by 36degrees** [comment]
The Trello board we're using to collate this information is here (not publicly viewable):
https://trello.com/b/REPdiaeT/govuk-frontend-js-component-features

We're meeting to go through the board next Tuesday.

**Comment by stevenjmesser** [comment]
Playback and team review is happening tomorrow, so I'll move this to In Review.

**Comment by domoscargin** [comment]
The team has reviewed this, and decided to:

* Add labels to Trello board to show which features rely on on ECMAScript version (#3292)
* Explore principles, rules or scoring systems to help us make decisions about browser support for individual features **[card incoming]**
