### ISSUE TITLE
Including the JavaScript source map in the prototype kit config

### ISSUE THREAD

**Issue by nataliecarey** [alphagov/govuk-frontend#3254]
## What

Add Javascript maps to the prototype kit config

## Why

1. Because at the moment there is a 404 when the console is open in the browser
2. So that prototype users get the benefit of the new source maps

## Who needs to work on this

 - Developer

## Who needs to review this

 - Developer

## Done when

- [ ] Source maps are used by the dev tools for prototype kit users

**Comment by 36degrees** [comment]
As discussed in dev catch up, we think that adding the source maps to the `assets` array should do what we want:

https://github.com/alphagov/govuk-frontend/blob/394c67abdd06895a7d05f70f5fc0dd549d178790/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs#L29-L31

**Comment by colinrotherham** [comment]
Related issue:

* https://github.com/alphagov/govuk-prototype-kit/issues/1950

**Comment by colinrotherham** [comment]
Tested using `npm link` on a locally-built **GOV.UK Frontend** into a prototype 👍
