### ISSUE TITLE
Explore frameworks to help us make decisions about browser support for features

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#3293]
## What

Spend some time individually prototyping frameworks that we might be able to use in the future when we need to make decisions about browser support for different features.

Frameworks might include things like principles, rules, a scoring system or a flow chart – or anything else that we think might help to guide our decision making process.

Once we've prototyped a few different options, we'll review them together and see which idea(s) we want to take forward.

## Why

We're exploring moving towards a graded browser support model where we don't always aim to provide exactly the same experience to every user. For example, we may decide that it's OK for the Character Count not to format numbers in a locale aware way if the [browser doesn't support `Intl.NumberFormat`](https://caniuse.com/?search=intl.numberformat). Treating these things as enhancements means that we need to include fewer polyfills, but we think it might be difficult to make decisions about which things can be treated as enhancements and which features are critical enough that they need to be made available to all users.

## Who needs to work on this

All of the frontend squad

## Who needs to review this

All of the frontend squad

## Done when

- [x] Individuals have spent time prototyping different frameworks
- [x] We've reviewed them together and identified the ideas we want to take forward

**Comment by stevenjmesser** [comment]
We decided that Ollie is going to pull together aspects from Claire's and Romaric's frameworks into his. We'll then review it again and use that framework to start scoping work, put in team reminders for review (e.g. in 6 months' time), etc.
