### ISSUE TITLE
Select Component invalid test fixture scenario for multiple selected options and size attribute support

### ISSUE THREAD

**Issue by mgladdish** [alphagov/govuk-frontend#3317]
## Description of the issue

I'm implementing a test harness around component fixtures.jsons and run in to an issue with a scenario for the Select component.

## Actual vs expected behaviour

The 'with selected value' scenario has one item flagged as selected and also has another value, er, value. The expected select html fragment looks like this:

```
  <select class="govuk-select" id="select-1" name="select-1">
      <option value="1">GOV.UK frontend option 1</option>
      <option value="2" selected>GOV.UK frontend option 2</option>
      <option value="3" selected disabled>GOV.UK frontend option 3</option>
  </select>
```

But isn't a Select element only able to have more than one selected option if its `multiple` attribute is set?

I'd expect the select element to be more like:

```
<select class="govuk-select" id="select-1" name="select-1"  multiple size="2" >
...
```

But then a second issue appears in that the Select box seems to ignore the size attribute and renders single-height regardless of its value. This makes it pretty much unusable as there's no good way to see the choices to select any of them other than the first in the list. (Tested on Firefox and Chrome on MacOS and Firefox on Fedora)

## Environment (where applicable)

- Operating system:
- Browser:
- Browser version:
- GOV.UK Frontend Version: 4.5.0

**Comment by querkmachine** [comment]
Thanks for raising this! This appears to be an issue with the data that generates this fixture. 

We don't support `select[multiple]` in Frontend due to there being a history of poor usability and assistive technology support for it, so only one of these should have the `selected` attribute.

**Comment by mgladdish** [comment]
Thanks.

Any chance you could also add a note to the component's docs to say the multiple attribute is not supported? I spent a chunk of time trying to see what I'd done wrong when adding it didn't work.

**Comment by querkmachine** [comment]
A fix for the fixtures has been merged and will go out in the next release. 

I've opened a separate issue for any documentation changes. Feel free to comment on it if I've missed anything you think should be included: https://github.com/alphagov/govuk-design-system/issues/2625

Thanks again for bringing this to our attention!
