### ISSUE TITLE
Collect feedback about our intended approach for cutting the mustard

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3369]
## What

Share the approach we'd be looking to take with other people, so we can collect feedback and get aware of any barrier it would cause.

## Why

We've[ investigated how we'd go for preventing our JavaScript to run in old browsers](https://github.com/alphagov/govuk-frontend/issues/3264) and tried to anticipate the impacts as best as we could. Best to check with the people it would impact to make sure we didn't miss anything.

## Who needs to work on this

Developers, Technical writers

## Who needs to review this

Developers, Technical writers

## Done when

We shared the approach with:
- [x] the other squad
- [ ] the prototype team
- [x] the frontend community
- [ ] services

**Comment by romaricpascal** [comment]
Slides (not public): https://docs.google.com/presentation/d/1y45VZhPOYHuN2pqL5HOZMImxi2iLO0Dv_teHUuBN1Os/edit#slide=id.g21b7a091c2e_0_4
Doc for collecting comments (not public): https://docs.google.com/document/d/1bxAD2plul6IE_i1e-iTxSqLJCVMNmbky6A1OrLWCHes/edit#

**Comment by NickColley** [comment]
Is there a quick summary on the conclusions you came to?

**Comment by romaricpascal** [comment]
Closing as:
- we're planning to collect feedback from services for our overall approach to v5
- there's a [separate issue for tracking checking with the prototype team](https://github.com/alphagov/govuk-frontend/issues/3484)
