### ISSUE TITLE
some nunjucks snippets have {{- some just have {{

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#344]
eg `date-input.njk` has hyphens in the brackets, `cookie-banner.njk` does not
should probably be consistent?
note: these hyphens do not work with Nunjucks v2, which we are currently using on the kit, however we may well upgrade. We have avoided because of this issue:

https://github.com/mozilla/nunjucks/issues/696

**Comment by nickcolley** [comment]
Looks like we've successfully upgraded the current beta version to use the new version of Nunjucks.

Is this still an issue? https://github.com/alphagov/govuk-prototype-kit-private-beta/blob/master/package.json#L36

**Comment by nickcolley** [comment]
Closing this out since it seems to be an issue for the kit to solve.

**Comment by joelanman** [comment]
@nickcolley the main issue here was consistency, not usage in the kit

**Comment by nickcolley** [comment]
We're going to add pretty printing to output HTML, so when we do that we can make the templates easier to read and consistent.
