### ISSUE TITLE
Remove settings and mixins for building IE8 specific stylesheets

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3461]
## What 

Remove the Sass settings and mixins used for building IE8 specific stylesheets, including:

- the `$govuk-is-ie8` setting
- the `$govuk-ie8-breakpoint` setting
- the `govuk-if-ie8` mixin
- the `govuk-not-ie8` mixin

## Why

We're [dropping support for IE8 in v5](#2621) so we no longer need the mixins for outputing IE8 specific code

## Who needs to work on it

Developers

## Who needs to review it

Developers

## Done when

- [x] The mixins and settings have been removed from the code
- [ ] References to these mixins and settting in the docs have been removed

**Comment by querkmachine** [comment]
We've decided to handle the docs changes after all of the IE removals have taken place, rather than doing them piecemeal, so I'm closing this as done.
