### ISSUE TITLE
Remove the `nodeListForEach` helper function

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3466]
## What

Replace all calls to the `nodeListForEach` helper function with calls to `NodeList.prototype.forEach` (of `for...of` depending on what we support).

Remove the `nodeListForEach` function and related tests.

## Why

As of GOV.UK Frontend v5.0, JavaScript will only run in browsers that support ES6 modules. All browsers that support ES6 modules also support NodeList.prototype.forEach, so can get rid of this helper function.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Calls to `nodeListForEach` have been replaced with vanilla API calls
- [ ] The `nodeListForEach` function has been removed

**Comment by 36degrees** [comment]
Looks like this was done as part of #3570.
