### ISSUE TITLE
Deprecate properties that will no longer be part of the public API

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3473]
## What

Mark properties that will no longer be part of the public API in v5 as deprecated, so users are aware ahead of time.

## Why

We'll be clarifying our public API in v5, which means we will either not support or prevent access to some of the properties currently available on our components. We need to make people aware of this ahead of time to give them as much time as possible to anticipate the change.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

```[tasklist]
### Done when
1. [x] Confirm that any property that's not `init` should be deprecated
2. [x] Properties have been marked as `@deprecated` in their JSDocs
3. [x] We've drafted communications to make people aware of the deprecations
```

**Comment by 36degrees** [comment]
I’ve had a little look through the various methods we have on our components and I think the only current existing useful methods that actually work when called externally are:

- [`CharacterCount.updateCountMessage`](https://github.com/alphagov/govuk-frontend/blob/c628dd114adf3062aa0e169cf02754a8396abc4c/src/govuk/components/character-count/character-count.mjs#L253-L262)
- [`Checkboxes.syncAllConditionalReveals`](https://github.com/alphagov/govuk-frontend/blob/c628dd114adf3062aa0e169cf02754a8396abc4c/src/govuk/components/checkboxes/checkboxes.mjs#L84-L89)
- [`Radios.syncAllConditionalReveals`](https://github.com/alphagov/govuk-frontend/blob/c628dd114adf3062aa0e169cf02754a8396abc4c/src/govuk/components/radios/radios.mjs#L84-L89)

They all meet a similar need – if the textarea’s value or the checkbox or radio checked state is is programatically updated, calling the method brings the count message or the conditional reveal back in sync.

I still think it makes sense to mark them as deprecated for now; we should then write up issues to provide that functionality through a properly designed method that has tests – likely in a future 5.x release.
