### ISSUE TITLE
Create a new git branch for ongoing v4 support

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#3477]
## What
v5 of GOV.UK Frontend removes a lot of legacy features, including dedicated support for older browsers (including IE 8–10); JavaScript support for browsers that don't support modules; and compatibility options for GOV.UK Elements, GOV.UK Template and GOV.UK Frontend Toolkit.

Because of this major step change, we intend to continue providing security and major bugfixes to v4 for at least a year following the release of v5.

## Why
Service teams may not be able to move onto v5 quickly, or may still have a significant number of users on older browsers. We want to ease the transition by allowing them to still use v4 whilst receiving security and bugfixes for it.

## Who needs to work on this
- Developers

## Who needs to review this
- Developers

## Done when

- [ ] The `main` branch has been forked into a `v4` (or similarly named) branch, which has similar merging rules and can be released independently

**Comment by 36degrees** [comment]
> The `main` branch has been forked into a `v4` (or similarly named) branch, which has similar merging rules and can be released independently

We should set this up as a ['support branch'](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing-from-a-support-branch.md), so I'd expect the branch name to be `support/4.x`.

**Comment by querkmachine** [comment]
We have the release git tagged so we're not doing this as part of the release now.

**Comment by colinrotherham** [comment]
Can see @romaricpascal has already made [`support/4.6.x`](https://github.com/alphagov/govuk-frontend/tree/support/4.6.x) so we can close this

Good shout about merging rules though

I've enabled code owner reviews and added these missing status checks:

* Dart Sass v1 (latest)
* Ruby Sass v3 (latest, deprecated)
* LibSass v3 (latest, deprecated)
* Accessibility tests

**Comment by 36degrees** [comment]
@colinrotherham @romaricpascal I think the support branch needs to be called `support/4.x` as we're e.g. likely to release 4.7.0 from it.

**Comment by colinrotherham** [comment]
@36degrees ✅ Done

Hypothetically for #3817 would `support/4.6.x` (patch) be more semver-correct until a new feature lands (minor)?

**Comment by 36degrees** [comment]
> Hypothetically for #3817 would `support/4.6.x` (patch) be more semver-correct until a new feature lands (minor)?

We can use this to test the [new docs on using support branches](https://deploy-preview-21--govuk-design-system-team-docs.netlify.app/how-we-work/version-control/support-branches.html#support-branches) I've been working on! 😁 

I think regardless of what the fix is we're in 'Using support branches for previous major versions' territory. It's a little odd because we haven't released v5 yet, but main is conceptually now a v5 branch.

I think the only reason we'd use `support/4.6.x` is if we had unreleased changes for 4.7 on the main branch and wanted to get a hotfix out ('Using support branches for hotfixes')
