### ISSUE TITLE
Define new package directories, filenames, extensions

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3482]
## What

Agree on what the published package should look like for v5, focusing on what versions of the component JavaScript (and other entry points) need to exist, including:

- directory structures
- file names and extensions
- what transformations need to be made to each version (transpilation, addition of polyfills)

Draft updated documentation for [Importing JavaScript](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#javascript) that shows how and when the various versions of the JavaScript would be used by teams.

## Why

Build a shared vision for the package so we know where we're trying to get to.

We can use the agreed package structure and draft documentation when communicating the upcoming changes to the community, allowing us to get feedback and reduce the risk around the changes.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

### We've agreed on

```[tasklist]
- [x] Folder structures
- [x] Necessary transformations
- [x] File extensions
```

```[tasklist]
- [x] Update the README "Importing JavaScript" documentation
- [x] Update CHANGELOG with breaking change to swap `all.js` with ES modules
```

**Comment by colinrotherham** [comment]
Decision record for this issue:

* https://github.com/alphagov/govuk-design-system-architecture/pull/28

I've updated the tasks with remaining documentation changes

**Comment by colinrotherham** [comment]
That's all the outstanding changes to `govuk-frontend` ticked off in https://github.com/alphagov/govuk-frontend/pull/3950

Next it's the Frontend documentation site

**Comment by colinrotherham** [comment]
Going to close this one 🙌

Realised we've double-task-listed the Frontend Docs changes in:

* https://github.com/alphagov/govuk-frontend-docs/issues/308
