### ISSUE TITLE
Set up Babel transpilation for browser compatibility

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3504]
## What

Set up Babel transpilation using [`@babel/preset-env`](https://babeljs.io/docs/babel-preset-env) to transform modern JavaScript code so it runs without errors in `<script type="module">` ES module scripts (see [`.browserlistrc`](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/.browserslistrc) supported browsers).

Polyfill libraries like [`core-js`](https://github.com/zloirock/core-js#readme) can be considered later.

## Why

We want to maximise the chances of JavaScript running properly in browsers that will load our JavaScript.

Transformed code should not cause parsing or syntax errors. Since feature detection can guard against code we choose not to run, unsupported browser APIs don't have to be transformed.

## Who needs to work on this

Developers

## Who needs to review this

Developers

### Depends on
- [x] #3462
- [x] #3280 
- [x] #3281  
- [x] #3482
- [ ] https://github.com/alphagov/govuk-design-system-architecture/issues/27

```[tasklist]
### Done when
- [x] We've set up Babel to transform our files, according to the structure defined in #3482
```

**Comment by colinrotherham** [comment]
This issue previously included browser polyfills

Since we don't currently have the issue's been split out into:

* https://github.com/alphagov/govuk-frontend/issues/3948

**Comment by colinrotherham** [comment]
Linking the PR to enable Babel transforms:

* https://github.com/alphagov/govuk-frontend/pull/3820
