### ISSUE TITLE
Update components to only initialise where GOV.UK Frontend is supported

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3509]
## What

Prevent components from initialising where GOV.UK Frontend is not supported.

Services may know whether we’ll initialise or not using the presence of `govuk-frontend-supported` on the `<body>`.

> **Note**: We may complement this with either an `IS_SUPPORTED` boolean or `isSupported()` function so both us and services share the same value for sure.

## Why

Support for `noNodule` is not quite the same as support for `<script type=”module”>`, with [Safari 10.1 supporting the later but not the former](https://caniuse.com/es6-module). This means we’ll need to guard our component’s initialisation the same way we guard the addition of the styling class. Otherwise, we’ll risk running our JavaScript against elements that have not been styled anticipating the JavaScript to run.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Depends on
- [ ] #3479

## Done when

1. [ ] Components only initialise where GOV.UK Frontend is supported

**Comment by colinrotherham** [comment]
We completed this in:

* https://github.com/alphagov/govuk-frontend/pull/3801
* https://github.com/alphagov/govuk-frontend/pull/3872

I'll remove the dependency on https://github.com/alphagov/govuk-frontend/issues/3479 as we can still look to abstract our checks into `isSupported()` in future:

```mjs
if (!($module instanceof HTMLElement) || !isSupported()) {
  return this
}
```
