### ISSUE TITLE
Create a base class for the components

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3510]
## What

Introduce a base class for the components to gather shared behaviours (like receiving configuration, internationalisation, error handling).

## Why

Having a base class to handle the behaviours shared across multiple components will ensure they behave consistently. Ultimately, it could also be made available to services code to help create their own component.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] List the behaviours we'd want to refactor in that base class
- [ ] Design an API for the base class that allows sharing these behaviours
- [ ] Define if that base class is public or not
- [ ] Implement the base class
- [ ] Refactor components to use the base class
- [ ] Document the base class in the repository's internal documentation

**Comment by domoscargin** [comment]
We have an implementation of a base class doing some work behind the scenes, but are not intending to make it public in v5.

Capturing some of the thinking we've been doing around [validating component configuration](https://github.com/alphagov/govuk-frontend/pull/4176). We've currently got a bare bones validation for Character Count to cover what we were previously checking for in v4.

This involves a partial schema within the Character Count component, and a`validateConfig` method in the base component which we can add to later.

We'd potentially like to be able to validate every component's config completely (though we recognise the cost of doing this validation could outweigh the benefit).

Suggestions so far:

Repurpose component YAML files, clean ‘em up and add schemas, and use them to validate
[Move the YAML config into JavaScript and use that](https://github.com/alphagov/govuk-frontend/pull/3812).
Keep schemas within components, but make them more complete
Keep to this minimal approach and only validate certain things

**Comment by Izabela-16** [comment]
@romaricpascal marking this done but have a look.

**Comment by romaricpascal** [comment]
Closing this as we do have a base class in our components and it's been already marked as done in out GitHub project.
