### ISSUE TITLE
Run final manual accessibility testing of Exit This Page component

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#3525]
## What
Run a final internal accessibility audit of [the Exit This Page component code](https://github.com/alphagov/govuk-frontend/pull/2545) using our [accessibility testing grid](https://docs.google.com/spreadsheets/d/1O0rWoH3ah_rj2iJ2We9VfyHNOr0gOVItXRy3vKzuYSw/edit#gid=0).

We have created a testing grid to work from for this work: https://docs.google.com/spreadsheets/d/1ruOHpJ4ERL8nshwLpQ7N6WGoFscrFwkr215gxsVPO-Q/edit#gid=0

Part of https://github.com/alphagov/govuk-design-system/issues/1755

## Why
So we can ensure with confidence that we are shipping an accessible component.

## Who needs to work on this
@davidc-gds @querkmachine @owenatgov 

## Done when

- [x] The grid has been filled out
- [x] Those involved have reconvened to discuss any outliers or concerns

**Comment by 36degrees** [comment]
Is this done?

**Comment by owenatgov** [comment]
Thanks for the prompt in this @36degrees. This got a bit lost in the runup to publishing ETP and the WCAG 2.2 work.

I've just had a chat with @davidc-gds and we're going to reconvene on this after launch to see if there's anything clearly identifiable that we can iterate in 5.0/5.X and close it after that.

**Comment by kellylee-gds** [comment]
@owenatgov can this be closed?

**Comment by davidc-gds** [comment]
I think we're still waiting to do this. Been a bit hectic the past 2 weeks, unfortunately.

**Comment by Ciandelle** [comment]
Hey @owenatgov and @davidc-gds have either of you had a chance to look at this? And are we able to close it?

**Comment by owenatgov** [comment]
@Ciandelle Nothing has changed since my above message as I've only just come back from AL. Recommend we discuss this at planning next week but maybe me and David can commit to going through this soon.

**Comment by Ciandelle** [comment]
Sounds good, thanks :)

**Comment by davidc-gds** [comment]
New issues opened for skip link accessibility bugs found during the manual accessibility testing. Once these issues are resolved for skip links, any changes can be applied to the 'Exit this page' secondary link.

- https://github.com/alphagov/govuk-frontend/issues/4098
- https://github.com/alphagov/govuk-frontend/issues/4100

**Comment by davidc-gds** [comment]
And with those 3 GitHub issues spun-off, this issue is complete! Thanks for the patience!

Here's the finalised version of the manual accessibility testing spreadsheet:
https://docs.google.com/spreadsheets/d/1ruOHpJ4ERL8nshwLpQ7N6WGoFscrFwkr215gxsVPO-Q/edit?usp=sharing
