### ISSUE TITLE
Plan how we can support documentation for v4 and v5 in parallel

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3549]
## What

Define the location, content requirements, and processes for ongoing management for v4 and v5. Also define communications plans - directions for uses within the content (such as banners) and external comms (such as announcements).

## Why

Supporting two versions of the documentation is a large task, we need to figure out which constraints shape that piece of work (in terms of content organisation, design and technical feasibility, likely among other things).

## Who needs to work on this

Tech writers, Developers

## Who needs to review this

Tech writers, Developers

## Done when

We have agreed plans for where v4 and v5 documentation is published, what topics they will cover and processes for managing changes. Also, plans for how we will tell users where to find the information they need.

**Comment by claireashworth** [comment]
Draft proposal is ready for further review.
