### ISSUE TITLE
Should label hints be using aria-describedby?

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#355]
https://govuk-frontend-review.herokuapp.com/components/label

Our hint text in labels are directly embedded, if this were very long it could make these labels unwieldily.

Should we be using aria-describedby and move these hints outside the label?

https://developer.paciellogroup.com/blog/2014/12/using-aria-describedby-to-provide-helpful-form-hints/

```html
<label class="govuk-c-label">
  National Insurance number
  <span class="govuk-c-label__hint">
    It’s on your National Insurance card, benefit letter, payslip or P60. For example, ‘QQ 12 34 56 C’.
  </span>
</label>
```

vs 

```html
<input id="input-example" aria-describedby="label-hint"/>
<div class="govuk-c-label">
  <label class="govuk-c-label__text" for="input-example">National Insurance number</label>
  <span class="govuk-c-label__hint" id="label-hint">
    It’s on your National Insurance card, benefit letter, payslip or P60. For example, ‘QQ 12 34 56 C’.
  </span>
</div>
```

**Comment by selfthinker** [comment]
We were pondering the same for GOV.UK Elements, see https://github.com/alphagov/govuk_elements/issues/574

**Comment by nickcolley** [comment]
Also is recommended here https://www.w3.org/TR/wai-aria-practices-1.1/#radiobutton

**Comment by nickcolley** [comment]
You can see this in action here

- http://government-frontend.herokuapp.com/component-guide/radio
- https://github.com/alphagov/government-frontend/pull/552

specifically this commit https://github.com/alphagov/government-frontend/pull/552/commits/786ab1df467373f4b2e26e83102a52e26fd03218

**Comment by nickcolley** [comment]
This can be closed now, nice :)
