### ISSUE TITLE
Pagination in stacked mode relies on whitespace for correct text alignment

### ISSUE THREAD

**Issue by matteason** [alphagov/govuk-frontend#3554]
## Description of the issue

When in stacked (block) mode (no page numbers displayed), the pagination component relies on whitespace in the HTML to align the 'Previous' and 'Next' text with the labels below.

If there's no whitespace between the `govuk-pagination__icon` SVG and the `govuk-pagination__link-title` span, the 'Previous' or 'Next' link is displayed about 4 pixels too far to the left.

With whitespace:

![Previous and Next links stacked on top of each other, each with an example label below them and an arrow to the left. The text and labels are almost aligned vertically, demonstrated with a red line](https://user-images.githubusercontent.com/1935173/234560418-fd1fb657-711b-4a63-8f90-1c7e5cd28ce5.png)

Without whitespace:

![Previous and Next links stacked on top of each other, each with an example label below them and an arrow to the left. The text and labels are unaligned, demonstrated with a red line](https://user-images.githubusercontent.com/1935173/234560463-ab953204-9b55-4626-a917-acc3fc84e6a9.png)

(The text is actually slightly misaligned even in the first version - 'Previous' aligns with the end of the underline on the label rather than the first letter - I'm not sure if this is intentional)

## Steps to reproduce the issue

Open [this Design System pagination example](https://design-system.service.gov.uk/components/pagination/labels-2/index.html) in Firefox, right-click > Inspect the link, expand the `<a>` tag, click the whitespace node and press Delete

![HTML code from GOV.UK pagination component](https://user-images.githubusercontent.com/1935173/234561589-64a7dcd4-ce1d-4ee7-b691-55eaf488c52c.png)

## Actual vs expected behaviour

I would expect the text alignment to not rely on whitespace in the HTML. In my particular case (a [Vue component library](https://github.com/govuk-vue/govuk-vue)) I have no control over whether consumers of the library will have [the whitespace compression option](https://vuejs.org/api/application.html#app-config-compileroptions-whitespace) enabled or not, though by default it's enabled

There's been [a previous issue with whitespace causing layout changes in the header component](https://github.com/alphagov/govuk-frontend/issues/828), and there appears to be a fix for a similar issue when pagination is used in list mode:

https://github.com/alphagov/govuk-frontend/blob/eed94f8b29072325542f2ca4c4d0ffec6c4c543d/src/govuk/components/pagination/_index.scss#L57-L61

## Environment (where applicable)

- Operating system: Windows 10
- Browser: Firefox/Chrome
- Browser version: Firefox 112.0, Chrome 112.0.5615.138
- GOV.UK Frontend Version: 4.6.0

**Comment by matteason** [comment]
I'm happy to have a go at fixing this if you agree it's worth doing. I know you've just hit a code freeze for v5 so I wouldn't expect it to be merged any time soon.

**Comment by querkmachine** [comment]
@matteason Ah, the code freeze we had was for last week's [4.6.0 release](https://github.com/alphagov/govuk-frontend/releases/tag/v4.6.0). You're welcome to contribute a fix if you want!

**Comment by matteason** [comment]
Ah sorry! I misinterpreted [this comment](https://github.com/alphagov/govuk-frontend/pull/3523#issuecomment-1514421421). I'll see what I can do!

**Comment by frankieroberto** [comment]
Just a ➕1  to say I spotted this bug too – working on a service which uses this component on almost every page.
