### ISSUE TITLE
Improve visibility of build failures on Windows

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3638]
## What

We'd like a better way to detect that our build fails for Windows. Currently the Windows actions are only set up to be run manually due to [the slowness in restoring caches](https://github.com/actions/cache/issues/752). This means we only see them failing if we go and look (like recently with #3584). 

There are other routes we could take to get more visibility:

1. ~Run the workflow on a schedule, rather than manually, to get more frequent feedback~
2. Run the workflow on each PR, like our regular workflows for even more frequent feedback:
	a. As is, accepting that they'll be a bit slower
	b. Turning off caching on Windows (hypothesising that `npm install` will be quicker)
	c. Limiting the installation to the workspaces that are necessary
	d. Using a different way of caching (for example, uploading/downloading artifacts)

We may also want to consider whether to run macOS workflows if we start running thing more automatically.

**Update:** Removed scheduled approach as we've decided against it

## Why

Some contributors may be working on Windows and this would give us more certainty that our build would work for them.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] We've investigated the cost (engineering, maintainance...) and benefits of the different options
- [x] We've decided on which way to go
- [x] We've implemented the chosen option

**Comment by colinrotherham** [comment]
GitHub Actions "Tests" workflow now includes Windows in:

* https://github.com/alphagov/govuk-frontend/pull/3955
