### ISSUE TITLE
Make sure the `docs` folder is up to date with new structure

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#3639]
## What

Check that the documentation inside the repository (in `docs`) are up to date with the new repository structure, especially:

- the docs for releasing to npm
- the docs for pushing a pre-release as a branch on Github
- but also all the other pieces of documentation in there

## Why

We're making [substantial changes to our repository structure](https://github.com/alphagov/govuk-frontend/issues/3291) ahead of v5. We need to ensure that our docs reflect these changes so they can help future us and contributors appropriately.

Pushing a pre-release branch, especially, is really helpful for contributors as it allows them to install their changes as an npm package (without releasing to npm)

## Who needs to work on this

Developers, Tech writers?

## Who needs to review this

Developers, Tech writers?

## Done when

```[tasklist]
### We've reviewed
- [ ] The npm release docs (both from main and from support branch)
- [x] The docs for making a pre-release on Github
- [ ] The rest of the docs
```

**Comment by romaricpascal** [comment]
Closed by #3975 (the PR was referencing the wrong issue).
