### ISSUE TITLE
Summary card actions must specify which card they are for

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-frontend#3673]
This issue is from May 2023 external accessibility audit report.

**WCAG Reference:** 
2.4.4 Link Purpose (In Context) (Level A)
[Understanding Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html) | [How to Meet Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/quickref/#link-purpose-in-context)

2.4.9 Link Purpose (Link Only) (Level AAA)
[Understanding Link Purpose (Link Only)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-link-only.html) | [How to Meet Link Purpose (Link Only)](https://www.w3.org/WAI/WCAG21/quickref/#link-purpose-link-only)

**Issue ID:**
DAC_Link_Purpose_01

**URLs:**
[https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/work-history#/delete](https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/work-history#/delete)

## Screen shots
<img width="529" alt="Summary card component with 'delete work history' link" src="https://github.com/alphagov/govuk-frontend/assets/56260216/2c53f7b4-0fae-46d7-9534-f1c8813c2025">

The ‘Delete work history’ links for each section, rely on surrounding content to understand their context and which work they will be deleting. As the link is not marked up in the same list item, table cell, or using different methods of aria, the link requires a user to move their focus to understand which work history they will be deleting.

## Current code ref(s)
`#main-content > div > div > div:nth-child(2) > div.govuk-summary-card__title-wrapper > div > a`

## Screen-reader comments
> “I located multiple links on the page which read to me as ‘Delete work history’. These links related to different sections of the page and would delete different areas although at the time of testing did not perform a function. I was not aware when browsing out of context that the links would perform a different action or what would be deleted as the links did not contain enough description within the link text to make this obvious. Giving each link text clear and unique information that can be understood either in or out of context will prevent any confusion and will ensure that I can select easily.”

## Solution
Ensure that all links are descriptive of their purpose and functionality, allowing users of screen reading assistive technologies to confidently interact and understand the link.
The best way to make sure of this, is to locate links where some additional link context is needed to understand the purpose of the link. For each link:

1. Check whether the context is contained in the same sentence, paragraph, list item, table cell, or associated table headers.
2. Check whether the link context can be programmatically determined in some other way, for example, by using a WAI-ARIA property such as aria-label, aria-labelledby or aria-describedby on the link to provide sufficient context.

Consider adding additional text to the link which can be visually hidden to maintain the visual aesthetic.

**Comment by Marat-Faizov** [comment]
Hello 
On the [example](https://design-system.service.gov.uk/components/summary-list/card-with-actions/) from summary card design system pattern. action links on top level in card header have repeated content in the brackets. ie. `Delete choice +  of University of Gloucestershire (University of Gloucestershire)`
I was wondering if the additional visually hidden text in the brackets, crept in by mistake on summary card header action links. I think it only meant to be on action links within summary card. Would be good to clarify this. I think it meant to be just `Delete choice +  of University of Gloucestershire `
