### ISSUE TITLE
Hover states for checkboxes and radios aren't visible in Windows High Contrast Mode

### ISSUE THREAD

**Issue by davidc-gds** [alphagov/govuk-frontend#3695]
This issue is from May 2023 external accessibility audit report.

**Usability issue**
A component did not display a change of state to indicate mouse hover.

**Issue ID:**
DAC_Usability_Mouse_Hover_01

**URLs:**
Example page link: https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/search

Relevant guidance pages: [Checkboxes](https://design-system.service.gov.uk/components/checkboxes/) and [Radios](https://design-system.service.gov.uk/components/radios/).

## Screen shots
<img width="335" alt="A set of radio options within a search filter module, shown in Windows High Contrast Mode. The mouse pointer is hovering over the first radio input and there is no visual change to indicate a hover state." src="https://github.com/alphagov/govuk-frontend/assets/98318778/77e0094c-b9ae-4c16-ac42-abeadf7c9584">

<img width="328" alt="A set of checkboxes within a search filter module, shown in Windows High Contrast Mode. The mouse pointer is hovering over the first checkbox input and there is no visual change to indicate a hover state." src="https://github.com/alphagov/govuk-frontend/assets/98318778/57191928-5d47-4f23-85e5-8dc52d7fd0e2">

The checkboxes and radio buttons do not display a visible change when receiving mouse hover in high contrast mode. This means that some users may not be able to distinguish when they are able to activate the component and form.

## Current code ref(s)
`#main-content > form > div.govuk-grid-row > div.govuk-grid-column-one-third > ul > li:nth-child(4) > div > fieldset > div > div:nth-child(1)`

```
<div class="govuk-checkboxes__item">
    <input class="govuk-checkboxes__input" id="organisation" name="organisation" type="checkbox" value="hmrc">
    <label class="govuk-label govuk-checkboxes__label" for="organisation">HM Revenue and Customs (HMRC)</label>
</div>
```

### Low vision user
> “I noticed that each radio button/checkbox does not become highlighted when hovering the pointer over them. I found this to be an issue because my eye condition prevents me from clearly seeing the pointer change state. Therefore, I rely on highlighted elements on the radio buttons etc, to visibly indicate to me which radio button I am hovering over. It would be beneficial for me that each button is to become highlighted with an underline for example, that appears/disappears on the text when mouse hover occurs, as this will help me to determine which radio button/checkbox/button I am hovering over also to help me determine that the component can be selected.”

## Solution
Consider adding a clear indication for users when hovering over inputs and forms with a mouse to indicate that they are interactive.
Example: 
```
.govuk-radios__input {
    cursor: pointer;
}
```

**Comment by querkmachine** [comment]
I also find this one a bit interesting. 

It's not specific to High Contrast Mode, as we do not provide a hover style on radios or checkboxes in regular colour modes either—we only do this on the smaller variants to indicate that despite the smaller visual appearance they still have the same target area as the regular variant.

In High Contrast Mode, disabled (non-interactive) inputs appear in a different colour than active equivalents. I'm not sure if the low vision user quotes was unaware of this distinction. 

Generally speaking, having a hover style on radios and checkboxes is uncommon. Chrome and Firefox (macOS) only slightly darken the input border colour on hover, not by a degree to be particularly noticable. Safari on macOS does not apply any style changes on hover at all. None change the cursor appearance or the appearance of the associated label.

**Comment by joelanman** [comment]
yes, its the 'solution' part I was confused by, which refers to adding a pointer hand

**Comment by davidc-gds** [comment]
Ahh I didn't even notice that the example code they offer in their solution is at odds with the rest of their info in this issue 😂 

I would personally chalk that up to a copy/paste from a set of pre-made solution texts they probably work with. In our case, I would say that example code is unhelpful. But the main idea of having a more visible hover state for contrast-themed setups (like Windows High Contrast Mode) does still seem like a solid idea to me, which would increase usability.

**Comment by 36degrees** [comment]
I can provide a little additional context as to _why_ the small radios and checkboxes (hereafter referred to as 'controls' for brevity!) have a hover state but the regular size ones don't.

As beeps has already noted, the small controls actually have the same target size (clickable area) as regular controls. In order to achieve this whilst still making the controls visually more compact we remove the 'gap' between the controls.

You can see this clearer if you make the underlying HTML inputs visible again.

Moving between regular controls, there's a clear gap between each input where the cursor changes back to the default pointer:

https://github.com/alphagov/govuk-frontend/assets/121939/08353dd2-8de0-407f-a773-7738a84a116a

Moving between small form controls, there is no gap between each input, the cursor moves straight from one input to the next:

https://github.com/alphagov/govuk-frontend/assets/121939/99147249-0859-4603-9f7e-bc92b3497a85

The hover state was therefore added to the small controls make it less ambiguous which one would be activated if you clicked the area between each visible control.
