### ISSUE TITLE
Error resolving GOV.UK Frontend subpath exports in Node.js 17+

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3755]
## Description of the issue

We've identifying two scenarios when trying to `require()` or `import` GOV.UK Frontend

1. Node.js >= 17 errors with GOV.UK Frontend v4 [folder mapping in `"exports"`](https://nodejs.org/docs/latest-v18.x/api/deprecations.html#dep0148-folder-mappings-in-exports-trailing-)
2. Node.js <= 12.18 errors with GOV.UK Frontend v5 (unreleased) [subpath patterns in `"exports"`](https://nodejs.org/docs/latest-v18.x/api/packages.html#subpath-patterns)

```console
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './govuk/all.js' is not defined by "exports" in /Users/romaric.pascal/code/package-exports/node_modules/govuk-frontend/package.json
```

This can happen if extending our components and having a test suite run with a tool like [Mocha](https://mochajs.org/) that uses native Node `require` or `import` to load modules.

## Steps to reproduce the issue

1. Create a new prototype GOV.UK Frontend v4.6.0
    ```shell
    npx govuk-prototype-kit create package-exports
    cd package-exports
    ```
2. Run Node.js `require.resolve()` to locate GOV.UK Frontend's default exports
   ```shell
   node --eval "console.log(require.resolve('govuk-frontend'))" --conditions require
   node --eval "console.log(require.resolve('govuk-frontend'))" --conditions import
   ```

3. Run Node.js `require.resolve()` to locate a subpath export
   ```shell
   node --eval "console.log(require.resolve('govuk-frontend/govuk/all.js'))"
   ```

   Using Node.js 16 you'll see the following warning:
   
   ```console
   [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./govuk/" in the "exports" field module resolution of the package at /node_modules/govuk-frontend/package.json.
   Update this package.json to use a subpath pattern like "./govuk/*"
   ```

   Using Node.js 17+ you'll see the following error:

   ```console
   Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './govuk/all.js' is not defined by "exports" in /node_modules/govuk-frontend/package.json
   ```

## Actual vs expected behaviour

Instead of receiving an error, the subpath export should should be resolved properly.

@colinrotherham suggested the following update to our exports to achieve so, using both :

```
"exports": {
  ".": {
    "sass": "./govuk/all.scss",
    "import": "./govuk-esm/all.mjs",
    "require": "./govuk/all.js"
  },
  "./govuk/": "./govuk/",
  "./govuk/*": "./govuk/*",
  "./govuk-esm/": "./govuk-esm/",
  "./govuk-esm/*": "./govuk-esm/*",
  "./package.json": "./package.json"
},
```

**Comment by colinrotherham** [comment]
Thanks @romaricpascal

The hybrid idea was because [**package.json** subpath patterns](https://nodejs.org/docs/latest-v18.x/api/packages.html#subpath-patterns) requires Node.js 12.20.0+

But we should check if a single `"./*": "./*"` catch-all is all we need:

```json
"exports": {
  ".": {
    "sass": "./govuk/all.scss",
    "import": "./govuk-esm/all.mjs",
    "require": "./govuk/all.js"
  },
  "./govuk/": "./govuk/",
  "./govuk-esm/": "./govuk-esm/",
  "./package.json": "./package.json",
  "./*": "./*"
},
```

**Comment by colinrotherham** [comment]
@romaricpascal Updated the description to show how both v4 and v5 are affected

**Comment by colinrotherham** [comment]
Node.js <= 12.18 fix (v5 only) ready for review:

* https://github.com/alphagov/govuk-frontend/pull/3816

Node.js >= 17 fix (v4 only) ready for review:

* https://github.com/alphagov/govuk-frontend/pull/3817
