### ISSUE TITLE
The Prototype Kit has a hardcoded reference to the assets folder which has moved in v5

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#3759]
## What

The [changes to our repo structure in #3498](https://github.com/alphagov/govuk-frontend/pull/3498/commits/3f0db82f9cdeb8c0f1d2296753ebf51ee02b8d08) mean that the structure of the published package will change in v5. Most files have moved inside a top-level `dist` folder. For example, the favicon has moved from `govuk/assets/images/favicon.ico` to`dist/govuk/assets/images/favicon.ico`.

However, the govuk-branded layout in the Prototype Kit [includes a hardcoded `assetPath`](https://github.com/alphagov/govuk-prototype-kit/blob/d12135d3731c649d3101781a45979c9b425caaf9/lib/nunjucks/govuk-prototype-kit/layouts/govuk-branded.njk#L1) that references the old assets location.

Work with the prototype team to support passing the asset path as part of the [Prototype Kit config file](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs).

## Why

We need a way for the Prototype Kit to know where to find the assets in v5, whilst still allowing it to work with older releases of GOV.UK Frontend.

## Who needs to work on this

Developers, Developers from the Prototype team

## Who needs to review this

Developers, Developers from the Prototype team

## Done when

- [x] The Prototype Kit config file in GOV.UK Frontend sets the assets path correctly
- [x] The integration between Frontend and the Prototype Kit has been manually tested to ensure that the assets path is correctly set
- [x] [If possible] Automated tests have been added that ensure the Prototype Kit sets the asset paths correctly based on the config in GOV.UK Frontend

**Comment by colinrotherham** [comment]
Linking this [alternative idea for `require.resolve()`](https://github.com/alphagov/govuk-frontend/issues/3721#issuecomment-1568478864) which locates the assets path (same code) for both v4 and v5

For ES modules we also have [`import.meta.resolve()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve) but it needs [`--experimental-import-meta-resolve`](https://nodejs.org/api/esm.html#importmetaresolvespecifier-parent) in Node.js so would require us to continue providing CommonJS (or UMD) support

**Comment by romaricpascal** [comment]
@colinrotherham Sorry, I stepped a bit on this piece of work. To facilitate discussions for the Prototype Kit team, I quickly spiked the approach described by Ollie in [spike-prototype-kit-constant](https://github.com/alphagov/govuk-frontend/tree/spike-prototype-kit-constant) to check that it did indeed solve the 404 when used with @nataliecarey's branch, which it does 🥳. It's just a spike branch, with [preview-spike-prototype-kit-constant](https://github.com/alphagov/govuk-frontend/tree/preview-spike-prototype-kit-constant) so very throwaway, just to validate things work.

**Comment by romaricpascal** [comment]
Also a few thoughts from that quick spike:

- it’s a bit weird to have the `/plugin-assets/govuk-frontend` part of the path inside `govuk-frontend` package . It looks like an implementation detail from the Prototype Kit (where the packages content are served from) leaking into the plugins. Is that part something that could be kept inside the Prototype Kit so that plugins only specify the part that corresponds to their package (eg. with relative paths getting prefixed by `/plugin-assets/<NAME_OF_THE_PLUGIN>`, leaving the possibility to specify absolute paths or full URLs if assets are on a CDN)
- the array of object structure is a bit strange to edit for that kind of mapping, where a plain object feels more natural. Are there other keys than name and value planned for this list of constants?
- this brought to mind the question of where these constants would be documented so users would know what to tweak. But that’s a bit of a separate topic.

**Comment by colinrotherham** [comment]
>@colinrotherham Sorry, I stepped a bit on this piece of work.

Thanks @romaricpascal, no that's great

Here's the part I've been working on, running the Prototype Kit with our local GOV.UK Frontend:

* https://github.com/alphagov/govuk-frontend/pull/4056

**Comment by colinrotherham** [comment]
I've been working on path changes in this PR:

* https://github.com/alphagov/govuk-prototype-kit/pull/2306

@romaricpascal Your comments regarding `/plugin-assets/govuk-frontend` were right. In the Sass for example, we'd receive this part using [**`$govuk-extensions-url-context`** in `init.scss`](https://github.com/alphagov/govuk-frontend/blob/c0aa275a42d239d4bd9f76cfcb6c694959e4069e/src/govuk-prototype-kit/init.scss#L5-L6) which the kit provides

E.g. Prototype management pages use `/manage-prototype/dependencies/govuk-frontend`

## GOV.UK Frontend paths
The following paths are used currently in various places:

1. Base path: `node_modules/govuk-frontend`
2. Entry path: `node_modules/govuk-frontend/govuk/all.js`
3. Include path: `node_modules/govuk-frontend/govuk`

**Comment by colinrotherham** [comment]
PR ready for review

Some tests are failing because scripts aren't waiting for the GitHub preview to finish installing

**Comment by colinrotherham** [comment]
Happy to say this is now closed in https://github.com/alphagov/govuk-prototype-kit/pull/2306

The Prototype Kit supports `govuk-frontend@4.0.0` so backporting new config fields wasn't feasible

Instead we simply join `/assets` to the directory of our `main` package export (as [shown above](https://github.com/alphagov/govuk-frontend/issues/3759#issuecomment-1580240204))

```mjs
const { dirname, join } = require('path')

// `govuk-frontend@4` /path/to/project/node_modules/govuk-frontend/govuk/assets
// `govuk-frontend@5` /path/to/project/node_modules/govuk-frontend/dist/govuk/assets

const assetsPath = join(dirname(require.resolve('govuk-frontend')), 'assets')
```
