### ISSUE TITLE
Add a 'highlighted text' style

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#396]
There's occasionally the need to highlight text in user interfaces.

For example:

- matching text in search results
- placeholders in GOV.UK Notify templates
- showing changes to contracts in Digital Marketplace

The [Home Office design system](https://home-office-digital-patterns.herokuapp.com/components/highlighting-matches) has a style for this.

**Comment by nickcolley** [comment]
Related https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark

**Comment by timpaul** [comment]
Nice! And looks like we already have a default style for mark on GOV.UK:

![image](https://user-images.githubusercontent.com/1590604/34212160-57ccaf10-e593-11e7-8a63-4b246a407b74.png)

**Comment by igloosi** [comment]
yeah all new browsers have default style built-in

**Comment by nickcolley** [comment]
@timpaul can we close this?

**Comment by govuk-design-system** [comment]
Yep

**Comment by timpaul** [comment]
Yep

**Comment by timpaul** [comment]
It's possible that the default browser styles for highlight are not accessible enough:

https://twitter.com/patrick_h_lauke/status/963503046813782016
