### ISSUE TITLE
Update the Prototype Kit config to load the JavaScript as a module

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#3972]
## What

Update our Prototype Kit configuration to load the JavaScript as module

To maintain compatibility with existing plugins and prototypes that rely on the UMD `window.GOVUKFrontend` global, we should update our `init.js` plugin initialisation script to polyfill this window

But to other scripts running too early (global not added yet) the kit must add the [`defer` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer)

## Why

To follow our new loading strategy

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] [Plugin config `scripts`](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs#L53) script `all.bundle.js` (UMD) replaced with `govuk-frontend.min.js` (ESM)
- [x] [Plugin config `scripts`](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs#L53) script `init.js` migrated to ESM with `window.GOVUKFrontend` polyfill
- [ ] ~https://github.com/alphagov/govuk-prototype-kit/issues/2353~

**Comment by colinrotherham** [comment]
To help us test this, I've created:

* https://github.com/alphagov/govuk-frontend/pull/4056

**Comment by colinrotherham** [comment]
We have a couple of potential approaches for this issue:

1. Loading GOV.UK Frontend ESM bundle using `<script type="module">`
2. Loading GOV.UK Frontend UMD bundle using `<script type="module">`

But both are blocked without considerable collaboration with the Prototype Kit, such as dynamically swapping between `<script>` and `<script type="module">` based on GOV.UK Frontend version number

For approach 1) we'd see plugin and user code break on removed window globals that don't exist
For approach 2) we'd see plugin and user code break on deferred window globals that are added later

```js
window.GOVUKPrototypeKit.documentReady(function () {
  window.GOVUKFrontend.initAll()
})
```

But since the Prototype Kit is compatible with GOV.UK Frontend v4.0.0 and up, we'd also see legacy Rollup UMD wrappers from our older releases break in an ES module context, as the wrapping code throws with:

```console
TypeError: undefined is not an object (evaluating ‘global.GOVUKFrontend = {}’)
```

### Old Rollup wrapper (v4.x)
```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define('GOVUKFrontend', ['exports'], factory) :
  (factory((global.GOVUKFrontend = {})));
}(this, (function (exports) { 'use strict';
```

### New Rollup wrapper (v5.x)
```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define('GOVUKFrontend', ['exports'], factory) :
  (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.GOVUKFrontend = {}));
})(this, (function (exports) { 'use strict';
```

**Comment by colinrotherham** [comment]
I've kept this issue in review as maintaining classic `<script>` might be our best option

Do we mind if prototypes run without `<script type="module">` protections?

**Comment by colinrotherham** [comment]
One good suggestion was to upgrade user scripts from `<script>` to `<script defer>`

This would let GOV.UK Frontend switch on `type="module"` without user scripts running too early

**Comment by colinrotherham** [comment]
We discussed this in dev catch-up this morning.

It was initially proposed that we hold back our [plugin config `scripts`](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs#L53) as UMD for compatibility reasons, but this means GOV.UK Prototype Kit users would fall behind with our [documentation](https://frontend.design-system.service.gov.uk) which will soon use ES modules by default

### New decision
Instead we agreed to update to ES modules with compatibility in mind:

* Collaborate with GOV.UK Prototype Kit to add `defer` to plugin scripts by default
* [Plugin config `scripts`](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs#L53) script `init.js` migrated to ESM with `window.GOVUKFrontend` polyfill
* [Plugin config `scripts`](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs#L53) script `all.bundle.js` (UMD) replaced with `govuk-frontend.min.js` (ESM)

These steps will eliminate all major breaking changes, but our releases notes will still guide advanced users

**Comment by colinrotherham** [comment]
Just going to re-open this as we still need to add `defer` to plugin scripts loaded _after_ GOV.UK Frontend

**Comment by colinrotherham** [comment]
All done. Will track the load order issue in:

* https://github.com/alphagov/govuk-prototype-kit/issues/2353
