### ISSUE TITLE
Prevent `initAll` from failing when one of the components' instantiation errors

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4010]
## What

Prevent `initAll()` from failing at the first component that may error during `instantiation` and let it carry on to initialise all the other components. 

For components that do error, `initAll` should log the error to the console so users know something went wrong.

As [components would throw if GOV.UK Frontend is not supported](https://github.com/alphagov/govuk-frontend/issues/4009), we'll want to not clutter the logs with an error for each components. Instead, we'll want to abort early and only log once that GOV.UK Frontend is not supported.

## Why

With components [throwing errors](https://github.com/alphagov/govuk-frontend/issues/4009) when instantiated over invalid markup, we want to keep `initAll()` as a quick "fire and forget" way to initialise all components on the page.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] We've agreed on an implementation (among [those offered in comment](https://github.com/alphagov/govuk-frontend/issues/4010#issuecomment-1650193531) or new propositions)
- [ ] `initAll()` logs any error happening during components' initialisation and initialises properly components that do not error.

**Comment by romaricpascal** [comment]
Possible implementations:

1. Add `try/catch` blocks in the `initAll`, simple if a bit repetitive. We'll likely want to go a step further.

2. Introduce a `create` static method on our components, which would catch and log the errors thrown by the constructor. This method does not necessarily need to be part of the public API for v5, to keep the API minimal

This would allow our `initAll` method to not get riddled with `try/catch` blocks and maybe centralise the implementation in a base class (as the logic would be the same for all components).

3. `initAll` could even be refactored to invoke a `createAll` static method on our components, that would look up the elements to initialise using a static `selector` property and invoke `create` for each of them (in a loop similar to [this spike](https://github.com/alphagov/govuk-frontend/compare/wip-classes#diff-d723b3f52ca2a1fa599015f8cf2d3fa4dbc0161e45516e4c071c6d52a5c52efeR49)).

Other considerations:
2 and 3 introduce the possibility of a base class for our component to centralise the implementation of these static methods. It's worth noting that unless we find a clever workaround, we'll need to have [these instance methods on each component class for proper typing](https://github.com/alphagov/govuk-frontend/compare/wip-classes#diff-975f2bf8f043e295f28e91aaa8f2965604ecd98db097009192b1e6defa37c12bR104) [^1]

[^1]: >As we cover in [our section on classes](https://www.typescriptlang.org/docs/handbook/2/classes.html), a class has two sides to its type: the static side and the instance side. Generic classes are only generic over their instance side rather than their static side, so when working with classes, static members can not use the class’s type parameter.

    [From TypeScript documentation](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-classes)

**Comment by romaricpascal** [comment]
After discussion at dev catch up, looks like there's quite a few unknowns around static methods that needs lifting (which throw and which don't, which return something and what). This is something that can wait till after v5, even though these static methods would have remained internal and free to be reshaped.

We can still start some tidy-up of `initAll` by making it loop over our components with static properties providing the value of `data-module` and the key to access in the `config`:

```js
[Accordion, Button /*,... */].forEach(Component => {
  const $elements = $scope.querySelectorAll(`[data-module="${Component.moduleName}"]`)
  $elements.forEach($element =>
     try {
       new Component($element, config[Component.configKey])
     } catch (error) {
       console.error(error)
     }
  )
})
```

The `configKey` may even be something we derive from the `moduleName` to avoid leaking something related to `initAll` (the key in the map of all component's configuration) in the component's classes themselves 😊 ?

**Comment by 36degrees** [comment]
> The `configKey` may even be something we derive from the `moduleName` to avoid leaking something related to `initAll` (the key in the `config` map received by `initAll` is kind of that module's responsibility) in the component's classes themselves 😊 ?

Is it just a case of lower-casing the first letter of the component name?

Also wondering how well the TypeScript compiler will be able to follow all the references… I guess we'll see!

**Comment by 36degrees** [comment]
I've pushed where I've got to and raised a draft pull request. Unfortunately I've not worked out how to make the TypeScript compiler happy when passing config, so that still needs doing – I had to skip commit hooks to allow me to push what I'd done so far.

I'm off for a few days now – happy for someone else to pick this up in my absence.
