### ISSUE TITLE
Mark internal classes and functions as `@internal`

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#4017]
## What

Annotate all of our 'internal' classes or functions (like the I18n class and the mergeConfigs function) as `@internal`.

Remove any other access annotations (like `@private`) from classes and functions. (Individual properties within an `@internal` class can still be marked as private)

## Why

This is part of our decision to [reset the public JavaScript API](https://github.com/alphagov/govuk-design-system-architecture/blob/main/decision-records/008-reset-the-javascript-api.md).

When using access related annotations we want to be clearer about whether the annotation refers to:

- access in context of the class – whether a particular method can be called from outside the class, including by other classes in GOV.UK Frontend
- access in context of the library – whether a particular method is considered to be available for use outside of GOV.UK Frontend

Using `@private`, `@protected` and `@public` only for describing class-level access helps with this.

We can then use `@internal` (and potentially in the future [the other release tags](https://api-extractor.com/pages/tsdoc/doc_comment_syntax/#release-tags)) for library level access annotations.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] All 'internal' classes and functions are marked as `@internal`
- [x] Other access annotations are removed from the class JSDoc and any internal functions

**Comment by colinrotherham** [comment]
Related PR (and [commit](https://github.com/alphagov/govuk-frontend/pull/3958/commits/b0410bc18ba14f866c484051cc388568c633ee13)) regarding comment removal for `@internal` etc

* https://github.com/alphagov/govuk-frontend/pull/3958
