### ISSUE TITLE
Review ElementErrors and tie up any loose ends

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4036]
## What

Review the MissingElementError work (tracked here: https://github.com/alphagov/govuk-frontend/issues/3478) and tie up any loose ends before a content review.

- [Skip Link](https://github.com/alphagov/govuk-frontend/issues/4128)
- [Exit this page](https://github.com/alphagov/govuk-frontend/issues/4129)
- [Header](https://github.com/alphagov/govuk-frontend/issues/4130)
- [Radios & Checkboxes](https://github.com/alphagov/govuk-frontend/issues/4131)
- [Character Count](https://github.com/alphagov/govuk-frontend/issues/4125)
- [Tabs](https://github.com/alphagov/govuk-frontend/issues/4127)
- [Accordion](https://github.com/alphagov/govuk-frontend/issues/4126)

## Why

This is part of our work to [have our components throw rather than silently return during initialisation](https://github.com/alphagov/govuk-design-system-architecture/blob/main/decision-records/009-throw-errors-component-constructors.md).

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] Review the list of affected components for consistency, functionality and any other concerns
- [x] Ensure errors are ready for content review
- [ ] #4323

**Comment by romaricpascal** [comment]
Let's divide this issue into smaller ones, in order of complexity:
 
- Skip Link
- Exit this page
- Header
- Radios & Checkboxes
- Character Count
- Tabs
- Accordion
- Review any loose ends (keep this issue)

**Comment by domoscargin** [comment]
From a discussion on slack:

We may want to look at removing the `element` param from the `ElementError` and just tell the error what's missing or invalid. We're using it like a boolean, and often just pass in `null`.

**Comment by romaricpascal** [comment]
Maybe it's a sign that we need to have the `ElementError` just accept a generic string message and move the formatting to separate helper functions rather than pass that boolean-ish first param: `missingElementMessage` and `missingOrMistypedElementMessage`.

I'd like to propose something like the following (the passing of the `componentName` being a parallel concern as it affects multiple errors, we can always add in an extra `options` parameter to the constructor anyway or with a `componentErrorMessage` function to wrap other message).

```js
class ElementError extends Error {
  name = 'ElementError'
}

function missingElementMessage(identifier) {
  return `${identifier} is missing`  
}

// Two little updates here:
// - identifier as first param to keep in line with the `missingElementMessage
//
function missingOrMistypedElementMessage(identifier, {value, expectedType = HTMLElement.name}) {
  if (!value) return missingElementMessage(identifier)

  return `${identifier} is not of the type ${expectedType}`
}

throw new ElementError(missingElementMessage('button'));
throw new ElementError(missingOrMistypedElementMessage('input', {value: $input});
```

Depends on how we want to word things for 4072, and is an internal refactoring so could wait if necessary.
