### ISSUE TITLE
Constraining text Inputs and Safari autofill

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#411]
If autofill is turned on (default) Safari adds the "person" icon to the right hand side of the input.

Relating to constraining inputs to an appropriate size of their content, this example on the DVLA Driving Licence service shows the autofill icon completely obscuring the content of the input. The user needs to type blindly and will only see what they have typed by de-focussing. (side note, this example will also lead to a year typed many times which is also not apparent even after de-focussing)

![safari-autofill](https://user-images.githubusercontent.com/23356842/34563968-c79214e2-f14c-11e7-85ce-84322d76c4e8.gif)

**Do we want to suggest that inputs should:**
be "x" many characters bigger than expected content
or 
override the autofill icon all together?
```
input::-webkit-contacts-auto-fill-button {
  visibility: hidden;
  display: none !important;
  pointer-events: none;
  position: absolute;
  right: 0;
}
```

**Comment by nickcolley** [comment]
Hi Dave,

Is this an issue with GOV.UK Frontend? Can we close this?

**Comment by nickcolley** [comment]
The example given does not relate to GOV.UK Frontend, please re-open if this is not the case.
