### ISSUE TITLE
Draft a blog post outlining the changes in GOV.UK Frontend v5.0

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#4123]
## What

Draft a blog post that outlines the changes coming in GOV.UK Frontend v5.0.

The release notes describes the detail of the changes, so the blog post should provide a high level overview and focus on the context and rationale for why we've made the change, some of the interesting challenges, etc.

It might also be a good place to flag future upcoming changes (for example building out the JS API, dropping support for LibSass…)

## Why

Writing a blog post about the v5 changes:

- increases the visibility of the v5 release (especially for non-technical people for whom GitHub releases and Dependabot updates etc aren't going to be visible)
- allows us to share the driving forces behind the changes, helping to take people on the journey with us and to understand why these changes (which require service teams to do work) are beneficial and necessary
- promotes GDS as a great place to work, where we get to work on loads of interesting things 🤓 

## Who needs to work on this

Everyone! But probably mainly developers and designers.

## Who needs to review this

Everyone! But mainly a content designer and the comms team.

## Done when

- [ ] We have a draft blog post for v5.0 outlining the main changes

**Comment by 36degrees** [comment]
[Draft so far](https://docs.google.com/document/d/1KFDUCAayYDHpB853jSB9k7SaHGwEwLOWogTZJ3ZHnD8/edit#heading=h.11naifllz7qb) (only visible to GDS folks)

The lessons learned and results sections are just a sketch at the minute, but reasonably happy with the top bit.

If anyone does fancy picking it up and running with it, feel free. Not precious about it being edited, reworked, revised etc.

**Comment by stevenjmesser** [comment]
Looks good to me. I've added [one comment](https://docs.google.com/document/d/1KFDUCAayYDHpB853jSB9k7SaHGwEwLOWogTZJ3ZHnD8/edit?disco=AAABEr5QPU8) but otherwise I think it hits all the right points.

**Comment by 36degrees** [comment]
Sadly, I think too much time has passed since v5 was released.

(Feel free to re-open if you disagree and want to do something with it!)
