### ISSUE TITLE
Throw errors during Radios and Checkboxes initialisation if key HTML elements are missing

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#4131]
## What

Update our JavaScript components requiring specific HTML elements to be present so they throw a `MissingElementError` (extending `GOVUKFrontendError`) rather than silently fail:

- The `<input>` elements

## Why

This is part of our work to [have our components throw rather than silently return during initialisation](https://github.com/alphagov/govuk-design-system-architecture/blob/main/decision-records/009-throw-errors-component-constructors.md).

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Component has been updated to throw errors

**Comment by romaricpascal** [comment]
A little heads up on the wording, [where we've tried to align the messages of the tests for the errors to `throws when ... is missing [ + optional extra context]`](https://github.com/alphagov/govuk-frontend/pull/4206#discussion_r1323214316)
