### ISSUE TITLE
Update I18n errors to extend GOVUKFrontendError

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4144]
## What

Throw errors extending `GOVUKFrontendError` inside `I18n` and `extractConfigByNamespace`.

## Why

The `I18n` class, as well as `extractConfigByNamespace`, throw simple `Error` with a custom message. These should throw errors that extend `GOVUKFrontendError` to match what we do when throwing during instantiation.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] The i18n class throws errors that extend `GOVUKFrontendError`

**Comment by colinrotherham** [comment]
@romaricpascal Think we should close this issue?

We've flagged the utility `extractConfigByNamespace()` as `@internal` so the errors never get thrown

ESLint logs "Unnecessary conditional, value is always truthy" using `@typescript-eslint/stylistic-type-checked`

**Comment by colinrotherham** [comment]
Removed in https://github.com/alphagov/govuk-frontend/commit/72f9ae31bdc0b709e22e062ee92cd2a3e9967453
