### ISSUE TITLE
Follow up session to complete scoping of 'show/hide' password work

### ISSUE THREAD

**Issue by Ciandelle** [alphagov/govuk-frontend#4153]
## What
Arrange a follow up session to scope the work to add a 'show / hide' password variant.

## Why
So we understand:
- the risks to users
- the risks to delivery
- Order of the work
- Further details of the timeline
- The tools needed to complete the work

## Who needs to work on this
Developer, Designer, Accessibility Specialist

## Who needs to review this
Product Manager, Delivery Manager, Content Designer

## Done when
- [x] Planned a follow up session
- [x] Run a follow up session
- [x] Documented decisions
- [x] Decision log has been implemented
- [x] Updated [epic card](https://github.com/alphagov/govuk-frontend/issues/4063) with plan of action

**Comment by Ciandelle** [comment]
Question has gone out to the team over whether to park this work until post DSDay - waiting on a response.

**Comment by kellylee-gds** [comment]
@Ciandelle how would you feel about reframing this follow up session to "what's next" and scoping what the first stage of this work looks like.

Then when we have that scoped, we can identify risks, tools etc, and build a timeline.

**Comment by stevenjmesser** [comment]
Just need to update the epic card.

**Comment by stevenjmesser** [comment]
Updated the epic card and split the giant task list into stages.
