### ISSUE TITLE
Fix GitHub Actions workflow flaky tests

### ISSUE THREAD

**Issue by colinrotherham** [alphagov/govuk-frontend#4169]
## What

Our GitHub Actions workflows only have two flaky tests

They typically pass when re-run. We should fix them

1. [**Banner** in JavaScript behaviour tests](https://github.com/alphagov/govuk-frontend/blob/7a33714d5a0d48a7805877330cce96954dddcfcf/packages/govuk-frontend-review/src/routes/banner.test.mjs#L5-L8) throws `TypeError: fetch failed` calling `fetchPath()`
    
    > https://github.com/alphagov/govuk-frontend/actions/runs/6072389732/job/16472409676
    > https://github.com/alphagov/govuk-frontend/actions/runs/6072198194/job/16471867044
    > https://github.com/alphagov/govuk-frontend/actions/runs/6072787178/job/16473539140
    > https://github.com/alphagov/govuk-frontend/actions/runs/6072960509/job/16474064674
    > https://github.com/alphagov/govuk-frontend/actions/runs/6039910759/job/16389701125
    > https://github.com/alphagov/govuk-frontend/actions/runs/6039836317/job/16389477864
    > https://github.com/alphagov/govuk-frontend/actions/runs/6039338891/job/16387907168
    > https://github.com/alphagov/govuk-frontend/actions/runs/6037941434/job/16383398031

2. [**Rollup** stats build](https://github.com/alphagov/govuk-frontend/blob/01981fa9f05b59c5bca16672c4c688984e62c35d/packages/govuk-frontend/tasks/scripts.mjs#L56-L57) throws `RollupError: Unexpected token`

    > https://github.com/alphagov/govuk-frontend/actions/runs/6122493682/job/16618794894#step:5:40
    > https://github.com/alphagov/govuk-frontend/actions/runs/6144727581/job/16670866996#step:5:40
    > https://github.com/alphagov/govuk-frontend/actions/runs/6144759438/job/16670871062#step:4:55
    > https://github.com/alphagov/govuk-frontend/actions/runs/6147512336/job/16679295401#step:4:55
    > https://github.com/alphagov/govuk-frontend/actions/runs/6145962649/job/16674439248#step:4:55

Flaky test 2) [also affects webpack](https://github.com/alphagov/govuk-frontend/actions/runs/6144759438/job/16670871062#step:4:463) with "missing semicolon" logged

Perhaps `dist/govuk/common/index.mjs` isn't valid due to Babel not updating the Rollup source maps?

## Why

* It's time consuming to re-run workflows that take ~8 minutes
* It catches out new team members and contributors

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] Test files clearly named by environment (e.g. `*.puppeteer.test.mjs`)
- [x] Tests using flaky helper `fetchPath()` are migrated to use Puppeteer
- [x] Rollup build issue is investigated and resolved

**Comment by colinrotherham** [comment]
One hypothesis for HTTP requests to the Review app throwing `TypeError: fetch failed` is that some tests projects run `globalTeardown()` whilst others are starting up or still running.

To avoid overlap we should replace complex Jest project wildcards with workspace **jest.config.mjs** files that can be configured separately. We've [mentioned this previously](https://github.com/alphagov/govuk-frontend/issues/2886#issuecomment-1261027939) but de-scoped it:

```mjs
export default {
  projects: [
    '<rootDir>/packages/*',
    '<rootDir>/shared/*',

    // Tasks
    '<rootDir>/packages/*/tasks/*',
    '<rootDir>/packages/*/tasks/*',
  ]
}
```

For example, regardless of whether they need it we:

* Start the Review app for every Puppeteer test
* Add the JSDOM browser globals for every unit test

# Jest projects

To illustrate some of the overlap, here are our current Jest named projects and the files they match:

## Build tasks

```console
packages/govuk-frontend/tasks/build/release.test.mjs
packages/govuk-frontend/tasks/build/package.test.mjs
```

## JavaScript behaviour tests

```console
packages/govuk-frontend/src/govuk/all.test.mjs
packages/govuk-frontend/src/govuk/helpers/colour.test.js
packages/govuk-frontend/src/govuk/helpers/grid.test.js
packages/govuk-frontend/src/govuk/helpers/helpers.test.js
packages/govuk-frontend/src/govuk/helpers/links.test.js
packages/govuk-frontend/src/govuk/helpers/media-queries.test.js
packages/govuk-frontend/src/govuk/helpers/spacing.test.js
packages/govuk-frontend/src/govuk/helpers/typography.test.js
packages/govuk-frontend/src/govuk/objects/objects.test.js
packages/govuk-frontend/src/govuk/objects/width-container.test.js
packages/govuk-frontend/src/govuk/settings/colours.test.js
packages/govuk-frontend/src/govuk/settings/settings.test.js
packages/govuk-frontend/src/govuk/settings/typography.test.js
packages/govuk-frontend/src/govuk/settings/warnings.test.js
packages/govuk-frontend/src/govuk/tools/exports.test.js
packages/govuk-frontend/src/govuk/tools/font-url.test.js
packages/govuk-frontend/src/govuk/tools/image-url.test.js
packages/govuk-frontend/src/govuk/tools/tools.test.js
```

Should this be in **JavaScript component tests**?

```console
packages/govuk-frontend/src/govuk/components/components.test.js
```

Could these have their own Jest project for the Review app?

```console
packages/govuk-frontend-review/src/app.test.mjs
packages/govuk-frontend-review/src/common/lib/files.test.mjs
packages/govuk-frontend-review/src/common/middleware/request.test.mjs
packages/govuk-frontend-review/src/common/middleware/robots.test.mjs
packages/govuk-frontend-review/src/routes/banner.test.mjs
packages/govuk-frontend-review/src/routes/full-page-examples.test.mjs
```

This should be a unit test but the JSDOM environment prevents us:

```console
shared/helpers/jest/browser/download.test.mjs
```

## Nunjucks macro tests

```
packages/govuk-frontend/src/govuk/components/components.template.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/template.test.js
packages/govuk-frontend/src/govuk/components/radios/template.test.js
packages/govuk-frontend/src/govuk/components/input/template.test.js
packages/govuk-frontend/src/govuk/components/date-input/template.test.js
packages/govuk-frontend/src/govuk/components/select/template.test.js
packages/govuk-frontend/src/govuk/components/file-upload/template.test.js
packages/govuk-frontend/src/govuk/components/character-count/template.test.js
packages/govuk-frontend/src/govuk/components/textarea/template.test.js
packages/govuk-frontend/src/govuk/components/cookie-banner/template.test.js
packages/govuk-frontend/src/govuk/components/summary-list/template.test.js
packages/govuk-frontend/src/govuk/components/pagination/template.test.js
packages/govuk-frontend/src/govuk/components/button/template.test.js
packages/govuk-frontend/src/govuk/template.test.js
packages/govuk-frontend/src/govuk/components/tabs/template.test.js
packages/govuk-frontend/src/govuk/components/header/template.test.js
packages/govuk-frontend/src/govuk/components/error-summary/template.test.js
packages/govuk-frontend/src/govuk/components/footer/template.test.js
packages/govuk-frontend/src/govuk/components/table/template.test.js
packages/govuk-frontend/src/govuk/components/task-list/template.test.js
packages/govuk-frontend/src/govuk/components/phase-banner/template.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/template.test.js
packages/govuk-frontend/src/govuk/components/accordion/template.test.js
packages/govuk-frontend/src/govuk/components/back-link/template.test.js
packages/govuk-frontend/src/govuk/components/panel/template.test.js
packages/govuk-frontend/src/govuk/components/fieldset/template.test.js
packages/govuk-frontend/src/govuk/components/error-message/template.test.js
packages/govuk-frontend/src/govuk/components/label/template.test.js
packages/govuk-frontend/src/govuk/components/details/template.test.js
packages/govuk-frontend/src/govuk/components/breadcrumbs/template.test.js
packages/govuk-frontend/src/govuk/components/hint/template.test.js
packages/govuk-frontend/src/govuk/components/tag/template.test.js
packages/govuk-frontend/src/govuk/components/inset-text/template.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/template.test.js
packages/govuk-frontend/src/govuk/components/warning-text/template.test.js
packages/govuk-frontend/src/govuk/components/skip-link/template.test.js
```

## JavaScript unit tests

```console
packages/govuk-frontend/postcss.config.unit.test.mjs
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
packages/govuk-frontend/src/govuk/all.unit.test.mjs
packages/govuk-frontend/src/govuk/common/closest-attribute-value.unit.test.mjs
packages/govuk-frontend/src/govuk/common/index.unit.test.mjs
packages/govuk-frontend/src/govuk/common/normalise-dataset.unit.test.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.unit.test.mjs
packages/govuk-frontend/src/govuk/errors/index.unit.test.mjs
packages/govuk-frontend/src/govuk/i18n.unit.test.mjs
packages/govuk-frontend/src/govuk/macros/i18n.unit.test.mjs
```

Could these have their own Jest project for the Review app?

```console
packages/govuk-frontend-review/postcss.config.unit.test.mjs
```

Could these have their own Jest project for our shared packages?

```console
shared/lib/components.unit.test.js
shared/lib/names.unit.test.mjs
shared/tasks/helpers/task-arguments.unit.test.mjs
```

## JavaScript component tests

```console
packages/govuk-frontend/src/govuk/components/accordion/accordion.test.js
packages/govuk-frontend/src/govuk/components/button/button.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.test.js
packages/govuk-frontend/src/govuk/components/globals.test.js
packages/govuk-frontend/src/govuk/components/header/header.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.test.js
```

## Accessibility tests
Matches only `govuk-frontend/src/govuk/components/*/accessibility.test.mjs`

**Comment by colinrotherham** [comment]
Raised an issue on the Rollup repo regarding flaky test 3)

* https://github.com/rollup/rollup/issues/5132

**Comment by colinrotherham** [comment]
@romaricpascal I'm going to move this one to Done

These tasks were removed:

- [ ] Test files are configured by separate Jest projects for each workspace
- [ ] EditorConfig checker binary is replaced with an alternative (or cached) to avoid rate limits

The EditorConfig issue affects us weekly when multiple Dependabot PRs are in flight:

* [**EditorConfig** checker CLI](https://github.com/alphagov/govuk-frontend/blob/7a33714d5a0d48a7805877330cce96954dddcfcf/package.json#L37-L38) throws `HttpError: API rate limit exceeded`

    > https://github.com/alphagov/govuk-frontend/actions/runs/6071806328/job/16470664245
    > https://github.com/alphagov/govuk-frontend/actions/runs/6037824738/job/16382948939

See https://github.com/alphagov/govuk-frontend/issues/4169#issuecomment-1705213455 for information on Jest projects

**Comment by romaricpascal** [comment]
Ported the remaining tasks to their own issues:

- https://github.com/alphagov/govuk-frontend/issues/4224
- https://github.com/alphagov/govuk-frontend/issues/4226
