### ISSUE TITLE
Replace `MissingElementError` with `ElementError`

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4209]
## What

Update `SkipLink` to throw an `ElementError` instead of a `MissingElementError` and remove that error from the codebase.

As the `ElementError` already handles the prefixing with the component name, this is also the occasion to just let the errors through from where the missing bits are detected rather than throw, catch, wrap and re-throw. 

## Why

Due to a lot of checks for the presence of element being `instanceof` checks, we introduced an `ElementError` to format the message appropriately depending on whether the element was actually missing or the wrong type. This error overlaps a lot what `MissingElementError` was doing so we need only one of those.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] The `SkipLink` component no longer throws a `MissingElementError`
- [x] The error has been removed from the codebase

**Comment by romaricpascal** [comment]
Blocked until we discuss #4072/#4074 as how we decide to finalise our errors may impact what exactly the replacement error will be.

**Comment by colinrotherham** [comment]
Closed by https://github.com/alphagov/govuk-frontend/pull/4219

**Comment by colinrotherham** [comment]
@36degrees Yeah, should have said "Will be closed by" and it's closed now 🎉

Thanks
