### ISSUE TITLE
Run an internal pre-release to npm

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4228]
## What

Run an undocumented, private pre-release, publishing an early version on our package on npm (proposing under an `@internal` tag).

## Why

Validate that our pre-release process before actually publicly pre-releasing, as well as offer an easier way to integrate with the Prototype Kit's test to validate that things work OK.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] Agree upon a name for the prerelease tag (`internal`?)
- [x] Make the pre-release
- [x] Update the Design System release branch ([release/5.0](https://github.com/alphagov/govuk-design-system/tree/release/5.0)) to use the pre-release and create any issue necessary if fixes are needed
- [x] Update the Frontend docs release branch ([release/5.0](https://github.com/alphagov/govuk-frontend-docs/tree/release/5.0)) to use the pre-release and create any issue necessary if fixes are needed

**Comment by colinrotherham** [comment]
Both preview PRs are now updated:

* https://github.com/alphagov/govuk-frontend-docs/pull/333
* https://github.com/alphagov/govuk-design-system/pull/2977

Moving this into "Needs review" for:

* https://github.com/alphagov/govuk-frontend/pull/3977

**Comment by colinrotherham** [comment]
Having said that, our first internal pre-release is done

I'll split out PR https://github.com/alphagov/govuk-frontend/pull/3977 separately on the board and close this
