### ISSUE TITLE
The review app stops compiling Sass after encountering an error

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#4237]
## Description of the issue

If you make a change that causes an error in Sass compliation whilst using the review app, the build process for the review app crashes and is not restarted.

This means that even if you fix the change, you need to stop the process and restart it (Ctrl + C then re-run `npm start`).

## Steps to reproduce the issue

1. Run npm start
2. Edit *.scss file to cause a Sass or PostCSS error

## Actual vs expected behaviour

Expected behaviour:

The error is outputted on the console and the watch task for the review app build continues to retry compilation when further changes are made

Actual behaviour:

The error is outputted on the console but the watch task for the review app build crashes.

## Environment (where applicable)

- Operating system: macOS 13.5.1
- Browser: N/A
- Browser version: N/A
- GOV.UK Frontend Version: N/A (happening on `main` branch)

**Comment by colinrotherham** [comment]
Will be fixed by https://github.com/alphagov/govuk-frontend/pull/4239 and tested in https://github.com/alphagov/govuk-frontend/pull/4240
