### ISSUE TITLE
Rename `govuk-typography-responsive`

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#4243]
## What
Rename the mixin [`govuk-typoraphy-responsive`](https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-typography-responsive) to something that more clearly dictates what it does.

## Why
It emerged during https://github.com/alphagov/govuk-frontend/issues/3837 that users may not understand how to use `govuk-font` is it is intended. Part of this is driven by the fact that users don't know about `govuk-typography-responsive` as the mixin that handles the retrieval of `font-size` and `line-height` from the typography scale. Part of this can be handled by documenting it better however we have a reckon that a more appropriate name would help users understand it at a glance and recall it easier.

A name that emerged during the linked spike is `govuk-font-size` however this isn't set in stone.

## Who needs to work on this
Developers

## Who needs to review this
Developers

## Done when

- [x] A new name is decided
- [x] The new name is applied
- [x] `govuk-typography-responsive` is deprecated

**Comment by 36degrees** [comment]
It looks like it's already covered in the done whens (thanks! 🙌🏻 ) but we should follow our [process for renaming Sass mixins](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/managing-change.md#renaming-sass-mixins-and-functions) for this.

**Comment by querkmachine** [comment]
`govuk-font-size` feels like a nice, self-explanatory name. Helps that it's aligned with the name of the existing `font-size` property, which is already something we aim to do with the naming of components. 

That does make me wonder if there needs to be some formality introduced as to how all the mixins are named though. Some begin with `govuk-typography` and others use `govuk-font`. The likes of `govuk-typography-weight-regular` would probably be more intuitively named `govuk-font-weight-regular`, etc.

That might be spinning off a whole other bunch of changes, though 😅

**Comment by owenatgov** [comment]
@querkmachine Excellent point. I do wonder if there's an argument to changing all our typography mixins to use a `govuk-font-xyz` prefix. To me, that feels easier to parse than "typography" although there are arguments for both eg: when we use `govuk-typography-common` we aren't just applying a font, we're applying some settings that are central to our _typography_. 

I can guess at the reason for at least the weight mixins since they're tied explicitly to the `$govuk-font-weight-bold` and `$govuk-font-weight-regular` variables. Having mixins and vars with the same name is a bit messy. Having said that, I do wonder if we can't make them both a bit more nuanced ie: have a single `govuk-font-weight` mixin.

I personally would like to do some data gathering on our naming somewhen during the lifecycle of the typography work since it feels non-trivial to change in-flight mixins in our API. I'm thinking about polling the community about this. We already have https://github.com/alphagov/govuk-frontend/issues/4276, maybe instead of being specifically about the need for a mixin we ask about our font mixins in general?
