### ISSUE TITLE
Review types used in `instanceof` checks

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4244]
## What

Review the types used in `instanceof` checks to verify that they are not overly specialised, especially if checks for `HTMLElement` could be simple `Element` and note:
- where checks could use a more generic class due to the component not using any of the specialised class API
- if there'd be ground to keep the generalised class to ensure some checks related to accessibility

## Why

Using the correct class to check against (especially `Element` which is naturally returned by `querySelector` or `querySelectorAll`) would allow to be clearer on what our code is actually trying to achieve, and in turn possibly clarify some of our tests.

There's some grounds to discuss instanceof checks to validate accessibility concerns. That's a discussion we can open once we have a view of which of our components may already do that.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] We have a list of components where more specialised `instanceof` checks are used 
- [ ] We have a lined up a discussion for those where these checks could fullfil some accessibility validation

**Comment by romaricpascal** [comment]
Worth having a look, while reviewing things, at whether `instanceof` checks (or sometimes just falsy checks) leading to early returns might be ommited in favour of leaving JavaScript to error further down the line. Especially for event listeners, a runtime error will not impact other listeners running for the same event, so we might have an opportunity to be a bit looser there.

**Comment by colinrotherham** [comment]
Feels like the TypeScript team are watching our repo 😮

From the [TypeScript 5.3 beta](https://devblogs.microsoft.com/typescript/announcing-typescript-5-3-beta/) release notes we now have:

1. Narrowing types for booleans like `'a' in x`
1. Narrowing instanceof types
1. Checks for `super.XXX` field access

>TypeScript 5.3 now more-closely inspects `super` property accesses/method calls to see if they correspond to class fields. If they do, we’ll now get a type-checking error.

Will have to confirm if `instanceof` checks can be moved to the base class now

**Comment by colinrotherham** [comment]
I've reviewed all the `instanceof` types in https://github.com/alphagov/govuk-frontend/pull/4325 and narrowed them down unless guarding required APIs such as:

```mjs
$element.dataset
$element.click()
$element.focus()
```

### ARIA attributes and element types

We may want to tighten our checks to confirm `aria-*` attributes match their required element types (or role)

At the moment we only do this for **Radios** and **Checkboxes** inputs:

1. **Accordion** section button

```mjs
// $button instanceof Element
$button.getAttribute('aria-controls')
$button.getAttribute('aria-expanded')
```

1. **Header** menu button

```mjs
// $menuButton instanceof Element
$menuButton.getAttribute('aria-controls')
```

1. **Radios** and **Checkboxes** inputs

```mjs
// $input instanceof HTMLInputElement
$input.getAttribute('aria-controls')
```
