### ISSUE TITLE
Plan briefing to let us do some light user research

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4292]
## What 

Prepare an intro and questions to guide pairing sessions with developers from other teams.

## Why

We'd like to take advantage of the v5 pre-release to pair with people from other teams and witness which issue they come across when trying to upgrade to v5.

## Who needs to work on this

Developers, User researcher, Technical writer?

## Who needs to review this

Developers, User researcher, Technical writer?

## Done when

- [ ] We have an intro and a set of questions to guide the pairing sessions

**Comment by kellylee-gds** [comment]
@romaricpascal hey we had a quick look at this in DS sprint planning. Is this done?

**Comment by romaricpascal** [comment]
@kellylee-gds Yes, the last bits were on me to turn our plans into more of a guide interviewers could follow and note-takers could add their notes to, which is now done.
