### ISSUE TITLE
Contact people in other teams for interest in pairing

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4293]
## What

Contact other frontend developers in service teams to propose pairing for observation while they try to upgrade to v5.

## Why

We'd like to take advantage of the v5 pre-release to pair with people from other teams and witness which issue they come across when trying to upgrade to v5.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] We've contacted the other developers and have a list of who's keen for pairing.

**Comment by claireashworth** [comment]
Moved as this is underway.

**Comment by romaricpascal** [comment]
Closing as pairing is underway: https://github.com/alphagov/govuk-frontend/issues/4294
