### ISSUE TITLE
Refactor ElementError class

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#4300]
## What
Potential changes include:

- Ensuring `ElementError.options.expectedType` is always a string, when present
- Simplifying expected type error messages to something like `${identifier} is not of type ${expectedType || 'HTMLElement'}`
- Make `identifier` the mandatory first param and move `element` into options:

```constructor(identifier, {componentName, element, expectedType})```

## Why
Making `expectedType` a string allows us to avoid having different cases for when it's a string vs when it's an element, reducing our checks and allowing us to simplify the outputted message.

Using `identifier` as our mandatory param allows us to avoid the hack of passing in `null` as the element to get the right error messages.

## Who needs to work on this
Developer

## Who needs to review this
Developer

## Done when

- [x] A decision has been made on which changes to make
- [ ] Changes have been implemented
- [ ] All existing tests and throws have been refactored to work with the changes

**Comment by romaricpascal** [comment]
Little note to make sure we account for the Skip Link's error when there's no hash in the URL, which may need its own little case (see [end of that comment on #4299](https://github.com/alphagov/govuk-frontend/issues/4299#issuecomment-1753245288)).
