### ISSUE TITLE
Review Nunjucks `default()` fallbacks for "falsey" values

### ISSUE THREAD

**Issue by JoPintoPaul** [alphagov/govuk-frontend#4305]
## Description of the issue

When using the tabs template, it used to be the case the an empty string ("") being passed as title would result in the default string "Contents" being displayed:
https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk/components/tabs/template.njk#L7

However, since Nunjucks 2.0, an empty string will NOT trigger the default, as Nunjucks now only uses default when a value is undefined rather than falsey:
https://mozilla.github.io/nunjucks/templating.html#default-value-default-boolean

If the template is passed an empty string for the title parameter, should the page render as:
```
<h2 class="govuk-tabs__title"></h2>
```
or as:
```
<h2 class="govuk-tabs__title">Contents</h2>
```
## Steps to reproduce the issue
Pass an empty string ("") for the title to the tabs template:
https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk/components/tabs/template.njk

## Actual vs expected behaviour
Expected: Passing an empty string for title renders as `<h2 class="govuk-tabs__title">Contents</h2>`
Actual: `<h2 class="govuk-tabs__title"></h2>`

**Comment by colinrotherham** [comment]
Thanks for opening this @JoPintoPaul

I did wonder if our `default()` usage needed tweaking so I've update the title for a wider review

Your example is spot on though, we always need a title so "falsey" values should be skipped:

```patch
<h2 class="govuk-tabs__title">
- {{ params.title | default("Contents") }}
+ {{ params.title | default("Contents", true) }}
</h2>
```

But in contrast we'd take care with other "falsey" values such as:

1. [**Checkboxes** input](https://design-system.service.gov.uk/components/checkboxes/) `item.checked` should preserve `false` values
2. [**Select** menu](https://design-system.service.gov.uk/components/select/) `item.selected` should preserve `false` values

We also use `params.value` without `default()` but maybe they should keep `""` values too

Will be good to tighten things up, thanks again

**Comment by JoPintoPaul** [comment]
@colinrotherham Great stuff, thanks for the update!

**Comment by colinrotherham** [comment]
Thanks for raising this @JoPintoPaul

We'll have it fixed in our next release
