### ISSUE TITLE
Update README to reflect changes to browser support

### ISSUE THREAD

**Issue by claireashworth** [alphagov/govuk-frontend#4368]
## What
Once the new Graded Browser Support documentation is published, update the README to reflect the changes and link to the documentation.
## Why
To provide another avenue for users to find the documentation.
## Who needs to work on this
Developer, Tech Writer
## Who needs to review this
Developers
## Done when

- [ ] Team agrees changes
- [ ] README is updated

**Comment by claireashworth** [comment]
@colinrotherham - do you want to be on this issue as well?

**Comment by romaricpascal** [comment]
Closed by #4381
