### ISSUE TITLE
Determine if we have breaking changes, decide on a release strategy

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#4466]

**Comment by owenatgov** [comment]
I've made a spreadsheet assessing the technical changes we've made or are planning on making https://docs.google.com/spreadsheets/d/1DKFLp3Kk7SAkMU8z1_B-pSzSbuAduHIhRYF9yUMj1b8/edit#gid=0 (internal only)

**Comment by stevenjmesser** [comment]
Did you post somewhere else @owenatgov that you think we _don't_ have any breaking changes?

**Comment by owenatgov** [comment]
@stevenjmesser Sorry I forgot to follow this up. Yep, we don't have any breaking changes that haven't already been merged into `main`. We can close this now unless you think there's more to do?

**Comment by stevenjmesser** [comment]
Nope, that's ideal, thank you!
