### ISSUE TITLE
Document how people can install pre-releases

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4476]
## What

Add some documentation (either in the GOV.UK Frontend docs, or as a step for shipping a pre-relase or its comms) to advertise the `@next` tag on `npm` for installing the pre-release versions.

## Why

During user tests, people seemed to not be aware of its existence for easily getting the pre-release version installed.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

- [ ] We have decided how to document the npm tag
- [ ] We've added the documentation where necessary

**Comment by romaricpascal** [comment]
@claireashworth Beyond [the PR](https://github.com/alphagov/govuk-frontend-docs/pull/417) that adds the instructions to [our 'Staying up to date' page](https://frontend.design-system.service.gov.uk/staying-up-to-date/#updating-to-the-latest-version) (see [the preview of the page](https://deploy-preview-417--govuk-frontend-docs-preview.netlify.app/staying-up-to-date/#updating-to-the-latest-version)), I was wondering if it'd be worth adding some link to that section as an introduction to each release notes to help people get the instruction or even a quick reminder of the command (as it's a short one and would save people a click). Something like "To install this version with npm, run `npm install govuk-frontend@<VERSION_NUMBER>`. You can also find more [information about how to stay up to date in our documentation](https://frontend.design-system.service.gov.uk/staying-up-to-date/#updating-to-the-latest-version).`.

1. Does that sound useful?
2. Is there a template for this kind of introduction? It might be worth its own issue, though, as there may be other info to put in there 🤔 .

**Comment by claireashworth** [comment]
Can I check I understand you correctly? You want the sentence about installing a particular version as part of the intro to release notes with a link to 'staying up to date'? It does sound like a good idea. We have a template of sorts for release notes, but I need to check it's up to date.

**Comment by romaricpascal** [comment]
Yup, that's exactly that. Given users were struggling to know which command to use during user research and they all went through the release notes, felt a good place to add a little hint about it 😊

**Comment by romaricpascal** [comment]
@claireashworth GitHub closed this automatically when I merged, but I'm reopening it to close once the release notes template is up to date 😊

**Comment by claireashworth** [comment]
@romaricpascal at some point, could you review [the release notes template](https://docs.google.com/document/d/1J3LjBGh3VAXJNAPP9Lv_z3IrUPFt87pV_iuGMBAajNo/edit?usp=sharing), please?

**Comment by romaricpascal** [comment]
@claireashworth Added a couple of comments 😊 Also noticed we have [this CHANGELOG_TEMPLATE.md](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/CHANGELOG_TEMPLATE.md) file in the docs of the project. We may want to keep only one of the two?

**Comment by claireashworth** [comment]
I can work on merging them.

**Comment by romaricpascal** [comment]
That'd be ace to have a single reference. Thanks for offering (and getting the new template up, forgot to say it was neat overall in my previous comment 😊 ).
