### ISSUE TITLE
Unignore package-lock.json

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#453]
To make sure we have deterministic builds we should commit in the package-lock.json.

**Comment by 36degrees** [comment]
When it was [originally ignored](https://github.com/alphagov/govuk-frontend/commit/c41c3f6ad6cdc68028f93b91ecf4774f41cae6f2) there was a comment about fs-events:

```
* Remove package-lock.json

Do this until the issue with fs-events is resolved.
```

From some of Gemma's notes on Travis:

> Travis CI breaks because the optional dependency, fs-events is installed. The platform used by Travis isn’t supported and it breaks the build.
>
> Setting fs-events to be optional in package.json and ensuring that the no-optional flag is passed when travis runs npm install fixes this.

It looks like both of these are now done:
https://github.com/alphagov/govuk-frontend/blob/master/package.json#L71-L73
https://github.com/alphagov/govuk-frontend/blob/master/.travis.yml#L11-L12

So… I guess this should be OK?
