### ISSUE TITLE
Empty govuk-if-ie8 mixin isn't valid Sass

### ISSUE THREAD

**Issue by DavidBiddle** [alphagov/govuk-frontend#4556]
## Description of the issue

The release notes for v5.0.0 say:
> If a library you depend on is not yet updated and relies on these mixins and variables, as a temporary workaround you can define the following mixins and variables before importing:
  ```scss
$govuk-is-ie8: false;
$govuk-ie8-breakpoint: ('desktop');
@mixin govuk-if-ie8 {}
@mixin govuk-not-ie8 {@content}
```

The mixin on the third line of the example doesn't work for all cases. In the latest dart-sass (1.69.5), attempting to invoke this mixin with any content results in the following error:
>  [sass] Mixin doesn't accept a content block.

## Steps to reproduce the issue

```scss
@mixin govuk-if-ie8 {}

body {
  @include govuk-if-ie8 { display: flex }
}
```

## Actual vs expected behaviour

The ideal behaviour would be for the mixin to ignore the content given to it, though this appears to be what Sass is objecting to.

A less ideal alternative might be to put the content inside an unlikely-to-collide selector - this works in our build:

```scss
@mixin govuk-if-ie8 {
  .a-class-you-should-never-use-because-it-is-a-workaround-for-the-govuk-frontend-ie8-mixin {
    @content
  }
}
```

## Environment (where applicable)

- Operating system: macOS
- Browser: Firefox developer edition 
- Browser version: 121.0b9
- GOV.UK Frontend Version: 5.0.0
- Sass version: dart-sass v1.69.5

**Comment by romaricpascal** [comment]
Whoops, was a bit hasty adding that, sorry, thanks for letting us know. 

Looks like the following works without adding a new selector on Sassmeister, could you confirm it works for you as well?

```scss
@mixin govuk-if-ie8 {
    @if (false) { 
        @content
    }
}

```

**Comment by DavidBiddle** [comment]
@romaricpascal Thanks for the quick response - that version of the mixin works in our repo (and is a lot more elegant than my workaround!)

**Comment by romaricpascal** [comment]
Awesome, thanks for testing it in your repo. I'll update our release notes with this updated version 😊
