### ISSUE TITLE
Ask teams not to update crown before 19 Feb 2024

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#4620]
## What

Once the new versions have been released, ask teams not to update the crown before 19 February 2024.

## Why

If GOV.‌UK has the new crown first, it can be trusted that this is a change that is happening, which should ensure and increase trust. (Content will be published on GOV.‌UK about the change when it happens, which will further increase trust.)

**Comment by stevenjmesser** [comment]
Getting more info on the 'why', I think it's to do with reducing the chance that a service looks fraudulent. For example, if GOV.‌UK has the new crown first, it can be trusted that this is a change that is happening.

**Comment by stevenjmesser** [comment]
The above is true, it's to increase trust by trying to ensure that the central domain has the change before linked sub-domains.

**Comment by querkmachine** [comment]
@stevenjmesser As the crown launch has been rescheduled, should this be updated to the new (provisional) date of 19th February?

**Comment by 36degrees** [comment]
@stevenjmesser @querkmachine is this done?

**Comment by querkmachine** [comment]
@36degrees I suspect so. We included the note not to update in our changelogs and release comms, not sure if there's anything else we have to do on top of that.

**Comment by 36degrees** [comment]
I'll close this on the basis we can re-open it if @stevenjmesser disagrees!

**Comment by stevenjmesser** [comment]
Is done, thank you :)
