### ISSUE TITLE
After 19 February 2024, encourage teams to update crown before 1 March 2024

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend#4621]
## What

If the new crown is live on www.gov.uk, use our Slack channel and mailing list to inform teams that they can now update the crown.

## Why

We told teams we’d let them know when it was time to update the crown.

## Who needs to work on this

Content designer

## Who needs to review this

One of the leads

**Comment by 36degrees** [comment]
Don't we want to encourage teams to update _before_ the 1st March? (but after the 19th?)

Or is this more about chasing stragglers?

It might be useful to add more detail to this issue if we've got specific things we want to do.

**Comment by stevenjmesser** [comment]
Done.
