### ISSUE TITLE
Consider `all-contributors` for this repo

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#465]
We could recognise contributors with something similar to https://github.com/kentcdodds/all-contributors

**Comment by joelanman** [comment]
I like it - is it automated from the git log?

**Comment by nickcolley** [comment]
It can be somewhat automated, but the minimum is just a consistent way of listing contributors.

**Comment by 36degrees** [comment]
For the Design System, we could also consider a [humans.txt](http://humanstxt.org/) file - though I think they're less popular than they used to be.

https://www.theguardian.com/humans.txt
https://trello.com/humans.txt
https://basecamp.com/humans.txt

**Comment by ignaciaorellana** [comment]
I like this idea as well 👯

**Comment by timpaul** [comment]
We think we could do the same on the backlog repo too. I'll mock something up in a branch.

**Comment by nickcolley** [comment]
We've started doing this work across all products, so will close from here for now.
