### ISSUE TITLE
govukDateInput macro could have default `items`

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#468]
The majority of the time, you want Day, Month, Year, so we could just have that as the default without the user having to specify `items`

**Comment by nickcolley** [comment]
Let's make this easy to copy paste from the design system?

**Comment by joelanman** [comment]
I don't think we should be relying solely on the Design System site. We should also be looking at the usability of the Frontend API - 'do the hard work to make it simple'. In this case, the vast majority of use cases will be day month year, so why not make that really easy?

**Comment by nickcolley** [comment]
Since with inputs you need to specify the inputs so you can link them to a form I'm not sure how much easier it'd be?

Would be worth sketching up what the difference is before and after in a code snippet.

**Comment by nickcolley** [comment]
Could you sketch your proposal in code @joelanman?

**Comment by nickcolley** [comment]
Hey Joe,

This seems useful but without the proposal I'm not sure how we can make changes.

I'm going to close for now but feel free to re-open with your proposal in code.
