### ISSUE TITLE
Review app preview on smaller screens clips iframe(ed) example

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#477]
![screen shot 2018-01-29 at 14 47 11](https://user-images.githubusercontent.com/3758555/35516327-64639754-0503-11e8-9be4-f3849e7ae899.png)

**Comment by nickcolley** [comment]
I can't reproduce this on master, can you make sure you're on master and try this again?

If you reproduce can you post what browser (including version number)/device you're using

**Comment by igloosi** [comment]
on master, chrome 63 and 64

**Comment by alex-ju** [comment]
Tested on Google Chrome 63.0.3239.132 on MacOS, can't reproduce either.

**Comment by nickcolley** [comment]
Can reproduce this on Windows, it seems to be due to scrollbars

**Comment by nickcolley** [comment]
Want to hold off doing this until we've refactored the views...
