### ISSUE TITLE
Build process is generating CSS incompatible with IE11 and legacy browsers

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-frontend#4810]
## Description of the issue

Part of our CSS build process is outputting CSS that is incompatible with older browsers that are still within our browser support window, principally Internet Explorer 11.

@colinrotherham identified the issue as being the `postcss-colormin` package (which is bundled with `cssnano`) not respecting Browserslist workspaces. There is an issue open for this in the cssnano repo: https://github.com/cssnano/cssnano/issues/1513

Other packages bundled with cssnano may also have this issue, but we aren't sure just yet.

## Steps to reproduce the issue

The most obvious symptom of this occurring is that instances of the `transparent` color keyword are being transformed into four-digit hex-with-alpha format `#0000`. Internet Explorer 11 doesn't understand this format, so any rule that uses it is discarded, causing previously transparent elements to become rendered.

This is most visible on the button component, whose borders are visibly rendered instead of being transparent in IE 11. The `::before` pseudo-element that slightly extends the clickable area is also visible in black below the button. 

![Screenshot of a negative button in the design system, with grey embossed borders around it and a thin black border on the bottom.](https://github.com/alphagov/govuk-frontend/assets/1253214/581080aa-dbd6-4059-9d55-29fd4206cfd6)

The inspector showing the transformed colour value and that IE 11 considers it invalid.

![Screenshot of web inspector in IE 11 showing the CSS rules for .govuk-button. It highlights the border rule, which has a red zig-zagging line under it.](https://github.com/alphagov/govuk-frontend/assets/1253214/18dedad4-b59b-41e0-9f4a-031820cb36e1)

## Actual vs expected behaviour

Ideally, cssnano and its dependencies would respect our Browserslist configurations and not generate code that's invalid in IE 11. 

## Environment

Visible in the `dist` CSS files that are bundled with npm releases.

Tested with:

- Operating system: Windows 10
- Browser: Internet Explorer
- Browser version: 11
- GOV.UK Frontend Version: 5.2.0

**Comment by colinrotherham** [comment]
Had a bit of homework at the weekend so I've fixed this in:

* https://github.com/cssnano/cssnano/pull/1573

Other alternatives would be to:

1. Move the PostCSS config back to project root
2. Use [`npm ci --install strategy`](https://docs.npmjs.com/cli/v10/commands/npm-install#install-strategy) to use workspace-level `node_modules`

**Comment by colinrotherham** [comment]
The fixes in https://github.com/cssnano/cssnano/pull/1573 have been published 🙌

1. Browserlist configs are discovered (upwards) from the input CSS file not `node_modules`
2. Browserlist `env` is now accepted by [cssnano-preset-default](https://www.npmjs.com/package/cssnano-preset-default) like Autoprefixer does

We'll need to apply the following patch to:

* [**govuk-frontend**/postcss.config.mjs](https://github.com/alphagov/govuk-frontend/blob/47551e37f5191229fb2802398d078311d6bf1d6c/packages/govuk-frontend/postcss.config.mjs#L34)
* [**govuk-frontend-review**/postcss.config.mjs](https://github.com/alphagov/govuk-frontend/blob/47551e37f5191229fb2802398d078311d6bf1d6c/packages/govuk-frontend-review/postcss.config.mjs#L23)

```patch
 cssnano({
   preset: [
+    cssnanoPresetDefault({
+      env: 'stylesheets',
+
-    cssnanoPresetDefault,
-    {
       // Sorted CSS is smaller when gzipped, but we sort using Stylelint
       // https://cssnano.co/docs/optimisations/cssdeclarationsorter/
       cssDeclarationSorter: false
+    }),
-    }
   ]
 })
```

**Comment by colinrotherham** [comment]
Will keep this open until we have a CHANGELOG entry

**Comment by 36degrees** [comment]
We now have a changelog entry so I'm going to close this.
