### ISSUE TITLE
Spike to understand which colours would need adjusting to have a well designed dark mode

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4903]
## What

Create stylesheet overriding our styles as bluntly as necessary to define which colours would need changing to implement dark mode, form a design point of view.

Particular attention might be necessary around links and focus styles.

## Why

This will let us indentify the scope of the colours needing to be adjusted to support a dark mode.

## Who needs to work on this

Designers, potentially with support from developers and accessibility specialist

## Who needs to review this

Designers

## Done when

- [ ] We have a branch where our components sport a dark mode style

**Comment by 36degrees** [comment]
@christopherthomasdesign is it accurate to say you're working on this one?

**Comment by christopherthomasdesign** [comment]
Yes it is! Hoping to push something and write a summary on Monday 👍

**Comment by querkmachine** [comment]
> * for ‘area’ hovers like task list, that background obvs needs to still work with any text… so it may work better for it to go darker (see the accordion and task list states)
> * that isn't too different to how it works in light mode, where it goes from white to grey – as discussed, might we need a concept of `govuk-area-hover-colour` or something?

This would align with my understanding for how dark modes should typically work. Dark mode shouldn't work like an inversion of light mode, but just as a darkening. If in light themes Thing A is darker than Thing B, or if Thing C becomes darker when focused, the same should be true when dark.

**Comment by romaricpascal** [comment]
Forgot to tidy issues at the end of the cycle, so closing this now 😊
