### ISSUE TITLE
Discussion: Remove `input` variant from button component

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#492]
Following on from the conversation here https://github.com/alphagov/govuk_elements/issues/545.

It seems that input style buttons are only useful in IE6/7, since we do not support these browsers should we remove this from our macro and reduce complexity in the component?

**Comment by 36degrees** [comment]
I think we should definitely consider making `<button>` the default behaviour. I'm less sure whether we should remove the support for `<input>` entirely.

**Comment by nickcolley** [comment]
Can you explain what issues you can think of that would prevent us from removing input support?

**Comment by 36degrees** [comment]
Only really that IE7 bug - whilst we may not 'support' older browsers, using a `<button>` on a form where multiple buttons are provided could cause confusing behaviour in IE7.

I'm fine with not caring about how it looks in those browsers, but removing `<input>` support entirely makes it harder for teams to correct it.

**Comment by nickcolley** [comment]
As part of our migration guidance from elements, we could include how to replace input elements with buttons, would this be acceptable?

One other thing to consider is when people port the macros, if they have less complexity it'll make it a lot easier for them.

**Comment by nickcolley** [comment]
Had a look into what we could suggest to move away from inputs, doesn't look too easy so, seems OK to compromise on changing the default instead.
