### ISSUE TITLE
When using a width modifier on the password input component, it makes the show/hide button wide (fill out space)

### ISSUE THREAD

**Issue by tim-s-ccs** [alphagov/govuk-frontend#4934]
## Description of the issue

When using a width modifier on the password input component, it makes the show/hide button wide (fill out space).
I'm not sure if this is really a bug but I thought it was worth bringing to your attention as I was not expecting this behaviour.

## Steps to reproduce the issue

In the below example I've added the `govuk-!-width-one-half` width modifier to the password input.

![Password input component with a govuk-!-width-one-half width modifier on the input](https://github.com/alphagov/govuk-frontend/assets/58297459/09622bdb-fc32-4f70-966c-ce5c60b998bf)

```HTML
<div class="govuk-form-group govuk-password-input" data-module="govuk-password-input">
  <label class="govuk-label" for="password-input">
    Password
  </label>
  <div class="govuk-input__wrapper govuk-password-input__wrapper">
    <input class="govuk-input govuk-password-input__input govuk-js-password-input-input  govuk-!-width-one-half" id="password-input" name="password" type="password" spellcheck="false" autocomplete="current-password" autocapitalize="none">
    <button type="button" class="govuk-button govuk-button--secondary govuk-password-input__toggle govuk-js-password-input-toggle" data-module="govuk-button" aria-controls="password-input" aria-label="Show password" hidden>
      Show
    </button>
  </div>
</div>
```

## Actual vs expected behaviour

I would expect the show/hide button size to be unaffected by the width of the input.

## Environment (where applicable)

- Browser: Chrome
- Browser version: 123.0.6312.107
- GOV.UK Frontend Version: 5.3.0

**Comment by querkmachine** [comment]
A quick fix, seemingly. Just an errant line of CSS that didn't need to exist. 😋 

Thanks for bringing it to our attention!

**Comment by tim-s-ccs** [comment]
No problem, happy to help 😄
