### ISSUE TITLE
Move responsibilities from `initAll` to the components

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#4945]
## What

Move as many responsibilities from `initAll` to the components so that `initAll` is doing as little as possible.

For example, the `data-module` selector is only defined in `initAll`.

Add any new methods to the JavaScript API reference

## Why

To make it easier to include the JS for components without needing to import or use the `initAll` function.

## Who needs to know about this

Developers

## Done when

- [x] `initAll` does as little as possible.
- [ ] Any new methods are clearly documented in the JavaScript API reference

**Comment by romaricpascal** [comment]
Reopening waiting for alphagov/govuk-frontend-docs#443 to be merged.
