### ISSUE TITLE
Investigate tree shaking of common js utilities

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#4964]
## What
Investigate ways to ensure that our [common js utilities](https://github.com/alphagov/govuk-frontend/tree/main/packages/govuk-frontend/src/govuk/common), primarily the multiple modules in [common/index/mjs](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk/common/index.mjs), are correctly tree-shaken when bundled. This includes but is not limited to splitting the modules in index.mjs into their own files.

## Why
We found during https://github.com/alphagov/govuk-frontend/issues/4957 that whilst we were able to effectively get tree shaking to work as expected for components, bundlers were importing all of common/index.mjs when not all of common was being used. It would be good to further optimise our js and understand why our `"sideEffects": true` solution in https://github.com/alphagov/govuk-frontend/pull/4961 didn't work for common.

## Who needs to work on this
Developers

## Who needs to review this
Developers

## Done when

- [ ] Test if splitting out common/index.mjs fixes tree shaking
- [ ] Optional: Investigate alternative methods to fix the tree shaking

**Comment by romaricpascal** [comment]
The issue appears to be Webpack specific. For Rollup and Vite[^1], functions from`common/index.mjs` that are not used by the Button component, like `getFragmentFromURL`, are properly absent from the built `single-component.mjs`.

[^1]: Vite was tested by building a single entry point to avoid the issue listed in https://github.com/alphagov/govuk-frontend/issues/4978 regarding how code is split by Vite automatically
