### ISSUE TITLE
Consider removing aria-expanded from conditional radios

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#4974]
## Description of the issue

`aria-expanded` on radios is not valid in the spec. According to this thread, it's potentially superfluous and only adds noise

 - https://github.com/w3c/aria/issues/1404

So this is an issue to consider removing it from radios

Came up recently here:

 - https://github.com/alphagov/govuk-design-system-backlog/issues/59#issuecomment-2102440106

**Comment by romaricpascal** [comment]
It's a duplicate of https://github.com/alphagov/govuk-frontend/issues/979, so I'll close it to track things in a single place.
