### ISSUE TITLE
Fix Dependabot timing out

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend#4982]
## What

Restore Dependabot's ability to update our dependencies, as [our dependabot builds have been timing out](https://github.com/alphagov/govuk-frontend/network/updates/827461463) lately.

We're in touch with GitHub support which suggested looking into [Dependabot's option](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file), especially its [`allow`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#creating-ignore-conditions-from-dependabot-ignore:~:text=allow,updates%20are%20allowed) and [`ignore`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#creating-ignore-conditions-from-dependabot-ignore:~:text=ignore,certain%20dependencies%20or%20versions) parameters, to limit the packages being updated.

Before we look into it, we've asked more details about the 39min gap at the end of Dependabot's log, which make it look like something is stuck rather than us having too many things to update.

## Why

Dependabot not running means we're no longer keeping up to date with our dependencies. As the library we ship is dependency free and our tooling is OK for now, this doesn't stop us from working or releasing but the longer Dependabot remains stuck, the more work we'll have to get back up to date once it's unblocked.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Our dependencies are updated again by Dependabot

**Comment by romaricpascal** [comment]
Further discussions with GitHub support got us pointed to running [Dependabot on Actions](https://github.blog/2024-05-02-dependabot-on-github-actions-and-self-hosted-runners-is-now-generally-available/)

**Comment by patrickpatrickpatrick** [comment]
It seems like https://github.com/alphagov/govuk-frontend/pull/4999 fixed the issue. I suppose that Dependabot shouldn't just hang forever if it encounters an error like this, so it might still be worth talking to Github Support about that.

**Comment by romaricpascal** [comment]
I think it's fine to close given we have https://github.com/alphagov/govuk-frontend/issues/4853 to nudge us to upgrade to the new syntax for ESLint plugins. I'll add a note on that one to remember to re-enable updates of ESLint once we've done that 😊
