### ISSUE TITLE
Allow tests for '{% call %}' use case for components that support it

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#510]
Some of our components allow nesting using https://mozilla.github.io/nunjucks/templating.html#call.

We currently can't show this in the guide or tests, so this functionality could break.

For example https://github.com/alphagov/govuk-frontend/pull/509 we do not have coverage for 'caller'

We would need to

- Allow the review application to show 'caller' examples
- Allow the tests to test 'caller' examples

**Comment by nickcolley** [comment]
I've spiked this out: https://github.com/alphagov/govuk-frontend/compare/spike-expose-caller-in-review?expand=1

You can see in the current way our application is structure it results in duplication of logic in three places. I'd recommend we refactor app.js to have a unidirectional data flow.

Then share the rendering of components between the HTML Code examples, the iFrame preview and the test render helper.

**Comment by 36degrees** [comment]
As long as we have test coverage, I don't think we need to have examples in the review app, as neither the generated HTML nor the styling should differ from any other example.

So I'd suggest scoping this to just making sure we have tests that cover the `{% call %}` use case.

**Comment by nickcolley** [comment]
This has been implemented
