### ISSUE TITLE
Proposal: add a 'positive' colour

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#518]
Copied over from [GOV.UK Frontend toolkit](https://github.com/alphagov/govuk_frontend_toolkit/issues/386)

There are cases where it's useful to have a colour with a semantic meaning of 'positive'.

We already have error_colour which is a good red for 'negative' - but we don't have a counterpart.

We could use an existing colour, or make a new colour. Either way, a semantic SASS name would be good.

The closest colour would be button_colour. An alternate would be #008800 which is the green used by petitions. It's warmer, which feels more positive to me.

![image](https://user-images.githubusercontent.com/3758555/36030708-2d13ea06-0da0-11e8-9154-882cd7b219ec.png)

**Comment by fofr** [comment]
In https://whitehall-prototype.herokuapp.com/patterns/flash-notices we are using the button colour. 

![screen shot 2018-02-09 at 13 57 19](https://user-images.githubusercontent.com/319055/36030993-303775c6-0da1-11e8-915c-029fa66ee9c1.png)

**Comment by edwardhorsford** [comment]
I might also suggest we possibly make a 'negative' colour that references `error-colour`. Semantic names FTW.

## Use cases
We used positive / negative on the first version of the Performance Platform.

Certain other services which include tables / graphs may also benefit. I'm thinking things like flood warnings / travel advice.

**Comment by dashouse** [comment]
Be aware, Mark Hurell has some broader colour changes coming up. I would not suggest adding any other colours to the palette.

**Comment by igloosi** [comment]
closing, will await colour changes
