### ISSUE TITLE
Unused border classes on details component

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk-frontend#521]
https://github.com/alphagov/govuk-frontend/blob/e0da7faf2dd5eca1f97dd944aeaffc281cb347a9/dist/components/details/details.html#L7-L8
https://govuk-design-system-production.cloudapps.digital/components/details/

The classes `govuk-c-border govuk-c-border--left-narrow` have no associated styles.
The border comes from the text element nested beneath it.

**Comment by 36degrees** [comment]
Thanks for raising this! This has been fixed in #481 but that has not yet been released.
