### ISSUE TITLE
Warning text does not explicitly set font-weight

### ISSUE THREAD

**Issue by matteason** [alphagov/govuk-frontend#5279]
The warning text component doesn't explicitly set a font weight, instead assuming that `<strong>` will always be bold because of browser default styles: https://github.com/alphagov/govuk-frontend/blob/a5a50ea57175c0031168d227513b7710579d9c98/packages/govuk-frontend/src/govuk/components/warning-text/_index.scss#L9-L12

I think this was introduced in GOV.UK Frontend 5.0.0: https://github.com/alphagov/govuk-frontend/commit/18caff508c0cb45207f63312c03cf92f77f7e276#diff-245553285fc1127f05c68705df40d7fdf95abebef3173eab71ea6b4d8bf89546

I think in almost all other places, Frontend is very careful to avoid relying on default styles. `<strong>` is a semantic element and the spec [doesn't specify that user agents should render \<strong\> as bold](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-strong-element), though it's a common convention.

I happened to run into this on a project using the [Meyer reset](https://meyerweb.com/eric/tools/css/reset/), where the warning text was rendering as `normal` weight, but it may also affect similar reset/normalise stylesheets.

**Comment by romaricpascal** [comment]
Hi @matteason, that's a good spot, we missed that subtlety at the time! I've opened a PR with a fix which hopefully will be able to ship with our next release.
