### ISSUE TITLE
New typography scale causes wrapping of OGL text in footer

### ISSUE THREAD

**Issue by matteason** [alphagov/govuk-frontend#5290]
https://github.com/alphagov/govuk-frontend/pull/4064 (later feature-flagged: https://github.com/alphagov/govuk-frontend/commit/5fcf17619c736a258d526a2128cc77ec1f975dc2) increased the footer font size to 19px, which means the OGL licence text in the footer now wraps when viewed at full width at the default zoom level/text size:

**Before (16px)**
![GOV.UK footer with text on one line: All content is available under the Open Government Licence v3.0), except where otherwise stated](https://github.com/user-attachments/assets/38b608df-eefa-4a30-aab8-1043053e0bab)

**After (19px)**
![GOV.UK footer with text on two lines, the last word on the second line: All content is available under the Open Government Licence v3.0](https://github.com/user-attachments/assets/4b8991bb-18cf-43f8-b4a4-fbe6d84537b4)

You can see this live on https://design-system.service.gov.uk/patterns/question-pages/default/

Typographically this looks a bit strange as it makes `stated` an orphan

**Comment by romaricpascal** [comment]
Hi @matteason, thanks for flagging that. I've proposed a fix in [this draft PR](https://github.com/alphagov/govuk-frontend/pull/5332), but it raises a few questions I'd like to put to the different specialists in the team so it may take a little before we fix the issue 😊
