### ISSUE TITLE
Investigate solution for operating the details component with Dragon

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend#5308]
## What
Investigate if it's possible to enhance the details component in order for it to be operable via Dragon.

## Why
This is in response to https://github.com/alphagov/govuk-design-system/issues/4029. This was raised in a recent DAC audit that dictation software Dragon doesn't recognise the details component and can't operate it. More detail is available in that issue.

## Notes
As mentioned in the linked issue, we'd like to avoid DAC's suggestion to convert the details component from a literal `details` element into an accordion-like component as this will add extra weight to govuk-frontend and [undo work we did to remove the details polyfill for 5.0](https://github.com/alphagov/govuk-frontend/issues/3464).

## Timebox
1 week (preliminary)

## Questions to answer

- [x] Can we make Dragon recognise the details component as a `details` element?
- [x] Is there a way to reimplement the polyfill progressively?

## Done when

- [x] Questions have been answered or we have a clearer idea of how to get to our goal
- [x] Findings have been reviewed and agreed with at least one other person
- [x] Findings have been shared, e.g: via a write-up on the ticket, at a show & tell or team meeting

**Comment by owenatgov** [comment]
## Update
Alongside desk research to see if there are other solutions we could try, we'll be experiementing with reverting [the removal of the details polyfill](https://github.com/alphagov/govuk-frontend/pull/3766) to see if that version of the details component works.

This isn't a guarantee that we'll merge that reversion as there are other downsides to including the details polyfill.

**Comment by owenatgov** [comment]
Update on the above comment: we've discovered the js `aria-controls` enhancement does work! We've updated the linked PR to include it.

We'd like to double check this with DAC to both verify that the change in announcement from 'summary' or 'disclosure triangle' to 'button' isn't an issue and so that they know about our solution for future audits.

**Comment by owenatgov** [comment]
We're closing this issue as we have a way forward as per my previous comment. I'll be making an issue to talk to DAC after this.

**Comment by SteveMilnes** [comment]
Hi @owenatgov. We use the details component in a service I work on in DfE. Did this fix make it into the design system? As in, if our devs use the coded example there, will it work for Dragon users?
