### ISSUE TITLE
initAll fails without adding govuk-frontend-supported class to the body

### ISSUE THREAD

**Issue by ttbarnes** [alphagov/govuk-frontend#5416]
## Description of the issue

- I am updating some services to the latest GOV design version (5.7.1), including the previous version, 5.7.0.
- 5.70 introduces an `isSupported` function.

We have a client side script setup to run the GOV design `initAll` function:

```js
import { initAll } from 'govuk-frontend';

export default initAll({
  button: {
    preventDoubleClick: true,
  },
});
```

After updating, the following console error appears: 

```
SupportError: GOV.UK Frontend initialised without `<body class="govuk-frontend-supported">` from template `<script>` snippet
```

From reading the [release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v5.7.0) and looking at some of the code, it looks like part of updating to 5.7.0 is to add a `govuk-frontend-supported` class to the nunjucks template's body. **Is this correct?**

If so, shall we update the release notes? As it is not clear. I expected the `initAll` function to automatically check and add a `govuk-frontend-supported` class, similar to `js-enabled`.

## Steps to reproduce the issue

- Update to 5.7.0
- Load a page with client side GOV frontend JavaScript
- Do **not** add `govuk-frontend-supported` to the HTML body.

**Comment by romaricpascal** [comment]
Hi @ttbarnes, [the `govuk-frontend-supported` class is added by a separate snippet](https://frontend.design-system.service.gov.uk/import-javascript/#before-you-start), which needs to be added as the first thing inside the `<body>` tag of your pages. 

If you're upgrading from v4.x [you should have a similar snippet on your page](https://frontend.design-system.service.gov.uk/v4/get-started/#5-get-the-javascript-working). It would need upgrading as part of moving to v5.x, for which we recommend [using the changelog of the 5.0.0 release as some kind of checklist](https://github.com/alphagov/govuk-frontend/releases/v5.0.0) to bring you project to 5.0.0 (and have the new snippet) before updating to later 5.x versions.

**Comment by romaricpascal** [comment]
If there's no snippet already in your project, we obviously encourage you to add it, but would also be interested into what led to it not being there as we may be able to update our documentation 😊

**Comment by ttbarnes** [comment]
Thanks for the quick reply and explanation @romaricpascal 

I should have mentioned - we're upgrading from 4.8.0 to the latest version (5.7.1).

We do indeed have the JS snippet for modifying the body class - it previously just had `js-enabled`, i've updated it to include the latest with `govuk-frontend-supported`. It all makes sense now 😊 

I would suggest adding this requirement/breaking change specifically to the release notes - unless i've missed it after reading a lot of release notes(?).

I did not think to check if "the snippet" had been updated in [this page](https://frontend.design-system.service.gov.uk/import-javascript), feels very rare the snippet is updated (i've done a lot of other upgrades on other services). I rely on the release notes and only learnt about the snippet change from your reply, thanks again 👍

**Comment by romaricpascal** [comment]
No worries, I undestand the changelog can make it read like the `govuk-frontend-supported` was introduced in this one while it was actually in 5.0.0. 

All the breaking changes will be in [the release notes of v5.0.0](https://github.com/alphagov/govuk-frontend/releases/v5.0.0) as [we follow semantic versioning](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/versioning.md) and will only release breaking changes in new major versions.

**Comment by ttbarnes** [comment]
I see it now, thanks @romaricpascal - that was a big release, not surprised I missed it, my fault for not reading properly.
