### ISSUE TITLE
The code for Start button is complicated

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#542]
Here is the code for a start button on the Prototype Kit:

```
<a class="govuk-c-button govuk-c-button--start govuk-!-mt-r2 govuk-!-mb-r8" href="/start" role="button">Start now</a>
```

This seems complicated for a standard component? Are we doing it right on the Prototype Kit, or can the Start Button component be tweaked somehow to make the code less complex?

**Comment by nickcolley** [comment]
The guidance for start buttons are as follows: "Use a start button as the main call to action on your service’s start page."

This means that realistically these should only be used on GOV.UK Start Pages (example: https://www.gov.uk/register-to-vote)

Should we move this component into the GOV.UK Prototype Kit, as it won't be used by any services?

This would then allow us to do more general styles for this without worrying about how it could impact services that use this component.

**Comment by dashouse** [comment]
This is isn't the code for the start button - this is `<a class="govuk-c-button govuk-c-button--start" href="/start" role="button">Start now</a>`

The override classes are applied to the start button on that example of the start page for layout purposes

**Comment by joelanman** [comment]
I understand in theory it doesnt need them, however this is a start button on a start page, the most common use by far. It would be nice if it didn't need to have the override classes basically by default

**Comment by dashouse** [comment]
With the new release of Frontend there's a new class that can be added to `<hr>`'s called `govuk-section-break` (visible or invisible with three sizes).

Now it's released we can remove the margin-bottom override on the start button example and insert a section break between the Start button and the "Before you start" section.

```
<a href="#" role="button" class="govuk-c-button govuk-c-button--start govuk-!-mt-r2 govuk-!-mb-r8">
  Start now
</a>

<hr class="govuk-section-break govuk-section-break--l">

<h2 class="govuk-heading-m">Before you start</h2>

```

However the margin-top override is still a problematic one for me, and it's an issue for all components that follow a paragraph as they need 10px to be added to the top to balance them out.

**Comment by joelanman** [comment]
excellent about the section break!

would it be terrible to add the 10px to the start button css?

**Comment by dashouse** [comment]
As the issue was with all components I originally wanted to do something like this, but was "too magic"

```
p + [class^="govuk-c-"] {
   @include govuk-responsive-margin($govuk-spacing-responsive-6, "top");
}
```
We'd actually need to add 30px so it would collapse into the 20px margin bottom of the paragraph...can't use padding because of the components (like buttons) that are in a box

**Comment by nickcolley** [comment]
I'm going to close this out, since the start button is not a common component for people to use, lets see if this comes up in the research for this mission.
