### ISSUE TITLE
Do we need two files for each component - template and macro?

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#559]
Just chatting with Dave about his blog post, and what we call templates and what we call macros. Our discussion took us to the Frontend codebase, where we have a `macro.njk` calling a `template.njk` for each component. That reminded me that when I first started using the codebase I found this separation confusing.

Do we need this set up? It might be simpler to just have macro.

**Comment by nickcolley** [comment]
Makes sense, thanks Jani.

I think we'd likely not want to make a breaking change for this so will close for now.
