### ISSUE TITLE
Investigate throwing errors or warnings when components do not get required inputs

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#562]
Ideally our components would loudly complain if they're supplied with bad inputs.

This currently isn't trivial with our current Nunjucks setup.

Related comment:
https://github.com/alphagov/govuk-frontend/issues/558#issuecomment-369239872

See this skipped test:
https://github.com/alphagov/govuk-frontend/blob/master/src/back-link/template.test.js#L17

**Comment by joelanman** [comment]
tricky, as the easiest options (putting an error on the page, or writing an error to the console) are end-user facing. End users (the public) can't do anything about invalid usage of our macros, so we really should avoid them getting errors if possible.

**Comment by nickcolley** [comment]
This has worked really well for GOV.UK Publishing Components by the way.

It's much better to have loud warnings that can be picked up before deploying as part of tests and monitoring than to have silent failures that are picked up by end-users.

Example test: https://github.com/alphagov/govuk_publishing_components/blob/master/spec/components/input_spec.rb#L9

**Comment by joelanman** [comment]
good point. I can't see what the code in that link is doing? Does it write a big red message to the page or something?

**Comment by nickcolley** [comment]
@joelanman that test is making sure when a component doesn't get the right input it fails.

- In development this would be a big loud error
- In pre-deployment scenarios (for example, GOV.UK has traffic replay from live to 'staging') it'd turn up in your logs

**Comment by 36degrees** [comment]
In Ruby land you can raise an exception, but Nunjucks has no such equivalent so (as far as I know).

**Comment by nickcolley** [comment]
At least in the Ruby ERB templates, they will raise an exception if something is not passed through by default. We have an empty object passed through to our templates that may mask a default behaviour if Nunjucks has it, would be worth investigating that.

**Comment by 36degrees** [comment]
Closing this as this isn't something Nunjucks supports which makes this very difficult to do. It could be a good thing to look into in the next firebreak.
