### ISSUE TITLE
Sass Imports dependencies are too broad.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#597]
Current:

all.scss
```scss
@import "../globals/common";

@include govuk-exports("back-link") {

  .govuk-c-back-link {
    [...]
  }
}
```

Proposed:

```scss
@import "../globals/settings/settings";
@import "../globals/tools/tools";
@import "../globals/helpers/helpers";

@include govuk-exports("back-link") {

  .govuk-c-back-link {
    [...]
  }
}
```

However if you remove the first common import the build is the same, this is because the back-link component also imports common.

This means that the back-link component is importing globals that it is not declared as a dependency.

The result of this is it's not possible to import individual components without global CSS coming with it, including the font, core, helpers etc.

Proposal:

1. Separate Scss files that export something into it's own wrapper.
2. Only import Scss files that do not export CSS into components.

Question:
Should the exported globals be it's own 'package'?

**Comment by igloosi** [comment]
is this still relevant with the single package?

**Comment by nickcolley** [comment]
Solved
