### ISSUE TITLE
Individual components inconsistently import dependant components' scss

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#600]
The input component imports the label scss file

https://github.com/alphagov/govuk-frontend/blob/0fd001dfb65ece9378e8e2c30959ec175e3015ba/packages/input/_input.scss#L1-L5

from the dependant label component

https://github.com/alphagov/govuk-frontend/blob/0fd001dfb65ece9378e8e2c30959ec175e3015ba/packages/input/package.json#L7

but the radio component has the same dependency without importing

https://github.com/alphagov/govuk-frontend/blob/0fd001dfb65ece9378e8e2c30959ec175e3015ba/packages/radios/_radios.scss#L1-L3

https://github.com/alphagov/govuk-frontend/blob/0fd001dfb65ece9378e8e2c30959ec175e3015ba/packages/radios/package.json#L6

Would be good to have automated safe guards around this, since it's easy to do with no errors.

A lo-fi way we could do this is by *only* testing with individual packages by default in the review application.

**Comment by igloosi** [comment]
is this still relevant with the single package?

**Comment by nickcolley** [comment]
Believe this is solved now
