### ISSUE TITLE
Set up Nunjucks development environment with more meaningful errors

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#614]
Nunjucks has a couple of undocumented features for developers to make it easier to debug issues
We should look into implementing some.

Examples of available options
https://github.com/mozilla/nunjucks/blob/6f3e4a36a71cfd59ddc8c1fc5dcd77b8c24d83f3/nunjucks/src/environment.js#L40
and 
https://github.com/mozilla/nunjucks/issues/412#issuecomment-97839292

Trello triage ticket: https://trello.com/c/3qAck5jL/841-configure-nunjucks-development-environment

**Comment by nickcolley** [comment]
Since this is related to our review application I'm going to close this, we can still track this in trello.
