### ISSUE TITLE
Table: Rename captionSize -> captionClass for consistency

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#632]
It'd be good to change captionSize to captionClass to better describe what it's doing, this is consistent with other places we put a class on a part of a component.

http://localhost:3000/components/table

**Comment by 36degrees** [comment]
Recorded [here](https://trello.com/c/0NJ1zzEK/882-rename-tables-captionsize-to-captionclass).

**Comment by igloosi** [comment]
done in #643
