### ISSUE TITLE
Theming: Components should alias variables used within their file

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#641]
When using variables we're inconsistent where they're defined and consumed.

In some places we rely on an [`applied` file](https://github.com/alphagov/govuk-frontend/blob/master/src/globals/settings/_colours-applied.scss), in other cases [we define them next to component definitions](https://github.com/alphagov/govuk-frontend/blob/master/src/footer/_footer.scss#L23).

Another example is the panel component which [references a top level variable directly](https://github.com/alphagov/govuk-frontend/blob/master/src/panel/_panel.scss#L37), making theming very difficult without changing colours for other components.

My proposal would be to consistently set variables at the top of each component file that references top level variables.

**Comment by igloosi** [comment]
comment from slack

> Hi, I got an odd issue I am hoping you can help with.  I have overridden $govuk-brand-colour and the application.scss is updated (when inspecting it).  However this is used in the header indirectly via "$govuk-header-border-color: $govuk-brand-colour" ... however it still has this as "$govuk-header-border-color: $govuk-blue;"  (i.e no change in colour).  Any ideas?   [Also should it not be $govuk-header-border-*colour*]

**Comment by nickcolley** [comment]
Going to close for now, we may look into whitelabelling in the future so we can re-open then.
