### ISSUE TITLE
Theming: Move spacing scale to t-shirt sizing

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#642]
At the moment our spacing scale can be themed (depending on [variables being overridden](https://github.com/alphagov/govuk-frontend/issues/640)) but they could be confusing to do so.

This is because the variables reference the values they current are set to, so a font size of 80 is called [$govuk-font-80](https://github.com/alphagov/govuk-frontend/blob/master/src/globals/settings/_typography-responsive.scss#L12).

This is then used in [other places to generate the scale](https://github.com/alphagov/govuk-frontend/blob/ad2022ef044d2e67768199479e215f641e36cc5f/src/globals/core/_typography.scss#L9) that is based on t-shirt sizing.

My proposal would be to consistently use t-shirt sizing for our spacing scale, as seen at https://github.com/alphagov/govuk-frontend/blob/ad2022ef044d2e67768199479e215f641e36cc5f/src/globals/core/_prose-scope.scss#L10

**Comment by 36degrees** [comment]
I believe this _might_ have been addressed by #779 which makes it possible to override the entire spacing scale.

@nickcolley ?

**Comment by nickcolley** [comment]
Not what I imagined, but I suppose it's technically possible. Let's find out more when we do more white labelling later on.
