### ISSUE TITLE
Investigate if empty directories in `packages` are deleted before copying to it from `src`

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#649]
With a recent release running `npm run pre-release` (step 5 in [publishing docs](https://github.com/alphagov/govuk-frontend/blob/master/docs/publishing.md)) mistakenly suggested that a new package `cookie-banner` should be created, potentially due to a redundant directory in packages:

<img width="875" alt="screen shot 2018-04-12 at 10 20 04" src="https://user-images.githubusercontent.com/5007934/38671749-1a03bdae-3e44-11e8-92c8-cc77d481ca71.png">

This was fixed by running `git clean -dfx`.

We should make sure that `packages` folder, including empty directories, are deleted before copying files from `src` to avoid this happening in the future.

**Comment by igloosi** [comment]
task is already in place for that
https://github.com/alphagov/govuk-frontend/blob/master/gulpfile.js#L90

**Comment by hannalaakso** [comment]
Thanks @igloosi I've updated the title and description to reflect this.

**Comment by nickcolley** [comment]
Believe this is fixed with the restructure, we no longer have empty folders.

And this script no longer exists.
