### ISSUE TITLE
Proposal: Pull Request Template

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#677]
I was thinking we could have the following in a pull request template, which would be optional.
---

Feel free to delete any sections (or all) that do not apply.

### Browser testing

<details>
<summary>Testing with browsers</summary>

#### Windows
- [ ] Internet Explorer 11 
- [ ] Internet Explorer 8-10
- [ ] Edge (latest versions)
- [ ] Google Chrome (latest versions)
- [ ] Mozilla Firefox (latest versions)
#### macOS
- [ ] Safari 9+
- [ ] Google Chrome (latest versions)
- [ ] Mozilla Firefox (latest versions)
#### iOS
- [ ] Safari 9.3+
- [ ] Google Chrome (latest versions)
#### Android
- [ ] Mozilla Firefox (latest versions)
- [ ] Google Chrome (latest versions)

This is based on https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in
</details>

### Accessibility

<details>
<summary>Testing with colours overriden</summary>
  

This is based on https://accessibility.blog.gov.uk/2017/03/27/how-users-change-colours-on-websites/
</details>

<details>
<summary>Testing with assistive technologies</summary>

- [ ] JAWS, 15 or later inInternet Explorer 11
- [ ] ZoomText, 10.11 or later in Internet Explorer 11
- [ ] Dragon NaturallySpeaking, 11 or later in Internet Explorer 11
- [ ] NVDA, 2016 or later in Mozilla Firefox (latest versions)  
- [ ] VoiceOver, Mac OS X 10.10 in Safari 10 (or higher)
- [ ] VoiceOver, iOS 10.3 (or higher) in Safari

This is based on https://www.gov.uk/service-manual/technology/testing-with-assistive-technologies
</details>

---

**Comment by joelanman** [comment]
Pull request templates are just plain text in a textarea aren't they? So a user wouldn't see these nice `<details>` and links

**Comment by nickcolley** [comment]
@joelanman I believe they can be full markdown: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/ `PULL_REQUEST_TEMPLATE.md`

**Comment by joelanman** [comment]
they can be, but they appear to the user as the original markdown in a textarea, which I don't think is very usable ie.

```
## Testing

### Browser testing

<details>
  <summary>Testing with browsers</summary>
  
  This table is based on https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in

| Operating system | Browser                                           | Result |
|-------------------|----------------------------------|--------|
| Windows                | Internet Explorer 8-10                   |             |
|                                | Internet Explorer 11                        |             |
|                                | Edge (latest versions)                    |             |
|                                | Google Chrome (latest versions)  |              |
|                                | Mozilla Firefox (latest versions)    |              |
| macOS                   | Safari 9+                                        |              |
|                                | Google Chrome (latest versions ) |              |
|                                | Mozilla Firefox (latest versions)    |              |
| iOS                         | Safari 9.3+                                     |               |
|                                | Google Chrome (latest versions   |               |
| Android                  | Mozilla Firefox (latest versions)    |               |
|                                | Google Chrome (latest versions)  |               |
| Windows Phone    | Internet Explorer (latest versions) |              |
</details>

### Accessibility

<details>
  <summary>Testing with colours overriden</summary>

  This is based on https://accessibility.blog.gov.uk/2017/03/27/how-users-change-colours-on-websites/
  
  <!-- Include results here, a screenshot may be useful, but not required. -->
</details>

<details>
  <summary>Testing with assistive technologies</summary>

  This table is based on https://www.gov.uk/service-manual/technology/testing-with-assistive-technologies

| Software                             | Version          | Browser                                                    | Result |
|---------------------------|--------------|----------------------------------------|-------|
| JAWS                                  | 15 or later      | Internet Explorer 11                                  |            |
| ZoomText                            | 10.11 or later | Internet Explorer 11                                  |            |
| Dragon NaturallySpeaking | 11 or later      | Internet Explorer 11                                  |            |
| NVDA                                   | 2016 or later | Mozilla Firefox (latest versions)              |            |
| VoiceOver  Mac OSX          | N/A                | Safari 10 (or higher) on Mac OS X 10.10 |            |
| VoiceOver iOS                    | N/A                 | iOS 10.3 (or higher)                                 |            |

</details>

---

<!-- Add any context here, for example a trello card -->
```

**Comment by 36degrees** [comment]
Yeah, I think I agree with @joelanman – I'm not sure about requiring users to understand markdown tables or how the markdown relates to the `<details>` HTML. I'd suggest doing something simpler - two list of checkboxes or something.

However, I'm generally not sure about this at a broader level. I think it's likely to put users off because they feel they _have_ to test with all those different tools. If the change is small and very unlikely to affect assistive technologies then I don't think we'd expect or require contributors to spend time testing in all of the things. Even if it's a complex change, they may not have access to JAWS or Browserstack so we may have to help them.

Perhaps we could just have saved replies that we could use when we get a contribution that we think requires further testing?

**Comment by nickcolley** [comment]
@joelanman I've formatted the tables so they're easy to edit within the github interface.

<img width="554" alt="screen shot 2018-05-02 at 11 42 36" src="https://user-images.githubusercontent.com/2445413/39519250-eef4cf1c-4dfd-11e8-9eca-912dfce5139f.png">

@36degrees this would be clearly labeled as optional, and could be removed if it's not useful.

**Comment by nickcolley** [comment]
Closing as is controversial
