### ISSUE TITLE
Conditional reveal aria-hidden/display none being used

### ISSUE THREAD

**Issue by adamsilver** [alphagov/govuk-frontend#686]
Currently, the `[aria-hidden=true]` attribute/selector is being used to visually hide the conditional panel when clicking a checkbox or radio button.

My thinking is that we can just use `.js-hidden` which will stop a potential flicker and hide the panel for both sighted users and screen reader users without having to have special attributes just for AT.

**Comment by nickcolley** [comment]
I believe originally we tried `.js-hidden` and `hidden` but then moved towards `[aria-hidden=true]` to avoid problems but I confess to have forgotten what that problem was.

**Comment by adamsilver** [comment]
Oh I know what it might be. The reveal is based on checkbox/radio `checked` state.

**Comment by nickcolley** [comment]
We resolved this by using a modifier rather than a global class in https://github.com/alphagov/govuk-frontend/pull/885

Thanks for raising Adam
