### ISSUE TITLE
Allow classes to be passed to a form group in Nunjucks macros

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#713]
Take the following example
![screen shot 2018-05-22 at 21 55 30](https://user-images.githubusercontent.com/3758555/40389670-f58f5186-5e0a-11e8-9a40-e3e26331dd29.jpg)

We wrap the label (empty in this case) and input in a `form-group`
If one wanted to align a button to that input they would have to wrap the`form-group` in another container and set available `govuk-!-display-inline-block` class. 
Additional classes can be set on the button by default.

New `formGroupClasses` parameter would be available to set on all components we set from-group on

Example with `formGroupClasses`
![screen shot 2018-05-22 at 22 06 51](https://user-images.githubusercontent.com/3758555/40390254-7fa344f8-5e0c-11e8-8c40-1dbfb2bd4a4c.jpg)

```
{{ govukInput({
      "id": "national-insurance-number",
      "name": "national-insurance-number",
      "formGroupClasses": "govuk-!-display-inline-block"
 }) }}
 {{ govukButton({
      "classes": "govuk-!-display-inline-block",
      "text": "Save and continue"
 }) }}
```

It's worth considering if this kind of alignment is actually being used anywhere

**Comment by igloosi** [comment]
closing as there seems to be no need

**Comment by chdesign** [comment]
![image](https://user-images.githubusercontent.com/22620603/42171360-fd38fac4-7e10-11e8-9bd5-655031fc19d1.png)
![image](https://user-images.githubusercontent.com/22620603/42171379-0d6420b8-7e11-11e8-90ae-ba4572dc0f25.png)

On the same note, where I would have used `.form-group-related` before I would now use the spacing override on the form group.
