### ISSUE TITLE
Allow checkbox items to have explicit names

### ISSUE THREAD

**Issue by solidgoldpig** [alphagov/govuk-frontend#717]
I would like the ability to set the names of checkbox items explicitly rather than have them all share the same name.

This would allow me not to have to map values from one variable to another at the backend, but also to target the checkbox items on the clientside using the name (the latter being of less importantance since I could always pass an explicit id to achieve much the same effect)

Proposed code changes here:

https://github.com/solidgoldpig/govuk-frontend/compare/master...checkboxes-items-can-have-explicit-names

**Comment by igloosi** [comment]
Hi @solidgoldpig 
thanks for raising the issue. We're always looking to get the community's feedback as well as getting the community involved in the contribution.

If you're willing to raise a pull request for us to review it as a team, that'd be great.

**Comment by igloosi** [comment]
Thanks. 
We'll aim to release this next week.

**Comment by igloosi** [comment]
Hi @solidgoldpig,
this has now been released in [v0.0.30-alpha](https://github.com/alphagov/govuk-frontend/releases/tag/v0.0.30-alpha), so I will close the issue.
