### ISSUE TITLE
Relative paths for nunjucks imports

### ISSUE THREAD

**Issue by web-bert** [alphagov/govuk-frontend#722]
I have my nunjucks configure path set to `node_modules/@govuk-frontend` that way when I import govuk macros I use a path that describes where they are coming from (and they are not confused with my own macros):

```
{% from 'frontend/components/radios/macro.njk' import govukRadios %}
```

This has been working fine (for things like the footer), however this doesn't work when a macro template imports other macros - such as radios.

The fix for this would be to use relative paths for the imports. I have tested locally and it works for me...

**Comment by igloosi** [comment]
Hi, @web-bert 
thanks for raising this.

Once the team is back on Tuesday, we'll have a look to see if we can work this into our backlog.
We'll keep you posted.

**Comment by nickcolley** [comment]
This makes sense to me, and is consistent with how we encourage users to import JavaScript and SCSS

**Comment by igloosi** [comment]
should we also consider having an 'all.njk' like we do for JS and SCSS where we import all components?

**Comment by web-bert** [comment]
I guess the use case for that would be:

```
{% from "all.njk" import govukRadios, govukInput %}
```

Could be useful, I assume there wouldn't be any performance impact for bringing them all in at once?

**Comment by nickcolley** [comment]
@web-bert thanks a ton for raising this, the fix for this will go out in the next release.

**Comment by web-bert** [comment]
Great stuff, I look forward to the release 👍

**Comment by 36degrees** [comment]
@web-bert would you be OK with us crediting you in the changelog?

**Comment by web-bert** [comment]
Sure, thanks for the swift resolution
