### ISSUE TITLE
Add sensible classes default to header

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#736]
At the moment we require users to add the container class themselves, when most people will want this.

We need to make sure 'core' is a dependency of this component.

Currently:
```
{% from 'header/macro.njk' import govukHeader %}

{{ govukHeader({
  "homepageUrl": "/",
  "containerClasses": "govuk-width-container"
}) }}
```

**Comment by 36degrees** [comment]
This was closed by #807
