### ISSUE TITLE
Using comment blocks before the `<html>` tag breaks layout in IE8

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk-frontend#751]
Using comment blocks (e.g. `<!-- block:pageStart -->`) before the `<html>` tag is breaking the template examples layout in IE8.

### With `<!-- block:pageStart -->`
<img width="727" alt="screen shot 2018-06-01 at 17 21 17" src="https://user-images.githubusercontent.com/788096/40851828-6d5b0e82-65c0-11e8-9895-2820ece1623e.png">

### Without `<!-- block:pageStart -->`
<img width="1024" alt="screen shot 2018-06-01 at 17 21 58" src="https://user-images.githubusercontent.com/788096/40851878-899526aa-65c0-11e8-9ca0-32bf7614fe4c.png">

**Comment by nickcolley** [comment]
What is the need for this block? Can you put anything before the doctype without it breaking?

If not, we should probably remove this.

**Comment by igloosi** [comment]
in non html5 documents you could have something before doctype
"Anything before the DOCTYPE, like a comment or an XML declaration will trigger quirks mode in Internet Explorer 9 and older."

since we're all about html5, let's remove it

**Comment by nickcolley** [comment]
Would this be a problem if we added `<meta http-equiv="x-ua-compatible" content="ie=edge">` to template?
