### ISSUE TITLE
Review `package/README`

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#753]
Since this is the doc that gets pushed to `npm`, we should review whether it should include installation instructions, usage instructions etc. that are included in the main repo docs.

**Comment by igloosi** [comment]
package has it's own README, src one doesnt get copied over

**Comment by igloosi** [comment]
#797

**Comment by nickcolley** [comment]
At the moment the README published to npm is not great.

We could consider publishing the main README (without relative links)

We could consider publishing https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md

Or maybe something that mixes the two.

**Comment by 36degrees** [comment]
Closed by #797
