### ISSUE TITLE
Check for broken links in markdown files

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#755]
It would be good to run tests against the project markdown files to ensure they don't contain broken links.

**Comment by 36degrees** [comment]
Closing this as I don't think we'd prioritise it now that most of the user-facing documentation lives in alphagov/govuk-frontend-docs.

There's a new issue (https://github.com/alphagov/govuk-frontend-docs/issues/8) that represents adding a link checker to that repo.
