### ISSUE TITLE
Document how to include and use browser JavaScript bundle.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#757]
At the moment we only document how to use a JavaScript bundle, when users may choose to bring 'all.js' into their project and execute that.

**Comment by igloosi** [comment]
should this be done? https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md#option-1-include-javascript

**Comment by nickcolley** [comment]
Nice!
