### ISSUE TITLE
GOV.UK Radios (Checkboxes) Items do not support Hints

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#768]
Raised by Alex T.

It's currently it is not possible to use hints in items as seen in https://www.gov.uk/log-in-file-self-assessment-tax-return/sign-in/prove-identity

Current work around:

```
{{ govukRadios({
  "idPrefix": "example",
  "name": "example",
  "fieldset": {
    "legend": {
      "text": "Create a new organisation"
    }
  },
  "items": [
    {
      "value": "Create new organisation",
      "html": "test <span class="govuk-hint">hint here.</span>",
    },
    {
      "value": "Merge organisations",
      "html": "test <span class="govuk-hint">hint here</span>",
      "checked": true
    }
  ]
}) }}
```

**Comment by igloosi** [comment]
for this it would be good to understand what the relationship is between the label text and hint text in the way they're read with screenreaders

**Comment by timpaul** [comment]
This is a relatively common pattern, so we should support it. In the self assessment example above the hint text is not part of the label, it's in a span immediately following it. However, on Voiceover at least it does get read out when you navigate between the radio options, which is probably what we want to happen.

**Comment by 36degrees** [comment]
> In the self assessment example above the hint text is not part of the label, it's in a span immediately following it. However, on Voiceover at least it does get read out when you navigate between the radio options, which is probably what we want to happen.

This works because the span is associated with the input using `aria-describedby`, which mirrors how we now associate hints and error messages with inputs generally.
