### ISSUE TITLE
Header component has visible unusable menu button when CSS fail to load. 

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#775]
Not a big deal but might be nice to use the 'hidden' attribute, or a hardcoded 'display: none'.

<img width="325" alt="Screenshot 2021-09-01 at 10 34 39" src="https://user-images.githubusercontent.com/29889908/131648607-0d52fbe3-bd80-4431-a13f-d1e83a91608d.png">

## Done when

- [ ] TBC
- [ ] "Details of breaking change" section below completed to help with writing release notes

## Details of breaking change

- which users are affected: TBC
- the change that’s been made: TBC
- changes users will have to make: TBC
- impact of users not making those changes: TBC

**Comment by igloosi** [comment]
button is also visible if CSS succeeds and JS fails
