### ISSUE TITLE
Review if gutter variables need to coupled with spacing scale

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#780]
`$govuk-gutter` used to use the spacing variables but is now hardcoded. However with the changes introduced in https://github.com/alphagov/govuk-frontend/pull/779, it is not possible to access the new `govuk-spacing` function from inside the settings layer. It isn't immediately clear if the gutter variables should be coupled with the spacing scale. 

If we feel that the gutter settings need to use the spacing scale, we could use `map-get` to fetch these inside the settings layer, or refactor the way helpers are imported.

**Comment by dashouse** [comment]
Closing as the gutter is now only used by the layout grid. We would like to keep it in line with existing values so that the gutter remains the same when a user goes from gov.uk to a service.
