### ISSUE TITLE
Missing `govuk-label--bold`

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#783]
we talk about this in the component variants http://govuk-frontend-review.herokuapp.com/components/label/

but we seem to have removed it

Shall we remove it totally or add the style?

**Comment by 36degrees** [comment]
It was removed in https://github.com/alphagov/govuk-frontend/pull/684/files#diff-9b612986ac316b3a5eec016d9384448fL20 – `govuk-label--s` is effectively the same thing.

**Comment by igloosi** [comment]
ql, lets update the yml, review app then. will raise a pr
