### ISSUE TITLE
Default text for back link

### ISSUE THREAD

**Issue by web-bert** [alphagov/govuk-frontend#792]
Considering the component is called "back-link" I think it would make sense to default the text to "Back" if none is provided - then you only need to specify the text when you want to override the default?

**Comment by web-bert** [comment]
I have done this locally and it works:

```
<a href="{%- if params.href %}{{ params.href }}{% else %}#{% endif -%}" class="govuk-back-link{%- if params.classes %} {{ params.classes }}{% endif -%}"
  {%- for attribute, value in params.attributes %} {{attribute}}="{{value}}"{% endfor %}>{{ (params.html | safe if params.html else (params.text if params.text else 'Back')) }}</a>
```

**Comment by nickcolley** [comment]
Hey @web-bert this sounds great, do you want to do a Pull Request for that?

**Comment by web-bert** [comment]
Sure, can I clone this repo and push a branch or do I have to fork?

**Comment by nickcolley** [comment]
You'll have to fork this repository since you're not a maintainer.
