### ISSUE TITLE
Add guidance on how to write Accessibility Acceptance criteria

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#799]
We would like to add guidance to GOV.UK Frontend on how to write Accessibility Acceptance criteria for components. 

The [criteria for Accessible Autocomplete](https://github.com/alphagov/accessible-autocomplete/blob/master/accessibility-criteria.md) could provide a basis for this.

**Comment by dashouse** [comment]
Closing as we will look at this as part of https://github.com/alphagov/govuk-design-system/issues/677

**Comment by hannalaakso** [comment]
Reopening as this wasn't done as part of alphagov/govuk-design-system#677

**Comment by EoinShaughnessy** [comment]
Closing this issue as it's been superseded by[ #1781](https://github.com/alphagov/govuk-design-system/issues/1781).
