### ISSUE TITLE
Create `initAll()` for components with JavaScript

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#805]
Currently if you want to initialise multiple instances of a component on a page, you'll have to iterate through them yourself (which might not support IE8). We get around this problem by initialising all the components using our own `nodeListForEach` function which supports IE8. However we are not exposing this utility function in `all.js`. 

We should have an `initAll` function for each component that accepts an array of components and loops through them with `nodeListForEach`. This would make it easier for consumers to initialise multiple components on a page while supporting IE8.

[Installation docs](https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md) should be updated accordingly.

**Comment by nickcolley** [comment]
We could also consider a shared function that any component can use.

`www.GOVUKFrontend.init(Checkboxes)`

**Comment by hannalaakso** [comment]
After discussion with team, it was decided that it would be better from users' point of view to try and add this feature using a polyfill of `nodeList` and 'forEach', rather than add our own custom function that users have to learn to use.

**Comment by hannalaakso** [comment]
This is not the right approach as discussed above. Closing issue.
