### ISSUE TITLE
grid containers may need a clearfix

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#814]
When implementing the task-list pattern I needed to use `govuk-clearfix` to stop the page from collapsing:

<img width="1008" alt="screen shot 2018-06-21 at 14 13 14" src="https://user-images.githubusercontent.com/2445413/41721254-52ddec6c-755d-11e8-8775-5956aa1567d8.png">

**Comment by igloosi** [comment]
grid-row has a clearfix https://github.com/alphagov/govuk-frontend/blob/master/src/helpers/_grid.scss#L50
you just used the wrong class :) `grid-grid-row`

**Comment by nickcolley** [comment]
Thanks Jani
