### ISSUE TITLE
Header component - Service name alignment

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#838]
The service name should sit on the same baseline as GOV.UK

![screen shot 2018-06-27 at 08 42 06](https://user-images.githubusercontent.com/23356842/41969164-73aa8068-79fe-11e8-85ca-5de07ada1b40.png)

The navigation links are ok to be vertically centred and should remain unchanged.

**Comment by igloosi** [comment]
line-height: 1.25 (as per your work) will get us closer (if not dead on)

**Comment by igloosi** [comment]
font :)

**Comment by dashouse** [comment]
Thanks, of course.
Will close issue until we know how we're rolling out the new version of the font. :)
