### ISSUE TITLE
Init all components macros in the Template

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#840]
I'm not sure if this is a good idea, but I've noticed that you do not need to import components that are already imported by the template.

For example setting the govukFooter block can be done without first importing. Since it's imported in the inherited template.

Is this a good thing? Could we make using the macros really easy if you're using the Template?

Not sure.

**Comment by igloosi** [comment]
part of me things we should get people to import it when they need it, to get into a habit of doing so.

**Comment by nickcolley** [comment]
Yeah, I guess I was just surprised to be able to use the footer component without importing it...
