### ISSUE TITLE
Alternative font path requires trailing slash

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-frontend#842]
## What I'm trying to do

I've copied the fonts to the folder `/public/fonts` and I want them to be accessible from there, so I set the path in my SASS file to

```
$govuk-fonts-path: '/public/fonts';
```

as documented [here](https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md#alternative-solution).

## What I expect

Clients performing successful GET requests such as 

```
GET /public/fonts/bold-a2452cb66f-v1.woff2 HTTP/1.1" 200
```

## What I actually see

```
GET /public/fontsbold-a2452cb66f-v1.woff2 HTTP/1.1" 404 -
```

## Workaround

Adding a trailing slash to the path so that `$govuk-fonts-path: '/public/fonts'` works as expected.

## Suggested fix

Either the documentation should be updated to reflect the need for a trailing slash, or the paths should be fixed so it's not necessary.

**Comment by igloosi** [comment]
Hi, @lfdebrux 
thanks for raising this. 
I've created a pull request to fix this
