### ISSUE TITLE
Should we be using <html lang="en-GB"> not <html lang="en">?

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-frontend#851]
Page template is currently using `<html lang="en">`

I believe (un-tested) using `<html lang="en-GB">` should tell a screenreader to switch to a British accent and pronounce words like aluminium, advertisement differently.

**Comment by accessiblewebuk** [comment]
We should test this to see if this improves pronunciation, but also be wary of changing it as it may introduce other confusing effects. In all my years of testing I don't remember seeing any sites specifying en-GB, the majority have been en or en-US, but that doesn't mean we shouldn't consider this if it helps make things clearer and simpler.

**Comment by dashouse** [comment]
"For accents, formatting, spelling, etc. If the user is not British nothing will break as the ‘en’ does the heavy lift, ‘-GB’ sub-tag makes it better."

"go nuts and use en-gb."

http://adrianroselli.com/2018/04/slides-mind-your-lang-at-london-web-standards.html

https://twitter.com/aardrian/status/1014223003847135232

**Comment by nickcolley** [comment]
Looks positive, let's do some testing :)

**Comment by nickcolley** [comment]
Comment from his blog post:

> I had a screenreader user on complaining that my website made his screenreader read out oddly: turned out the en-gb tag was switching his TTS. Confused him utterly! Most users won't have multiple TTS variants, I suspect, but might be best to stick with "en" rather than "en-gb" and "en-us" so as not to surprise users?
