### ISSUE TITLE
Add component principle around keeping to the 5px spacing scale

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#867]
When adjusting the tag component I mistakenly broke a rule around heights for our components.

We should document this somewhere to help people in the future.

See Ollie's helpful comments:
https://github.com/alphagov/govuk-frontend/pull/855#pullrequestreview-133602078
https://github.com/alphagov/govuk-frontend/pull/855#discussion_r199477367

**Comment by dashouse** [comment]
Closing this as it will be covered in #1121
