### ISSUE TITLE
Allow passing classes to govukRadio label

### ISSUE THREAD

**Issue by timja** [alphagov/govuk-frontend#879]
Currently there is `'govuk-radios__label'` applied but you can't pass your own class in, it would be useful to allow for a bold label and a nonbold hint underneath
https://github.com/alphagov/govuk-frontend/blob/master/src/components/radios/template.njk#L58

<img src="https://user-images.githubusercontent.com/3758555/42398697-c1950ee0-8162-11e8-91a3-21d559e17b82.png">

**Comment by igloosi** [comment]
released in v1.2.0
