### ISSUE TITLE
Make it easier to set widths on table columns

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#887]
Sometimes you need to set widths on table columns. For example to set a good line width, or to have columns in two tables line up.

You can currently achieve this using the `format` argument but this is not documented

**Comment by igloosi** [comment]
`format` attributes translates into a modifier, so we can't use override classes directly (with adding extra css)
we might have to bite the bullet and allow classes to be added to child elements like we did elsewhere

**Comment by igloosi** [comment]
this is now possible to do with https://github.com/alphagov/govuk-frontend/pull/1015
after the release we can add an example to the Design System
