### ISSUE TITLE
Updating the kit instructions – beta.9 to beta.10

### ISSUE THREAD

**Issue by gazjoy** [alphagov/govuk-frontend#889]
I have just updated the kit from `beta.9` to `beta.10` and it seems as though the instructions on updating the kit are missing a few bits: https://govuk-prototype-kit.herokuapp.com/docs/updating-the-kit

I had to update `app/includes/scripts.html`
and the `window.GOVUKFrontend.initAll()` is now in `application.js`

Cheers.

**Comment by igloosi** [comment]
Hi @gazjoy thanks for raising this. I have opened this issue in the prototype kit repo and will close this one here.
