### ISSUE TITLE
Prefix `js-` classes

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-frontend#901]
The current classes we're using are:
- `js-hidden`
- `js-header-toggle`
- `js-enabled`

The class names used could very easily conflict with other app styles. We should therefore consider prefixing them eg. `govuk-js-hidden`.

The convention is to use the `js-` prefix to signal classes used by JS so alternatively we could consider `js-govuk-hidden`. Or something else?

**Comment by nickcolley** [comment]
Ollie, Hanna and I caught up to talk about this in relation to the tabs and conditional reveal component.

We decided to avoid a global utility for now, instead opting to have specific `hidden` modifiers.
