### ISSUE TITLE
Extend header navigation items properties to allow for data- attributes on items in a macro

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-frontend#904]
I have a need to add data- attributes to header navigation items.
We currently use a header macro, which unfortunately does not allow data- attributes on navigation items. 

Consider allow that. Fallback is not to use the macro to generate the header, just use HTML.

**Comment by nickcolley** [comment]
Could this mean adding 'attributes' property support for the individual items?

**Comment by igloosi** [comment]
yeah ! :)

**Comment by nickcolley** [comment]
Original https://github.com/alphagov/govuk-prototype-kit/pull/551 need
