### ISSUE TITLE
HTML table examples have trailing spaces in class names

### ISSUE THREAD

**Issue by zuzak** [alphagov/govuk-frontend#915]
The generated HTML on the [Table](https://design-system.service.gov.uk/components/table/) examples have trailing spaces after some of the class names, which they probably shouldn't:

```html
<td class="govuk-table__cell ">£109.80 per week</td>
```

**Comment by nickcolley** [comment]
I believe there's several places this happens, so potentially this should be done consistently.

**Comment by igloosi** [comment]
fixed by https://github.com/alphagov/govuk-frontend/pull/1015
