### ISSUE TITLE
Use `get-function` for calling Sass functions

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk-frontend#918]
### What
`src/tools/_font_url.scss` and `src/tools/_image_url.scss` should use `get-function` instead of passing a string directly; e.g. `@return call(get-function($govuk-font-url-function), $filename);`

### Why
`get-function($string)` is deprecated and adds loads of warnings to the log
```
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("image-url")) instead.
```

I have a PR for this, but I can no longer push it.

**Comment by 36degrees** [comment]
Thanks for raising Alex!

> I have a PR for this, but I can no longer push it.

Are you able to open a pull request from a fork?

**Comment by alex-ju** [comment]
@36degrees I am, but I was to lazy to cherry pick the commit. Will do that.

**Comment by 36degrees** [comment]
Thanks Alex – appreciate it!

To avoid cherry picking I think you should be able to do this by forking the repo in the GitHub interface and then adding it as a new remote (renaming the existing remote to upstream):

`git remote rename origin upstream`
`git remote add origin git@github.com:alex-ju/govuk-frontend.git`

You should then be able to push your branch – I think…!
