### ISSUE TITLE
Tabs result in a flash of unstyled content as the page loads

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#927]
Similar to the [problem we had with conditional reveals](https://github.com/alphagov/govuk-frontend/issues/787) if the JavaScript is slow to load tabs will be shown stacked in a broken fashion. 

You can see a simulation of this in this closed PR https://github.com/alphagov/govuk-frontend/pull/917

**Comment by nickcolley** [comment]
I have a WIP branch for this: https://github.com/alphagov/govuk-frontend/compare/fix-fouc-with-tabs-panels

Main thing I think we'd need to introduce is being able to set an initial active state for tabs.

**Comment by adamsilver** [comment]
Originally I had it so that the default active state (unless in the location hash) is the first tab.
