### ISSUE TITLE
Consider making more components callable

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/govuk-frontend#941]
It feels fairly common to include html (eg multiple paragraphs), and possibly even other components, with a Details component, or other components such as Panel or Inset Text.

To this end, it'd be nice to make these component callable, so you could do this:

```
{% call govukDetails({summaryText: 'Test'}) -%}
  <p>hello</p>
  <p>world</p>
{% endcall %}
```

as an alternative to this:

```
{% set detailsHtml %}
  <p>hello</p>
  <p>world</p>
{% endset %}

{% call govukDetails({summaryText: 'Test', html: detailsHtml}) -%}
```

**Comment by vanitabarrett** [comment]
This came up again today, suggested by a new user https://github.com/alphagov/govuk-frontend/issues/2299

> GDS components support passing HTML content inline or via a variable with separate set block. Often the structure of this content means that passing HTML content inline is messy or impossible. This results in many set blocks that are disconnected from their components, which is difficult to read.

> A solution to this would be to support the caller() block within GDS macros. From Nunjucks documentation: A call block enables you to call a macro with all the text inside the tag. This is helpful if you want to pass a lot of content into a macro. The content is available inside the macro as caller().
