### ISSUE TITLE
conditional reveals don't work with HTML

### ISSUE THREAD

**Issue by zacmarshall** [alphagov/govuk-frontend#953]
We are using the HTML versions of the new GDS standards and have found that the code for conditionally revealing content doesn't work. 

Please see attached example, changing to use the JavaScript supplied for the Node version or the JS used on the demo page works OK. 

I have attached html, css and js based on the page at 
https://design-system.service.gov.uk/components/radios/conditional-reveal/index.html 

Swapping the JS to use the commented line will result in the conditional reveal working. 
      
      <script src="./javascripts/govuk-frontend-1.2.0.min.js"></script>

**Comment by 36degrees** [comment]
Hi Zac,

I don't believe you're able to attach files to GitHub issues – can you email govuk-design-system-support@digital.cabinet-office.gov.uk and we can investigate.

Thanks,

Ollie

**Comment by zacmarshall** [comment]
Just emailed the html, earlier zip file with JS got bounced. 

Zac

**Comment by 36degrees** [comment]
Hi Zac,

It looks like you're not initialising the components – at least not that I can see from the index.htm file you sent over, but it's hard to tell without the context of the other files you're including.

You can initialise all Frontend components on the page by calling `<script>window.GOVUKFrontend.initAll()</script>` before your closing `</body>` tag, as documented in the ['installing from dist' instructions](https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-from-dist.md#2-include-resources).

Thanks,

Ollie

**Comment by 36degrees** [comment]
Hi Zac,

I'm going to close this now as I believe we've resolved your problem. If you're still having issues, please feel free to re-open this.

Ollie
