### ISSUE TITLE
Link underlines sit too low in Firefox

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend#962]
As [originally raised by @dashouse on GOV.UK Template](https://github.com/alphagov/govuk_template/issues/359), link underlines looks like they're sitting below the text (almost as if they are using text-underline-position: under; (which they aren't). This is affecting GOV.UK Frontend as well:

<img width="1392" alt="screen shot 2018-08-23 at 09 55 53" src="https://user-images.githubusercontent.com/121939/44515603-df94d100-a6ba-11e8-854b-7b9f9b59c560.png">

Dave identified that this started happening in Firefox 39, and from doing some digging it looks like [Firefox 39 was the release that enabled support for WOFF2](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/39), and this seems to be related – commenting out the woff2 file from the font-face declaration 'fixes' it. We think this is something to do with the way that the text decoration is aligned with the 'baseline' (which we know is 'high' in the current cut of our font-face) in woff2 fonts.

However, it looks like updating to use the new cut of the font, with the normalised baseline, will fix this, so we might not need to do anything except prioritising the work to move to the new font:

<img width="1392" alt="screen shot 2018-08-23 at 09 56 41" src="https://user-images.githubusercontent.com/121939/44515655-03f0ad80-a6bb-11e8-9809-b4da091c42f7.png">

**Comment by nickcolley** [comment]
I spoke to @dashouse and he said that this will be resolved when we roll out the new version of the font.

**Comment by 36degrees** [comment]
Looks like this will be addressed with the font change in 3.0 as we expected.

## Before

<img width="1392" alt="Screenshot 2019-06-07 at 15 33 17BST" src="https://user-images.githubusercontent.com/121939/59111794-a96aca00-8939-11e9-9659-9e1777f147e7.png">

## After

<img width="1392" alt="Screenshot 2019-06-07 at 15 33 19BST" src="https://user-images.githubusercontent.com/121939/59111795-a96aca00-8939-11e9-9351-5878cd6004d7.png">

I wonder if we should list this as a fix in the changelog? / cc @aliuk2012
