### ISSUE TITLE
Make sure users can override template elements if they need to

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#971]
For example:
- open graph image
- crown copyright
- OGL
- skiplink location
- page language
- custom attributes on body tag

This issue has come up a number of times:

- https://github.com/alphagov/govuk_template/issues/188
- https://github.com/alphagov/govuk_template/issues/137
- https://github.com/alphagov/govuk_template/issues/271
- https://github.com/alphagov/govuk_template/issues/342
- https://github.com/alphagov/govuk_template/pull/285
- https://github.com/alphagov/govuk-frontend/issues/813

**Comment by hannalaakso** [comment]
Split this into cards (apart from the skiplink location one as that functionality already exists):

https://trello.com/c/GbXpmjYJ/1420-add-ability-to-override-or-remove-open-graph-meta-tag-in-template
https://trello.com/c/ZB1o8lcI/1421-add-ability-to-override-or-remove-crown-copyright-in-footer
https://trello.com/c/8VjEokHR/1426-add-ability-to-override-or-remove-ogl-logo-in-footer
https://trello.com/c/Be65Mgph/1429-add-ability-to-override-language-for-page-title-and-main-in-template
https://trello.com/c/nVhT0Foq/1431-add-ability-to-set-attributes-on-body-in-template

Closing this card as there doesn't seem to be any value in tracking these changes as a single item.

**Comment by edwardhorsford** [comment]
This just came up on my service. We'd been using the footer without thought to the OGL text. I'm so used to seeing it I didn't think about whether it was correct to use.

Some services contain official / confidential information and it would be inappropriate to release under the OGL.

**Comment by aliuk2012** [comment]
Closing this issue as these have been split out into separate tickets
